### ISSUE TITLE
RucioInjector  checking unnecessary conditions to create Container Rules

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#10064]
**Impact of the bug**
WMAgent

**Describe the bug**
It's not really a bug, but an outdated behavior. RucioInjectorPoller will create rules only for containers whose blocks have been uploaded to DBS. Apparently, this behavior was needed with PhEDExInjector, but makes no sense for Rucio as it causes an unnecessary delays in transfers.

**How to reproduce it**
Create a new container whose blocks are not uploaded to DBS, and define a subscription for it on the database. The subscription/rule will not be created as the status of files within the container will be `bsbuffer_file.status = 'NOTUPLOAD'`

**Expected behavior**
RucioInjector should create container rules as soon as the container subscription/rule is properly defined in the database. i.e:
`dbsbuffer_dataset_subscription.subscribed = 0`
`dbsbuffer_dataset.path != 'bogus'`

**Additional context**
None

**Comment by germanfgv** [comment]
Looking into [GetUnsubscribedDatasets.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/Database/MySQL/GetUnsubscribedDatasets.py) I see that the query also check that `dbsbuffer_file.in_phedex = 1`. I'm guessing this column is not meaningful anymore. If that's the case, it can also be removed.

**Comment by amaltaro** [comment]
Thanks for creating and owning this issue, German. As I said on slack, having data already injected in DBS was a pre-requirement for creating PhEDEx subscriptions, that's why that extra condition is there. 

With Rucio in production, we no longer need that. In my opinion, we should only make container-level rules - from the RucioInjector - once at least one file has been injected into Rucio `in_phedex=1`. This also answers your second question regarding the database column, it's very much needed (it keeps track of files injected into Rucio), however at some point we will probably have to rename it.
