### ISSUE TITLE
WMCore Rucio vs native Rucio API for CRAB

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10164]
Hi @amaltaro @ericvaandering @nsmith- @dciangot 
since apparently Diego C. has been captured by his boss(es) in Perugia for other things,
looks like I have to take over ownership of CRAB/Rucio interface.

Well.. I have my tastes. So I am questioning the usefulness, at least for CRAB goals, of using WMCore Service class for this
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py

Would anybody object if CRAB code also instantiates directly a Rucio python clien API and uses it ?
Does anybody sees good reasons why I should not ?

I can use WMCore wrapper in a few cases where it provides added value
 but in many cases the native one is fine and all in all more clear.

As for the motivation:

It looks to me that WMCore wrapper suffers of being heavilly tailored for WMAgent specific needs,
hiding some functionalities and making somethings out of reach
(like adding containers in scope A to containers in scope B)

There are also minor nuisances like not always which argument has a name, which not, and
position of the un-named ones does not follow underlaying Rucio python API convention.
Such signature changes are confusing.

And every time we need a change "only for CRAB" I need a new WMCore tag etc.

In the end, I found that one needs to understand Rucio anyhow, and the main usefulness
of the WMCore wrapping the additional documentation, which is great, but should better be added to
  https://rucio.readthedocs.io  , can we make PR's for that ? I mean.. it is a pity that
all the work Alan did for that is not shared ! (esp. since python API documentation in Rucio is very minimal)

All in all it is not like "I call Rucio everywhere", there are only a handful of places, each requiring
ad-hoc handling anyhow. The only real common use with WMCore is to list replica locations for blocks.
But creating/managing containers, is just different.

WMcore wrapper tries to catch all exceptions and keep going, possibly useful for some WMA daemons,
but in my case I may need different exception handling.

Besides, the "ASO" code, which now runs as a script in the schedd's, still uses old CMSRucio.py stuff, and it
looks much simpler to me to drop that and call Rucio Client directly (as done for lfns2pfns already) instead
of adding a dependency on WMCore in there and tweak WMCore/Rucio to properly deal with user scope.

**Comment by ericvaandering** [comment]
I don't have an opinion on this

**Comment by vkuznet** [comment]
Stefano, is there any good reason to use python APIs at all? What you describe is exact nightmare I pointed out with Python maintenance. Since DAS is written in Go, I can't use Python API and just use plain Rucio HTTP REST APIs. Again, I'm not advocating it per-se, but all of these wrappers, dependencies, maintenance in a long run is a main source of our time we spend maintaining our software stack.

**Comment by amaltaro** [comment]
Stefano, that's a valid concern and I think you are the best person to actually evaluate it.

The way we started creating this wrapper was based on the known use cases and APIs used in the WM Production system, instead of porting similar functionalities as we used to have in the PhEDEx wrapper. So this might be an explanation as of why some of the features required by CRAB are not there.

Given that this is a wrapper around the rucio-clients package, this module does not inherit from the `Services` class, which provides additional HTTP/HTTPS/PyCurl/Caching functionality. The main differences between the WMCore wrapper and using the rucio-clients API itself is:
* some calls are cached
* there is error handling embedded in this module (instead of spreading it everywhere where you need to call the same API)
* plus some "silent" error handling for things that are harmless or expected (some which Todor - for instance - dislike and has already pointed out).
* last but not least, some unit tests that can catch any problems with rucio APIs and or breaking changes.

From my side/WMCore, I am happy to adapt it to CRAB use cases as well; provided that gives us less work and gives you a more robust integration.

PS.: as Valentin suggests, one can use the RESTful APIs - and we do have those integrated into MSTransferor - but my experience is that that is a PITA. You need to control the token and it's validity, and some APIs respond a plain json, others do streaming and you need to parse the output, and so on.

**Comment by nsmith-** [comment]
I think some motivation why the WM wrappers exist is the fact that, for some time, the system was "dual-stack" with PhEDEx and Rucio, and it was better to abstract the DM interface. Now, it may make more sense (even in WM) to use rucio client directly. As for REST API, indeed there are performance considerations that make one want to move to that. But, it is unclear to me which (REST vs. python) API is "public" in the view of rucio core team. I've worked with the REST API for a bit and find it quite inconsistent in places, and perhaps even less documented than the python client.
I think it would be great if @amaltaro could contribute the documentation he wrote upstream, when there is time. All would benefit.

**Comment by belforte** [comment]
Thanks all. I'll go then for whatever is simpler for CRAB.
And will look into shareing with WMCore as much as possible.

As to talking to REST API's... Unless the interface is really trivial, one  will end up in needing to replicate the python client functionalities. So it is "write my client" vs. "use your client". One would hope that "your client" is good enough to make writing mine not needed. Given what Alan and Nick wrote it sounds more promising to push on Rucio core team for making python the first class citizen. Hey.. Rucio is supposed to be "ours" as much as "anynbody else's".

As examples go, DBS python client is great, CRAB Server python calls stinks big time, possibly because its restful API already is bad, so that eventually we gave users a "python API" which basically a wrapper around CRAB Client CLI. If one writes in GO, there's no need for "your python client", but I'd not change language only for that. It is certainly possible that DAS only needs a smaller subset of what Rucio offers than CRAB and WMA do.

**Comment by ericvaandering** [comment]
The python client in Rucio IS the first class citizen. Another reason Alan need to use the REST client directly in places is because he needed to be able to make many parallel calls to it. Valentin perhaps would have needed to do the same, even absent the Go issue. 

But from the CRAB point of view, I think only two things are viable: use the Rucio python client or extend the WMCore Rucio Service so that it covers all the CRAB needs as well and does it as nicely as the Rucio python client.

**Comment by amaltaro** [comment]
Stefano, something else just came to my mind. Isn't CRAB (or ASO) already using the WMCore Rucio wrapper in a compatible way with the PhEDEx `blockreplicas` API? I'm asking this question because I'd like to eventually (sooner than later) remove that data formatting compatibility, which can be set here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py#L137

and which is only used by the `getReplicaInfoForBlocks`.

If you decide to implement anything new - that would rely on that method - can you please try to use it without the phedex compatible flag enabled?

**Comment by belforte** [comment]
Thanks Alan. I had indeed come to same conclusion. Looks like we start
from a simple list, spend effort in turning in the format PhEDEx was using,
and then more acode again on our side to turn it into a simple list again :-(
Yes, I'd like very much to cleanup things there !
I'll make and ad hoc issue.

**Comment by amaltaro** [comment]
Hehe, exactly! The PhEDEx response format is just **terrible** with millions of nested dictionaries.
Once things are all set on your side, just ping me and I'll remove that from the Rucio module. Thanks!

**Comment by amaltaro** [comment]
@belforte Stefano, I don't mind keeping this issue open for a little longer. However, if you think there is no more value in keeping it open, would you mind closing it?

**Comment by belforte** [comment]
I think it was debated long enough. Conclusion is that Rucio usage inside CRAB is limited enough and different enough, that I prefer to avoid using WMCore Rucio wrapper and will call directly the Rucio python client.
