### ISSUE TITLE
Streamline WMCore development cycle in light of the kubernetes environment

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10177]
**Impact of the new feature**
Every single WMCore service that gets deployed in the CMSWEB cluster

**Is your feature request related to a problem? Please describe.**
As most of the WMCore services have now migrated to the Kubernetes setup, it means we also have to change the way we implement/test/build/deploy central services, such that we test and deploy services as similar as possible to the production setup.

**Describe the solution you'd like**
This ticket expects - as outcome - to have our own documentation to deal with WMCore services in face of the Kubernetes environment.
A non-exhaustive list of items that need to be addressed here is:
* which configuration to use for k8s-dev WMCore services
* how to build our own WMCore docker images
* how to deploy our own WMCore docker images in the cmsweb-dev clusters (and perhaps in our own private cluster...)
* how to build official WMCore docker images
* how to deploy official WMCore docker images in CMSWEB pre-production AND production clusters
* perhaps, how to deal with frontend changes

It's still not clear to me whether all our validation will be done against the cmsweb-dev clusters (and if there are enough clusters for our WMCore team). We also need to check which CouchDB setup we have in place for those clusters.

This ticket is NOT requesting a replication of the CMSWEB documentation from:
https://cms-http-group.docs.cern.ch/k8s_cluster/cmsweb_production_cluster_doc/

to our own Wiki. However, I think there would be value in having a short WMCore-specific version of those, with the most crucial commands, clusters available (with pointer to the configs), and of course links to the CMSWEB documentation for further details.
 
**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
@goughes @khurtado @todor-ivanov please do let me know what your thoughts are and if we are missing anything important on this whole migration.

**Comment by amaltaro** [comment]
And before I forget, this issue:
https://github.com/dmwm/WMCore/issues/10396

should be taken into consideration when working on this issue and preparing further instructions for the WMCore team.

Or you might even work on that one before completing this one, Todor.

**Comment by todor-ivanov** [comment]
Thanks for mentioning that @amaltaro. I will take into account for sure. Still haven't decided which should go first though.

**Comment by todor-ivanov** [comment]
Here is the wiki document in which I kept track of the process of deploying the WMCore central services in a testbed cluster. In big portions it is a repetition of what we have in cmsweb documentation server, but with all the details relevant to WMCore and one section, called `Automation`, which I find particularly useful for the purpose of speeding up the operational effort. 

p.s. The current state of the document does not include the creation of docker images and deployment tags, which are basically the first stage of the release management for WMCore. But in case we agree that those may be considered as a separate step, we may safely explain the process in a separate wiki document and track it's development in a separate GH issue.

@amaltaro, please take a look and tell me what do you think.

**Comment by amaltaro** [comment]
This documentation is looking great, Todor. 

I think the last piece we need is indeed the image creation and how to properly deal with CMSWEB/deployment tags, as you mentioned above. And I would suggest to actually add those instructions to the same wiki, to make sure we can find it when needed :-D

Perhaps we should try to have a 15min Zoom chat with Imran to clarify these questions above.

**Comment by todor-ivanov** [comment]
Thanks @amaltaro for the feedback!

> Perhaps we should try to have a 15min Zoom chat with Imran to clarify these questions above.

This is a must indeed, because there are still some blurry spots in this regards.

**Comment by todor-ivanov** [comment]
In parallel to the decision we took to have this month's validation from a dev K8 cluster, I also decided to push a little bit harder and finalize this issue. I think in the light of the recently setup CMS Registry [1] everything became much more fluent for all the users/developers who are supposed to be authenticated and given the permissions to upload images. This all helped a lot for me to be able to follow the whole procedure to the very end so that we may now close this issue. Here are the instructions for the final step [2], which also cover @amaltaro's previous request:
> And I would suggest to actually add those instructions to the same wiki, to make sure we can find it when needed  


[1]
https://registry.cern.ch/

[2]
https://github.com/dmwm/WMCore/wiki/WMCore-central-services-deployment-k8#building-docker-images

**Comment by vkuznet** [comment]
@todor-ivanov I don't want to disappoint you but I think another iteration will be required as we will move towards using helm charts. To unify k8s deployment across all CMS k8s clusters we may finally switch to helm charts. The change to your instructions will be two-fold in this case:
- instead of managing individual service manifest file(s) we'll ask dev-teams to manage corresponding helm chart (which is a bundle of all k8s manifest files required for services, from deployment, to service, to scaling).
- and, instead of using `deploy*.sh` scripts (which is custom made by CMS HTTP group), we'll rely on `helm`.

Since we provided helm tutorial already I suggest that you add at least a link to it in your wiki, that you'll remember how to do it.  All helm documentation we keep in centrally here:
- [deploying services](https://cms-http-group.docs.cern.ch/helm/deploy-services/)
- [push services](https://cms-http-group.docs.cern.ch/helm/push-services/)
- [upgrade, rollback and deletion](https://cms-http-group.docs.cern.ch/helm/manage-services/)

**Comment by todor-ivanov** [comment]
Hi @vkuznet I am reading the `helm` documentation now. Thanks for providing the links to the official documentation. I also followed the instructions from the tutorial given in September, but was not aware that this is going to be the default deployment method and how soon that would become the new normal. I'll include the set of instructions regarding `helm` in a separate section of the same wiki so we can have them both for the moment.

**Comment by amaltaro** [comment]
This is great to hear that we have completed this setup and can start doing things on our own, Todor.
I will go through the documentation you put in place and try to deploy something with k8s in the coming week. Thanks!

**Comment by vkuznet** [comment]
@todor-ivanov the decision is not yet finalize it since we need to discuss and adopt different things. But since CERN IT, and other groups (Rucio) using helm as well as additional 3rd party tools which we plan to adapt also rely on helm I think it would be wise to apply common deployment procedure across all cms k8s clusters. As such we're preparing and documenting everything for helm and will start transition most likely in 2022.

**Comment by todor-ivanov** [comment]
Thanks @vkuznet , I am working on updating the procedures. Helm seems comfortable to use and I am confident we will be able to switch to it once CMS decides to make it the default deployment tool.
