### ISSUE TITLE
AgentStatusWatcher errors due to interrupted polling cycle of DrainStatusPooler

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10170]
**Impact of the bug**
WMAgent

**Describe the bug**
Recently we started noticing in the agents that `AgentStatausWatcher` goes in red. The usual cause is a stuck and not updated thread - `DrainStatusPooler`. No clue what is causing it yet. We only noticed that the sub component in question just stops following its regular pooling cycle, which in general should be once per hour. A single log record for a healthy sub component run is given in [1].

[1]
```
2020-12-10 04:15:25,947:139645241743104:INFO:DrainStatusPoller:Running agent drain algorithm...
2020-12-10 04:16:14,845:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for NoJobRetries. 
2020-12-10 04:16:14,846:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for EnableAllSites. 
2020-12-10 04:16:14,846:139645241743104:INFO:DrainStatusPoller:Checking speed drain threshold for CondorPriority. 
2020-12-10 04:16:22,538:139645241743104:INFO:DrainStatusPoller:Finished collecting agent drain status.
2020-12-10 04:16:22,538:139645241743104:INFO:DrainStatusPoller:Drain stats: {'workflows_completed': False}
2020-12-10 04:16:22,538:139645241743104:INFO:BaseWorkerThread:DrainStatusPoller took 56.591 secs to execute
```
 
**How to reproduce it**
Unknown - the cause is yet not figured out.

**Expected behavior**
`DrainStatusPooler` to follow its regular polling cycle

**Additional context and error message**
N/A

**Comment by jenimal** [comment]
FYI all the draining agents have heartbeat issues with this, I am assuming that it's OK to just leave them be that way, we can discuss in the P&R Meeting tomorrow

**Comment by amaltaro** [comment]
I have added some debugging statements (printing `AMR` to the log) on vocms0251.

**Comment by amaltaro** [comment]
I tracked the problem down to this schedd query made with the python bindings:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/PyCondor/PyCondorAPI.py#L31

I guess I'll stop debugging it now.

**Comment by amaltaro** [comment]
Since I'm taking a break from this issue, to summarize, whatever changes we make on how the schedd object is used and how queries are done (through the `query` API), it eventually gets stuck again (usually after 10 calls or so). Why the `schedd.query` never completes is still a mystery to be solved.

Future work could be:
* use the `xquery` instead, but then we would have to iterate/yield every single job class add because it does not work with `SummaryOnly` option
* update our python bindings to the latest stable release and see if the problem persists
* create an standalone multi-threading script and keep executing the same call from the child thread, which might reproduce this issue...

**Comment by amaltaro** [comment]
We haven't seen this issue for quite some time. So I am assuming this has resolved itself with condor upgrades, python bindings upgrades and so on.
