### ISSUE TITLE
Move acdcserver to k8s production

### ISSUE THREAD

**Issue by goughes** [dmwm/WMCore#10184]
**Impact of the new feature**
Updates to acdcserver will be handled via some method in the k8s production environment

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Acdcserver code updates are handled in k8s production

**Describe alternatives you've considered**
See issue: https://github.com/dmwm/WMCore/issues/10183

**Additional context**
None

**Comment by amaltaro** [comment]
This is a couchapp-only service deployed on top of CouchDB. Even though there are ACDC service configuration files:
```
amaltaro@alancc7-cloud1:/data/srv/current $ vim config/acdcserver/ACDCConfig
ACDCConfig-default.py  ACDCConfig-dev.py      ACDCConfig-preprod.py  ACDCConfig-prod.py     ACDCConfig.py 
```

I do not think they are used and I do not see any acdcserver process running on my VM:
```
amaltaro@alancc7-cloud1:/data/srv/current $ ps aux | grep acdcserver
amaltaro 32300  0.0  0.0 112808   980 pts/0    S+   22:44   0:00 grep --color=auto acdcserver
amaltaro@alancc7-cloud1:/data/srv/current $ 
```

Said that, this issue is only relevant if we actually create a backend application for this service (as we did for WorkQueue many years ago). Maybe we should just close this out? @goughes what do you think?

**Comment by goughes** [comment]
So it looks like we resolved this issue awhile back when we redesigned the couchapps deployment method. Now acdcserver gets pushed when couchdb starts.

https://github.com/dmwm/deployment/blob/9ea27ff7b68af90d9ebad3f46040160728299d1a/couchdb/manage#L128

And acdcserver deploy script doesn't really do anything anymore.

https://github.com/dmwm/deployment/blob/9ea27ff7b68af90d9ebad3f46040160728299d1a/acdcserver/deploy#L28-L32

I will close it out. We can also close #10183 and #10090.
