### ISSUE TITLE
T0 Reqmon cherrypy threads missing in the kubernetes pods

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10260]
**Impact of the bug**
T0Reqmon

**Describe the bug**
While checking our `dmwm` and `tzero` pods configuration (service config), I noticed that the `t0reqmon` and `t0reqmon-tasks` contain the same configuration file, which means the t0reqmon-tasks are missing a couple of cherrypy threads configuration, as defined in the `deployment` repository.

**How to reproduce it**
connect to the pod and check the service config

**Expected behavior**
This was probably done intentional, to avoid the same threads running from the VM and from k8s.
Given that all those are disabled in the VMs, we need to update the services_config repository with the correct configuration for t0reqmon-tasks (both preprod and prod), re-enabling those cherrypy threads that are missing in k8s.

Once a new configuration is in place, either we or Imran will have to push the new config/secrets and restart the pod.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
@goughes Erik, could you please work on it today/tomorrow? T0 will have a MWGR in the coming days, so we better have services running properly by then.

**Comment by goughes** [comment]
Looks to me like the services_config repo is correct for each.
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/t0_reqmon-tasks/config.py
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/t0_reqmon/config.py

The issue lies in the secrets configuration of the t0_reqmon-tasks service. It points to the t0reqmon secret so we get the same config for both:
https://github.com/dmwm/CMSKubernetes/blob/572dac74c5d8d616e36fbc51c1a424db15ff6fbd/kubernetes/cmsweb/services/t0_reqmon-tasks.yaml#L100

CMSKubernetes PR in the works to update that to the proper secret (t0reqmon-tasks-secret).

**Comment by goughes** [comment]
Valentin merged the fix for this so t0_reqmon-tasks can be redeployed whenever you want @amaltaro

**Comment by goughes** [comment]
Pod was redeployed Feb 9. Closing this issue.
