### ISSUE TITLE
Check both DBS and Rucio in Global Workqueue

### ISSUE THREAD

**Issue by klannon** [dmwm/WMCore#10315]
**Impact of the bug**
Global Workqueue

**Describe the bug**
Global Workqueue only checks DBS when deciding which blocks to process, but WMAgent (and MSTransferor) checks the intersection of DBS and Rucio.  If the data are lost from Rucio, Global Workqueue will create elements for blocks that WMAgent will not process.

**How to reproduce it**
See Slack thread on https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-RunIISummer19UL17MiniAODv2-00342__v1_T_210205_113221_4288 (in rip-phedex channel)

**Expected behavior**
Global Workqueue should check DBS and Rucio.

**Additional context and error message**
N/A

**Comment by amaltaro** [comment]
Just to complement the initial description. A couple of months ago we implemented this functionality in MSTransferor:
https://github.com/dmwm/WMCore/pull/10205

such that CMS blocks with no data/files/replicas in Rucio, would be skipped from the input data placement.

Global workqueue works slightly different, it iterates over blocks found in DBS (with >= 1 valid files):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L35

and simply fetches its location from Rucio (considering wmcore_transferor locks and dataset_locks information). This, as reported in this issue, can generate a workqueue element that will never be able to be processed, because its input block will have an empty list location that will never change.

Having said that, the expected changes to be addressed here is that, workqueue elements should never be created for CMS blocks that don't have any replicas in Rucio (the same as it's already done for DBS).
