### ISSUE TITLE
Respect explicitely provided ports by clients in PortForward

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10359]
**Impact of the new feature**
Everything

**Is your feature request related to a problem? Please describe.**
In the recently developed portForward decorator and class [1] we do not respect if a client has explicitly provided a port for the url to be mangled. In such cases it would be wise to respect the clients wish, given that  they may have a solid reason for calling the specific port they provide.  

[1]
https://github.com/dmwm/WMCore/pull/10330

**Describe the solution you'd like**
While parsing the url to be mangled, check the presence of a port parameter. If it is there, avoid changing it.

**Describe alternatives you've considered**
No alternatives. This is something I consider a flaw in the original design. Thanks to others for spoting it. 
@belforte @vkuznet @amaltaro  https://github.com/dmwm/WMCore/pull/10330#issuecomment-803018864

**Additional context**

**Comment by amaltaro** [comment]
@todor-ivanov given that you will work on this PortForward implementation once again, I'd suggest to simplify these urls:
https://github.com/dmwm/WMCore/blob/master/src/python/Utils/PortForward.py#L41-L43

and consider only the cmsweb one. Otherwise it has an increased complexity and performance penalty as well.

Can you please provide these changes as well together with the port fix?

**Comment by todor-ivanov** [comment]
@amaltaro the work which is about to be done is a single line repeated twice. The change is extremely simple, but yes it would require a new PR. When you say:

>  Otherwise it has an increased complexity and performance penalty as well.

Did you happen to make some measurements. I myself need to admit did not have the time for that, even though I promised to do so in our private conversation.

Because those two machine prefixes  were put there in order for us both to avoid the need to patch our deployments every time. This of course can be made configurable, but do not know how big the increase of CPU cycles would be (if any at all).

**Comment by amaltaro** [comment]
> Because those two machine prefixes were put there in order for us both to avoid the need to patch our deployments every time. This of course can be made configurable, but do not know how big the increase of CPU cycles would be (if any at all).

I see the usefulness in that. However, giving it a second thought, this code is going to be heavily used in production and I'd rather not affect the production services performance because we need to have hooks for our development setup. Making it configurable would be awesome indeed, but I think there is no easy way for that. So I'd simply ditch that code and always parse for cmsweb urls only.

 > Did you happen to make some measurements. I myself need to admit did not have the time for that, even though I promised to do so in our private conversation.

I just finished it and here's a script to time it: https://github.com/amaltaro/ProductionTools/blob/master/timePortForward.py
As you can see, it times 3 options for updating the url: 1) decorator; 2) decorator wrapped in a class; 3) the basic string replacement that was part of the Service.py module.

Tests on my laptop suggest a large difference in those implementations, for 1 million substitutions:
```
(PY2) alannewmacpro:ProductionTools amaltaro$ python timeFunctionCalls.py 1000000
Going to make 1000000 url conversions
testDecorator received payload: 1000000
Finished single function call in 21.0341100693 secs

testFuncDecorator received payload: 1000000
Finished single function call in 22.8150680065 secs

testSimpleFunc received payload: 1000000
Finished single function call in 0.416056871414 secs
```

I believe this time difference is going to be negligible for most of the cases, but might be a problem in the long run when we start seeing >= 10 million requests a day.

Please let me know if you see anything wrong with that script and/or any inconsistencies.

One thing that I have not tested is the impact of turning that list of urls into a simple string (for cmsweb case only). Can you please check that?

**Comment by belforte** [comment]
why do you need to siwtch port for private test instances ? if that becase we run our own FE ? What about moving to run BE as a container in a cmsweb-* test cluster pod where FE "comes from Imran" and all URL's are cmsweb*.cern.ch ?
I am still running my own FE in my VM e.g., but it is not really convenient, should give the resource back and get a private K8s setup instead. I am not interested in debugging the FE !

**Comment by todor-ivanov** [comment]
Hi @belforte you are absolutely correct. It was put there temporarily, until we fully reach to the point you are talking about. I am removing this list now anyway. I am about to paste the results from me running Alan's script with few modifications in a while.

**Comment by belforte** [comment]
I am in same situation, and simply decided that as long as I run a FE in my private VM it will be "the old FE" which accepts x509. I do not know enough about tokens authentication to have any desire to run it myself if I can avoid it.

**Comment by todor-ivanov** [comment]
@amaltaro Thank you for the extremely good example and a start measurement! I took the liberty to make some  adjustments so that the results we get are a little bit more expressive. Here [1] is the change I propose.  And the reason I changed  the script like that is to be able to measure for real not the construction of function calls being it with or without decorator and an extra class, but actually the two different approaches to parsing the url, which is the significant part here. Which are:
   * Just replacing a string portion
   * Parsing the whole url in components based on the current living standard 

And here [2] are the results. There is indeed a contribution from the decorator implementation, but not that much - this was  I price I was ready to pay for the sake of not touching the original functions. So the difference of a direct function call to `urlparse` or through a decorator I think  is not that stressful. 

Now about the comparison between string replacement and `urlparse` it is a significant time difference in an order of magnitude, but there is a reason for that and we need to decide if it worth paying the price for. And the reason is we lack all the flexibility and safety and standard compliance the `urllib.urlparse` provides. And speaking of which, the change @belforte were suggesting in the context of the `urllib.urlparse` is just a single line as simple as: [3], While if we keep dealing with strings directly and want to figure out if the client provides a port to the url we will for sure end up developing our own regular expression doing the job which at the end will perform exactly the same as `urllib.urlparse`, but on the other hand will be extremely more error prone, because we will have to face all the errors and hidden bugs the mainstream developers already have worked out all by our won. 


[1]
https://github.com/amaltaro/ProductionTools/blob/3dea2ecf432cc2e6415222a58d04b05d6afa8fb8/timePortForward.py  

[2]
```
$ python timePortForward.py 1000000
Going to make 1000000 url conversions
testDecorator received payload: 1000000
Finished single function call in 9.86223888397 secs

testFuncDecorator received payload: 1000000
Finished single function call in 10.6508691311 secs

testSimpleFuncUrlParse received payload: 1000000
Finished single function call in 6.68189811707 secs

testSimpleFuncStrReplace received payload: 1000000
Finished single function call in 0.18202495575 secs
```

[3]
```
oldUrl = urlparse('https://cmsweb.cern.ch:8080/couhdb')
if getattr(oldUrl, 'port', None):
    netlocStr = u'%s:%d' % (oldUrl.hostname, oldUrl.port)
else:
    netlocStr = u'%s:%d' % (oldUrl.hostname, port)
```
```

**Comment by amaltaro** [comment]
Thanks Todor, timing urlparse and string replacement was a good idea!

I would be in favor of using something that is already provided by the community and work for whatever url juggling one wants to perform. However, I like keeping things as simple as possible, which brings me to the following question: do you see any problem with the string replacement pattern we have before:
```
url.replace('.cern.ch/', '.cern.ch:8443/', 1)
```
?

I believe it would work for all our use cases:
1) updating url with no explicity port
2) not updating url which already sets port to 8443
3) not updating url which already sets another specific port

It's a simple and performant implementation (and of course, very simple to read and maintain ;)).

**Comment by belforte** [comment]
@todor-ivanov : Keep It Simple and Stupid. Don't make it a state affair of parsing the string a.b.c:1

**Comment by todor-ivanov** [comment]
Hi @amaltaro 

> do you see any problem with the string replacement pattern we have before:

I can immediately come up with at least two:
   * lack of dual stack: python3 / python2 compatibility
   * we are silently skipping urls ending up with just `cern.ch`

I've already been there. And that was actually how I started it at the very beginning and the exact reason why I went looking for `urlparse`. Because in the way it is done right now, there is a hidden cast to the proper string type that happens through the % operator for creating the proper `netlocStr`, while if I were to cover all the case of the 3 combinations of string like types  `'...', u'...', b'...'` to work properly in both python3 and python2 I ended up with six different sets of `if` conditions and was quite sure I would miss or break something. Especially given that I have no idea what type of parameter the function would be called with. So the simple single line we are talking about here is not that simple at all at the end.

**Comment by amaltaro** [comment]
> lack of dual stack: python3 / python2 compatibility

Good point. I had done some tests this morning, but only in python2, where that simple string replacement worked just fine. If I test the same in python3, it breaks when a `bytes` string is passed in.

I have just done some interactive tests and it looks like we can convert byte to unicode strings, calling this Utils.decodeBytesToUnicode function:
https://github.com/dmwm/WMCore/blob/master/src/python/Utils/Utilities.py#L195

and then perform the string replacement on its output. That way you can drop all those `if` statements for data type and, result would be a unicode string in python2 like `u'https://...` and a string in python3 `https://...`.

> we are silently skipping urls ending up with just cern.ch

There shouldn't be any HTTP requests to `https://cmsweb.cern.ch` because that's just the index page in the frontends. So, I think we can call it as an invalid case.

If I apply the `decodeBytesToUnicode` function on the url, this is the new time I get:
```
testSimpleFunc received payload: 1000000
Finished single function call in 1.95176315308 secs
```

so it looks very attractive to me.

**Comment by todor-ivanov** [comment]
Hi @amaltaro, I think I tackled it.  Solution on its way with my next commit.

**Comment by todor-ivanov** [comment]
@amaltaro  Here are the new measurements with the latest solution:

```
$ python timePortForward.py 1000000
Going to make 1000000 url conversions
testDecorator received payload: 1000000
Finished single function call in 0.861701011658 secs

testFuncDecorator received payload: 1000000
Finished single function call in 1.33222103119 secs

testSimpleFuncUrlParse received payload: 1000000
Finished single function call in 6.72056293488 secs

testSimpleFuncStrReplace received payload: 1000000
Finished single function call in 0.547676086426 secs
```
