### ISSUE TITLE
questions about Utils/Throttled.py

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#10360]
Hi @amaltaro @vkuznet 
Yesterday , during some testing, I hit for the first time the concurrency limit from
https://github.com/dmwm/WMCore/blob/e45a4425c5437d194d0d02814b7011c752c33548/src/python/Utils/Throttled.py#L168-L171 [1]

Which we call (a relic from previous implementation with limit=3)
I was surprised because I was the only use of this CRABServer instance which runs with 25 threads,
but "my code" was indeed working on 3 crab tasks at same time.
Also in this particular case I run a test CRABServer instance with just one pod, while in production
there would be e.g. 5 and calls would be spread.

So I think that the limit (3 in my case) is counted sort of "across all threads", is that intentional ?

Just so that I know what to expect, and then can decide how to setup thing !
Thanks

By the way, IMHO this confirm that throttling is working, even if I would have naively thought that this calls
were fast enough not to overlap. Back to "why did not it kicking when Spyros was sending tens of simultaneous requests to DBS ?"

[1]
which for some historical reason is only used (since ever) around one specific CRAB REST call
 https://github.com/dmwm/CRABServer/blob/56cbe809068209bb6214b2ad181430a8083de02e/src/python/CRABInterface/HTCondorDataWorkflow.py#L176-L184

**Comment by amaltaro** [comment]
@belforte Stefano, the way I see this user throttling mechanism is that every cherrypy request object (thread) enters a context manager which to account a request for that given user. In other words, if CRABServer runs with a pool of 25 threads, any given user could reach up to 25 parallel requests within the same server instance.

I can't say anything about DBS because I don't know which throttling mechanism it has adopted (I believe the first version).

Valentin, you are the one that conceived this code, so please correct me if I said anything wrong here.

**Comment by belforte** [comment]
For sure I was not running 25 clients, and my log has

[21/Mar/2021:23:01:17]    HTTPError: ('429 Too Many Requests', 'The current number of active operations for this resource exceeds the limit of 3 for user service@crab-preprod-tw01.cern.ch')

Actually I think I had exactly three threads running at same time and would have expected the limit to kick-in at 4. But I am not picky about 3 vs 4.

**Comment by vkuznet** [comment]
If I understand Stefano correctly User throttle was used. In this case the error comes from this line:
https://github.com/dmwm/WMCore/blob/e45a4425c5437d194d0d02814b7011c752c33548/src/python/Utils/Throttled.py#L64
which happens when user already has 3 requests, i.e. the kick-out happens on 4th request.

**Comment by belforte** [comment]
CRAB code uses
```
from Utils.Throttled import UserThrottle
throttle = UserThrottle(limit=3)
```
So everything is consistent if you confirm that usage is summed across al cherrypy threads. I think this is the case because this throttling is inside our server which runs as a single instance in each pod, and the cherrypy threads are sort of below it. But I have been wrong on easier things to guess !

**Comment by vkuznet** [comment]
Stefano, code relies on one dict per throttler which keeps track of user's requests in all threads of the server. But in k8s it means that throttler will be bound to single pod which runs your server. In other words, if you have 2 pods (2 servers) each can have 3 user accesses, which sums up to total 6 (2 servers and each may have 3 user accesses). But it also possible that one pod (server) will kick out user because it exceed the limit, and another pod may still not have 3 user accesses. Here everything depends on scheduling of HTTP requests across all pods. But on average the load across pods should be the same.

**Comment by belforte** [comment]
thanks @vkuznet . All clear.
