### ISSUE TITLE
WMAgent fails to load spec pickle file created in Python3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10609]
**Impact of the bug**
ReqMgr2/WorkQueue and WMAgent

**Describe the bug**
Workflows created in Python3 WMCore central services version `1.5.0.pre3`, running on Python2 WMAgent 1.4.7.patch3, fail in the agent's WorkQueueManager because the agent isn't able to load the pickle file retrieved from ReqMgr2 (actually it comes from the workqueue database, but it should be exactly the same!). Error message can be seen in [1]

**How to reproduce it**
See scenario and versions in the comment above

**Expected behavior**
We need to adopt a common pickle protocol that will work and provide the same behaviour in both python2 and python3 version. Which means, WorkQueueManager should not fail to load the workflow spec file when a workflow is being acquired.

NOTE: even though the problem happens in WMAgent, we should make sure this issue is addressed before Python3 central services are deployed. Such that we can avoid spec creation incompatibilities.

**Additional context and error message**
Related to: https://github.com/dmwm/WMCore/issues/9128

[1]
```
2021-06-21 22:44:45,141:140647810840320:INFO:WorkQueueManagerWorkPoller:Obtained 3 unit(s) of work
2021-06-21 22:44:45,250:140647810840320:INFO:WorkQueueManagerWorkPoller:Splitting new work
2021-06-21 22:44:45,250:140647810840320:INFO:WorkQueue:fixing conflict...
2021-06-21 22:44:45,340:140647810840320:ERROR:WorkQueueManagerWorkPoller:Error during split: unsupported pickle protocol: 4
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.4.7.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch3/lib/python2.7/site-packages/WMComponent/WorkQueueManager/WorkQueueManagerWorkPoller.py", line 114, in processWork
    self.queue.processInboundWork()
  File "/data/srv/wmagent/v1.4.7.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueue.py", line 1138, in processInboundWork
    inbound_work = self.backend.getElementsForSplitting()
  File "/data/srv/wmagent/v1.4.7.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch3/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueBackend.py", line 111, in getElementsForSplitting
    wmspec.load(self.parentCouchUrlWithAuth + "/%s/spec" % ele['RequestName'])
  File "/data/srv/wmagent/v1.4.7.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.4.7.patch3/lib/python2.7/site-packages/WMCore/WMSpec/Persistency.py", line 78, in load
    self.data = pickle.loads(data[0])
ValueError: unsupported pickle protocol: 4
2021-06-21 22:44:45,341:140647810840320:INFO:WorkQueueManagerWorkPoller:Splitting finished
2021-06-21 22:44:45,341:140647810840320:INFO:BaseWorkerThread:WorkQueueManagerWorkPoller took 0.501 secs to execute
```

**Comment by amaltaro** [comment]
Just a note before I forget. Hopefully pickle files created with our python2 web-services can be loaded by the soon python3 services and agent. Otherwise, we have a BIG and incompatible blocker in our system and something else will have to be considered to deal with workflows already injected into the system.

**Comment by klannon** [comment]
Normally I try to avoid micromanaging but I'm concerned about this particular problem.  If I understand correctly the reason we can't just update to the latest pickle protocol (whatever the default in Py3) because we have a bunch in progress workflows that have already generated pickle files in the old protocol and cannot be read if we switch.  The [proposed solution](https://github.com/dmwm/WMCore/pull/10619) is to keep using protocol v1.  The problem is that this solution basically locks us into protocol v1 forever because we'll never have the chance to stop the system and clear out all of old pickle files.

What if we did the following?  Continue writing and reading pickle files in the default protocol for the Python version being used.  If the attempt to read a pickle file generates an exception indicating a protocol problem then we retry with protocol v1.  This way, the code would still read the old version but over time we'd be able to gradually transition to a newer protocol.  What do you think?

Note: I'm completely fine with just fixing it to protocol v1 to get us past the Python 3 migration and then making the change to migrate protocols as a separate step.  I'd just hate to be locked into an old protocol version because we can't take a down-time to clean out the system.

**Comment by mapellidario** [comment]
> If the attempt to read a pickle file generates an exception indicating a protocol problem then we retry with protocol v1

`pickle.load()` is pretty smart and determines the protocol version from the pickle file itself. If we have a protocol version mismatch, we need to recreate the pickle file. Would this be feasible?

Otherwise, what we could do is to create multiple versions of the same pickle files but with different protocols, if this does not cause network and storage problems. The py3 WMAgents would read the ones with a recent protocols, the py2 WMAgents would fail to load the pickle and fallback to a version with an older protocol. I am not sure this is feasible yet, i am experimenting with pickle protocol versions these days. I should have an answer for our monday meeting.

**Comment by amaltaro** [comment]
I still didn't manage to digest all of this, and also to give a few things a try, but I think we will only need protocol=1 in the central services, until we have swapped all the WMAgents to python3 (which will then support higher pickle protocols, like 4).

**Comment by klannon** [comment]
Totally fair.  My only request is that we have an issue for moving us past protocol=1 afterwards so we're not stuck there forever!
