### ISSUE TITLE
Requests in running-closed status whose WQEs are not in Running state, thus stuck requests

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#10656]
**Impact of the bug**
WMAgent, Workqueue

**Describe the bug**
In the P&R meeting, while trying to understand why some high priority requests are not being completed for weeks, we discovered that there are some workflows whose WQEs are in Available state, thus not acquired by agent. Since they are in running-closed state, by definition, all WQEs should be in state in Running or further according to [1]

Here are some requests: (Click on `Workqueue` in the following pages to check WQEs)
1. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIIAutumn18NanoAODv7-02608
2. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_EXO-RunIISummer20UL16NanoAOD-00011
3. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_B2G-RunIIFall17NanoAODv7-02817
and more.

Here is the list of "Late" workflows. [Link](https://its.cern.ch/jira/issues/?jql=project%20%3D%20CMSCOMPPR%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20labels%20%3D%20Late%20ORDER%20BY%20updated%20DESC%2C%20lastViewed%20DESC) I haven't checked all of them, but probably many of them suffers from this issue.

[1] https://github.com/dmwm/WMCore/wiki/Request-Status#running-closed 

**How to reproduce it**
Check the requests above

**Expected behavior**
Jobs must have been created for each WQE by `running-closed` status.

**Additional context and error message**
None

**Comment by haozturk** [comment]
I've just estimated the impact of this bug: It affects **1908** workflows in `running-closed` as of now. Note that we have ~5k workflows in `running-closed`, ~6k if we can include `running-open` as of now. So, ~ 30% of  all running workflows seem to be affected. This looks like the primary culprit for the overload in the system. According to my initial investigation, those workflows cannot move, so, I believe they will stay stuck forever unless an action is taken. Please let me know if I miss anything. 

Here is the list: 

[workflowsAffectedBy10656.txt](https://github.com/dmwm/WMCore/files/6877329/workflowsAffectedBy10656.txt)

@nsmith- @drkovalskyi @jenimal @z4027163 FYI

**Comment by amaltaro** [comment]
@haozturk Hasan, thanks for creating this issue. After investigating the code multiple times, and getting confused with all those sets logical operations, it turns out `running-closed` status can indeed have workqueue elements in `Available` status. It seems to be like that since the beginning. I do not think it makes sense, since `running-open` can match elements still left in `Acquired` status.

I'm going to make a fix for it such that (and reflect these changes to the wiki page):
* `running-open`: when not all workqueue elements have been pulled by the agents (thus, still elements left in Available/Negotiating/Acquired)
* `running-closed`: when all the workqueue elements are at least in Running status, thus no workqueue elements left in Available/Negotiating/Acquired.

I do not think this definition - or the new definition to be implemented - impacts the system health in any sense though, including the unmerged area usage. Please let me know if there is anything that I'm missing.

**Comment by haozturk** [comment]
I see. Yes, I agree that we should make a fix to reflect the explanations in this wiki https://github.com/dmwm/WMCore/wiki/Request-Status#running-closed That wrong explanation led us to reach to wrong conclusions and decisions.

I also agree that this is now unrelated to the unmerged issue. The most important issue now is the force-complete one [1] and I see that you already have a progress there and I see some force-completions succeed. Thanks a lot Alan!

[1] https://github.com/dmwm/WMCore/issues/10675
