### ISSUE TITLE
Prometheus alerts being triggered for "ReqMgr2 service is down"

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10667]
**Impact of the bug**
ReqMgr2 (Monitoring?)

**Describe the bug**
This has been briefly discussed with Todor yesterday.
Since the day we have migrated our central services to Python3, last Friday July 2nd, I've been getting almost 10 email/slack alerts per day, stating that ReqMgr2 service is down, e.g. [1].

The alerting system seems to be based on the Go-http-client tool, which is probing our services every 10 seconds. 

**How to reproduce it**
I followed one of those alerts, checked the POD logs and status, and everything was okay. So, at least for the alert I was looking at, it looked to me to be like a false alert. It does coincide though with python3 services deployment.

**Expected behavior**
If these alerts are legit, we should investigate what is causing them and properly update this GH issue with that information, such that a proper fix can be implemented.
We might need to have help from the Monitoring experts though.

NOTE: I'm labeling it as a BUG, but this is not yet clear to me.

**Additional context and error message**
[1]
```
Labels
alertname = ReqMgr2 service is down
action = Please restart ReqMgr2 service on XXX
apod = reqmgr2-6fb98bcdd5-strf8
app = reqmgr2
env = k8s-prod
host = cmsweb-k8s-services--zone-a-btos23lfjel2-node-1
instance = XXX
job = kubernetes-pods
kind = dmwm
ns = dmwm
service = reqmgr2
severity = high
tag = cmsweb
```

Update, resource usage for the WMCore services can be seen here:
https://monit-grafana.cern.ch/d/M2U6T6uGk/kube-eagle-k8s-metrics?orgId=11&from=now-6h&to=now&refresh=15m

**Comment by amaltaro** [comment]
Hopefully we can sort this out with the MonIT team. JIRA ticket created: https://its.cern.ch/jira/browse/CMSMONIT-408

**Comment by amaltaro** [comment]
Problem is still there, even with the new condition. 
I checked the pod/service logs, and I do not see any outage (reported in the JIRA ticket), so I'm actually considering in completely removing that cpu_load based condition and rely solely on the liveness probe, which is querying our services every 10sec anyways.

**Comment by vkuznet** [comment]
As I reported on [CMSMONIT-408](https://its.cern.ch/jira/browse/CMSMONIT-408) there is no issue with alert itself. I think the actual issue is to properly define what does it means "service is down". I provided several suggestions either to use fds or HTTP status as better alternatives. I suggest that you first define "service is down" condition, then properly evaluate if any existing metrics can answer your definition, and if so, report back to CMSMONIT-408 with proper suggestion which metric to use. Please note, that liveness prove is identical to http_exporter functionality, i.e. it send HTTP request to HTTP end-point of the service. If this is what you need to define "service is down" then we can set it up, either as part of reqmgr image (we'll need to include it into monitor.sh) or as separate process in monitoring cluster (similar how we other http exporters for wmstats, rucio, unified, cric, etc.).

**Comment by amaltaro** [comment]
Just to confirm, it's been the first weekend free of alerts. After having bad metrics and/or alert configuration for 3 months.
