### ISSUE TITLE
MSUnmerged: Change service certificate

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#10680]
**Impact of the new feature**
MSUnmerged

**Is your feature request related to a problem? Please describe.**
In the current setup the certificates used for testing and production run of the service are not the correct one to use. The  current ones are to be considered more as of temporary certificates, which should be used only in the initial phase of establishing the service under operation. 

**Describe the solution you'd like**
Once the service is running firmly, we should  issue the dedicated certificates and swap the temporary ones.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by todor-ivanov** [comment]
Here is a comment which is a must to be linked here in this issue too:
https://github.com/dmwm/WMCore/issues/10682#issuecomment-885972948

**Comment by amaltaro** [comment]
Let me try to summarize all the changes done in terms of authorization to access/delete those storage files, from mattermost and 10682 issue:
* MSUnmerged is currently using the standard `CMSWeb migration` service certificate (the same used by other WMCore services)
* the `dataops:production-operator` CRIC role has been granted to it (I do not think it's required though)
* a VOMS role has been requested: `cms:/cms/Role=production` and attached to the same service cert
* an specific - since the production voms extension is required by the service - proxy docker container has been created for MSUnmerged: https://github.com/dmwm/CMSKubernetes/pull/682
* and a new proxy cron service has also been created for MSUnmerged.

@todor-ivanov feel free to correct/complement with anything that I might have missed.

**Comment by todor-ivanov** [comment]
Hi @amaltaro,
You have made a good summary of what have been done with the current certificate of the service we use. But as discussed on different channels we will need to change that one with a dedicated  service certificate later.

**Comment by todor-ivanov** [comment]
We did have a quick private communication with anybody who may be concerned and a decision was taken to postpone this activity because of two reasons:

* We are about to migrate to a token based authentication in the near future, which will make it unnecessary the complication of changing  the whole service setup and maintaining yet another certificate out of it's use for almost an year.   
* There were only two site we have found to have any permission issues and it is followed in the relevant GGUS tickets:
   * T2_UK_London_Brunel
   * T2_BE_UCL

I am closing this issue, and in case we decide the dedicate service certificate is unavoidable, we may reopen it at any time.

FYI: @amaltaro  @klannon  @vkuznet
