### ISSUE TITLE
Upgrade CouchDB used in central services to version 3.1.x

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10833]
**Impact of the new feature**
WMCore central services

**Is your feature request related to a problem? Please describe.**
Sub-task of https://github.com/dmwm/WMCore/issues/8853
and dependent of https://github.com/dmwm/WMCore/issues/10831

**Describe the solution you'd like**
Once we have fully tested the new CouchDB version in CMSWEB, and upgraded the current database schema to the schema compatible with CouchdB v.2.3+, we can then consider upgrading CouchDB in central services.

**Describe alternatives you've considered**
Could start upgrading CouchDB in a sub-set of the backends first

**Additional context**
Sub-task of https://github.com/dmwm/WMCore/issues/8853

**Comment by amaltaro** [comment]
For the record, CouchDB 3.1.2 has just been released (a security release) and we should target at that version.

**Comment by vkuznet** [comment]
I revisited different options how we can make this transition easier and would like to suggest alternative approach. So far, we patch CouchDB with custom made patches to be complaint with CMS authentication headers. This requires us to propagate patches from one CouchDB version to another, and this process is very tedious since none of us are experts in Erlang (the programming language CouchDB is build on). But nothing stop us to use stock CouchDB and put it behind proxy server (which I developed in Go to replace CMS apache frontend). Since [auth-proxy-server](https://github.com/vkuznet/auth-proxy-server) is intend to replace CMS FE, provides full user authentication, and provides static executable, we can easily deploy CouchDB with it on any remote site and always use stock CouchDB from their repository. This will eliminate burden to build custom couchdb and always stay with recent versions. As such the CouchDB upgrades will become very trivial and will not require any labor from our side. Moreover, the usage of auth-proxy-server will guarantee that we can move from x509 authentication to token based one without touching CouchDB.

I suggest that we evaluate this approach and if agree I can provide details of configuration setup. Here are the steps will be required to setup auth-proxy-server with CouchDB:
- download new version of CouchDB from their web site
- download static executable from auth-proxy-server repository
- put them on a node, no RPMs builds required, and run with provided configuration
That's it!

**Comment by amaltaro** [comment]
We managed to deploy CouchDB 3.1.2 in production central services, yesterday July 13. 
Everything in the WM realm (including T0 WMStats) has been updated, after a complicated migration of the databases format from 1.6.1 to the new format in CouchDB 2+ (which includes sharding).

We have been running with this system for around 24h and things are looking good so far. There is one remaining task to be performed though, which is to complete the replication of the `acdcserver` database to CMSWEB. There were too many documents and we didn't manage to complete the migration during the outage window. 

I am working on an ad-hoc way to post those documents to central database and then this issue can be closed.

**Comment by amaltaro** [comment]
And now we also have all the ACDC documents in the central database.

For the record, I used this script to copy documents from the offline/localhost acdcserver database over to the cmsweb central one:
https://github.com/amaltaro/ProductionTools/commit/6f26ba929d932092937130708249f90d15dd967a

in short, it fetches all the workflows sitting in running-* or completed status, compares docs available in the offline vs cmsweb databases, and PUT missing documents in CMSWEB. If we ever need to run this procedure again, we can consider moving this script over to WMCore.

I think we can declare this issue done now, closing this out.
