### ISSUE TITLE
Excessive number of calls to reqmgr_auxiliary couch db

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10860]
**Impact of the bug**
WMAgent/CouchDB

**Describe the bug**
While checking central couchdb logs to investigate some alarms that have been popping up over the last couple of hours (vocms0742), I noticed many many calls to the agent configuration in `reqmgr_auxiliary`, sometimes multiple calls within the same second.

**How to reproduce it**
No clue

**Expected behavior**
We need to first investigate who is making all these calls. I believe it's WMAgent (we have 3 or 4 components that rely on the agent configuration), however it should be one call per cycle, so one call every few minutes (and some places have a cache of many minutes).

We need to make sure that the agent configuration is fetched only once per component cycle. If needed, some caching in the ReqMgrAux wrapper should be created.

**Additional context and error message**
Couchdb logs in vocms0742 should list something like:
```
... GET /reqmgr_auxiliary/WMAGENT_CONFIG_vocms0243.cern.ch 200
```

**Comment by goughes** [comment]
There are two levels of caching in ReqMgrAux: One in-memory cache from [MemoryCacheStruct](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Cache/GenericDataCache.py#L8) and one disk cache inherited from the [Service class](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Service.py). 

From my investigation, the MemoryCacheStruct is used, but a new object is created during each polling cycle, due to the scope of this cache variable: https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L58 So that cache doesn't really do anything to prevent multiple calls.

The disk cache from Service is also used, but it gets cleared everytime due to `clearCache=True` here: https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L38

I tested setting `clearCache=False` in the kwargs when the method is used here: https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L59

That prevents multiple calls to the API, but only within the same second, because the `cacheduration` used for the check here: https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/Service.py#L205
Is set to `0` here: https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L30

So I think we can limit some calls by doing `clearCache=False` via a change like https://github.com/goughes/WMCore/commit/aefbdf699501758dd3c3e2285c44c221e29fbff1 but it still leaves the memory cache in a spot where it is not performing as one would expect.

@amaltaro what do you think?

**Comment by amaltaro** [comment]
@goughes thanks for this investigation.

Do you think we could change the default value of `clearCache` in this method:
https://github.com/dmwm/WMCore/blob/ac83e5fdb1b4e7ddf38defbaa399285f73b1685d/src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py#L38
 instead?

The second step to actually use the cache, would be to define a short cache lifetime (5min?) when creating an instance of ReqMgrAux. What do you think?

**Comment by goughes** [comment]
Even setting the cache duration to 0 prevented a good amount of calls to the API that occur within the same second. For instance, at agent startup the number of calls for the aux agent config was reduced by half (8 to 4). I did not investigate the decrease during each agent thread's polling cycle.

**Comment by amaltaro** [comment]
@goughes Erik, just to make sure we come up with a safe cache duration. Would you be able to provide us with the top 10 urls being requested under reqmgr_aux db? I'm inclined to stay between 1 and 5min.

**Comment by vkuznet** [comment]
@goughes from our point of view (k8s issue we are trying to solve) it would be extremely useful if you'll provide exact timestamps when this happens, and total number of queries were made.
