### ISSUE TITLE
Increase persistence of T0 monitoring data in T0 WMStats

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#10904]
**Impact of the new feature**
WMStats, T0 WMStats

**Is your feature request related to a problem? Please describe.**
Currently, T0 monitoring info in WMStats  is only availalbe for a week after the workflow is completed. This is often not enough to properly study and debug processing issues. It also makes it impossible to use data from previous data taking to inform future operational decisions.

**Describe the solution you'd like**
We need T0 WMStats monitoring data to persist for longer and configurable amounts of time (6-12 months). This should be  as independent as possible of the management of T0 WMAgent itself (RucioInjector rules deletion, TaskArchival, etc).

**Describe alternatives you've considered**
Increasing the `TaskArchiver.archiveDelayHours` it's a possibility, but it would require modification of T0 block deletion logic, and probably  other unforeseen consequences in T0 Agent.

**Additional context**

**Comment by germanfgv** [comment]
If necessary, we could limit the increased persistence to workflows with processing issues (failed jobs, job progres<100%, etc)

**Comment by todor-ivanov** [comment]
Thanks for creating the issue @germanfgv. I'll take a look ASAP

**Comment by amaltaro** [comment]
>I would suggest looking into a solution that only affects WMStats and not the agent itself (i.e. making workflow archival in the agent independent of archival of a workflow in WMStats).

Hmm, it looks like creating a new WMStats CherryPy thread - or use one of those data cleanup something - is the way to go here. I like this idea!

**Comment by todor-ivanov** [comment]
Just an update on this one here.

We did have a deeper discussion on the idea with @amaltaro and I also was digging deeper lately and confirming the concerns raised during this discussion. Basically there is a problem with having kind of a 'new meta state' in T0 WMstats, which is supposed to keep records in WMStats's couch with status `archived` for longer. On a first glance it could indeed be achieved by:
* Adding few lines in the `CleanUpTask` CherryPy thread [here](https://github.com/dmwm/WMCore/blob/d75392c77de27337723f4f9c9effdb6d8cf14ce2/src/python/WMCore/WMStats/CherryPyThreads/CleanUpTask.py#L36), and make the deletion action be postponed by a configurable amount of time (e.g. having a config value of the sort: `cleanUpTask.archivedCleanUpDelayHours`.

But then this would have few consequences:
* We are basically in sync with the agent's CouchDB, so the records need to be preserved there too. Meaning we would need a change in the WMAgent:  `WMComponent/TaskArchiver/CleanCouchPoller` [here](https://github.com/dmwm/WMCore/blob/b77169aa015795d8725dd856f49023af9995549d/src/python/WMComponent/TaskArchiver/CleanCouchPoller.py#L321): because we sync
   * from `wmagent_summary` data
   * to `wmstats`   
* The other consequence would affect scalability. If doing the above we would have to also include all `*-archived` statuses in  updating the cache at [`DataCacheUpdate`](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMStats/CherryPyThreads/DataCacheUpdate.py) CherryPy thread not only active data as of [now](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMStats/T0/CherryPyThreads/T0DataCacheUpdate.py#L30). And since `*-archived` are final states, this would lead to querying CouchDB for every single document that have existed since beginning of time (in this case since beginning of T0 database existence). Which will simply not scale.

I may be missing some details here and there, but this is more or less the big picture. I still have not given up on the idea of tackling things through this `meta state` of the workflows but it would involve also more tricks at least in dealing with the CouchDB replication between agents and central WMStats. Because the other path is to go through disentangling archival status from block level deletions through WMBS queries and internal states, as discussed in the related GH issue: https://github.com/dmwm/WMCore/issues/11042. This is a dangerous and risky path to follow. And I still do not want to enter Moria.
  
@amaltaro  please correct me if I have missed or mistaken something in the above description.
FYI @hufnagel @drkovalskyi

**Comment by amaltaro** [comment]
You seem to have summarized it well, Todor. I am not sure I understand what you mean by "meta state" though.

I believe the best way to deal with this would be:
1. we allow workflows to be archived as usual and at the desired delay
2. when WMAgent is cleaning up all its data, we skip data that gets replicated to wmstats (and we skip any direct deletion against central wmstats, if any)
3. we instrument the WMStats CherryPy thread to clean up everything for a given workflow once it reaches the waiting period

Actually, if the workflow has been archived, it will go out of the WMStats watch and we no longer can know - in a cheap way - for how long the workflow has been in that given state. I would have deleted this text above, but I think it's important to keep it here to make sure that we thought about it and that we concluded it wouldn't work.

It requires further thought, but maybe having a CherryPy thread to archive T0 workflows together with WMStats data cleanup would be the way to go here....

**Comment by todor-ivanov** [comment]
thanks @amaltaro 
> I am not sure I understand what you mean by "meta state" though.

We konow that `archived` means everything related to a workflow is out of the system. It was just a figurative speech (hence the quatation marks) about those workflows for which we forcefully keep information in the system even though their state means otherwise.

**Comment by todor-ivanov** [comment]
@amaltaro about:
> Actually, if the workflow has been archived, it will go out of the WMStats watch and we no longer can know - in a cheap way - for how long the workflow has been in that given state

I think we do have access to this information. It can be fetched from the timestamp for the last workflow state transition: 
https://github.com/dmwm/WMCore/blob/9bd8f6c52400a6264b3c07438c3deeddcf4a60ef/src/python/WMCore/Services/WMStats/WMStatsReader.py#L29

As  long as the workflow is still in WMStats this should be accessible, right?

**Comment by amaltaro** [comment]
@germanfgv German, coming back to the original issue. Can you please clarify the following:

> This is often not enough to properly study and debug processing issues.

what type of debugging is this? Do we really need to have it set to 6-12 months? have you ever had a case where you had to come back 6 months to debug a workflow? can't we use the other logs available (at the schedd, site unmerged area, cmseosweb, and if needed, CTA once we retrieve this functionality)?

> It also makes it impossible to use data from previous data taking to inform future operational decisions.

what kind of studies are carried here that depend on active WMStats information? is there any system/script/code consuming this information for anything?

Sorry for all these questions German, I'm just trying to identify the use cases and evaluate alternatives before more effort is put into this.

**Comment by todor-ivanov** [comment]
This issue needs to be closed, since the so requested functionality is about to be resolved with a different approach by - disentangling the block level deletion rules from the workflow status as widely discussed in the following issue https://github.com/dmwm/WMCore/issues/11042 And better picture visualized in this particular [comment](https://github.com/dmwm/WMCore/issues/11042#issuecomment-1115078444) 

The related PR should be:  https://github.com/dmwm/WMCore/pull/11127


FYI @amaltaro  @hufnagel @germanfgv
