### ISSUE TITLE
SiteLocalConfig support in LogCollect jobs

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#10903]
**Impact of the new feature**
WMAgent, T0 WMAgent, WMStats, MicroServices (?)

**Is your feature request related to a problem? Please describe.**
By default, LogCollect jobs copy job logs to T2_CH_CERN. The only way to modify this behavior is to provide stage out params via the `overrides` section in the step's configuration. All the parameters required to configure the stage out process can be obtain by loading a SiteLocalConfig file. Nonetheless, it is currently not possible to directly use such file on LogCollect jobs.

This would be particularly useful for T0, as we intend to isolate our operations from T2_CH_CERN as much as possible.

**Describe the solution you'd like**
Provide means to use SiteLocalConfig to specify the output data placement for LogCollect.

**Describe alternatives you've considered**
Use the current method it's ok, although not ideal. 

**Additional context**

**Comment by todor-ivanov** [comment]
Thank you  @germanfgv  for creating the issue. As discussed during our meeting earlier today, we should use the proper configuration parameter to trigger the new behavior so that we do not affect the normal work of the current production system.
Could you please also put a link into the description to the proper file for the step configuration, which will be used from T0. The parameter itself may be discussed furhter in the PR supposed to resolve the ussue. And thanks again!
