### ISSUE TITLE
Update dbs3-client package to 4.0.6

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#10983]
**Impact of the bug**
It affects at least: WMAgent, WorkQueue and MicroServices (maybe ReqMgr2 as well)

**Describe the bug**
As discussed in this thread: https://github.com/dmwm/WMCore/issues/10842#issuecomment-1033018058

the client does not aggregate the output of `listFileLumiArray`, which may cause workflows to misbehave and/or trigger crashes in the code.

**How to reproduce it**
Use that client API against testbed x production

**Expected behavior**
We need to update the dbs3-client version to `4.0.6` and build new releases of our services, and finally deploy them to the production system.

In addition to that:
* WMAgents running on 1.5.7.patch1 need to be patched with
* a new WMAgent patch release needs to be made
* the requirements.txt file needs to be updated as well.

**Additional context and error message**
None

**Comment by vkuznet** [comment]
@amaltaro , even though I thoroughly went through APIs used in DBS3Reader, I don't know if I tested all possible use-cases based on combination of dataset parentage info. There were quite a few APIs which used child/parent info to get the data. Since I compared with DBS production Python server with dbs2go which points to copy of production DB I only used couple of datasets in my tests. The testbed dbs2go is not good for that since it points to integration DBS DB whose content is quite different from production one. Therefore, I suggest that you run validation test from your end (WMA or elsewhere) to test DBS3Reader especially with APIs involved parentage. You may use the following URL: https://cmsweb-testbed.cern.ch/dbs2go which points to copy of production DBS DB but of course it diverged at some point from production DB. Or, you may use https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader (which is again dbs2go server) but it points to DBS integration DB whose content (as I found) quite different. If you inject some data to testbed you can easily test it with this URL. The https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter still runs Python server, therefore your injection should be fine, while DBSReader end-point pots to dbs2go server which uses the same DB as DBSWriter and is suitable to look-up data which you injected. Without knowing exact dataset names it is very difficult to get consistent validation tests. But I did my best to use production DB dataset. For the record I used the following datasets (and therefore its blocks and files): `/VBF1Parked/Run2012D-v1/RAW`, `/ZMM/Summer11-DESIGN42_V11_428_SLHC1-v1/GEN-SIM`.

**Comment by amaltaro** [comment]
@vkuznet I see. It's better than to run some "specialized" checks to make sure that the child/parent related APIs are yielding correct results. I will follow this up in this GH issue: https://github.com/dmwm/WMCore/issues/10842
