### ISSUE TITLE
Put `T3_US_Anvil` in production: Update FNAL agent configuration accordingly

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11014]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Ops decided to use T3_US_Anvil for production. Unified assignment was already updated to include this site in the sitewhitelist of suitable workflows. Now, the only obstacle is that FNAL agents don't know about this site and don't send jobs there.

**Describe the solution you'd like**
Update existing and incoming FNAL agents to include this site in their config.

**Describe alternatives you've considered**
None.

**Additional context**
This isn't urgent, but required. Currently, we have no allocation, but it will come and we'd like to utilize the site as soon as it becomes available. 
@hufnagel  FYI

**Comment by amaltaro** [comment]
As mentioned in the private email, this has been done since January (likely during the FNAL agent deployment). Script `/data/srv/addUSOpportunistic.sh` has been updated accordingly.

However, I think it's time to update the deployment script to bring that script in and make sure that we always include US opportunistic resources during the deployment.
