### ISSUE TITLE
RucioInjector deleting blocks prematurely due to multiple workflows writting on them

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#11244]
**Impact of the bug**
T0 Agent

**Describe the bug**
Current deleteBlocks logic is faulty. In order to delete a block, the component should check that there are no workflows that need the files in the block. Nonetheless, right now it assumes each clock is associated with a single workflow. If only one of the workflows is deletable, RucioInjector deletes the block, even to other workflows may still need it.

Full description of the error can be found here:
https://its.cern.ch/jira/browse/CMSTZ-1001

**How to reproduce it**
Running a replay with 2 runs that share some datasets. You must stop prompt reconstruction workflows for the seconde run. Set DeletionDelay to a short value. After the first run finishes processing, you will see that several blocks will be deleted, including those that are still needed by the second run.

**Expected behavior**
If a block is needed for processing, it should not be deleted

**Comment by germanfgv** [comment]
There is and aditional issue with [GetCompletedBlocks.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/Database/MySQL/GetCompletedBlocks.py). As now we group blocks by workflow too, the line:
```
HAVING COUNT(*) = SUM(dbsbuffer_workflow.completed)
```
no longer ensures all workflows related to the block need to be completed in order for the block to appear in the query

**Comment by germanfgv** [comment]
I think we should remove the `dbsbuffer_workflow.completed` check from [GetCompletedBlocks.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/Database/MySQL/GetCompletedBlocks.py) as this check now is done with [GetDeletableWorkflows.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Workflow/GetDeletableWorkflows.py). What do you think @todor-ivanov ?

**Comment by todor-ivanov** [comment]
> I think we should remove the dbsbuffer_workflow.completed check from [GetCompletedBlocks.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/Database/MySQL/GetCompletedBlocks.py) as this check now is done with [GetDeletableWorkflows.py](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Workflow/GetDeletableWorkflows.py).

Difficult to say immediately. This is tricky, since the check that  you are mentioning to be redundant to the old one is from another table - [GetCompletedBlocks](https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/RucioInjector/Database/MySQL/GetCompletedBlocks.py) performs the check for "all workflows completion"  by looking only into `dbsbuffer_workflow` table, while [GetDeletableWorkflows](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Workflow/GetDeletableWorkflows.py) does its magic by looking into `wmbs_workflow` table. On the other hand we  have already proven that with the current level of granularity of the groups created by the `GetCompletedBlocks` query we do have a faulty logic which needs to be fixed.
