### ISSUE TITLE
Update Dockerfiles to build image from PyPi packages, deprecating the RPM model

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11310]
**Impact of the new feature**
Every single WMCore service

**Is your feature request related to a problem? Please describe.**
This is part of the effort migration to PyPi packaging and the deprecation of RPM-based deployments.

**Describe the solution you'd like**
Once WMCore packages are available in PyPi, we should revisit all the WMCore CMSKubernetes/Dockerfiles and build images based on PyPi (pip install). Directory structure and environment might have to be tweaked.

Note that dependencies still have to be sorted out (e.g., jemalloc, gfal2 tools, rotatelogs, etc), given that PyPi is only meant to manage python-based applications.

**Describe alternatives you've considered**
Likely dependent on this intermediate step: https://github.com/dmwm/WMCore/issues/11309
and this automated packaging and upload to PyPi: https://github.com/dmwm/WMCore/issues/11276

**Additional context**
None

**Comment by vkuznet** [comment]
I reported progress on this issue over here: https://github.com/dmwm/WMCore/issues/11327#issuecomment-1274828413, https://github.com/dmwm/WMCore/issues/11327#issuecomment-1274838526,  https://github.com/dmwm/WMCore/issues/11327#issuecomment-1274847371

The short summary is the following:
```
docker images
REPOSITORY                        TAG            IMAGE ID       CREATED             SIZE
<none>                            <none>         e8c4c7efc2f7   About an hour ago   982MB
veknet/reqmon                     latest         ee58f6b49f92   About an hour ago   1.08GB
veknet/wmagent                    latest         568b7b13b718   About an hour ago   1.39GB
veknet/reqmgr2ms-rulecleaner      latest         6f6dbdd52fcf   About an hour ago   1.18GB
veknet/reqmgr2ms-monitor          latest         ccb1893afe6c   2 hours ago         1.18GB
veknet/reqmgr2ms-output           latest         3bdc3a0912d5   2 hours ago         1.18GB
```
We only have unresolved issue with gfal python package on Debian which is required to build `reqmgr2ms-unmerged` image. All Dockfiles are present over here: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi

**Comment by vkuznet** [comment]
We also may need this https://github.com/dmwm/WMCore/issues/11338 to include into Dockerfiles

**Comment by khurtado** [comment]
@vkuznet JFYI for gfal2, Rucio installs gfal2 on a debian/ubuntu based container via conda:

https://hub.docker.com/r/rucio/jupyterlab/dockerfile

Here is another example:
https://github.com/JColl88/sdc1-solution-binder/blob/fc6b771e5e5549e6356cea88ee0ecc05bf561f63/ska/notebook/Dockerfile#L84-L88

**Comment by vkuznet** [comment]
@khurtado , the Rucio approach does not work for several reasons:
- if I'll use their initial image `jupyter/scipy-notebook` it provides Python 3.10 which is not certified for WMCore
- if I'll use their image in order to copy gfal2 library we deal with shared library issue since it requires boost and python libraries from above image, e.g. here is what I get when I copied gfal2 library from their image to python:3.8 image and tried to load it in python
```
Python 3.8.14 (default, Oct  5 2022, 15:43:08)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gfal2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libboost_python310.so.1.78.0: cannot open shared object file: No such file or directory
>>>
```
In both case we have a problem. There three solutions here:
- use `jupyter/scipy-notebook` but it implies to use their version of python
- build our own version of gfal2 using boost, conda, whatever but it is separate work which I suggest to offload to separate image.
I will try with later to see if it can be done.

**Comment by khurtado** [comment]
@vkuznet hopefully the conda lines in the second example work with a generic debian based container. They use conda for both boost and gfal2 itself

**Comment by vkuznet** [comment]
I managed to build gfal within python debain image. This was done using two-layer proceudre:
- I created independent gfal image based on python image and anaconda, see https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/gfal/Dockerfile 
- Then, I adjusted `reqmgr2ms-unmerged` image to use gfal image as seeder and copied miniconda area into python based image, see https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2ms-unmerged/Dockerfile
- The trick was to deal with `pip install` to avoid installing gfal as dependency. For that, I downloaded `requirements.txt`, and then skipped gfal from it, then I installed all dependencies manually and finally was able to install via pip `reqmgr2ms-unmerged`via pip, please see lines https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2ms-unmerged/Dockerfile#L11-L19
The final build looks like this:
```
docker images
REPOSITORY                        TAG            IMAGE ID       CREATED          SIZE
veknet/reqmgr2ms-unmerged         latest         1db2bed32221   44 seconds ago   2.12GB
registry.cern.ch/cmsweb/gfal      latest         93385e3a2b9f   49 minutes ago   2.42GB
```
And, I tested that I can load both WMcore and gfal2 libraries within newly build image.

The **flaw** with this approach is that we need to use two tags, one is what you tag the python package on pypi, see `TAG`, and another (since the `TAG` value does not exist in github tags) for fetching `requirements.txt` file.

For the reference, here are commits to `gfal` and `reqmgr2ms-unmerged`:
- https://github.com/dmwm/CMSKubernetes/commit/5f8a6c69cf94a583a7364901dba679b9e6ef888b
- https://github.com/dmwm/CMSKubernetes/commit/351a1fccebef6cc94358e16f03217405850b67aa

Please review the proposed image procedure and make your suggestions how to improve it. Due to gfal dependency and cumbersome build I suggest to tag WMCore before putting it on pypi with the same tag. This will eliminate usage of `REQTAG` and we will only rely on `TAG` which will be used in GitHub Action build workflows.

**Comment by vkuznet** [comment]
@todor-ivanov , please notice how easily image size grow by adding only **one gfal** dependency. It added additional 1GB due to the fact that it requires shared libs from boost, etc. Therefore, a simple additional of one dependency can cost you quite a lot in a final image.

**Comment by todor-ivanov** [comment]
Thanks for pointing this out @vkuznet . I have never performed `gfal2` package size  measurements, because: 
* it is a must for this service and I am not aware of an alternative so far
* the `gfal2` dependencies in MSUnmerged have  bad history. At some point we were using the system packages and not building it ourselves. This was leading to a really odd and not quite pleasant way of service setup. So any ideas of substituting this dependency are pretty welcome. 

As of the shared libraries from BOOST, I do not see a way fro them to be avoided, since `gfal2` has no pure python version but instead uses  boost to port its C code in python. I wonder though if nothing could be done for gfal2-python to be compiled in a more cheap way... But as I said I've never done additional investigation on installed package size, so such thing has never been tried actually.

**Comment by vkuznet** [comment]
@todor-ivanov , if gfal code will be statically compiled executable, then we will not have this issue with image. The dependency on shared libraries blow up docker images. And, all python packages which rely on C library, e.g. numpy, scipy, etc. will have the same issue. My point is that choice of language influence the final product (in this case docker image).

**Comment by vkuznet** [comment]
Now, about security and gains. I scanned newly built pypi based image and found the following:
- `reqmgr2ms-output` image has
```
Total: 1218 (UNKNOWN: 1, LOW: 614, MEDIUM: 242, HIGH: 339, CRITICAL: 22)
```
- gfal image Ihas
```
Total: 1186 (UNKNOWN: 1, LOW: 606, MEDIUM: 233, HIGH: 330, CRITICAL: 16)
```
- `reqmgr2ms-unmerged` image which now include gfal stuff has
```
Total: 2622 (UNKNOWN: 0, LOW: 1260, MEDIUM: 1319, HIGH: 43, CRITICAL: 0)
```

This should be compare to RPM based image, e.g. `reqmgr2` which has
```
Total: 2622 (UNKNOWN: 0, LOW: 1260, MEDIUM: 1319, HIGH: 43, CRITICAL: 0)
```

Therefore, by switch from RPM to pypi deployment method we gain:
- about 1/3 in image size, 1GB of reqmgr2ms-output vs 3.5GB of reqmgr2
- about 30% for reqmgr2ms-unmerged image size, 2GB vs 3.5GB
- we reduce number of vulnerabilities by factor of 2 if we not using gfal
- gfal brings back the same amount vulnerabilities we had in RPM based image

Said that, pypi still gives significant gain both in image size and reduces number of vulnerabilities but it is far from what can be achieved by re-writing services in Go (for the record, DAS/WMArchive have 0 vulnerabilities and their image size is 20MB, while DBS has 82 vulnerabilities due to ORACLE shared libs and its image size is close to 800MB).

For the record, the image scans are done using [trivy](https://trivy.dev/) tool which tool (written in Go) which is used by CERN registry portal. You can also find image scans on registry.cern.ch directly or download trivy executable and run it from local node. Please note I used the following options: `trivy image --timeout 10m0s --security-checks vuln <image-name>` which may be different from what is used inside registry.cern.ch service but should be close enough. For example, I saw this warning `'--security-checks vuln' to disable secret scanning` and used this option in my scan, therefore I do not know if secret scanning is enabled on registry.cern.ch and I do not know what it exactly means.

**Comment by vkuznet** [comment]
I uploaded new pypi based images to registry.cern.ch:
- [reqmgr2ms-monitor](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-monitor)
- [reqmgr2ms-output](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-output)
- [reqmgr2ms-unmerged](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-unmerged)
- [reqmgr2ms-transferor](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-transferor)
- [reqmgr2ms-rulecleaner](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2ms-rulecleaner)
- [reqmgr2](https://registry.cern.ch/harbor/projects/1771/repositories/reqmgr2)
- [wmaget](https://registry.cern.ch/harbor/projects/1771/repositories/wmagent)
- [gfal](https://registry.cern.ch/harbor/projects/1771/repositories/gfal)

The images have `pypi` tag and therefore you can use them to install on your k8s dev clusters by using this tag.

**Comment by vkuznet** [comment]
@amaltaro , @todor-ivanov , @khurtado , @goughes please proceed with testing new pypi based images in your dev clusters. So far I only build the images, but I did not test if they have anything useful and more importantly if it can run the service. For your information all Dockerfiles used to produce these images can be found in [CMSKubernetes/docker/pypi](https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi) area.

**Comment by vkuznet** [comment]
@amaltaro ,do we need anything else for this issue. The Dockerfiles for pypi based images are available at: https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi

**Comment by amaltaro** [comment]
I think the last bit that I would like to see fixed before we can declare this task as done, is to have fully functional manage scripts, such that we can perform the very basic operations such as start|stop|restart|status. 
There are some use cases where we might want to test a simple change within the POD, so having the ability to restart the service from within the POD is the only option for such cases.

**Comment by amaltaro** [comment]
For the record, here is a CMSKubernetes fix for dealing with different directory/file permissions, after the logs volume is mounted in testbed/production: https://github.com/dmwm/CMSKubernetes/pull/1295

**Comment by vkuznet** [comment]
@amaltaro , I had a look at test10 cluster where I deployed recent tag, reqmgr2:2.1.6rc4, and the issue is not in manage script per-se, it stop and start the service, but rather that after we stop the service and start it again it miss something which is required to run it, here is the actual error from the log:

```
<@---------- WMException End ----------@>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Service.py", line 150, in __init__
    self["requests"] = requests(cfg_dict['endpoint'], cfg_dict)
  File "/usr/local/lib/python3.8/site-packages/Utils/PortForward.py", line 69, in portMangle
    return callFunc(callObj, url, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 131, in __init__
    self['key'], self['cert'] = self.getKeyCert()
  File "/usr/local/lib/python3.8/site-packages/WMCore/Services/Requests.py", line 469, in getKeyCert
    raise WMException('Request requires a host certificate and key',
WMCore.WMException.WMException: <@========== WMException Start ==========@>
Exception Class: WMException
Message: Request requires a host certificate and key
        ClassName : None
        ModuleName : WMCore.Services.Requests
        MethodName : getKeyCert
        ClassInstance : None
        FileName : /usr/local/lib/python3.8/site-packages/WMCore/Services/Requests.py
        LineNumber : 469
        ErrorNr : WMCORE-11

Traceback:
```
Honestly, I have no idea which certificates should be read and where they should be located, and I hope you can provide some insight about them. Once we identify what are those certificate I think we'll only need either to define some env in manage script to make it run.

**Comment by vkuznet** [comment]
I think I found the issue. If I change in mange script these lines:
```
#export X509_USER_CERT=/data/srv/state/$srv/proxy/proxy.cert
#export X509_USER_KEY=/data/srv/state/$srv/proxy/proxy.key
export X509_USER_CERT=/etc/proxy/proxy
export X509_USER_KEY=/etc/proxy/proxy
```
then it starts the reqmgr2 service. The proxy files in k8s are provided via `/etc/proxy/proxy` and they are not located in `/data/srv/state`. So, my question is do we change X509 env in manage script or need to copy proxy file to `/data/srv/state/$srv/proxy/` are?

**Comment by amaltaro** [comment]
I think this dmwm-base script can answer some of these questions:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/run.sh#L27

for possible environment variables, please refer to the corresponding deployment manage script.

**Comment by amaltaro** [comment]
I'd like to keep the manage and the run.sh script consistent, so the answer is neither of the options above. Instead, it should use the AUTHDIR, as defined in the run.sh script, which I link here as well:
https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/run.sh#L30-L31

I'd appreciate if you can make a PR with the relevant changes and request for a proper review, before pushing changes upstream.

**Comment by vkuznet** [comment]
ok, thanks, here is relevant PR: https://github.com/dmwm/CMSKubernetes/pull/1296

**Comment by amaltaro** [comment]
@vkuznet Valentin, as reported by Todor a few hours ago in this comment:
https://github.com/dmwm/WMCore/issues/11413#issuecomment-1376343339

we are having problems with the t0_reqmon/t0_reqmon-tasks services in CMSWEB testbed.

I just verified that cluster and I see that t0_reqmon pods are running, but it turns out they had a problem when starting up the service. This is what I can see from the logs (skipping some information not suitable to be shared):
```
amaltaro@lxplus8s17:~/CMSKubernetes/kubernetes/cmsweb $ kubectl logs t0reqmon-tasks-6c4678dcfc-vsbsl t0reqmon-tasks -n dmwm
...
chown: cannot access '_t0_reqmon._t0_reqmon': No such file or directory
t0_reqmon not running, not killing
...
```

I had a look at the Dockerfiles and the run.sh script, and I cannot spot any errors that could cause it. I could also confirm that those services are using the latest dmwm-base image (from Jan 6th). Could you please have a look into this?

**Comment by vkuznet** [comment]
@amaltaro , there are two issues:
- issue with chown command in run.sh, see my fix here https://github.com/dmwm/CMSKubernetes/commit/5b8d77ffdec5d07d390699fdea16da161eb6de58
- issue with WMCore code
```
Traceback (most recent call last):
  File "/usr/local/bin/wmc-httpd", line 3, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 617, in main
    server.start_daemon()
  File "/usr/local/lib/python3.8/site-packages/WMCore/REST/Main.py", line 406, in start_daemon
    logger = open(self.logfile, "a+", 0)
ValueError: can't have unbuffered text I/O
```
I saw this issue in my local setup too and it can be fixed by changing
```
logger = open(self.logfile, "a+", 0)
```
to
```
logger = open(self.logfile, "ab+", 0)
```

Since I did not use this code I saw that may be it was a trick somewhere (or different version of python), but the open should have `b` flag to avoid this error. Once I manually fixed both problems I was able to start the service in one of the pods.

**Comment by amaltaro** [comment]
Thanks Valentin.

I created a new `dmwm-base` image and provided a PR to use it in the WMCore dockerfiles:
https://github.com/dmwm/CMSKubernetes/pull/1297

once it gets merged, we can cut another WMCore tag and get the images automatically available.

For the python issue, we have been successfully running all the other services with the same codebase. I suspect the issue is somewhere else. Let's see how it goes with the new image.

**Comment by amaltaro** [comment]
And reason why t0_reqmon wasn't working is that the namespace map was wrong (other than the run.sh fix provided by Valentin). Here is a reference to the services_config changes:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/188

Now we have `2.1.6rc6` deployed to cmsweb-testbed (which includes fix to the manage script).

**Comment by amaltaro** [comment]
Today we completed the migration away from the RPM model, and CMSWEB production services are now running Pypi-based packages (version 2.1.6).
@vkuznet from my side we can now close this issue out. What do you think?

**Comment by amaltaro** [comment]
@vkuznet I think you will agree with me on closing this issue out. In case you do not, please feel free to reopen it. Once again, thanks for driving this migration!
