### ISSUE TITLE
Pull request Jenkins default test always gets marked as failed

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11333]
**Impact of the bug**
WMCore Jenkins

**Describe the bug**
I noticed that even when all the PR tests have succeeded, the PR is still marked as failed (e.g. 1 failing and 3 successful checks), and the `default` check is marked as failed.

**How to reproduce it**
Create any PR and check the final state result provided by Jenkins.

**Expected behavior**
Investigate and fix the logic in Jenkins which is supposed to mark the `default` test as successful or failed. We might want to rename that test as well, if that fixes the problem.

**Additional context and error message**
None

**Comment by d-ylee** [comment]
The reason why the default check failed was because of the JUnit plugin. If the JUnit plugin finds an XML report with failures, it will mark the Job as UNSTABLE, and thus, display FAILED in GitHub. This was also happening in our dmwm/ WMCore-Jenkins setup, but will be fixed with the merging of this: https://github.com/dmwm/WMCore-Jenkins/pull/17

The change was to set `skipMarkingBuildUnstable: true` as one of the JUnit parameters.

**Comment by d-ylee** [comment]
As of this comment, the currently running PR jobs mark default as successful, but will mark unit tests as failed if one of the affected tests fails.

**Comment by amaltaro** [comment]
Haa, indeed! I just checked this PR
https://github.com/dmwm/WMCore/pull/12201
and it is all green!

Finally it is working properly, thanks Dennis! With that, we can close this issue out as well!
