### ISSUE TITLE
Exit code reporting of stepchain job failures to MONIT requires improvement

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#11349]
**Impact of the bug**
Monitoring

**Describe the bug**
When a stepchain job fails, different cmsRuns generate different exit codes. While one of these exit codes indicate the real error, the others indicate that the particular cmsRun couldn't run because the previous one failed. Our MONIT dashboards use ` Chirp_WMCore_cmsRun_ExitCode, ExitCode` classAds to demonstrate the error and in many cases, these fields don't include the main exit code, but rather the `Skipping this step due to a failure in a previous one. (Exit Code: 99108)`

**How to reproduce it**

Please check this JSON file to see an example. 
```
"Chirp_WMCore_cmsRun3_ExitCode": 8021,
```
is the main problem whereas `Chirp_WMCore_cmsRun_ExitCode`, `Chirp_WMCore_cmsRun[4-6]_ExitCode` and `ExitCode` shows `99108`. 

[99108.json.zip](https://github.com/dmwm/WMCore/files/9839338/99108.json.zip)

**Expected behavior**
IMO, MONIT dashboards should use `ExitCode` for exit code monitoring (`Chirp_WMCore_cmsRun_ExitCode` has precedence over `ExitCode`, don't know why) and the agent should report the real exit code in this classAd, not 99108. 

It's also possible to implement this logic in MONIT, but I don't think it's the proper way to do it. IMO, this info should be propagated from central services.

**Additional context and error message**
None

**Comment by vkuznet** [comment]
I can take this issue but I need additional information and guidance. Here are open question for me:
- can someone provide location of codebase which is responsible for stepchain and propagating/setting information in final JSON (attached in description)
  - I found that code 99108 is set only in single place `WMCore/WMSpec/Steps/Executors/CMSSW.py` and the same code sets `'Chirp_WMCore_cmsRun_ExitCode` attribute, but I can't find anywhere in WMCore universe where `'Chirp_WMCore_cmsRun<X>_ExitCode` for different values of X are set
- if we CMS Monitoring should use `ExitCode` I need to know where it is set, and more importably does this place have JSON input which contains previous steps because this information is required to get previous step exit code. If such information is not propagated around I doubt it would be possible to fetch correct exit code
- One way to solve this issue is to take all ExitCode and walk backward the chain to find non `99108` code since all exit codes below have it. This is can be easily done at CMS Monitoring side. 

@amaltaro if we can discuss these topics I can work on this ticket.

**Comment by amaltaro** [comment]
Valentin, it looks like all this chirp'ing exit code logic is available in the module you already mentioned:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L52

If you want to learn how a StepChain workload is built, here is its spec:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StepChain.py

but I don't think you need any of that information on this ticket.

The initial description of this issue isn't very clear to me and I am not sure of where `ExitCode` comes from(?)

The main goal though is to ensure that the job will report `Chirp_WMCore_cmsRun_ExitCode` with the first non-0 exit code from the cmsRunx classads. In case of all cmsRunX had exit code 0, then `Chirp_WMCore_cmsRun_ExitCode` should report 0 as well.

Please let me know if something wasn't answered.

**Comment by vkuznet** [comment]
Any ideas how to simulate the failure in order to test changes to metrics values assignment?

**Comment by vkuznet** [comment]
@amaltaro , I run wmagent_SC_6Steps_PU_Test_issue_11349_v3_230505_122642_9524 WF and it finished without any errors, therefore I'm still stuck to proceed with this issue as I need a WF which will actually fail. You can find the log of my WF in vocms0193, where all `Chrip_WMCore` are set to 0. For the record, this workflow was submitted with the following command:
```
python3 inject-test-wfs.py -m DMWM -c DMWM_Test -r Test_issue_11349_v3 -t testbed-vocms0193 -a DMWM_Test -p issue_11349_v3 -f SC_6Steps_PU.json
```

**Comment by vkuznet** [comment]
ok, here is two more WFs:
- `wmagent_SC_6Steps_PU_Test_issue_11349_v4_230508_164725_4605`
- `wmagent_SC_6Steps_PU_Test_issue_11349_v5_230508_164754_7942`
Let's see how they will go.

**Comment by amaltaro** [comment]
@vkuznet Valentin, I had a look at this job:
```
install/wmagentpy3/JobArchiver/logDir/w/wmagent_SC_6Steps_PU_Test_issue_11349_v5_230508_164754_7942/JobCluster_4/Job_4079.tar.bz2
```

and I think we have the expected behavior now. Here is a grep for the record:
```
cmst1@vocms0193:/data/srv/wmagent/current $ grep 'with result' Job_4079/wmagentJob.log 
2023-05-08 17:20:45,402:INFO:ExecuteMaster:StepName: cmsRun1, StepType: CMSSW, with result: 0
2023-05-08 18:45:45,771:INFO:ExecuteMaster:StepName: cmsRun2, StepType: CMSSW, with result: 0
2023-05-08 19:01:06,209:INFO:ExecuteMaster:StepName: cmsRun3, StepType: CMSSW, with result: 8028
2023-05-08 19:01:06,226:INFO:ExecuteMaster:StepName: cmsRun4, StepType: CMSSW, with result: 99108
2023-05-08 19:01:06,239:INFO:ExecuteMaster:StepName: cmsRun5, StepType: CMSSW, with result: 99108
2023-05-08 19:01:06,254:INFO:ExecuteMaster:StepName: cmsRun6, StepType: CMSSW, with result: 99108
2023-05-08 19:01:06,342:INFO:ExecuteMaster:StepName: stageOut1, StepType: StageOut, with result: 0
2023-05-08 19:01:12,036:INFO:ExecuteMaster:StepName: logArch1, StepType: LogArchive, with result: 0
```

I also unpickled the Report.0.pkl file and it looks good as well.
In addition, report in WMStats is look Okay too.

Lastly, from the logs, I believe chirp commands are also providing the correct information.

Feel free to remove your debugging commit from the PR. Then we can follow up with further review. Thanks!

**Comment by vkuznet** [comment]
ok, I'm glad to hear it worked this time. I removed the logging and squashed commits. Please proceed with review and merge.
