### ISSUE TITLE
Naming convention of the campaigns

### ISSUE THREAD

**Issue by sunilUIET** [dmwm/WMCore#11344]
Hi

We created campaigns [1] recently and passed the validation step successfully. But while the pilot there was a failure complaining about the naming conventions i.e. campaign names can not start with numeric as discussed in [2]. If there is no serious issue with the setup, we would like to remove this constraint on the naming convention of the campaigns. 

Thanks!

Sunil (for pdmV), @bbilin @kskovpen

[1]
https://its.cern.ch/jira/browse/PRCAMPAIGNS-321
https://its.cern.ch/jira/browse/PRCAMPAIGNS-322
https://its.cern.ch/jira/browse/PRCAMPAIGNS-323

[2]
 https://its.cern.ch/jira/browse/PRCAMPAIGNS-321

**Comment by amaltaro** [comment]
@sunilUIET Hi Sunil, thanks for creating this issue.

From one of the JIRA tickets, I see that Hasan managed to identify and explain what the problem is. 

To add to that, a workflow campaign gets validated with this regular expression:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L308

unfortunately, we do not have the same validation for campaigns created in WMCore.

Given that a campaign is defined in Unified, and then propagated to WMCore, I think we will have to apply the same regex validation on the Unified side, such that these problems can be spotted right at the beginning (and we should also implement the same validation on the WMCore side).

Is there any strong reason blocking us from renaming that campaign `2022CommissionGS` to `CommissionGS2022`? Or anything that would fulfill the regular expression?

We apologize for the extra work that this causes.

**Comment by amaltaro** [comment]
@haozturk Hi Hasan, is it something that you could easily implement on the unified side? While we work on unifying these campaign definitions among the systems.

**Comment by amaltaro** [comment]
@sunilUIET @haozturk do you know if this ticket is still relevant? Has Unified enforced any campaign name validation?

**Comment by sunilUIET** [comment]
@amaltaro I think we can close this issue
