### ISSUE TITLE
Update HTCondor python bindings for WMAgent to the 9 series

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11402]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Starting from May 2023 the 9 series of HTCondor python bindings are  about to be deprecated. The current issue is intended to keep track of the migration process for WMAgent.  

**Describe the solution you'd like**
Migrate to the latest version 

**Describe alternatives you've considered**
It must be done

**Additional context**
None

**Comment by Farrukh-Aftab** [comment]
FYI, WMAgents are actually using HTCondor 8:
```
# condor_q -limit 1 -af condorversion
$CondorVersion: 8.9.7 May 20 2020 BuildID: UW_Python_Wheel_Build $
```

From the HTCondor schedd perspective, we will be moving to HTCondor 10. The WMAgents are packaging their own HTCondor python bindings so ideally we should upgrade there too.

HTCondor 10 does not support GSI, so the proxy will just be forwarded along with the job and it won't be used to authenticate with the schedd anymore. At Fermilab, we will provide the `cmsdataops` user an IDToken to submit to the scheduler. We can have a testbed agent (submit1 or 2 for example) upgraded if you'd like to test things

**Comment by khurtado** [comment]
Hi @farrukh-aftab-khan 
When you say `8.9.7`, do you mean just the python bindings from WMAgent, or is there anything else that needs an update, besides the WMAgent condor schedd?

We get them from pip and can update if necessary.
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py3-htcondor.spec

When is the HTCondor 10 update planned? It would be good to test in ITB to see if the update is urgent for Q1,  otherwise, if things are functional with the current python binding version and a schedd update,  we can move this to Q2.

**Comment by farrukh-aftab-khan** [comment]
Hi @khurtado 

Lucas Azevedo from my team is working on setting up a schedd with GSI disabled and HTCondor 10 on it. He should reach out to you guys early next week so you can test things. Everything in principle should work out of the box without any major modifications from your side (i.e. you don't necessarily have to move away from 8.9.7 but it would be a good idea to do since 8.9.7 is quite old).

We (Fermilab) are tentatively look at upgrading the production schedds before end of March this year. CERN schedds will probably follow their own schedule. It is up to you guys to decide when you want to move away from 8.9.7 because that's internal to how the WMAgent is packaged.

Farrukh

**Comment by khurtado** [comment]
Since the current python bindings ([version 9.2.0](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condorpy3.spec)) is compatible with HTCondor 10.0.1 (tested both at CERN and FNAL), we consider the investigation on this issue finished and I'm closing this ticket. 

We don't need to update the python bindings at this point (this quarter). However, I made an issue to update it for the next quarter, since it would be good for both version to be at the same v10 level:

https://github.com/dmwm/WMCore/issues/11464

**Comment by amaltaro** [comment]
I was debugging why a `schedd.xquery` isn't returning the requested `ServerTime` classadd attribute for running jobs and it might be related to incompatibilities between python bindings and the schedd itself. @belforte you might want to check whether it affects you.

Coming back to the python binding condor versions, it is actually confusing in the cmsdist comp_gcc630. The reason for that is that we actually have 2 different spec files:
1) [condorpy3](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condorpy3.spec), in version 9.2.0
2) [py3-htcondor](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py3-htcondor.spec), in version 8.9.7

where, according to the current cmsdist/comp_gcc630, this is how we are using it:
* `py3-htcondor` is used by `crabserver` and `wmagentpy3`
* `condorpy3` is used by `crabtaskworker` and `t0`

I think we should all converge to using `py3-htcondor` and deprecate `condorpy3`. We might want to upgrade `py3-htcondor` spec to version `9.2.0` as well, before taking a larger jump to 10.x series.

**Comment by amaltaro** [comment]
Great! Thank you for this information, Farrukh!
