### ISSUE TITLE
Validate workflow run lists (RunWhitelist and RunBlacklist)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11466]
**Impact of the bug**
ReqMgr2

**Describe the bug**
As reported by the P&R in this GitLab ticket:
https://gitlab.cern.ch/CMSToolsIntegration/operations/-/issues/9#note_6390478

ReqMgr2 does not validate the data type for the request level parameters: `RunWhitelist` and `RunBlacklist`, which can be either at top level or at the task/step level as well.

**How to reproduce it**
Inject a workflow providing a list of runs with the format of `["123"]` instead of `[123]`

**Expected behavior**
The run list must be a list of integer values. So, we need to ensure that parameters RunWhitelist and RunBlacklist are properly validated before a workflow gets accepted by ReqMgr2.

This needs to be considered for all workflow types used in production (ReReco, TaskChain and StepChain).

**Additional context and error message**
None

**Comment by vkuznet** [comment]
@amaltaro , I assigned this issue to myself and in order to proceed I need further clarification about expected changes:
- do you want to validate only `RunWhitelist` and `RunBlacklist` or do you want to have general validation function for provided workflow?
- should validation through an error if parameter is a wrong data-type or should it correct its value, e.g. in gitlab ticket you provided example `"RunWhitelist": ["362439"]`, so what would be expected behavior, should we through an error or convert values from strings to ints?
- does this validation should touch only StdSpecs or any other parts of the WMCore codebase. So far I found the following files which has `RunWhitelist`:
   - src/python/WMCore/MicroService/MSTransferor/RequestInfo.py
   - src/python/WMCore/MicroService/MSTransferor/DataStructs/Workflow.py
   - src/python/WMCore/WorkQueue/Policy/Start/Block.py
   - src/python/WMCore/WorkQueue/WMBSHelper.py
   - src/python/WMCore/WorkQueue/Policy/Start/Dataset.py
   - src/python/WMCore/ReqMgr/Tools/cms.py
   - src/python/WMCore/WMSpec/WMWorkload.py
   - src/python/WMCore/WMSpec/StdSpecs/TaskChain.py
   - src/python/WMCore/WMSpec/StdSpecs/DataProcessing.py
   - src/python/WMCore/WMSpec/StdSpecs/StdBase.py
   - src/python/WMCore/WMSpec/StdSpecs/StoreResults.py
   - src/python/WMCore/WMSpec/StdSpecs/StepChain.py
   - src/python/WMCore/WMSpec/WMTask.py
and, I will expect that `RunBlacklist` will appear in the same files
- Taken into account above questions, do we need a common function to apply at every single file, or we should provide some validator for StdSpecs, or anything else.

**Comment by amaltaro** [comment]
@vkuznet Hi Valentin, answer to your questions are:
1) yes, we need to validate both `RunWhitelist` and `RunBlacklist` (as written in the original issue description)
2) we should NOT fix values in place. Instead, the request should fail (HTTP 4xx) and an exception needs to be raised. Looking into StdBase, this seems to be the way to handle it:
https://github.com/dmwm/WMCore/blob/02f70c36892c146546a7eeec5d3e4fda4b278682/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L933
3) changes need to be done only for the Spec factories, those are: StdBase.py, TaskChain.py and StepChain.py. Note that each spec has a different schema, such as:
* StdBase: those two fields are available in the top level dictionary.
* TaskChain/StepChain: RunWhitelist/RunBlacklist can be in an inner dictionary (Task1 or Step1).

I see two possible places to implement this validate function, either here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Utils/Validation.py
or in StdBase.py

**Comment by vkuznet** [comment]
Alan, thanks for clarification, I need you to look quickly (not a review, just check the logic) into this PR https://github.com/dmwm/WMCore/pull/11535 and tell me if it is what you expect.
