### ISSUE TITLE
deleteRule function from Services/Rucio/Rucio.py should cancel all the FTS request prior to the deletion

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/WMCore#11486]
**Impact of the new feature**
WMAgent and any system that use this functionality in WMCore
**Is your feature request related to a problem? Please describe.**
This is related to a huge storm in FTS request when a campaign staging out `Parking*` data from CERN_Tape was aborted. See the attached image for Submitted FTS request for Parking*
When a wf is aborted, the rule can be deleted by MSRuleCleaner if a dataset is no longer required/locked by any other workflow in the system. But this requires a perfect communication between 3 layers of the system MSRuleCleaner-Rucio-FTS. Lets take for example a rule that is still in replicating/stuck/injecting state
Rucio use the following core function to [delete](https://github.com/rucio/rucio/blob/8c640c503ef0f432cd682db8489de567aaf86823/lib/rucio/core/rule.py#L842) a rule. The last part of that function shows that :
```
for transfer in transfers_to_delete:
    transfers_to_cancel = request_core.cancel_request_did(scope=transfer['scope'], name=transfer['name'],
                                           dest_rse_id=transfer['rse_id'], session=session)
    transfer_core.cancel_transfers(transfers_to_cancel)
```
That in few words mean: Rucio will try to cancel the on-going requests, assuming that there’s not other similar rule. There’s is no absolute guarantee that the requests will be cancelled. Meaning that, if the cancellation request to FTS fails, Rucio won’t make a second attempt. _Orphans_ FTS request (fts requests on which replicating/stuck rule was deleted) will process it until it reaches some terminal state will remain in the system.

This could be a potential issue if a campaing requiring a huge amount of data from Tape is created by mistake and then is aborted. Probably the same issue is happening when all the input data is not 100% replicated for a campaign and is cloned. 
**A clear and concise description of what you want to happen.**
Before MSRuleCleaner delete the rule, must check the state of that rule. If MSRuleCleaner needs to delete rules that are in state `Replicating/Stuck/Injecting` first the rule must be updated with `update_replication_rule(rule_id=rule,options={'state':'suspended','cancel_requests':True})` and once Rucio server returns True, proceed to delete the rule. For rules that are in state `Ok` is safe to proceed with the current logic.
**Describe alternatives you've considered**
Other alternative will be to modify the loop inside the function [delete rule](https://github.com/rucio/rucio/blob/8c640c503ef0f432cd682db8489de567aaf86823/lib/rucio/core/rule.py#L842) to raise an exception if all the FTS request are not cancelled but currently the exception for that function are rule not found and rule can't be deleted because is locked.

**Additional context**
Distribution of submitted request at Feb 13th-2022 
[Submitted fts_request that match wmcore_input + _store_data_Run2022*_Parking*.pdf](https://github.com/dmwm/WMCore/files/10737375/Submitted.fts_request.that.match.wmcore_input.%2B._store_data_Run2022._Parking.pdf)

**Comment by amaltaro** [comment]
@jhonatanamado Jhonatan, thanks for creating this issue and kicking off this discussion.

My very first thought when I read it is that, having the correct communication with FTS and properly dealing with those tasks is up to the Data Management tool (Rucio). The internals of Rucio rule deletion and required actions - and possible retries - should not be exposed to the clients, but it should be gracefully dealt with from Rucio itself.

Making an extra (blocking?) HTTP request to Rucio, from MSRuleCleaner, should not be a big problem for us. However, I strongly believe that this would not be the right way to solve it. In addition, this problem must be common among other Rucio clients, so having a proper fix implemented within Rucio would be beneficial to all the Rucio community.

**Comment by todor-ivanov** [comment]
Hi @jhonatanamado reading this 7 hours after @amaltaro, I can 100% agree with him. 
And to add to this, I wouldn't rely on a blocking HTTP request because this could be dangerous to our component, but rather develop a retry mechanism inside `MSRuleCleaner`, but that is just a minor (implementation) detail, what bothers me more here is the dealing with `Stuck` rules. 

You yourself, are already well aware that we can badly suffer from transfers in this states in other corners of the system. Starting to treat rules differently by status, means we immediately get ourselves tied to bottlenecks outside WMCore (in this case between RUCIO and FTS). Bottlenecks on which we have no control what soever. The end result will be, if for some reason, a massive pile of transfers get stuck due to the mechanism explained above, that would result in a massive pile of Workflows stuck in WMCore and unable to progress through the workflow state chain. This may cause various long term issues, because many of those my stay unnoticed for long periods. This would produce hidden islands of constantly occupied parts of the system by some workflows stuck there for reasons belonging to a component outside our realm.      

And just to add some examples, covering our past experience:

Here [[1]](https://github.com/dmwm/WMCore/blob/fea1de4119a9091233f3e6414f33f069971b5a74/src/python/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py#L333-L342),  we already do check if the tape transfers for an `announced` workflow are completed and we hold the workflow for archival while they are in any transient status. Unfortunately this we cannot avoid, because otherwise we risk data loss. And we've already seen how it did follow exactly the scenario from above. So I'd be really careful before adding the same mechanism also for all workflow statuses  `MSRuleCleaner` deals with (i.e. `announced`, `aborted-completed`, `rejected`).

  


[1]
https://github.com/dmwm/WMCore/blob/fea1de4119a9091233f3e6414f33f069971b5a74/src/python/WMCore/MicroService/MSRuleCleaner/MSRuleCleaner.py#L333-L342

**Comment by todor-ivanov** [comment]
And thinking about this twice now. It could be even worse. 

Now imagine that by changing the condition under which the deletion of data happens a deadlock situation is created between FTS and RUCIO (I know I am talking about extreme scenarios here, but I believe such things shouldn't be overlooked). This being out of our system would be impossible to debug. While at the same time it will not create only islands of constantly occupied parts in WMCore, but we may slowly fill up the system and start experience various and strange saturation effects which would be difficult to relate to something that happens outside our scope.

**Comment by amaltaro** [comment]
Given the arguments not to implement it in WM, and the lack of activity on this ticket for half a year, I am going to close it out as not planned.
Please reopen it if there is anything important that we are missing. Thanks!
