### ISSUE TITLE
ArchiveDataReporter component not reporting jobs to WMArchive

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11516]
**Impact of the bug**
WMAgent

**Describe the bug**
As it has been reported in this JIRA ticket:
https://its.cern.ch/jira/browse/CMSMONIT-526

WMArchive monitoring is missing job information from many of the agents. I understand that Valentin and others already checked the service itself and there are no apparent problems, so the issue is likely on the data producer (WMAgent).

ArchiveDataReporter component does not report any issues in the logs, but something is causing it not to be able to fetch job documents from CouchDB (i.e., it must mean that the Couch view does not return any data).

**How to reproduce it**
No clue. There are no changes to the codebase that should have caused this.

**Expected behavior**
ArchiveDataReporter component should properly report every single completed job in the agent, but for some reason some of the agents are not (as I was creating this ticket, I think only submit3 and vocms0255 were properly reporting it).

**Additional context and error message**
Potentially related to the large documents that JobAccountant fails to write to CouchDB: https://github.com/dmwm/WMCore/issues/11342

Scanning all the logs of the agents, I see a the following errors in the logs:
* ErrorHandler: every now and then hitting a `CouchInternalServerError` when changing a job state
* JobAccountant: every now and then failing to write a document to local CouchDB (issue 11342, above)
* ArchiveDataReporter: seems to be properly executing its cycles, but for some reason no job documents are coming its way.

**Comment by amaltaro** [comment]
For the record, I restarted all the components in vocms0254, vocms0256, submit3, submit4, submit5 and the component seems to be properly updating documents to WMArchive now. Issue is obviously not understood and fixed though.

**Comment by vkuznet** [comment]
@amaltaro , in order to investigate this issue properly I need the following information from you:
- which codebase is used by ArchiveDataReporter?
- according to its ComponentLog there are messages where it successfully find docs and vice versa:
```
Found 0 not archived documents from FWRJ db to upload to WMArchive.
...
Found 723 not archived documents from FWRJ db to upload to WMArchive.
```
therefore, the question is where this daemon gets its docs? Please provide a description, or diagram to understand the data flow logic.
- in order to trace document propagation to MONIT it would be desired to adjust one WMA to make more verbose printouts, e.g. dump document ID or entire JSON, which later can be used to match with documents in MONIT. If is allowed please specify which agent I can touch for that.

**Comment by vkuznet** [comment]
@amaltaro , in order to investigate this issue properly I need the following information from you:
- which codebase is used by ArchiveDataReporter?
- according to its ComponentLog there are messages where it successfully find docs and vice versa:
```
Found 0 not archived documents from FWRJ db to upload to WMArchive.
...
Found 723 not archived documents from FWRJ db to upload to WMArchive.
```
therefore, the question is where this daemon gets its docs? Please provide a description, or diagram to understand the data flow logic.
- in order to trace document propagation to MONIT it would be desired to adjust one WMA to make more verbose printouts, e.g. dump document ID or entire JSON, which later can be used to match with documents in MONIT. If is allowed please specify which agent I can touch for that.

**Comment by vkuznet** [comment]
@amaltaro , in order to investigate this issue properly I need the following information from you:
- which codebase is used by ArchiveDataReporter?
- according to its ComponentLog there are messages where it successfully find docs and vice versa:
```
Found 0 not archived documents from FWRJ db to upload to WMArchive.
...
Found 723 not archived documents from FWRJ db to upload to WMArchive.
```
therefore, the question is where this daemon gets its docs? Please provide a description, or diagram to understand the data flow logic.
- in order to trace document propagation to MONIT it would be desired to adjust one WMA to make more verbose printouts, e.g. dump document ID or entire JSON, which later can be used to match with documents in MONIT. If is allowed please specify which agent I can touch for that.

**Comment by vkuznet** [comment]
If I read code correctly then the ArchiveDataReporter is located in `src/python/WMComponent/ArchiveDataReporter` and it uses `src/python/WMComponent/ArchiveDataReporter/ArchiveDataPoller.py` which by itself gets docs from `src/python/WMCore/Services/FWJRDB/FWJRDBAPI.py`  via `getFWJRByArchiveStatus` from `reportsByArchiveStatus` CouchDB view. @amaltaro , Is it correct? If so which CouchDB is used to fetch this docs?

**Comment by vkuznet** [comment]
And, I want to know how docs appear in CouchDB, i.e. I need to know data-flow where FWJR docs are injected into couch.

**Comment by vkuznet** [comment]
I see the following scenarios which can lead to this error:
1. there is an issue with codebase ArchiveDataReport which by some reason skip, drop documents
2. there is an issue with fetching documents from CocuhDB
3. there is an issue with injecting documents to CouchDB from external process, if so I need to know which process inject docs to CouchDB itself.

**Comment by vkuznet** [comment]
Here is technical detail about Couch calls on FNAL WMA submit5 which is done by `ArchiveDataPoller.py` who gets docs from `WMCore/Services/FWJRDB/FWJRDBAPI.py` via `getFWJRByArchiveStatus` function call from `reportsByArchiveStatus` CouchDB view.
```
curl -X POST \
    -H "Content-type: application/json" -d '{"keys":["ready"]}' "http://XXX:YYY@localhost:5984/wmagent_jobdump%2Ffwjrs/_design/FWJRDump/_view/reportsByArchiveStatus?include_docs=true&limit=1000&stale=update_after"
# which returns
{"total_rows":183586,"offset":0,"rows":[
]}
```
so, it means that there is no documents in `ready` status in this WMA. That's why we do not have any documents to send to WMArchive. The question is why we do not have any docs in `ready` state out of 183K documents?

**Comment by vkuznet** [comment]
@amaltaro , I would appreciate if you'll make a comment on my observation (above posts) and suggest how we should proceed.

**Comment by amaltaro** [comment]
I need to check things myself in submit5, but I won't be able to do so for the next couple of hours.

Regarding your last comment, it should not take more than 5min to get at least one job in this "ready" status. The agent is completing jobs every minute.

So, the three suggestions I can make right now are:
1) test the very same query in a different agent (set `limit=2` though, not to get an avalanche of data). You should be able to retrieve data after 2 or 3 random attempts
2) I would remove the "keys" filter and see what gets returned by the view (again, decrease the limit)
3) you might want to check who is setting that attribute/document to `ready` status. I would say it's something in JobAccountant (or a default value), but I am not 100% sure.

**Comment by vkuznet** [comment]
I checked 3 agents, submit3, submit5 and vocms0255 and I found the following using this query
```
curl -s "http://${creds}@localhost:5984/wmagent_jobdump%2Ffwjrs/_design/FWJRDump/_view/reportsByArchiveStatus?stale=update_after&limit=10000" | jq '.rows[].key'
```
- submi5 has 98K in uploaded state and around 1.3K in skip state
- submit3 has almost 66K in skip state and 33K in uploaded state
- vocms0255 has 71K in skip state and 28K in uploaded one

If I'll perform recurrent queries I can find ready state too but it is in < 1K range on vocms0255. Few questions here:
- how many states do we have and what is their transition?
- why submit3 and vocms0255 has 2/3 in skip and 1/3 in uploaded state while submit5 has almost 100% in uploaded

From this observations I may conclude that submit5 has some issue with state transition of docs. I checked WMCore/WMComponent codebase for `ready` and `uploaded` keywords but I found nothing where they are used to set anything in docs. I bet that such state comes from elsewhere, e.g. FWJR.

**Comment by vkuznet** [comment]
After further investigation, the `key=ready` is assigned to docs which have `jobState=success`, `jobType=Production` and `archiveStatus=ready` and we can look at this job state progress in couchdb log using the following query:
```
grep "newstate=success" install/couchdb/logs/couch.log | grep 2023-03-28 | wc -l
```
So, here are the stats for today for 3 agents:
- vocms0255 has 17991
- submi3 has 35343
- submit5 has only 460

the issue is clear, somehow submit5 agent has very little progress for successful jobs. And, for the record the `ready` state is set by `JobStateMachine.ChangeState` over here: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobStateMachine/ChangeState.py#L345-L359

**Comment by vkuznet** [comment]
I played with opensearch/ES and I found few inconsistencies. I requested further investigation from @mrceyhun in https://its.cern.ch/jira/browse/CMSMONIT-526 ticket. At the moment I only observe some trend that submit5 under-reporting docs but since we still have docs from it I rule out possibility that it is an issue with either WMArchive or WMCore ArchvieDataReporter codebase and I rather think it is related to CouchDB misbehavior on this agent. Still, we need to understand why WMArchive records with T1 sites are very low and for that I requested @mrceyhun assistance to investigate data in ES and/or HDFS.

**Comment by vkuznet** [comment]
With @mrceyhun help we now have clear picture that submit5 agent misbehaving all month long, the first plot shows 4 agents (submit3,4,5 and vocms0255) for all sites and second plot including T1 in steps:
![agents](https://user-images.githubusercontent.com/125138/228570678-a316a55a-5cf9-48d6-8242-4ca598efdf5d.png)


![agents_t1](https://user-images.githubusercontent.com/125138/228570717-d865c9d0-0a3e-4ed4-88b2-935b10814bad.png)

As you can see contribution of submit5 is very tiny.

**Comment by vkuznet** [comment]
Thanks to Ceyhun we now have full view over 1 year of data for 4 WMAgents (submit3,4,5 and vocms0255).
![Screen Shot 2023-04-04 at Apr 4, 7 46 58 AM](https://user-images.githubusercontent.com/125138/229783917-25245ed1-ab81-4065-a967-eb14161b2059.png)
As you can see from plot above, we do see patterns of activity between different agents, e.g. submit5 agent was active in April'22 and Oct'22 but in any other ranges, etc. I think it will be extremely useful to have such profile of agents activities as it clearly indicate the problem. We have something in a system which prohibit an agent to behave steadily during a long period of time and this problem alternates agents, i.e. it comes from one agent to another. I think the issue with large FWJR which stops agent from processing is primary candidate for such abnormal patterns.

**Comment by amaltaro** [comment]
@vkuznet we do not run the same agent without downtime, this is why we actually have many spare nodes available, such that we can rotate them. There is no specific pattern as well, but the closest we could say is that an agent runs for 2 or 3 months then remains down for another 2 or 3 months.

Having said that, the plot above looks expected and normal to me.

**Comment by amaltaro** [comment]
Moving this one from Q1 to Q2 as well, already a work in progress item.

**Comment by vkuznet** [comment]
@amaltaro , I'm not sure what else we can do with this issue except fixing large docs injection to couch, either by changing couch limits or zipping the docs. Please advise on next steps to move forward with this issue.

**Comment by amaltaro** [comment]
@vkuznet I think the next step depends on me in getting the 2nd part of the fix for https://github.com/dmwm/WMCore/issues/11342 in place. I will try to get to that tomorrow or the day after it.

**Comment by amaltaro** [comment]
It's been a few weeks that this issue does not show up. I am almost sure that the fix provided here (with the very large documents clogging JobAccountant):
https://github.com/dmwm/WMCore/pull/11502
was actually the root cause for this.

@vkuznet Valentin, I am closing this out. But please reopen it in case I missed anything and/or if we spot ArchiveDataReporter issues again in the coming weeks. Thanks!
