### ISSUE TITLE
Create base docker image for WMAgent based on Red Hat flavor

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11565]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
This is one of the first steps towards running WMAgent in a containerized environment.

**Describe the solution you'd like**
Similar to the `dmwm-base` image:
https://github.com/dmwm/CMSKubernetes/tree/master/docker/pypi/dmwm-base

we should create another base image to be used by WMAgent (and maybe in the future replace the Debian based dmwm-base one).

This is required to increase compatibility with the current WLCG grid resources that provide mostly SLC7 and will soon move to Alma8/RHEL8/SC8

Relevant Dockerfile needs to be provided to the CMSKubernetes repository and image uploaded to the CERN registry.

Note that once the image is stable, we need to label it accordingly to avoid automated registry cleanup.
Valentin says that the policy is: tag needs to have a `-stable` suffix.

**Describe alternatives you've considered**
Use the `dmwm-base` image

**Additional context**
None

**Comment by vkuznet** [comment]
A couple of observations which you may encounter with CC7/A8/RH8/SC8:
- it is very outdated and it means that default Python version will be very old, therefore you'll have few options:
  - either build Python by yourself (preferable in this case), or
  - use some RPM but it will require to find proper RH repo which will provide correct version of python, this will also lead to
     - blow up dependencies due to RPMs
 - similar to Python you'll need to handle pip as it is required now to manage WMCore deployment
 - because you'll need python, you'll need to install gcc and glibc, openssl, etc. where again you'll have again the same problem, i.e. either to build them manually or using RPMs (and finding proper repos to get proper versions)
 - So far no-one literally made any argument why CC7/A8/RH8/SC8 are required. In my view, we only need python and as such it can run on any distributions. We do not do precise calculations like CMSSW does, and therefore any distributions can be used to run Python code. 

A specific reason I chose Debian for k8s images is that we can pick Python based image, i..e. debian with python 3.8, or 3.10 or any other python, and start from it. This eliminates aforementioned issues. And, as we run in production all WMCore based services we have already a proof that WMCore code runs just fine with it. Moreover, a new version of Debian has much less security vulnerabilities than outdated CC7, etc., and much less dependencies. In fact, from security point of view, the smaller and more constrained image you start with, the less dependencies you have the more secure the image.

Another suggestion is to break WMAgent image into series of images:
- image for MariaDB
- image for CouchDB
- image for pure WMAgent code
   - better solution would be image for individual component, e.g. JobArchival and nothing else.

**Comment by khurtado** [comment]
@todor-ivanov , @amaltaro and I were discussing about this, so here is a summary:

One of the tasks that WMAgent performs is creating a sandbox with WMCore dependencies for the WM runtime code that later is executed in the Worker node, which will be: CC7, CC8, CC9 in the future, etc.

https://github.com/dmwm/WMCore/blob/31d65166dc62c7251edd52890bc4ac2f0b79d7fe/etc/submit.sh#LL183C1-L183C1

To that end, we need to be sure that WMCore.zip that is created from the WMAgent container (e.g.: debian) is compatible with the worker node (CC7,8,etc). 

The conclusion (to me) was that, since everything in the WMCore.zip is python files, the operating system does not matter, but rather the python version we are using. But even in the case we spot any dependency error during  the validation process, it's better to focus on fixing it/them, rather than trying to accommodate for the same linux flavor for both WMAgent and worker containers, since these can differ in versions (CC7, CC8, CC9) or even architectures anyway. 

The main advantage is what Valentin mentioned, we can use `FROM python:<version>` and get all of what we need to get that version working for free already, regarding libraries, python build version, etc.

@amaltaro @todor-ivanov  : Please, let me know if you agree.

**Comment by todor-ivanov** [comment]
hi @khurtado  I agree with you. 
@amaltaro  since we have advanced quite a lot with the Debian based docker image for `WMAgent` and all WMcore packages in particular are now completely independent from the old rpm packages uploaded to `cmsdist`, I suggest we close that issue as resolved. We can always reopen it if we observe any hiccups during the final tests and validations of workflows run through the docker based containers, but I doubt we will have the need to.

**Comment by todor-ivanov** [comment]
thanks @amaltaro
