### ISSUE TITLE
Investigate the meaning of Status:Removed jobs with ExitCode 0

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11614]
**Impact of the new feature**
While looking at the usage of resources per job and workflows, we realized we sometimes see jobs that were removed by the system but had an exit code:0, meaning it was sucessful (as if the job finished completely). We need to understand the reason.

**Is your feature request related to a problem? Please describe.**
It is important to understand this to fully understand the number in the dashboard below:
https://monit-grafana.cern.ch/d/ifXAfjLVk/production-jobs-exit-code-monitoring

**Describe the solution you'd like**
To investigate the meaning of this case

**Describe alternatives you've considered**
None

**Additional context**

**Comment by khurtado** [comment]
Just for context, [here](https://es-cms.cern.ch/dashboards/app/discover?security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-18T09:00:00.000Z',to:'2023-06-18T10:00:00.000Z'))&_a=(columns:!(Type,Status,JobFailed,ExitCode),filters:!(),index:d2ea6f80-d2e0-11ed-bdae-e3cf8c07f2fc,interval:auto,query:(language:lucene,query:'Type:production%20AND%20Status:Removed%20AND%20JobFailed:0%20AND%20RemoteWallClockTime:0'),sort:!())) is an example:

**Comment by khurtado** [comment]
Additional context: 
This issue is related to #11605 

An issue was created in order to display the answer to this question and because if someone wonders about this, github is easier to search than a google document.

The reason for this is that `ExitCode` in monit, is calculated in the following way: It tries to use `JobExitCode`, `Chirp_CRAB3_Job_ExitCode` (both are from analysis jobs), `Chirp_WMCore_cmsRun_ExitCode`, `ExitCode`, in that order, but if none exist, it defaults to `0`. 
@amaltaro I don't know if this is the right exit code, or if we should request something else to be put as ExitCode (`-1`?), but this would be the explanation of the removed jobs with exit code 0

Link:
https://github.com/dmwm/cms-htcondor-es/blob/c0a07da1776f8e379ef08c320f71cd657283d191/src/htcondor_es/convert_to_json.py#L1145-L1159

**Comment by amaltaro** [comment]
> @amaltaro I don't know if this is the right exit code, or if we should request something else to be put as ExitCode (-1?), but this would be the explanation of the removed jobs with exit code 0

Yes, I think it makes sense to stop declaring jobs without any exit code to be considered exit status = 0.
However, for that we need to make sure that both WMAgent and CRAB always set A exit code. For instance, the `Chirp_WMCore_cmsRun_ExitCode` is only set if a job invokes CMSSW, which is not the case for *at least* `Cleanup` jobs.

@mapellidario @belforte do you know if CRAB jobs - that run to completion - always define an exit code?

**Comment by belforte** [comment]
>  if CRAB jobs - that run to completion - always define an exit code?

that's the idea. If not, it is a bug, and we will have to fix it :-)
I think that here we see cases when spider use condor exit code, which is 0 unless job was preempted or otherwise failes very miserably.

**Comment by khurtado** [comment]
@amaltaro @belforte For condor to inject `ExitCode` as part of the classads, the runtime at the worker needs to finish. Preempted or killed jobs that didn't get to fully run won't have `ExitCode` in the job classad, but the spider sets those preempted/kill cases to `ExitCode=0`. Should we agree on a different exit code for those cases? E.g.: `-9999` or `-1`, etc?

**Comment by mapellidario** [comment]
Hello Alan, we CRAB team recently investigated a similar topic in https://github.com/dmwm/CRABServer/issues/7571

Long story short:

- CRAB uses WMCore to parse the FWJR.xml and obtain a json/python dictionary
- If the job fails and the report xml does not contain anything, the json/dict contains `exitCode=0` (if the job fail abnormally, i think `self.listSteps()` is empty in https://github.com/dmwm/WMCore/blob/eaaf7a3bf6b39fed0bbae03bf89238a72230e978/src/python/WMCore/FwkJobReport/Report.py#L323 )
- We changed the condition to declare a job successful: the FWJR.xml must contain `exitCode=0` and the payload exit code (let's say cmsRun) must be 0, see [here](https://github.com/dmwm/CRABServer/blob/c20f58db21f61eb346b8a48beb6d6f0c644c050b/scripts/CMSRunAnalysis.py#L713)
- We have a [trap](https://github.com/dmwm/CRABServer/blob/c20f58db21f61eb346b8a48beb6d6f0c644c050b/scripts/gWMS-CMSRunAnalysis.sh#L75) in our jobwrapper that allows us to set the classad `Chirp_CRAB3_Job_ExitCode` at the end of every job, whatever happens to it (if it does not, then we have a bug). This exit code is obtained from : 
  - the value contained in the FWJR.xml
  - if the FWJR.xml contains 0 but the application returned non-zero, then we use the application exit code
  - set to the default value `80001` if the FWJR.xml is not there (for example when the job is killed).
  - However, after a quick check, this does not always work [1]. We still have some jobs that have the status "Removed", empty "Chirp_CRAB3_Job_ExitCode", exitCode 0. can it be because we use the non-blocking `condor_chirp set_job_attr_delayed`?

We are open to changes if you have better ideas :)

---

[1] 

- condor_raw: https://monit-opensearch.cern.ch/dashboards/goto/870e4a00514893fded85cb4ae8e5f068?security_tenant=global
- task view: https://monit-grafana.cern.ch/goto/5weddTX4k?orgId=11

**Comment by belforte** [comment]
hm.. periodic_remove issues a condor_rm, I think, and it is properly trapped.

**Comment by belforte** [comment]
I beg to disagree a bit with @khurtado though. I think that condor jobs always have an exit code.  0 means "I could run your payload", does not matter if payload ended with exit status 0 or not, that's your problem. 1 means "I (condor) could not run your payload for one reason or another". Yeah.. I could be wrong. In any case we should not mix this exit status with what crab or wma report and indeed if those tools do not report anything, default to error.

I think that what Dario describes is a different topic, that was about "cmsRun failed but FJR says exitCode=0" which anyhow CMSSW people fixed (so it only happens on a restricted range of CMSSW versions). Let's keep things separate.
Again, CRAB may or may not set the correct exit code, but tries hard to always set one, if not in the jobWrapper, in the postJob. In case we fail, it is better to have "error" reported in Grafana, instead of "success".

**Comment by belforte** [comment]
I guess that usiing the condor exit code makes sense for CMS_Connect or institutional scheduler where nothing else is available. 

In any case I fully agree that default when nothing is available in classAds should be error !

**Comment by khurtado** [comment]
@belforte Interesting! From [condor](https://htcondor.readthedocs.io/en/latest/man-pages/condor_submit.html?highlight=want_graceful_removal#submit-description-file-commands), I see:

```
want_graceful_removal = <boolean expression>
If true, this job will be given a chance to shut down cleanly when removed. The job will be given as much time as the administrator of the execute resource allows, which may be none. The default is false. For details, see the configuration setting [GRACEFULLY_REMOVE_JOBS](https://htcondor.readthedocs.io/en/latest/admin-manual/configuration-macros.html#gracefully-remove-jobs).
```

So it is possible the periodic_remove tries a graceful shutdown first in CMS case, but there will be some cases in which a hard kill will be issued after the grace period, which won't be trapped.

In any case, I also agree with the "default when nothing is available in classAds should be error" logic.

**Comment by khurtado** [comment]
> 
> But I still do not understand how we can have a jobs which completed w/o a condor exit code. [documentation](https://htcondor.readthedocs.io/en/latest/classad-attributes/job-classad-attributes.html?highlight=exitcode#ExitCode) suggests that this happen when a job exits via a signal.

I don't think condor does, but the spider does.

Here:
https://github.com/dmwm/cms-htcondor-es/blob/c0a07da1776f8e379ef08c320f71cd657283d191/src/htcondor_es/convert_to_json.py#L669-L671

the spider sets 
```
result["ExitCode"] = commonExitCode(ad)
```
which ends up in `0` when `ExitCode` does not exists in the job classads. 

You can see it also sets a `CondorExitCode` when `ExitCode` exists in the job classad. The `CondorExitCode` does not exist in the CRAB example link that @mapellidario provided.

**Comment by khurtado** [comment]
Following up from Monday's WMCore Chat meeting:

I have confirmed `cleanup` jobs do [fail](https://es-cms.cern.ch/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(Type,Status,JobFailed,ExitCode),filters:!(),index:d2ea6f80-d2e0-11ed-bdae-e3cf8c07f2fc,interval:auto,query:(language:lucene,query:'Type:production%20AND%20TaskType:"Cleanup"%20AND%20JobFailed:1'),sort:!())) sometimes, meaning we do inherit the condor job exit code, which is not always 0.

Is there any other possible side effect that we should double check before making a PR against monit?

**Comment by amaltaro** [comment]
@khurtado that's good! It's still not clear to me if your comment above also answers the case of a successful Cleanup job (IF it does not set ExitStatus). Would you have this answer? If it is hard to answer it, we could update (via pull request) the condor job monitoring and keep a close look at the Cleanup jobs for the first 12/24h and roll things back in case we spot issues. What do you think?

@germanfgv @LinaresToine just a heads up that we are planning to update the default `ExitStatus` code in the condor job monitoring. Details can be found above.

**Comment by khurtado** [comment]
@amaltaro Yes, otherwise `ExitCode` would exist in ES, but not `CondorExitCode`. But [both](https://es-cms.cern.ch/dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15h,to:now))&_a=(columns:!(Type,Status,JobFailed,ExitCode),filters:!(),index:d2ea6f80-d2e0-11ed-bdae-e3cf8c07f2fc,interval:auto,query:(language:lucene,query:'Type:production%20AND%20TaskType:"Cleanup"%20AND%20ExitCode:0%20AND%20_exists_%20:CondorExitCode'),sort:!())) exist when `ExitCode:0` for successful jobs.

**Comment by amaltaro** [comment]
Thanks Kenyi. I think we addressed all the concerns then and I would suggest to go ahead and create a PR changing the default behavior.

I had another look at the monitoring source code and I see that the first field it uses to fetch the exit code is `JobExitCode`. WMAgent does not seem to be setting it - neither I can see it in the monitoring - do you know who is supposed to set it?

**Comment by khurtado** [comment]
Here is the monit related issue:
https://github.com/dmwm/cms-htcondor-es/issues/208
