### ISSUE TITLE
Demonstrate WMCore can run Data workflows based on lumilists instead of runlists 

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11623]
**Impact of the new feature**
WMCore/WMAgent as a whole 

**Is your feature request related to a problem? Please describe.**
This issue is in the context of the request  by PPD that they need to be able to run Data workflows based on lumi section whitelists instead of run lists. This should be a feature that  is already supported by the system and we need to demonstrate that by injecting on properly configured workflow and validate the result.

**Describe the solution you'd like**
Inject a data workflow with Limulist and validate the output. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by amaltaro** [comment]
I am already looking into this one, as I need to look at the test json workflow templates and validate the gfal2 stage out fix as well.

**Comment by todor-ivanov** [comment]
Super! 
Thanks @amaltaro! Then we may even consider resolving this inside the Q2 project. This one is marked `operations` and is  related to a high priority task already. I think it will be good.

**Comment by amaltaro** [comment]
As mentioned in different venues, lumi list based workflow processing has been supported in WMCore for potentially 8 years now and such workflows are exercised in the monthly integration validation.

Nonetheless, we took this opportunity to look deeper into these workflows by running in testbed a simple ReReco with lumi list workflow:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ReReco_Run2022C_LumiMask_June2023_Val_230629_124519_8011

and we can confirm that everything is working as expected and only the run/lumis provided in the workflow description are actually processed. This is the short summary, if you want further details, read on!


Looking into the data discovery performed in Global WorkQueue, we can see that the lumi estimation is correct:
```
  "TotalInputLumis": 67,
```
different than `"TotalInputEvents": 7018,`, which is not really relevant in this ticket, neither for a lumi based workflow processing. However, there is this ticket to track it: https://github.com/dmwm/WMCore/issues/10568

I copied the log tarball with the DataProcessing jobs (jobs that processed the RAW input data) under this web area in AFS:
https://amaltaro.web.cern.ch/amaltaro/forWMCore/Issue_11623/

I also untarred that tarball, which gave us 4 logArchives (a total of 4 processing jobs were created/executed). Next, I unpickled the original job configuration executed in the worker node (PSet.pkl, here named as PSet-jobX.pkl) and dumped them in a new file (here named as PSet-jobX.my.py). Now we can open those PSet python files and inspect their configuration, or a simple grep of the lumis to process give us the following:
```
Singularity> grep lumisToProcess PSet-job*.my.py
PSet-job0.my.py:    lumisToProcess = cms.untracked.VLuminosityBlockRange("355862:121-355862:133"),
PSet-job1.my.py:    lumisToProcess = cms.untracked.VLuminosityBlockRange("355863:1-355863:14"),
PSet-job2.my.py:    lumisToProcess = cms.untracked.VLuminosityBlockRange("355865:1-355865:4"),
PSet-job3.my.py:    lumisToProcess = cms.untracked.VLuminosityBlockRange("355870:31-355870:66"),
Singularity>
```

Note that for job2 processing run 355865, it only processed 4 lumis instead of 1..287, as defined in the workflow description. Reason for that is that the dataset really only contains those 4 lumis for that run number.

With that, we can with confidence say that lumi based workflow is fully functional in WM. And I close this issue out.
