### ISSUE TITLE
Estimate the need for --network=host in WMAgeent  Docker builds

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#11635]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
Once we are done with the two issues of separating the database instances from the agent container for both MariaDB and CouchDB we will have to make the estimation if it is possible to build and run the WMAgent container without  the option `--network=host`. This strongly depends on how we decide the agent should communicate with 3 major components:
* MariaDB
* CouchDB
* HTCondor

The possibilities are basically 3 again:
* Through sockets - it is highly not recommended to share sockets between the host and the container for security purposes.
* Trough the localhost network - this implies using the options `--network=host`
* Trough the network again, but use external Ips rather than the loopback device -  this absolutely restricts us from using shared network between the host and the container. Bridged network should be one possible choice in this case.

The first one is simply not an option.

The second one is the simplest to implement, but comes with some restrictions:
* All components live in a single host
* Single instance of an agent per host
* Single database instance per host
* Error prone if someone manages run a second container in the same host and connect to the database.

The later is the most flexible one, allowing us to be able to completely disassemble the WMAgent in the future and move to a fully distributed deployment model on component level. But this one may turn out to be also the most complicate one to implement and may bring some scalability issues (e.g. like network overloading).  

**Describe the solution you'd like**
A Clear decision on which of the 3 communication models between the agent's components we chose. 

**Describe alternatives you've considered**
None

**Additional context**
Depends on:
* https://github.com/dmwm/WMCore/issues/11313
* https://github.com/dmwm/WMCore/issues/11312
* https://github.com/dmwm/WMCore/issues/11570

Part of the following meta issue: https://github.com/dmwm/WMCore/issues/11314

**Comment by anpicci** [comment]
I had a chat with @todor-ivanov about this issue. Considering that we opted for the network model mentioned in option #2, the straightforward (and already working) way to communicate with DBs and HTCondor is using `--network=host`.

I am going to run some tests with and without that option, with the current build-and-run model, and share here the results.

**Comment by anpicci** [comment]
@todor-ivanov @amaltaro FYI

**Comment by todor-ivanov** [comment]
Hi @anpicci I just checked all the logs and I can confirm that we have exactly the expected behavior. 

I have only one minor comment, though.
The run run in the following combination: 
```
run_with_flag_after_build_without_flag
```

Is probably sucessfull, because the actual build without the flag has completely gone wrong and no image was created, so the following run must have been with an image from the last  known good build. You may cross check that by the images' `WMA_BUILD_ID` - it is always included in the build logs (if the build actually makes it to the end)

Another hint you may use for this is the fact that if you look at the log file ` run_with_flag_after_build_without_flag.log` you can see the initialization process is quite shortened. Almost no steps (only one - for the cleanup of the relational databse) which means you are running an image which have been previously already initialized on the very same host. 

So that was a minor clarification. Not changing the results from these tests. Thank you for doing them so thoroughly.  My opinion is - We can close that issue. I'll let @amaltaro  speak, though.

**Comment by amaltaro** [comment]
If I remember correctly, the goal of this issue was to evaluate whether we needed to modify our CD GH pipeline to adopt this `--network=host` option at build or not. The current workflow can be seen [here](https://github.com/dmwm/WMCore/blob/master/.github/workflows/docker_images_template.yaml#L49) and it does NOT use the --net=host option during the build process.
After googling about this, I learned that this option is completely different between "docker build" and "docker run", where the former is only used when building the image, while the latter is actually used during container runtime to define which network model to use. In other words, we do not need to build the image with --network=host in order to run a container with this option. Please correct me if I am wrong.

Having said that, I feel like we don't need to use this option in the wmagent-docker-build.sh script, and README file. I am always in favor of keeping things consistent.


Andrea, with these logs you provided above, are you trying to show a matrix of image vs container / host net vs non-host net and whether we are able to run a `wmagent` container in each of those setup? 

I wanted to note that log [build_without_flag.log](https://github.com/dmwm/WMCore/files/14998367/build_without_flag.log) actually fails to connect to the PyPi repository to pull down wmagent==2.3.0. Can you please give it a try with tag `2.3.1`? I just tried to build the 2.3.0 image on my laptop and I had no issues.

In addition, this log [run_without_flag_after_build_without_flag.log](https://github.com/dmwm/WMCore/files/14998424/run_without_flag_after_build_without_flag.log) shows that the container failed to communicate with Oracle. I assume this is because the container runs without `--network=host` option. Is that correct? Actually, this log [run_without_flag_after_build_with_flag.log](https://github.com/dmwm/WMCore/files/14998451/run_without_flag_after_build_with_flag.log) also has the same oracle communication failure.

I guess this is expected, as it then uses the default network=bridge and only supports 1 container using that network.

**Comment by amaltaro** [comment]
@anpicci Andrea, I would suggest one last check then. 

Assuming that wmagent `2.3.2rc6` has been built based on this CD workflow, can you please pull the image and try to run it with the network=host option?

If it fails, then we could take one extra step and ensure that the image is built by us (not the CD or the wmagent-docker-build script), in a node DIFFERENT than WMAgent nodes (your laptop, or another CERN machine), following this very same setup:
https://github.com/dmwm/WMCore/blob/master/.github/workflows/docker_images_template.yaml#L40-L53

for the tag, you can pick for instance 2.3.2rc6-andrea or anything like that (feel free to push the image to CERN registry.

Once that image is available, please try to run it with the network=host option and we will see what comes out of this.
Please let me know if this looks confusing to you, I am happy to clarify it over Zoom.

**Comment by todor-ivanov** [comment]
>  in a node DIFFERENT than WMAgent nodes (your laptop, or another CERN machine), following this very same setup:
https://github.com/dmwm/WMCore/blob/master/.github/workflows/docker_images_template.yaml#L40-L53

Please don't..... Lets not mix results and make conclusions based on different sources of errors. We  are already deviating into another issue here: https://github.com/dmwm/WMCore/issues/11568. First of all, yes, the current model does give the possibility to build wherever you'd want, but for the time being lets keep the practice of building those images within the same set of machines where we will be running them and where everybody is sure that the surrounding conditions are equal. This way we will have error reproducibility by anybody, and in the debugging process we will be able to compare apples to apples.  Alan, We have never talked about the possibility to build on a laptop, even though this possibility is implicit for the nature of the process. It have never been in the initial definition of this migation. It is never guarantied what and how is set on one's laptop..... I can already notice/forsee some bad practices in which (by mistake) builds from laptops get upstream (and even Kubernetes) and start misbehave in a unpredictable way and none of us would be possible to reproduce it and hence debug it. lets still stick to WMAgent machines when it comes to those builds. Once  we get to the point when everything is working I'll be more than happy if we prove to everybody, that just by a click of a button our images can build anywhere in the world. But lets not jump ahead of ourselves.

**Comment by amaltaro** [comment]
@todor-ivanov I beg to disagree with you.

In addition to figuring out what works or not, the goal of this issue is such that we can either rely or correct our CD pipeline. I don't see the point of building WMAgent images manually when we have everything implemented and automated in the repository.

I have also already expressed my opinion on building images in the WMAgent nodes themselves, and I don't think we should have this practice as we move along with this project. I fail to see any reason why we should stick with the WMAgent nodes for building images. In theory, docker images can be built anywhere that has the same architecture of the node where we are going to run the images. And if needed, a `docker buildx` should be enough to build images cross platforms.

Note that I am not advocating that we need to support all sorts of platforms. But if this scenario is needed, docker has a native way to do so.

I agree with you though that we should not be using our own laptops for building and uploading images. For development style tests, we can build from wherever we want; but for more serious testing (and production images!), we should always use upstream/official build setup (and the CD pipeline seems to be the way to go, IMO).

**Comment by anpicci** [comment]
From the test run with a central docker wmagent agent, it turns out that the CD pipeline can stay as it is for the time being, since it runs with `--network=host` with no errors in networking.

@amaltaro @todor-ivanov when you consider it convenient, we can close this issue

**Comment by amaltaro** [comment]
Thank you Andrea! From our chat today/yesterday, I understand that you would like to keep this `--network=host` in [this CMSKubernetes script](https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/wmagent/wmagent-docker-build.sh#L53), while we also keep our [CD pipeline](https://github.com/dmwm/WMCore/blob/master/.github/workflows/docker_images_template.yaml#L49) without it.

Once we are in a more stable and confident situation, we can decide to sync them up. Feel free to close this up, if you want.

**Comment by anpicci** [comment]
Thank you! I am closing the issue then.
@amaltaro do you want me to create a separate issue to persist this desire to align the CD pipeline to the CMSKubernetes setup?

**Comment by todor-ivanov** [comment]
@amaltaro 

May I have a naive question, here. 

How, difficult would that be if here: [docker_images_template.yaml#49](https://github.com/dmwm/WMCore/blob/9e20b58bf71dfa25ff0a5ba670bc3577e20310cf/.github/workflows/docker_images_template.yaml#L49) (since we have already synced the CMSKubernetes repository) we just call `wmagent-docker-build.sh -t ${PYPI_TAG} -p` , which will basically do it all?
