### ISSUE TITLE
Jobs with stage out failures can be marked as successful in the Condor Job Monitoring

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11655]
**Impact of the bug**
WMAgent / Condor Job Monitoring

**Describe the bug**
This ticket is very much related to: https://github.com/dmwm/WMCore/issues/11654
but meant to discuss a different problem.

Given that we only chirp exit code for the cmsRun steps, it is very likely (need to check on opensearch dashboards) that jobs failing to stage out would still be considered as a successful job by cms-htcondor-es script:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py

It is important to highlight that each production/processing job has at least 3 (WMCore) steps: cmsRunX, stageOut and logArch 

This assumption above will be wrong if we actually set the `ExitCode` or `JobExitCode` to the exit code of any of the steps above. But this needs to be further investigated.

**How to reproduce it**
Fail the stage out of a job and check the condor job monitoring job status.

**Expected behavior**
It is expected of the job monitoring system to reliably reflect the actual job outcome. 
IF WMAgent does not provide enough information to identify such cases, we need to think of a way to tell condor job monitoring that the stage out step failed. There are different approaches that we could take here, e.g.:
1) (Re)Setting `Chirp_WMCore_cmsRun_ExitCode` to the exit code of the stage out step (thus a clear failure)
2) Create a new classad - e.g. Chirp_WMCore_stageOut_ExitCode - where we can start providing the stage out outcome. The only problem is that this step is independent of CMSSW releases...
3) Or use one of the `ExitCode` or `JobExitCode` classads/attributes to pass this information on.
 
**Additional context and error message**
None

**Comment by khurtado** [comment]
I believe this is already passed in the `CondorExitCode` classad. For example [here](https://es-cms.cern.ch/dashboards/app/discover?&security_tenant=global#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1M,to:now))&_a=(columns:!(CondorExitCode,Chirp_WMCore_cmsRun_ExitCode,Chirp_WMCore_cmsRun1_ExitCode,Chirp_WMCore_cmsRun2_ExitCode,ExitCode),filters:!(),index:'0f3117a0-d2e6-11ed-bdae-e3cf8c07f2fc',interval:auto,query:(language:lucene,query:'Chirp_WMCore_cmsRun_ExitCode:0%20AND%20CondorExitCode:147'),sort:!())) is a list of jobs where `Chirp_WMCore_cmsRun_ExitCode` and `Chirp_WMCore_cmsRun_ExitCode` were `0`, but `CondorExitCode=147`, which translates to: `"Error during attempted file stageout.",`

The bug here of course is that `ExitCode=0`, because we don't account for `CondorExitCode` in the current logic inside `cms-htcondor-es` in the `commonExitCode` function, so this would need to be fixed.

**Comment by amaltaro** [comment]
Thank you for finding this example Kenyi. I decided to look at the logs of one of the jobs in the dashboard and indeed there was a stage out failure and our job wrapper (submit_py3.sh) script returned the same exit code you pointed above:
```
======== WMAgent final job runtime checks STARTING at Thu Jul 13 20:26:53 GMT 2023 ========
Thu Jul 13 20:26:53 GMT 2023: Job Runtime in seconds:  9089
Thu Jul 13 20:26:53 GMT 2023: Job bootstrap script exited:  147
Thu Jul 13 20:26:53 GMT 2023: Job execution exited:  147
======== WMAgent final job runtime checks FINISHED at Thu Jul 13 20:26:53 GMT 2023 ========
```

So it should be only a matter of updating it on the condor monitoring side. Let me make this GH issue Operations such that we get to it in the coming days/weeks.

**Comment by amaltaro** [comment]
This issue has been addressed with:
https://github.com/dmwm/cms-htcondor-es/pull/212
and
https://github.com/dmwm/cms-htcondor-es/pull/210

Thanks Kenyi!
