### ISSUE TITLE
Support campaign name for RERECO workflows

### ISSUE THREAD

**Issue by khurtado** [dmwm/WMCore#11704]
**Impact of the new feature**
Support the campaign names available in de workflow description for RERECO workflows.

**Is your feature request related to a problem? Please describe.**
It is related to: #10914

**Describe the solution you'd like**
For a RERECO workflow, we only have one campaign name set in the Workload and task level (WMTask). We need need to propagate this information at the job classad level (JobCreator and JobSubmitter) so that this information is part of the pickle file we send to the job submitter and create a new condor classad with it. Monit script also need to be modified so that we use this information only when the value is meaningful (not Unknown/Undefined), or fallback to the current inference of the campaign name otherwise.

If the campaign information is available for the JobSubmitter componen:

* `CMS_Campaign`: a string with the campaign name which the job belongs to.

**Describe alternatives you've considered**
Use current mechanism at monit level, which we want to change now.

**Additional context**
Child of  #10914

**Comment by amaltaro** [comment]
@khurtado while investigating the FJR code, I just happened to find this line of code:
https://github.com/dmwm/WMCore/blob/4170e4a/src/python/WMCore/JobStateMachine/ChangeState.py#L352

which is executed by the JobAccountant component.

If we indeed migrate the campaign to be an attribute of a task instead of the workload, we need to keep in mind to update that line as well.

**Comment by khurtado** [comment]
@amaltaro Good catch, thanks!
