### ISSUE TITLE
Allow for JobSubmitter to give priority to older workflows and tasks

### ISSUE THREAD

**Issue by germanfgv** [dmwm/WMCore#11772]
**Impact of the new feature**
T0 WMAgent, WMAgent

**Is your feature request related to a problem? Please describe.**
T0 requires to finish workflows as soon as possible in order to delete data fast. Currently, JobSubmitter gives priority to start processing new workflows instead of finishing old ones:
https://github.com/dmwm/WMCore/blob/a55235c93cf788d2f9dad1fd9180a9bb7897b1f0/src/python/WMCore/WMBS/MySQL/Jobs/ListForSubmitter.py#L37

This is problematic, specially when T0 accumulates a job backlog greater than the cache size.

**Describe the solution you'd like**
Add a JobSubmitter configuration parameter to define whether or not to give priority to new workflows. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by amaltaro** [comment]
@germanfgv Hi German, are you suggesting to replace that `wmbs_workflow.id DESC` by `wmbs_workflow.id ASC`? 
I think it makes total sense and there is no reason why central production should have it differently. So i would say go ahead and change it directly in the DAO, no need to make it configurable.
Can you please provide a pull request for this? Otherwise please let us know and we will take it.
