### ISSUE TITLE
Efficiently obtain file list and number of events information for a given list of block names

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#11899]
**Impact of the new feature**
WMAgent

**Is your feature request related to a problem? Please describe.**
In current implementation of https://github.com/dmwm/WMCore/pull/11884 we should cover the use case when we have increase of MSPileup blocks. As such, newly added pileup blocks should have appropriate file list and number of events information.

**Describe the solution you'd like**
Provide concurrent implementation to obtain desired information (`FileList` and `NumberOfEvents`) for a list of pileup blocks. This information should be obtained from DBS. Since we may have lots of blocks within given pileup we need an efficient, i.e. concurrent way, to grasp this information from DBS.

**Describe alternatives you've considered**

**Additional context**
Part of the meta-issue https://github.com/dmwm/WMCore/issues/11537
Please see algorithm implementation in https://github.com/dmwm/WMCore/pull/11884

**Comment by amaltaro** [comment]
For further context, WMAgent uses this module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/Steps/Fetchers/PileupFetcher.py
to construct the pileup JSON file (pileupconf.json), whenever a workflow gets acquired by the agent.

To ensure compatibility with the current model, we need to use the same logic, other than:
* input data will be a block (or list of) instead of a container
* locations don't need to be resolved through Rucio, given that we are fetching it from MSPileup

Valentin, I also tweaked a bit this issue with labels and etc, and linked/added it to the meta-issue as well.

**Comment by amaltaro** [comment]
Valentin, initial implementation looks good to me, other than what I have already mentioned about invalid files.
In addition, looking into the `multi_getdata` function, it looks like it yields results as the HTTP calls are served, so we might want to consider parsing that information on the fly to decrease memory footprint, e.g.: `for result in multi_getdata(...):`

One of the checks that we need to perform before pushing such changes upstream, will be a comparison of the result between the new and the old way of constructing this list (file list and number of events per block).

**Comment by vkuznet** [comment]
Alan, I'll add valid files flag, but unfortunately we can't generalize `multi_getdata` further to parse outcome results as there is no clear criteria how to do it in generic way (using python constrains). The point is that the GET APIs can be constructed in different ways, with positional parameters, with payload, etc. Therefore, parsing results should not about that, and this can only be done in the code which calls this function since this is the place where this is known. I'll put this code into new module as you suggested and add it later to #11884
