### ISSUE TITLE
MSPileupUtils not properly parsing query string on GET requests

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#11935]
**Impact of the bug**
MSPileup

**Describe the bug**
While validating testbed services based on version 2.3.2rc3, we started getting alerts for MSTransferor with error message like:
```
description = Workflow: tivanov_SC_6Steps_PU_Feb2024_Val_240314_125015_9875 could not proceed due to some PU misconfiguration,so it will be skipped.
hostname = ms-transferor-5c65f89886-mrr9l
summary = [MSTransferor] Workflow cannot proceed due to some PU misconfiguration.
```

which is clearly incorrect, given that this pileup does exist in cmsweb-testbed AND it is active, see:
https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup?pileupName=/Neutrino_E-10_gun/RunIISummer20ULPrePremix-UL16_106X_mcRun2_asymptotic_v13-v1/PREMIX

**How to reproduce it**
Run the same HTTP call executed in MSTransferor, such as:
```
>>> from WMCore.Services.MSPileup.MSPileupUtils import getPileupDocs
>>> mspileupUrl = "https://cmsweb-testbed.cern.ch/ms-pileup/data/pileup"
>>> pileupQuery = {"query": {"active": True}, "filters": ["expectedRSEs", "pileupName"]}
>>> getPileupDocs(mspileupUrl, pileupQuery)
[]
```
which apparently expands the url to https://***.cern.ch/ms-pileup/data/pileup?query=active&filters=expectedRSEs&filters=pileupName

**Expected behavior**
I don't really know how to expand the query string because it has a dictionary as value. But one potential change would be to change from GET to POST call, which definitely works well.

**Additional context and error message**
The MSPileup in this API https://cmsweb-testbed.cern.ch/ms-pileup/data/status reports the following number of pileups (proving the query silently fails):
```
  "total_num_pileups": 0,
```

bug inserted with: https://github.com/dmwm/WMCore/pull/11910

Further details in: https://github.com/dmwm/WMCore/pull/11870

**Comment by vkuznet** [comment]
FYI: @amaltaro , @d-ylee 

I think this issue miss important detail:
- the GET request can be composed using positional parameters, and if multiple values exists (like list) they can be passed using key=value multiply times, or
- the GET request can use JSON payload and use proper HTTP header `Content-type: application/json` to tell HTTP server how to properly handle it

Therefore, the issue is two-fold:
- client should properly compose HTTP GET request using either of the above options and setup proper HTTP header
- and, server should properly handle HTTP GET request using HTTP headers

Switching to POST goes against HTTP standard which suggests to use POST for creation of data and use GET for data retrieval. I provided concrete example here: https://github.com/dmwm/WMCore/pull/11936#issuecomment-2006918625

I suggest to review this issue and either open it again or create new one to address mishandling HTTP methods and align them with HTTP standard.
