### ISSUE TITLE
Stop relval output placement in MSOutput in favor of rucio subscriptions

### ISSUE THREAD

**Issue by haozturk** [dmwm/WMCore#12069]
**Impact of the new feature**
MSOutput

**Is your feature request related to a problem? Please describe.**
Currently relval output placement is done via MSOutput and changing the algorithm requires code changes which takes developer time. We'd like to change the relval output policy and start using Rucio subscription mechanism for relval placement instead of MSOutput, which gives CompOps the full control to change the policy as needed.

**Describe the solution you'd like**
Stop output placement for relval workflows. @amaltaro please let us know the date you'll deploy this change, so that we can start the relevant rucio subscriptions a few days in advance. After we make sure that subscriptions work, we can disable MSOutput relval logic.

**Describe alternatives you've considered**
None

**Additional context**
@Panos512 @drkovalskyi fyi

If anyone is interested in the new policy, please let me know, I can send it via private chat.

**Comment by amaltaro** [comment]
@haozturk thanks for creating this issue. Just so we can plan this work, is it Okay to wait until beginning of October, or would you like to have this implemented still this quarter?

**Comment by haozturk** [comment]
Hi @amaltaro this is pressing due to T0 activities and lack of free space at CERN. We're buying time by moving existing relval data from CERN to outside, but I'd like to get this done before October if possible.

**Comment by anpicci** [comment]
@amaltaro, talking with @hassan11196 about this issue, there are two scenarios to deal with:
1) for usual relvals, we would need a new Rucio account, like `wma_relval`, in place of `wma_prod`, to be used in MSOutput to create the Rucio rules for such workflows (I think it should be eventually specified in the secrets of the relval agents.
2) for relvals needed to submit to prod nodes (aka special relvals), P&R would like to use the new Rucio account, `wma_relval`, instead of `wma_prod`. In my understanding, the Rucio account is fixed once and for all by the secrets configuration of the agent, and then if a relval workflow is injected in a prod node, it will inherit the related Rucio account, `wma_prod`. One naive solution would be to have a prod-relval agent, with only the Rucio account different from the usual prod agents, but I suppose this would become very easily a unsustainable solution. @hassan11196 was wondering if it would be possible to workaround the configs at the post-production level, forcing the agent to use `wma_relval` instead of `wma_prod` when the workflow is a relval one and still injected in a prod agent.

**Comment by amaltaro** [comment]
@anpicci @haozturk I would suggest to create a fresh new ticket for the feature mentioned in the [comment above](https://github.com/dmwm/WMCore/issues/12069#issuecomment-2298353473), as it is completely different than the original feature change requested in this ticket.

We can then discuss details over there not to mix up different feature requests - but in short, given that we run **some** relval workflows in the production node, our only option would be to define the Rucio account based on the workflow or output data name.

**Comment by anpicci** [comment]
@amaltaro @haozturk @hassan11196 I have created a separate issue to discuss the topics reported in my last comment:
https://github.com/dmwm/WMCore/issues/12078

As a result, for this issue we can focus on the original request from Hasan
