### ISSUE TITLE
Recover all the services_config changes made throughout the last year

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#12072]
**Impact of the bug**
WM central services configuration

**Describe the bug**
It is far from being a WMCore issue, but it does affect us and here is the announcement of this issue with some details:
https://cms-talk.web.cern.ch/t/urgent-gitlab-repository-issue-and-action-required/45328

**How to reproduce it**
No clue!

**Expected behavior**
We need to revisit the merge history and aggregate all the changes for a given environment (prod, preprod, test) into a new merge request. For that, we need to look at the history of all these services:
```
        target: [wmagent, wmagent-devtools, wmcore, reqmon, reqmgr2, global-workqueue, acdcserver, reqmgr2ms-unmerged,
                 reqmgr2ms-output, reqmgr2ms-pileup, reqmgr2ms-rulecleaner, reqmgr2ms-transferor, reqmgr2ms-monitor]
```
AND we need to check it in all 3 branches as well.

That means, the expected outcome of this is to have 3 merge requests against the relevant services_config branches, which will provide all the configuration changes that have been lost in the last year or so.

**Additional context and error message**
None

**Comment by amaltaro** [comment]
Looking into the repository activity records, we seem to have a better understanding of what caused this, confirming the force push mentioned by Aroosha.
At least for the `prod` branch, it looks like we lost any changes between `April 10` and `June 11`. Hopefully this makes the recovery task easier.

**Comment by anpicci** [comment]
@amaltaro @arooshap since in my opinion running the check manually would haven't been reliable enough, I have tried the automate the process.

The underlying assumptions are the following:
- [this list](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests?scope=all&state=merged&target_branch=prod) can be retrieved with the GET API call to the GitLab server,
- the "faulty' history of merged PRs for a given branch, [this one](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/commits/prod/?ref_type=heads), can be retrieved with `git log --merges`.

Using the original repo as an upstream to run the checks and applying any modifications only to a forked repo of mine, I followed two approaches:

1. Once got the correct history of merged PRs to the upstream branch through the GET API call, I check if each of this PR resulted to be present according to
```
git diff [pr_commit_has] [branch_to_check]
```
if any difference is found, the PR is applied again to the forked branch.
2. Once got the correct history of merged PRs to the upstream branch through the GET API call, I compare it with the "faulty" list coming from `git log [upstream_branch] --merges`. If any of the former ones is not present in the latter list, it is reapplied to the forked branch.

For approach #1:
- [Script used](https://gitlab.cern.ch/apiccine/services_config/-/blob/master/check_and_reapply_prs_gitdiff.sh?ref_type=heads)
- [remerged test branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/test_remerged_test?ref_type=heads)
- [remerged prod branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/prod_remerged_test?ref_type=heads)
- [remerged preprod branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/preprod_remerged_test?ref_type=heads)

For approach #2:
- [Script used](https://gitlab.cern.ch/apiccine/services_config/-/blob/master/check_and_reapply_prs_apivsgit.sh?ref_type=heads)
- [remerged test branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/test_remerged_apivsgit?ref_type=heads)
- [remerged prod branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/prod_remerged_apivsgit?ref_type=heads)
- [remerged preprod branch](https://gitlab.cern.ch/apiccine/services_config/-/tree/preprod_remerged_apivsgit?ref_type=heads)

To me, the second approach is safer and actually get the result we are searching for, since the first approach reapplies also old merges on files that doesn't exist anymore. As a result, I would be in favor to merge the branches from my repo to the central obtained with the approach #2 .

**Comment by amaltaro** [comment]
@anpicci thank you for looking into this. I am afraid your links above are all broken (either returning 404 not found, or pointing to the first WMCore issues - # 1 and # 2). Can you please update this description?

**Comment by anpicci** [comment]
Sorry for that, I fixed the 1 and 2 in order to not point to WMCore issues.

Regarding the other links, I should have granted access to you and @arooshap to my `service-config` GitLab repo

**Comment by amaltaro** [comment]
@anpicci did we only have one merge request that was lost in all of this? Have you checked the `prod`, `preprod` and `test` branches? I only see this MR so far:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/274

**Comment by anpicci** [comment]
@amaltaro the one you reported has to be deleted, as I made it as a first attempt, before devising the scripts I reported here.

Following the second approach I have illustrated, there is 1 missing PR for test, 4 missing PRs for prod, 2 missing PRs for preprod.

If this approach is approved, I will open PRs to merge the healed branches from my GL repo to the central one

**Comment by amaltaro** [comment]
@anpicci I guess I didn't follow all the details, but can you please open at least the prod MR? I will then check the content (and if possible the commit/MRs that are being recovered). If everything goes Okay, we proceed with preprod and test.

**Comment by anpicci** [comment]
@amaltaro here it is:
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/276

**Comment by anpicci** [comment]
After some investigations, with the script reported [here](https://gitlab.cern.ch/apiccine/services_config/-/blob/master/check_and_reapply_prs_apivsgit.sh?ref_type=heads) I have been able to recover the following PRs for the three branches:

[Prod](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/277)
The following commits were re-applied:
- PR ID: 263    Commit #7807599dceae7be8549456224ec2def32f8a725b (File: t0wmadatasvc/t0auth.py.encrypted)
- PR ID: 244    Commit #dd87d7bf082f17266ba724746f9b86e18d1f2d73 (File: reqmgr2ms-output/config-output.py)
- PR ID: 241    Commit #37b67a43fff9e4d8db92c7439766a6de63f8de7c (File: reqmgr2ms-unmerged-t1/config-unmerged.py)
- PR ID: 241    Commit #37b67a43fff9e4d8db92c7439766a6de63f8de7c (File: reqmgr2ms-unmerged-t2t3/config-unmerged.py)
- PR ID: 241    Commit #37b67a43fff9e4d8db92c7439766a6de63f8de7c (File: reqmgr2ms-unmerged-t2t3us/config-unmerged.py)

[Preprod](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/279)
The following commits were re-applied:
- PR ID: 262    Commit #18104cd2368ad27f7a1ce86a4d70538b7aad6ca3 (File: t0wmadatasvc/t0auth.py.encrypted)
- PR ID: 254    Commit #03ac2d55c0c9c74d5df8a770f8bdb9dc4105dfe4 (File: x509-proxy-server/config.json)

[Test](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/280)
The following commits were re-applied:
- PR ID: 261    Commit #a4382acc21790765a37263bd547cccbc2edcd032 (File: frontend-ds/backends.txt)
- PR ID: 261    Commit #c3d2f65a1ceb7a52e8e4e25498303b3f83c82fc8 (File: t0wmadatasvc/t0auth.py.encrypted)

**Comment by anpicci** [comment]
@amaltaro since all the merge request on GitLab have been merged, I'm proceeding with closing this issue
