### ISSUE TITLE
Refactoring documentation about WM deployment with Docker and venv

### ISSUE THREAD

**Issue by anpicci** [dmwm/WMCore#12161]
**Impact of the new feature**
Have a more user-friendly documentation about WM agent deployment with Docker and venv. This particularly needs to be done before running the next training sessions on debugging (https://github.com/dmwm/WMCore/issues/11849)

**Is your feature request related to a problem? Please describe.**
The documentation is too scattered across the MKDocs repo

**Describe the solution you'd like**
Merge these documents into one.
- The beginning of the WMAgent overview document lists information and code structure mostly on a component-by-component basis. This should be mostly valid.
- The middle part of the WMAgent overview document, starting from https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent.md#a-set-of-usable-initial-commands-to-use-once-loged-in-to-an-agent up to the debugging section relates to the old rpm based agents and we must update this.
- The last part of this document starting from: https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent.md#running-wmagent-components-in-standalone-mode-for-advanced-debugging to the end is up to date.
- This deployment procedure: https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent-deployment.md is obsolete - relates to the rpm based agents
- This document https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent-in-Docker.md is valid up until this paragraph: https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent-in-Docker.md?ref_type=heads#single-docker-image-for-wmagentmariadbcouchdb-rpm-style everything for the later may be deleted, we can keep some minor explanations from there like what we need to mount, but some of them heavily changed because we moved the structure of our mount points to start from a single root, which is /data/dockerMount. Then we may wish to explain the different views of those mount points from inside and outside the container, there are also the user auth mounts that we take from the system and the docker mount points for the runtime environment, which end up inside the container at `$WMA_INSTALL_DIR/Docker`. We can consider dedicating a completely separate document on this explaining the whole structure of our containers 

**Describe alternatives you've considered**
None

**Depends on:**
https://github.com/dmwm/WMCore/issues/12182

**Comment by amaltaro** [comment]
@anpicci we briefly discussed this yesterday, but now that I read its initial description, I just wanted to share some extra information and perspective here.

If we really decide to refactor the WMAgent documentation, then I think we could add this ticket as part of the meta-issue https://github.com/dmwm/WMCore/issues/11875 (which already has a ticket for legacy/out-dated content); and perhaps consider it as normal plan instead of Ops.

If the goal is only to describe/improve the Docker and virtual-environment based deployments, then yes, this ticket looks self-container. In addition, I think a good starting point is https://gitlab.cern.ch/dmwm/wmcore-docs/-/blob/master/docs/wmcore/WMAgent-in-Docker.md, which already gives a brief description of the docker deployment.

For the outcome - especially if it involves content removal - I would ask you and @todor-ivanov to actually provide a merge request instead of pushing changes upstream. This way others have the opportunity to look into the actual changes and identify anything that might be undesired.

**Comment by todor-ivanov** [comment]
hi @amaltaro  @anpicci  @mapellidario 

And here is a big PR adding a full `Deployment` section.  The way how I structured it should mostly fit in what we have discussed a week ago regarding document purpose etc., And it also suggests a common structure with equal set of bullets in the relevant documents of matching types/proposes. 

I am still working on finalizing the last few documents - related to one or two setup methods, but I am working on them. the rest of the PR is soon to come. 

p.s. Before making comments or reject what is suggested here, please do render the so suggested change with the instructions provided in the `README`: https://gitlab.cern.ch/dmwm/wmcore-docs/#running-documentation-locally

**Comment by todor-ivanov** [comment]
The following issue must be resolved in parallel with the current one: 
https://github.com/dmwm/WMCore/issues/12182

The PR resolving it: 
https://github.com/dmwm/WMCore/pull/12183

**Comment by anpicci** [comment]
Here is the document:
https://cms-wmcore.docs.cern.ch/deployment/introduction/
