### ISSUE TITLE
Checks during assignment of workflows

### ISSUE THREAD

**Issue by gutsche** [dmwm/WMCore#1529]
We would like to add checks during the assignment process in the ReqMgr to make sure that the selected input samples are at the selected site(s). During assignment, we should check for:

- input sample is at selected sit(s)
- at least one block of the selected pileup sample(s) (MC and/or Data) is at the selected site(s)

and if not fail the assignment of the workflow with an error message. We have to figure out how to do that in batch mode as well.

Thanks,

OLI

**Comment by amaltaro** [comment]
It seems quite useful, but not very easy to do in cases we have a list of blocks or runs white or blacklisted (assignment may take several seconds in this case).
Since WorkQueue will acquire work - and users can still transfer the input pileup - and will update input location, I guess we could close this issue.

Unless @gutsche still wants this feature? :-) @ticoann

**Comment by amaltaro** [comment]
I guess silence means No. Seangchan, can we close this one?
