### ISSUE TITLE
Write DAS Service class

### ISSUE THREAD

**Issue by drsm79** [dmwm/WMCore#2201]
To start using DAS as a source of information we need a Service class that can communicate to the DAS REST interface. This should basically be a combination of:
 * [https://svnweb.cern.ch/trac/CMSDMWM/browser/WMCore/trunk/src/python/WMCore/Services/Service.py Service.py] to provide "client" side caching
 * [https://cms-http-group.web.cern.ch/cms-http-group/apidoc/das/current/das_client.html#using-das-cli-tool-in-other-applications DAS api/cli] to talk to DAS

This can then be used by Feeders and for other data lookups, with each feeder mapping to an optimised (one hopes) DAS query.

**Comment by ericvaandering** [comment]
This is a very old ticket and the code referenced was probably left behind in TRAC. Can we just close this? I suspect that if we've gotten by this long without a DAS service class, we don't actually need one. @ticoann ? @vkuznet ?

**Comment by vkuznet** [comment]
Eric, I think we can safely do that. Let's wait for Seangchan to confirm.

**Comment by ticoann** [comment]
Actually, in principle, this could be useful. Since DAS is collective call for all other services, instead of making different calls to dbs, PhEDEx, and agent can make call to DAS to get the information. This might be useful especially in validation step (close out), but I guess we can create the new issue if we really needed.
