### ISSUE TITLE
show when a merge job skips a file

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#4851]
We would like to be able to see in wmstats when a merge job skips a file when the robust merge happens. Even better would be to provide the number of events skipped and/or the number of lumis skipped. I recommend making another column (next to cool off) where we can see the number of jobs where this happened and then being able to click on that row and see more details.

**Comment by amaltaro** [comment]
This is something that T&I group has been asking for. So setting it to highprio

**Comment by ticoann** [comment]
@amaltaro, Alan,

I was thinking about doing following (couldn't find the better way)
1. Create the new fwjr view to get all the jobs which contains skippedFiles list. (It should be only merge (success) jobs and returns the event skipped and lumi skipped
2. With that result we calculate the lum list and total number of event by workflow and report to wmstats.

The question I have, 
1. Does ops need any other information than events or lumis? (job ids, unmerged file name for debugging purpose?)  -which could be problem on the size depending on the number of files.

Depending on the size of skipped files it might a little expensive procedure. (I can't have reduced view since lumi is the list not the sum.

**Comment by amaltaro** [comment]
Sorry Seangchan, I almost missed it. I think they just care about a) the total number of events skipped and b) the total number of lumis skipped. If they need further information, then it could be found in the ACDCServer (I don't think we need to replicate the same information here).

How are you going to publish this information? Is it going to be retrievable only by wmstats rest api or it will be visible in wmstats UI itself?

**Comment by amaltaro** [comment]
@ticoann is this issue completely taken care? if so, please close

**Comment by vlimant** [comment]
just to update that thread while preparing for a summary next week, wmstats does not report such missing stats, but we are now systematically getting also the information from the acdc server, and defacto can see when there is missing stats in the acdc because of "robust merge".
I think we can discard to have this reported another way, as long as we keep the acdc docs around.

**Comment by amaltaro** [comment]
This information should be getting propagated through wmstats now. So I'm closing this issue.
@ticoann please reopen in case I'm mistaken

**Comment by vlimant** [comment]
can one please explain how this is going to be visible, and how to retrieve that info in the json doc one can get from datasrv

**Comment by ticoann** [comment]
Hi Jean-Roch,
In wmstats (request view), if the workflow has contains skipped files,  (meaning if the merge job is successful but has skipped files), the box in D column will be read. (you can sort it by clicking the D column head, all read buttons will show up in the top)
If you click the red button, bottom of the pop up window you can see something like that.

```
Skipped Summary
SUS-RunIISummer16DR80Premix-00189_1MergeAODSIMoutput: skippedFiles:10,
```

It doesn't show which files are skipped or number of events skipped etc, It that is necessary we will try to add that. 

There is no dedicate api to find all for this. You can use following api. and search for skipped.
https://cmsweb.cern.ch/wmstatsserver/data/requestcache

If you need dedicated api or other information, please create the new issue. Thanks.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/wmstatsserver/data/request and https://cmsweb.cern.ch/wmstatsserver/data/jobdetails is that info in any of the two, or should I go for a third one with requestcache ?

**Comment by ticoann** [comment]
first one (https://cmsweb.cern.ch/wmstatsserver/data/request) contains the same information.
It depends one the use case. 
If you are querying  above call anyway, you can just extract the information. 
If you wants to find all the workflows which has skipped files it will be more efficient  to use requestcache, instead of making thousands calls for all the active requests.

If you are using  requestcache call, polling cycle should be at least 10 min. Since cache updates every 10 min, it doesn't make sense to call more often then that.  (This call is not cheap as well)
