### ISSUE TITLE
Stageout code error handling does not work for multiple files stageout

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#5086]
I've just observed a problem in the Tier0, where a job created 4 files. The first failed stageout, the other 3 staged out alright and in the end the job was declared a success. Which obviously caused problems later because the one file that failed stageout was missing and therefor the next job that was supposed to read it failed as well. I had to manually recreate the file and inject it into the SE.

Question, is this design intentional ? Normally I would say if one file fails stageout the job should be immediately failed. Don't even try to stageout the other files and definitely don't declare the job a success.

**Comment by amaltaro** [comment]
@hufnagel have we ever seen this problem again? This issue is from beginning of 2014, if we haven't cases like that for 2015, I suggest we close this issue.

**Comment by hufnagel** [comment]
Well, has anyone at least looked at the code and checked what it was supposed to do in this case ?

**Comment by amaltaro** [comment]
I think it was fixed by this patch:
https://github.com/dmwm/WMCore/pull/6695/files#diff-3552b4820c987f54dfa4666540b36164R212

in case the stage out fails, it raises an exception:
https://github.com/amaltaro/WMCore/blob/68f64875567501bc83ee63fb6543f84319f85611/src/python/WMCore/Storage/StageOutMgr.py#L241
