### ISSUE TITLE
Need to revisit running-open, running-closed works as intended

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5253]
running-open, running-closed introduced to handle when input dataset is finished processing. But when we use DBS2 it allows open blocks to be uploaded but not DBS3.

Basically checking this condition for new data is not valid anymore.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/Block.py#L264

All the file blocks should be closed. (To fix is either we allow open blocks on DBS3 or we need to keep track in WQ whether there is new block created).

**Comment by ericvaandering** [comment]
Any update on this or should we close it?

**Comment by amaltaro** [comment]
@ticoann can you please confirm/correct me please on the following summary.
* running-open: has no more meaning in the system besides pointing that there is still at least one GWQE in Acquired status (while all the others are running/done).
* running-closed: all GWQE were pulled by the agent(s)

a) There is no more use of `OpenRunningTimeout`, b) there is no check for "open blocks" in DBS, since they should no longer exist AND c) there is no more watching the input dataset for new blocks and turn those into GWQE. 

Is that correct? I'm just concerned about c), is it true we no longer add new blocks to requests already acquired by global_workqueue?
