### ISSUE TITLE
make acquistion era, process string, processing version mandatory in reqmgr.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5373]
Currently this is not mandatory and created None string when it is not set. 
Disable default values and make this mandatory field for some one who assigned workflows

**Comment by amaltaro** [comment]
And I happen to be investigating a possible issue exactly on this piece of code. The current status is: AcquisitionEra, ProcessingString and ProcessingVersion are *mandatory* during assignment. Not enforced during creation. There is still an adjustment needed for ProcessingString, since Tier0 can have empty/None value. We probably have to create a different Lexicon rule for T0 and production.

Then I have one more question related to it, possible to @vlimant . We know the dict sent during request creation is persisted in couchdb (workload_cache doc). Should we update those values during assignment, if they are provided? For instance:
https://cmsweb-testbed.cern.ch/reqmgr2/data/request?name=amaltaro_ReDigi_cmsRun3_HG1610_Validation_161004_151418_792

has empty string for `ProcessingString`, since that was not provided during creation.

**Comment by amaltaro** [comment]
And the summary from this discussion with PPD and the WF team:
"""
As discussed with Seangchan/Eric, this would be the goal for these parameters:
* **Campaign**: *mandatory* string during creation, then can never change again.
  And it applies to the whole workflow (not tasks).
* **AcquisitionEra**: *mandatory* string at request level during creation. *optional* string
  at task level during creation. "optional" during assignment.
* **ProcessingString**: *mandatory* string at request level during creation. *optional* string
  at task level during creation. "optional" during assignment.
* **ProcessingVersion**: *optional* during creation (default 1). *optional* during assignment.

Where *mandatory* means the user must provide the key/value for it. *optional* means
the request will use either the default value or what was already provided in earlier status.
"""

I'll try to make it by Wed.
