### ISSUE TITLE
do not change random seeds when a job is retried

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#5534]
Hi,

I think we should not change the random seeds in the pset.py when a job is retried because it could bias the monte carlo.

Andrew

**Comment by franzoni** [comment]
hello @AndrewLevin @hufnagel ,
we've been pointed to this thread, getting to it now. 
We agree with these statements :

- if the generator is so bad that we need to "random seed shop" to complete a sample, there is no way not to bias ourselves.
- not changing the random seed kind off makes sense as you want to see these failures and not just swipe them under the carpet. 

After a first thought, I would also lean towards the idea that the random seeds should not be modified in ACDC, intended to recover jobs which failed for non physics-related reasons.
What are you trying to set, a policy ? What is the context that lead to this discussion ? What is the current policy? 

Cheers, Giovanni @boudoul @srimanob

**Comment by AndrewLevin** [comment]
Hi Giovanni,

The context is this thread

https://hypernews.cern.ch/HyperNews/CMS/get/relval/3319.html

Yes, we are trying to set a policy.

Andrew

**Comment by hufnagel** [comment]
Problem is, if you never change the random seeds (not in retries and not in ACDC), you have to accept that some MC requests will never finish, they level out at 90%, 80% or whatever. There needs to be some mechanism that allows you to "random seed shop", otherwise you have to accept the fact that asking for 100k event will not give you that, the number you get will be fundamentally limited by the stability of the code paths for that MC sample. That's fine as it is, but it has consequences for operational procedures...

**Comment by ticoann** [comment]
@ericvaandering, Eric wants me to check what is involved to change code base for this.
To clarify,
1. seeding is by job not by request, correct?
2. first generation of jobs has random seeding but failed job will  have the same seeding, correct?

If 1. is true it will be harder to preserve that information in acdc.

**Comment by ericvaandering** [comment]
It seems to me that ACDCs are especially difficult since the jobs in an ACDC may not even map to jobs in the original workflow. Job splitting parameters, etc may have changed, right?

**Comment by amaltaro** [comment]
Seangchan/Eric, my understanding about this issue is the following:
 - about 1., yes, random seed is by job and not by request
 - about 2., that's correct again. When a job fails, the job retry should use exactly the same seed (that's intended to easily reproduce errors that may come from a "very special" seed)

About ACDCs, I see this as a second step since it's much harder.
At least in RelVals we do not run ACDCs, and in case these failures happen there (where the software is mainly validated), PPD/Offline folks would be able to reproduce the failures.

**Comment by ticoann** [comment]
Yes, ACDC is harder. I am not sure that is even possible since failed job in Original workflow doesn't match acdc job created later.

For the retrying case we need to find mechanism to save initial job seeding. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L282

It seems this algorithm just do that. Not completely sure how this works, though.

**Comment by ticoann** [comment]
Yes, ACDC is harder. I am not sure that is even possible since failed job in Original workflow doesn't match acdc job created later.

For the retrying case we need to find mechanism to save initial job seeding. 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L282

It seems this algorithm just do that. Not completely sure how this works, though.

**Comment by amaltaro** [comment]
Me neither :-) But it looks like there are several different seeds in the game. I was looking at one job configuration at this exact moment (DIGI job)
http://amaltaro.web.cern.ch/amaltaro/forSeangChan/myPSet.py

**Comment by ericvaandering** [comment]
We have lots of seeds but as long as you generate those with "random" #'s that themselves have a deterministic seed, you are OK. If I was doing this, I would see the python random # generator with some hash of the job definition. Perhaps what is happening.

**Comment by ericvaandering** [comment]
Another bit of discussion on this:


@ericvaandering:
Well, if we want deterministic + re-running with the same seed, the way I would think we would do this is that in the workflow request “someone” would supply a seed from which all other seeds are determined and that could easily signal to us exactly what to do. RelVal would probably tell us the same seed over and over again, or at least the same seed for each type of workflow where the release changes (if I understand what this is wanted for).

On the other hand, for *all* workflows, would McM want to supply such a seed for each workflow (here I assume every workflow starts with a different seed but resubmissions would be keyed to give the same random #’s as the job that does not succeed). Or would McM supply a “flag” that says “don’t change seeds between resubmissions”? Obviously the former is exactly the same as the RelVal case and is “easier” but the other is probably not so bad either.

Just one point I forgot in my little description: I think carrying this over into subsequent ACDCs of a workflow is ~impossible since its a completely different job sequence, etc. But since that doesn’t apply to RelVal and doesn’t really impede the issue with lhe+gen-sim+digi you are interested in (crash rate), it may not matter.


Earlier from @ericvaandering
So, it seems to me we need to answer two questions:

1) Is it possible (relatively easy) to build both of these pieces of functionality into WMAgent. I didn’t get a sense of that from Alan and Seangchan’s comments
2) Which workflows is this desirable for? Surely for RelVal, but is this what we want for normal LHE generating and GEN-SIM workflows? I think this 2nd discussion is one that has to happen at least with PPD and possibly with Physics or the GEN contacts. It’s definitely not a decision for me to make.

From @davidlange6

It would be easy to argue that CMS may want this for all workflows depending on its difficulty. It would quickly reveal the real crash rate (and thus possible bias rate) of workflows, that right now is hard to measure. Of course w would need to carefully introduce this capability to understand its downsides (starting with relval).

Do you see a big difference in implementation if the implementation is for relval vs relval+lhe+gen-sim vs relval+lhe+gen-sim+digi workflows?

Cheers-
David


Cheers,

Eric
