### ISSUE TITLE
move the transaction to close to the first db call

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5608]
This might cause the connection leak. 
following need to be moved 
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py#L205
To 
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py#L239

**Comment by hufnagel** [comment]
True, if you want a transaction, you should move the transaction.begin()

Look at

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L593

to see how I do it. Transaction handling should be integrated in exception handling. Because if something goes wrong, you need to cleanup after yourself (ie. rollback the transaction).

In this specific case, do you even need a transaction ? Usually you use one to protect multiple changes that need to go in together versus a failure in one of the changes. As far as I can see, here you have a single call. Why don't you just pass it transaction = False ?
