### ISSUE TITLE
Do not submit jobs asking for too much resources

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5738]
Now that glideInWMS is enforcing "MaxWallTimeMins" and "RequestDisk", we should change WMAgent NOT to submit greedy jobs to condor, otherwise those will be pending forever.
Instead, these jobs should be marked as jobfailed (or submitfailed) with a clear message.

It should be configurable and I guess it needs further discussion, but here is a first idea:
 - don't submit if job asks for more than 48h MaxWallTimeMins
 - don't submit if job asks for more than (27GB * RequestCpus) RequestDisk

**Comment by hufnagel** [comment]
The first is too broad. Different resources will support different max wall times, for instance CERN cloud resources allow much longer jobs and we might need to take advantage of this for the Tier0.

The latter should be coordinated with the changes we are making to the periodicremove conditions, where I am currently testing 27GB for singlecore and Nx20GB for multicore. These don't have to be the final number, its just something I came up with (the idea being that for multicore jobs we really don't need the extra space).

**Comment by hufnagel** [comment]
Checking what Farruk actually implemented was N*27GB, but this is almost certainly wrong not what we want.

**Comment by AndrewLevin** [comment]
I think we should make it configurable (i.e. in the config.py file) when we kill the job. 48h is what we want right now for release validation, but I doubt this will be always what we want for all kinds of workflows.

**Comment by Farrukh-Aftab** [comment]
Just to clarify what glideinWMS is doing at the moment:

(a) It will check your jobs for MaxWallTimeMins (assuming that the correct value is being specified). This value is then compared to what is being specified in the factory as GLIDEIN_Max_Walltime (the maximum life time for a glidein). So for example, if your job wants to run for 2 days, but the glidein can only run for 1 day, your job won't be matched and will continue to be idle in the queue. Keep in mind that this value varies from site to site. For example, CERN has this set to 7 days.

(b) Once the glidein is already in the system, and has completed a few jobs, the attribute MaxWallTimeMins is used again to compare it with the remaining life time of the glidein. If your job wants to run for 6 hours, and the glidein still has 8 hours to live, the negotiator will match them.

**Comment by Farrukh-Aftab** [comment]
For Andrew's case, this value was too low i.e. 300 something, 160 something. 300 mins are like 5 hours, so his jobs were being matched to old glideins and when the glideins were dying, the jobs were being evicted.

**Comment by bbockelm** [comment]
It's reasonable to enforce some high outer limits.

Currently, Julian has a stuck workflow because the jobs ask for 52 days of walltime.  While a global limit of 48 hours is too low - can we do 1 week?

**Comment by ticoann** [comment]
@julianbadillo,  Julian, What kind of jobs ask for 52 days of walltime? Is that a mistake or intentional?
Other problem seems to be that failing job for this is a little to late (Current code seems to define this value when job splitting happens). If possible we should probably reject when workflow is created, didn't we have enough information to check this before actual job splitting happens at least approximate value? (TimePerEvents, EventPerJobs, etc)

I was wondering whether GLIDEIN_Max_Walltime can be published to dashboard by sites or somewhere. That way, reqmgr can check whether particular workflow can be run or will be forever pending assuming we can get the walltime value from spec itself.

**Comment by ticoann** [comment]
I think required disk size might be harder to calculate from the spec.

**Comment by amaltaro** [comment]
Seangchan, it usually happens to i/o intensive jobs (or almost like that). Skimming, miniaod, alcareco jobs, etc. Since in these cases each job go through much more events than normal.
Since we have this MaxWallTime in condor, I believe we could 'submitfailed' it there, no?

About the disk size, yes, it's going to be trickier since we have have several output modules for a single job. However, maybe we could start considering each job will have 1 output module (?)

**Comment by ticoann** [comment]
Thanks Alan for the explanation.

> Since we have this MaxWallTime in condor, I believe we could 'submitfailed' it there, no?

Yes we could. what I meant "too late" means, if we can check this when request is create that would be better. We can avoid full down the work and creating the job altogether, just warn the requester 'this workflow won't run unless JobSplitting parameter changes'. However, I am not sure we can get proper estimate of "MaxWallTimeMins" with the given parameter without actually running the job splitting algorithm.

**Comment by ticoann** [comment]
Alan,  you are right it is hard to get the MaxWallTimeMins before job splitting unless it is EventBased.
I will take this issue.

**Comment by AndrewLevin** [comment]
Also, it would be good to have a configurable minimum and maximum walltime such that if a job has a walltime greater than the maximum walltime, it is automatically set to the maximum walltime. This is obviously different from killing the job if its walltime is too large. I think both options would be useful in certain cases, because sometimes the walltime is accurate and sometimes it is not (eg in release validation it is not very accurate). So, maybe it can also be configurable whether we kill a job with too large walltime or we just lower the walltime automatically.

**Comment by bbockelm** [comment]
Seems to be rather dangerous, no?
1.  If the walltime is accurate and you auto-shorten, you now waste 48 hours of CPU time when the job is going over the limits.
2.  If the walltime is wildly inaccurate, then you're going to be severely decreasing the effective priority of the job (c.f. the existing upgrade DIGI-RECO workflows).  Further, it likely indicates something has gone wrong with the workflow the operator should look at, no?

What would be an example of a case where you would want the system to auto-shorten the walltime?  You mention RelVal.  I don't have a good understanding of the struggles there - can you give the next layer of detail in your thinking?

**Comment by AndrewLevin** [comment]
1. The 48 hours of CPU time is not wasted, because the problem will be reported to the submitter and they will fix it. Relval is a very small fraction of the entire workflow share and the fraction of relval that runs for longer than 48 hours is a small fraction of that. So, I am not really worried about the wasted resource usage. I am more worried about the wasted human time the results from jobs getting stuck in pending, evicted, disconnected, etc.
2. I think we can live with the decrease in effective priority for relval, given that relval already has the highest priority. (However, as a side note, I am very suspicious about whether the priority is working properly, even considering the effect of WallTime matching. For example, during the long Easter weekend relval jobs never got more than 25% of FNAL.)

**Comment by bbockelm** [comment]
1.  Apologies - I still don't understand this, or I'm missing something.  My interpretation of what you wrote is that it is better to wait for 48 hours then fail the job than to fail the job on submit?
2.  Nope - this is completely expected.  The closer the MaxWallTime is to the maximum pilot lifetime, the less likely there is a that can run the job - and more likely some other job will run instead.
   - Hence, jobs asking for >24 hours of runtime are going to see significantly less resources than the lowest-priority GEN-SIM task.  The only way we have to solve this currently is to get the jobs closer to the target 8 hours of runtime.

**Comment by AndrewLevin** [comment]
1. No, because you don't a priori know whether the walltime is correct. 
2. OK,  but any new glidein should go to the highest priority job, regardless of it's walltime, right? For release validation, I think we want to eliminate evicted jobs "at all costs" even if it means wasted resources, inefficiency, etc. As you are aware from the e-mail thread, wmagent does not have any "evicted job protocol" right now, which means that when jobs get evicted it just creates confusion and manual work for us.

**Comment by bbockelm** [comment]
1.  So, instead of getting folks to fix the walltime of requests, we silently ignore them?
2.  Correct - any new glidein gets the highest priority job.  Let's say that a relval job requests 36 hours, but really runs for 12.  Then a new glidein will run one relval job - and potentially four 8-hour long lower-priority jobs.  In this example case, only 25% of the walltime goes to the highest-priority jobs.
  - The less accurate the requested walltime (and the more the walltime goes over the target of about 8 hours), the less time relvals will get at the site.  Hence, my suggestion to more aggressively push back on folks for better-formed relvals.
      - Then again, it's always a tradeoff.  They can continue to make the current requests and continue to get slower turn-around times.
   - For evicted jobs - doesn't this make it worse?  Any time you shorten the requested walltime, you'll be increasing the number of evicted jobs.
  - Seems that the easier path would be to get WMAgent to handle these jobs appropriately.  In a pinch, we can do this at the HTCondor level within about a day or two (but perhaps get crappy error codes).

**Comment by AndrewLevin** [comment]
1. Yes. 
2. OK. I see how it can happen that relval gets only 25%. So, there is a tradeoff. I think for release validation the disadvantages of walltime matching (the human effort needed to make sure the wall time is being set correctly, the possibility of evicted jobs and jobs stuck in pending) are worse than the advantages.  After 36 hours, WMAgent kills the job itself in a way that log files are returned, so no evictions should occur if you set the walltime for each job to be 36 hours. Getting the log files is very useful for the requesters to debug why the job ran too long.

**Comment by bbockelm** [comment]
Ah-ha!

The key piece I was missing was about the jobs timing out regardless at 36 hours.  Thanks!

I think we should probably brainstorm a bit more; I'm sure we can come up with something better (hopefully the suggestion I put in elog will tie you over?).  Can you send out a doodle with some available times this week?

(This is just for brainstorming, mostly to help my understanding.  Anything final can be done via normal tickets.)

**Comment by hufnagel** [comment]
About 1, we should still push to have better wall time estimates. If nothing else it makes scheduling jobs to pilots (and especially single core jobs to multicore pilots) much more efficient if we know how long the job is going to run.

OTOH, I do not think we can ever get to a point where we can rely on these wall time estimate to the extent that we can say "you are 10% over your estimate, now we kill you". I am approaching this from a Tier0 angle, where estimates for wall time are extremely difficult because they depend on machine performance and HLT event selection, which is hard to predict.

I would say though that for wall time estimates, if you have to guess, you should probably try to err on the high side, ie. giving estimates that are more likely to be larger than the actual wall time. The effects on the underlying glideInWMS system are less severe than giving too small estimates.

**Comment by belforte** [comment]
I think the brainstorming chat will be more effective if based on some data. 
How long to RelVal jobs really run for ? Given how excited people get whenever it is delayed by a few ours, I was imagining many O(1~2h) jobs. If large majority fits e.g. 4h I would submit everything with that and those who time out could be restarted with 12h or more via a JDL attribute.
That is coarse yes, but may be good enough.

Also, where to RelVal run ? If at CERN, we have 7day pilots, so much of the discussion above does not apply. Maybe we can run longer pilots at FNAL as well ? All problems are due to jobs duration being comparable to pilot life time, creating the problem of filling pilot "gaps". We gain in efficiency and scale by running many jobs per pilot, that's why we do not like that pilots harakiri after one job.

**Comment by AndrewLevin** [comment]
Hi Stefano,

RelVal runs 95% at FNAL. According to Farrukh, after a schedd claims a glidein, it can keep it as long as it wants. So, having 7 day glideins at FNAL would make the turn-on too slow I think. Maybe we should consider requiring the schedd to give up the glidein after each job.

Even considering the effect of walltime matching, I still cannot understand the attached plots. They would only make sense if all of the orange have a walltime set very close to the glidein lifetime limit, yet they are extremely short jobs. For example this job

cmst1@vocms053:/data/srv/wmagent/current $ condor_q 74330.48


-- Submitter: vocms053.cern.ch : <188.184.162.209:4080?noUDP&sock=1965168_af55_33> : vocms053.cern.ch
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
74330.48  cmst1           4/14 08:15   0+00:00:00 I  489000 0.0  submit.sh heli_RVC

has been pending for more than one day even though it has 

MaxWallTimeMins_RAW = 144
MaxWallTimeMins = 150

and higher priority than the green jobs.

![gy5uo2d](https://cloud.githubusercontent.com/assets/3329216/7153321/5e86a764-e34a-11e4-835d-fc9e1434ee48.png)
![condorjobnumbers_individual 5](https://cloud.githubusercontent.com/assets/3329216/7153236/fccd2986-e348-11e4-9c9e-520d0b114599.png)
![condorjobnumbers_individual 4](https://cloud.githubusercontent.com/assets/3329216/7153238/ff528dc2-e348-11e4-8a32-497e86a47bf0.png)



Andrew

**Comment by belforte** [comment]
thanks Andrew, it really helps to be concrete about what we talk about.
And clearly this is not doing what expected and may require more then
MaxWallTime tuning.
I defer to Brian on the exact policy under which a glidein is released for
a new matching cycle, although I think it is ClaimLifeTime or something similar
and mating is done to a user, not a schedd, when claim expires the pilot
goes back to the negotiator asking for a match across the full spectrum of
idle jobs.

**Comment by Farrukh-Aftab** [comment]
>> According to Farrukh, after a schedd claims a glidein, it can keep it as long as it wants.
That is not true Andrew. If you recall, I told you that there is a claim lifetime. Once a schedd gets a glidein, it keeps hold of it for 12 hours. After 12 hours, the glidein goes back to the pool. 

>> Maybe we should consider requiring the schedd to give up the glidein after each job.
That would be inefficient. The idea of having 12 hours as the claim life time was that more often than not a schedd has multiple jobs pending to the same site, so a schedd should reuse the glidein without having to put an extra load on the negotiator. IF the negotiator goes down, or has issues, the whole pool suffers. Most of settings/configurations keep this mind.

**Comment by Farrukh-Aftab** [comment]
I tried looking up the job you just mentioned. Taking a closer look, I saw that your jobs didn't have anything that would prevent them from being matched to glideins. I looked up the glideins in the pool [1] and there were available glideins. I tried reverse analyzing some of the jobs, and that shows that most of the glideins don't have any CPUs (if you recall, FNAL went all multicore, so perhaps we're seeing the effects of glidein partioning?). In short, these "idle" glideins cannot run your jobs.

I looked on your schedd, all of your jobs are running at T1_US_FNAL. I think the question here would be, why did the newer jobs got the slots and the old one stayed pending? Is there any difference in their prio? If not, then perhaps we need to revisit the schedd job sorting knobs, maybe something is not right there.

[1]
# condor_status -const 'GLIDEIN_CMSSite=?="T1_US_FNAL" && State=?="Unclaimed"' -totals
                     Total Owner Claimed Unclaimed Matched Preempting Backfill

        X86_64/LINUX  1430     0       0      1430       0          0        0

               Total  1430     0       0      1430       0          0        0

**Comment by AndrewLevin** [comment]
Hi,

So, Brian, we will need your help to debug this. Please let us know if you need any additional information.

Thanks.

Andrew

**Comment by bbockelm** [comment]
Hi,

Farrukh was on the right track - we had:

PostJobPrio2 = quantize(QDate, {3600})

(so newer was better).  We restored this to the original intent:

PostJobPrio2 = -quantize(QDate, {3600})

I now see older jobs being started preferentially.  It might take a few hours for the weirdness to filter out of the system.

On the original issue of job runtime: talking to Dave Mason at the FNAL T1, he was nonplussed about the idea of longer pilots and wanted to know why we couldn't ask the requesters to do better splitting.  Let's make sure he is at the phone discussion.

Brian

**Comment by belforte** [comment]
Dave Mason should say which job duration he expects to get with best splitting. 8h jobs in 48h pilots is a bit marginal IMHO, we are there out of necessity, not by some optimal design.

**Comment by belforte** [comment]
@bbockelm for my education where is PostJobPrio2 defined ? I'd like to understand this in depht.

**Comment by bbockelm** [comment]
Yes - I think 8 hour splitting is still desirable.  We only get ourselves in trouble when we have requests for 36 hours like RelVal occasionally does.

PostJobPrio2 is currently defined by the schedd (although there's a patch to have WMAgent manage this).

**Comment by belforte** [comment]
OK. I found some related info to PostJobPrio in
https://github.com/dmwm/WMCore/issues/5688 and https://github.com/dmwm/CRABServer/issues/4705
including that it is not documented (no point to dig in HTCondor).
Those talk about PostJobPrio1, not PostJobPrio2, but I guess if only one is defined it is not different.
Yet I am puzzled because I thought RelVal had higher basic "JobPrio" so should run before anything else because of that, during sorting by primary key, not because they were submitted earlier.

stefano

**Comment by bbockelm** [comment]
@belforte - yes - _JobPrio2_ only affects the ordering *once* the schedd has been handed the match (and only between jobs with the same _JobPrio_).  _JobPrio_ is the only sorting considered when the negotiator is deciding which negotiator to talk to next.

Digging in, there's another problem here - USE_GLOBAL_JOB_PRIOS is enabled on the negotiator but not the schedds.  That's causing the global use of priorities to be ignored.  I enabled it on vocms053, and the negotiation cycle it looks even better now.

**Comment by belforte** [comment]
cool.
if global priorities were ignored it may explain some other
situation where people argued at length on production not
delivering workflows in expected order

Is the conclusion that the mere threat of a meeting made us (well.. you!)
solve and the meeting is not not needed ?

**Comment by bbockelm** [comment]
Unfortunately not - we still need to figure out MaxWallTime issues on RelVal, and how to better handle jobs that exceed it.

**Comment by bbockelm** [comment]
@belforte - we probably didn't notice because "general" workflows are distributed across many agents.  With global priorities turned off, we basically start negotiating with a random schedd.  When high priority workflows are on many schedds, it's highly likely we start the negotiation with a schedd that contains the highest priority workflow.

However, this issue sticks out especially for RelVals as it is on a single schedd.  If we pick a random schedd for matchmaking, it's unlikely to hit the RelVal one.  This explains why Andrew was seeing pain but I didn't observe it elsewhere.

Anyhow, once I turned on global priorities for the relval schedd, it doubled the number of running jobs in about 30 minutes.  I'll bug Farrukh and Krista to get it enabled elsewhere.

**Comment by belforte** [comment]
@bbockelm yes, sort of working is exactly what makes for long and lively debates in meetings where none knows the inner details enough :-)

**Comment by amaltaro** [comment]
Fixed by #6201
