### ISSUE TITLE
Why do we need 'aborted-completed'?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5805]
Hey folks, I'm investigating why WorkQueue (or TaskArchiver) is not archiving aborted workflows, and I just found out that a new status was added (new at least for me :))
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/RequestManager/RequestDB/Settings/RequestStatus.py#L56

Is there any reason to have 'aborted-completed' status there? I'd simplify it with 'aborted' to 'aborted-archived'. 
I have a few changes in my local repo, in case we can get rid of it.

**Comment by ticoann** [comment]
Hi Alan, actually it is not a new state. Originally for the aborted workflow Ops wants the workflow summary as well. So when workflow aborted, it will go through all the normal complete procedure. cleaning up db and create the workload summary. Then TaskArchiver move the request status to aborted-complete status then it move to aborted-archived status

There are certain cases aborted in not moving to aborted-completed/archived. 
1. When workflow is aborted before agent pulled down the request.
2. Agent DB cleaned up before aborted-complete/archived status updated (some times happens when agent get drained).

I will add the patch to handle those cases.

**Comment by amaltaro** [comment]
> Originally for the aborted workflow Ops wants the workflow summary as well.

I barely see an use case for that :(, I hope Ops is really using this feature
Ok, thanks a lot Seangchan!

**Comment by ticoann** [comment]
create the new issue.#5825
