### ISSUE TITLE
move aborted workflow to aborted-archived when agent is not yet pulled the workflow

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5825]
via aborted-completed

**Comment by ticoann** [comment]
following #5805

**Comment by amaltaro** [comment]
@ticoann we have to fix it for the next cycle as well. High prio

**Comment by amaltaro** [comment]
Seangchan, as discussed privately, this is half fixed in the current testbed. If the workflow was either in 'assigned' or 'acquired' but only by the GQ, then it will remain in 'aborted' state in ReqMgr, though I see it in 'aborted-archived' in WMStats. Here is one example
https://cmsweb-testbed.cern.ch/reqmgr/view/details/amaltaro_MonteCarlo_PhEDEx_HG1506d_Validation_ChangeState_150603_130547_4450

**Comment by ticoann** [comment]
Yes that was intentional. reqmgr Oracle db will go away. I didn't think there is a need to move aborted status to aborted-archived in Oracle db. Since all the reading the status should be through reqmgr2 api not reqmgr api. (At least this might force people to use reqmgr2 api for status checking instead reqmgr rest api. Do you find any problem causing by this?

**Comment by amaltaro** [comment]
Provided people are not using reqmgr to retrieve the status, it should be fine.
I'd rather keep all of them in sync, since it may take several months for us to retire oracle, but anyways not a big deal :-)
Feel free to close this one, fixed by #5928

**Comment by ticoann** [comment]
One other thing is it also creates the reqmgr dependency to reqmgr2, since this code is in reqmgr2 cherry thread. Closing the issue. Let me know if you find any problem causing by this.
