### ISSUE TITLE
Improve PSet configuration for multiRun harvesting jobs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5848]
I had a "multiRun" harvesting job running over 2 runs and I noticed the fileNames in process.source contain duplicate lfns.
lumisToProcess does not contain duplicates, but it does not create lumi ranges when possible, e.g.:
202205:21-202205:21
202205:22-202205:22
202205:23-202205:23
202205:24-202205:25
202205:26-202205:27

instead of 202205:21-202205:27.
I guess the dup files is harmless, but it's worth it to fix it eventually.

**Comment by amaltaro** [comment]
BTW, putting a job configuration (for a successful job) here as example:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/myPSet_GH5848.py

**Comment by hufnagel** [comment]
Hm, could it be that it picks duplicates because it first assigns files for one run and then files for another run and there are overlaps between files ? If so, the problem is likely in the job splitter, doing a run by run assignment without properly taking into account the multirun nature.

With the file duplicates in the input, there could be bad effects (duplicate input transitions etc).

Also, a similar concern, if the data for the runs is not continuous in the input files, the harvesting could do the wrong thing. In that case you can get multiple beginRun and endRun transitions and some of the histogram merging code triggers on those and does some aggregation.

This might all work with the run/lumi filters we apply, but its something that should be looked at (and will be looked at by the DQM folks I assume).

From our side I just would make sure we actually do process data in such an edge case in the tests.

**Comment by ericvaandering** [comment]
I bet CMSSW is smart enough to ignore that, but we should still fix it with a quick list-set-list roundtrip.
