### ISSUE TITLE
ReqMr2 - Admin interface -> link of "check the status of these request"

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#5874]
I followed this steps:
- Go to Admin page
- User management option
- typed "jbadillo" on "new user name" and click on "Add"
This displays a "Confirmation" page, with a section "Further Actions"
If I click on the link "check the status of these request", this goes to the page of a workflow, I thought this was suppose to navigate to the status of the user creation request.

**Comment by ticoann** [comment]
Thanks Julian for testing, actually for admin page we haven determined what we should control for the access control, we completely rely on the sitedb so we don't need to create user. 
Currently there is no restriction for team or groups (group is not even defined). 
If you have any suggestions about what admin should do. we will implement that.  (Since you are the only one gives us feed back, you can suggest whatever you like. :smile: )

**Comment by vkuznet** [comment]
@ticoann , Seangchan, do we need this anymore?
