### ISSUE TITLE
ReqMgr2 -> Create Request by Table or JSON

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/WMCore#5875]
I followed these steps:
- Went to "Create" option
- selected "MonteCarlo" as template
- Either Table or JSON options (I tested both)
- Input the wf information
- clicked on "create"
It created a request, however the name is not displayed. I have to navigate back to "Home" to see which was the name of the workflow.

Also move the mandatory fields on top of the pages

**Comment by vkuznet** [comment]
The mandatory fields on top are addressed in this PR: https://github.com/dmwm/WMCore/pull/5877

**Comment by vkuznet** [comment]
@ticoann, Seangchan in order to implement Julian's request to show request name on web UI once user clicked create button I need REST request API to return the name of the request. The we can tweak ajacRequest function to show it within response pop-up UI element. Please let me know if REST request API can return request name or should we query it separately. If later then we need an id or something to put into the query.

**Comment by ticoann** [comment]
@vkuznet, Valentin, I thought it was returning the names with other stuff. 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L434

``` python
[{'RequestName': blah, ....]
```
But I will change to return only request names. ['request1', 'request2', ....]
Is that ok?
Could you check what is returned currently?

**Comment by vkuznet** [comment]
Currently it return the passed workflow parameters. I changed code to return created request name instead and modified web UI to show this. Please review PR: https://github.com/dmwm/WMCore/pull/5879
![screen shot 2015-05-08 at may 8 12 22 09 pm](https://cloud.githubusercontent.com/assets/125138/7540731/df8901be-f57d-11e4-8aa8-63af2d8422ff.png)

**Comment by vkuznet** [comment]
@ticoann, Seangchan, I think this is fully working by now. Should we close the issue?
