### ISSUE TITLE
Validate sitewhite list and blacklist.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#5892]
Shouldn't be able to set the site whitelist and blacklist for the same site.

**Comment by amaltaro** [comment]
From the discussions I had so far, it seems people would prefer to get an intersection of them instead of completely different lists. So we either:
 a) add validation not to have duplicate site in both lists
 b) (whitelist - blacklist) https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/WMBSHelper.py#L307 , and don't inject valid=False into wmbs anymore

**Comment by ticoann** [comment]
I was wondering why people set the same site for both black and white list. If it is just a human mistake we can validate when the site list is set.

**Comment by amaltaro** [comment]
It was not a mistake, but that's how Jean-Roch understood these site lists would work (intersection).
For me it also makes no sense saying that "I want a beer" and at the same time "I do not want a beer" :-)
