### ISSUE TITLE
Create trust PU site location flag

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#5971]
Since the 'useSiteWhiteListAsLocation' (or trustSiteList...) applies only to the input dataset, we should also create a flag to trust the PU site location, such that agents would pull down work even if PU sample is not available.

This is mainly to allow running redigi at opportunistic sites. With the SDSC, NERSC and AWS flying around, we should mark it as high prio for the next cmsweb cycle.

**Comment by hufnagel** [comment]
Instead of creating a new specific flag for this, we could also add the needed flags to use the "Tier0 style site override". That one is a direct override in the JobSubmitter, it doesn't rely on faking input data location. As such, it wouldn't care about secondary input location either.

Possible downside is that this needs a check and possible change of any location aware intermediate code layers. For instance, job splitting groups input by location, which can be suboptimal if you then submit the job to other sites anyways.

**Comment by amaltaro** [comment]
What do you mean by "it does not fake input data location". I guess the correct thing here is to get all the files available from the PU dataset and consider (fake) them as available at the site whitelist, no?
Maybe you can point me to a commit/PR containing these changes?

**Comment by hufnagel** [comment]
I mean that the regular site override fakes the data to be present at all sites it runs on. That has consequences for file location aware later code (like job splitting).

The "Tier0 mode" override is a direct override in the job submission, location information is not touched.

**Comment by hufnagel** [comment]
By design your current way of doing things has advantages in that you get the behavior of "run everything as if the data is also at site C, even if it isn't for free. But it has big disadvantages too because this mode by design only allows you to do remote xrootd reads for the very first task in a workflow. You can't override the later stages.

That was exactly the reason I needed something else for the Tier0.

**Comment by hufnagel** [comment]
This is activated with this parameter in a spec

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L902

and then applied per task like this

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L274

**Comment by amaltaro** [comment]
For most of the cases - up to now - faking the data location for the first task only would be all we wanted.
However, from the AWS discussions I've seen so far, we want to run one full workflow starting from scratch and going up to (MINI)AOD., so the Tier0 override is what needs to be done here.

Hmmm, so that's the difference between UseSiteListAsLocation and TrustSitelists... I wanted to learn these things (actually get rid of of one of them) since quite some time :-)

**Comment by ericvaandering** [comment]
Well, to first order we want to run as many (well few) cmsRun{1,2,3} steps on a single "worker node" as it takes to get from "scratch" to mini(AOD).

**Comment by belforte** [comment]
I have not tried to understand this discussion (yet). But of course the same use case happens for CRAB. Is there any interest for a common solution, at least semantic-wise. THe implementation may be different, but in the long run it may be good to use same  language and same logic.
Crab3 already has an issue for this:
https://github.com/dmwm/CRABServer/issues/4334

**Comment by ericvaandering** [comment]
So just to put my proposal in words, we would have a setting like like "Trust_Pileup_From='T?_US_*'" rather than just a boolean. 

What that would do is when it hits the worker node populate the list of available pileup LFNs from the superset of the files that exist at any site matching the RegEx.

This way we can draw pileup files worldwide or from regions or from a "sister site" like T2_UCSD for Gordon and balance performance against statistics in a number of ways.

**Comment by belforte** [comment]
Not sure if it makes sense that I write thi comment, but after trying to understand if this debate is useful for the CRAB sim with pileup use case:
do I understand correctly that that would be a setting in WMA for a specific workflow ?
At least that seems the idea of the former comments (to me). This concept of "Here I am, therefore I can user pileup from there and there" is intriguing, but it seems more a site property. I doubt we want to allow CRAB users to specify the trusted PU list. Maybe it is too early to try to optimize too much 2 input scenario for CRAB. We'll stay with one dataset decide sites, the other comes via AAA from wherever it is.

**Comment by belforte** [comment]
@ericvaandering how do you do this in practice ? Are pileup files drawn in via AAA or what ? are pile up samples sort of distributed a piece here and a piece there, rather than replicated ? If files have multiple non-local locations, one can not tell AAA to use site X rather then site Y as source for a file, it is decided by the redirectors. right ?

**Comment by ericvaandering** [comment]
I think CRAB is best of staying the way it is, not paying any attention to the location of the pileup since it's not really in the users power to move the two close together. Additionally, if I understand how CRAB works, it does not try to manage the list of pileup files for a job, that's left completely to the user.

WMAgent, in contrast, does do this, so it's not possible to run at a site where the PU does not exist because WMAgent refuses to correctly configure the job. Since we are doing something from scratch, we may as well do it well. :-)

I think since the pre-mixed sample is going to be O(1B) events, we may have situations where sites have just parts of it. And correct, AAA does not let us control where the files come from, we expect it to optimize things.

**Comment by belforte** [comment]
understood, thanks.
