### ISSUE TITLE
taskchain subsequent step job location matching data location

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#5982]
as discusssed during the workflow team meeting, it coud solve some limitation of using the taskchain if the TaskN(N>=2) could have job created to sites in the white list matching the output of step1 location.
example: A,B,C in whitelist.
Task1 gets fully done at A, but output is replicated at B and therefore end up at A & B. Task2 would only try to read from A, ignoring that B is a possible job location.

**Comment by amaltaro** [comment]
Eim? Probably you miswrote something, that's the current behaviour. Task2 will try to run at A only.

**Comment by vlimant** [comment]
The desired behavior is to have task2 running at A and B

**Comment by amaltaro** [comment]
Subsequent tasks don't use DBS nor PhEDEx for data location, that's why we currently cannot replicate output from task1 and get this new location in for task2. It uses the information returned from the task1 jobs.

At the time we get task1 output replicated to other sites, we most likely would have all the task2 jobs running or pending. That means:
 - we would need to query dbs/phedex for all files produced from task1
 - locate jobs using file x
 - condor_qedit those jobs to add new location.

It's a reasonable issue, however, since one can play with a golden site whitelist, it may take some time to get this done.

**Comment by hufnagel** [comment]
Seconded. All the data subscriptions run as an external step within the agent in a fire&forget mode and the actual PhEDEx transfers are outside the agent anyways. They are in no way coupled to the execution of the taskchain, which triggers when output of task1 is available and the job splitter for task2 sees that data. By design transfer requests and changes in location do not affect subsequent processing steps within the agent, period.

You can make a request to change this, but that would be a major design change for the WMAgent, ie. rewriting a core principle of how it works.

At the moment, if you really have a set of tasks where this is absolutely needed, you submit them as separate requests and wait til request1 is done at sire A, wait til the transfer to site B is done and then submit request2 to site B.

**Comment by hufnagel** [comment]
What "might" be possible is to implement something with different sitewhitelists and trustSiteLists for later tasks. That won't make the WMAgent location of the data match the after-transfer location, but as you know you also made the request to site B, you override the agent location matching and tell it to submit to site B anyways, even though all the input data is at site A as far as the agent is concerned.

PromptReco at T1 submitted from the Tier0 works a bit like that.

This would rely on adopting the Tier0 mode of site overrides for job submissions for the agent (they are using different methods at the moment) and some fancy code to get the configurations right.

**Comment by hufnagel** [comment]
You better make sure site A has functional xrootd export of its data though, because the job creation and submission for task2 is not going to wait for the transfers to run, which might make this unusable in practice...

**Comment by ericvaandering** [comment]
Yeah, we cannot do this without a major redesign of WMAgent. It's a great idea for an ideal system, but that's it.

**Comment by vlimant** [comment]
got around this with editing the site white list of secondary jobs in JobRouter
