### ISSUE TITLE
Request settings for allowed and force workflows to run on Amazon EC2

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#5994]
Perhaps name these more generically. But the point is that AWS will be a sub-type of FNAL resources and we should set a flag for workflows that are able to run on AWS and another (or different value of the same) that forces a workflow to run on AWS for debug purposes.

**Comment by ericvaandering** [comment]
@tiradani as a starting point, what should we name these classAd variables. Have you decided that yet? Presumably we would NOT like to choose a name that includes FNAL or AWS

**Comment by tiradani** [comment]
How about "SendToCloud"?  I think "Overflow" is overloaded at this point, but that would be my second choice.

**Comment by hufnagel** [comment]
SendToCloud is a bit generic, isn't it ? Especially in Europe AWS is basically a non-entity for cloud projects and some of the clouds here don't have the same restrictions (like charges for data out). The purpose of this flag is pretty much restricted to AWS right now, isn't it ?

**Comment by hufnagel** [comment]
Call it AllowAWS/ForceAWS or something like that. I currently don't see this flag being used for anything else. If we ever do generalize it, we can always rename, its easy enough.

**Comment by hufnagel** [comment]
@ericvaandering , why wouldn't you want to have AWS in the flag name ? That's what its there for after all...

**Comment by ericvaandering** [comment]
Well, for the general "can run on the cloud" variable, we could allow NERSC/UCSD/Italian Cloud to pick these up at some point in the future. I.e. a way of flagging a workflow that it has cloud-like parameters. Minimal I/O. For the "force" it may make sense to have something more specific. And if we can get away from encoding "force this to" in WMAgent, I'm happier. That sort of thing doesn't scale when you've got handfuls of such sites.

**Comment by hufnagel** [comment]
My point is that the minimal IO requirement is something AWS specific and has nothing to do with cloud in general. So using a generic "AllowCloud" flag for AWS makes not much sense because it doesn't apply to other clouds.

If you want to be generic, call the flag what it is: "WorkflowWithMimimumIO" or something like that.

**Comment by ericvaandering** [comment]
That's fine. MinimalIO is fine with me. The question I have then is do we even need the "force" setting. Presumably FNAL can take care of that on their end with a condor_qedit if needed.

**Comment by hufnagel** [comment]
Well, we need the force setting because some jobs we don't want to end up on Fermilab resources, ie. they should only run on AWS. You can do a condor_qedit, but that doesn't help you that much if the job is already running.

Both these flags are hacks. Our WM software stack and the way we define a site simply does not allow us to send workflows to separate resources within a single site.

**Comment by tiradani** [comment]
Actually Dirk, it isn't AWS specific.  What is specific to AWS is the
cost.  Excluding Google and MS, everywhere else it is a matter of
capability.  How many smaller cloud can or are willing to dedicate a 10Gb/s
network pipe to CMS?  There are other constraints, like where do we stage
data, where do we stage out data, etc.  These constraints go beyond the
network issues.

**Comment by hufnagel** [comment]
I just know what the constraints are for current European cloud procurement projects and there they ask for no restrictions on data input/output. And AWS for this reason and even more so for political reasons will not be considered. This doesn't even factor in the various university clouds where we sit in the same data center as all other CMS resources.

So my point is that a classification based on a resource type is pointless because that resource type covers a very wide area of capabilities. Better classify the workflow by what the workflow actually does (ie. minimal data input and/or output) and then a site can decide for itself what resources it maps these workflows classifications on).

The ForceAWS flag is purely for testing purposes, we can call it whatever we want. We need it for commissioning and testing on AWS, not for normal production later. So what we call it is kind of irrelevant.

**Comment by ericvaandering** [comment]
" Our WM software stack and the way we define a site simply does not allow us to send workflows to separate resources within a single site."

That's true, but not relevant in this case. The whole point of what Tony is trying to set up is an extension of T1_US_FNAL where they decide when and what to overflow. Not to set up T1_US_FNAL_AWS as an additional resource managed by WMAgent.

**Comment by hufnagel** [comment]
Yeah, I understand that. All I am saying is that we do not decide centrally at the RequestManager level "this workflow can run on AWS/Cloud/Whatever", but instead classify it as "minimal data input/output" and then Fermilab makes the decision on their end that these jobs can be offloaded to AWS.

The latter approach actually has a chance to be generalized later, the former with AllowCloud IMO has no chance.

**Comment by hufnagel** [comment]
I see two options here:

 - AllowAWS/ForceAWS flags only for the Fermilab use case, we can't and won't generalize.

 - Workflow classification with decision about what workflows to offload to AWS at FNAL

Anything in between IMO has no chance to be generalized and therefore you might as well not bother and just go with the simple first option.

**Comment by amaltaro** [comment]
I think we are over complicating this subject :) In the end, the only thing we care about in WMCore is that we set a binary flag saying what can run in AWS (or any other cloud/opportunistic resource) and what cannot. Keeping in mind that it will be defined during the workflow assignment such that the person responsible for this assignment will be "classifying" the type of workflow and where it is allowed to go.

Said that, how about "AllowOverflow"? If local site admins will properly setup resubmission/overflow to cloud resources, that's another story that goes beyond this issue IMO.

**Comment by hufnagel** [comment]
Any flag you can define is only applicable to the current AWS at FNAL resources. It might apply to other cloud resources or it might not. It might apply to other opportunistic resources or it might not.
That really depends on the resources and how they are hooked up into the site that is providing access to these resources.

**Comment by tiradani** [comment]
Hi Dirk,

Lets forget FNAL for a moment.  Look at HLT.  There are very specific
subsets of workflows that can be run there.  The main reason is that the
resources can disappear rapidly.  You still need to flag the workflows such
a way that they can be routed to a resource like HLT.  Logically, HLT sits
at CERN and *could* be considered part of the CMS CERN site.  If you did
that, it would be the responsibility of the CERN site to route those jobs
to HLT.

I know we haven't done that, but I think it was mostly because there was no
way to actually *do* something like that when HLT was being brought into
the mix.

In the end, your statement, "Better classify the workflow by what the
workflow actually does (ie. minimal data input and/or output) and then a
site can decide for itself what resources it maps these workflows
classifications on)." is absolutely true.  This flag is a starting point
which simply allows a site (in this case FNAL) to route jobs to
opportunistic resources.

The more I think about it, the more I like Alan's suggestion of
"AllowOverflow".

Thanks,

Anthony Tiradani

**Comment by hufnagel** [comment]
The only objection to "AllowOverflow" is that the term "overflow" is already used in the context of allowing jobs within the jobs to be moved to sites that don't host their input data. Could be confusing.

**Comment by tiradani** [comment]
How about "AllOpportunistic"?

**Comment by tiradani** [comment]
err... I meant, "AllowOpportunistic"

**Comment by hufnagel** [comment]
I like it. And we stay with ForceAWS for the other as that is temporary anyways.

**Comment by amaltaro** [comment]
For the record, almost half of our production pool is running the new agent version which may advertise
AllowOpportunistic = true

(or false...) The complete migration should finish by the next week.
