### ISSUE TITLE
Run-based MC workflows - EventBased splitting

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6132]
Let me put here what I discussed/understood with @drkovalskyi @vlimant 
For some very special cases, we need to run ReDigi workflows where the splitting algo is EventBased, since people want to simulate conditions in smaller pieces than a lumi section. Thus it requires assignment using EventBased algo, one example:
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/pdmvserv_BPH-Summer12DR53X-00190_00409_v0__150806_163347_6592

The problem here, AFAIR, is the following, when there is input dataset and the wf is set to EventBased, a different merge algo is used and it only triggers a merge job in case all the jobs (for its fileset?) succeed, so merges may not be created at all.

The SQL queries are super complex for these cases and I don't know yet all the deepest details of merges, but it should work as follows:
- once all jobs reading the same file are completed, their outputs should be eligible to be merged (no matter whether there are failures or not)
- the agent _cannot_ create merge jobs for unfinished files, otherwise we may get the same lumi in different files.

Dima told me it's not top priority, but we better fix it as soon as we can.

**Comment by hufnagel** [comment]
It already works like this, except if there are failures none of the output for the processing of that file is considered good. This is intentional, because we do not have bookkeeping that keeps track of less than a lumi. PromptReco was using this until recently, so this is working.

For data keeping less than a lumi is a complete no-no, even for MC I am not sure what the consequences are at the framework level. Which means a) we should check what the consequences of changing this are and b) if we change it, we better make 100% sure it's never accidentally used for data processing.

**Comment by hufnagel** [comment]
Also, why do people want to simulate for less than lumi section ??? In MC we can make a lumi section as small or as large as we want...

**Comment by amaltaro** [comment]
Dirk, about
> ... except if there are failures none of the output for the processing of that file is considered good.

so if the input dataset has 10 files and we get a single file for each of these files, there is no output since no merges are created, right? 

Basically, people using this setup will take their chances, nothing is guaranteed (unless we really can and want to merge broken lumis...)

**Comment by hufnagel** [comment]
No. Event splitting doesn't go across file boundaries. So if you get one failures it invalidates the output from all jobs processing the same input file, but not output from jobs processing other input files.

**Comment by amaltaro** [comment]
correction: get a single failure for *each* of those 10 files

**Comment by amaltaro** [comment]
ok, clear now. Thanks

**Comment by hufnagel** [comment]
Event based splitting is basically the same as file based splitting in how it treats errors. It just allows you to split the processing into more jobs (file based splitting can lead to very long jobs).

All the re-assembling and taking account of failures for a group of jobs processing the same file is also very expensive to deal with. You've looked at the queries :-)

**Comment by hufnagel** [comment]
Another problem: You have to merge along the original file boundaries, which can lead to problems if your workflow increases the event sizes. That was eventually the reason we abandoned this for good in the PromptReco, the RECO output files became too large to handle.

**Comment by drkovalskyi** [comment]
Dirk, can you clarify what happens when a job needs to cross the file boundary? We are getting a job with smaller number of events, right?

Regarding why people need something smaller than a lumi section, in run-based-MC it's a matter of sampling conditions properly. It's related to the limitation of the framework that doesn't allow to change the run number more than once per job.

The bottom line is that we do have use cases once in a while were having a functional event-based splitting is needed. A restriction not to cross a file boundary sounds Ok to me.

One more question. What do we do for ACDC? Do we resubmit all jobs that share the same input file? It's not very efficiency, but it should also be Ok (better than cloning and starting from scratch).

**Comment by hufnagel** [comment]
Jobs don't cross file boundaries. Lets say you have a file with 8345 events and an event splitter with 1000 events. You get 8 jobs with 1000 events and 1 job with 345 events.

I remember some discussion with Diego (ex FNAL, since left) about averaging this out, so assigning 8345/9 events to each job. But fundamentally it didn't change the fact that we didn't create jobs that processed parts of two files.

The only case the event based splitter could process multiple files was if the number of requested events was larger than the sum of events in multiple files.

**Comment by hufnagel** [comment]
I still don't understand what splitting by event gets you. The multiple n event jobs processing your m event lumi section (where m>n) still use the exact same job configuration. So what is the difference to just processing the whole lumi in a single job ?

**Comment by drkovalskyi** [comment]
The configuration is the same, but it's not doing the same things. It changes run number and use corresponding conditions from data. I don't know the details of how exactly it works inside, but basically they need the ability to run smaller than a lumi-section number of events.

**Comment by drkovalskyi** [comment]
Can someone please summarize what needs to be done to declare event-based splitting working and what are the restrictions? I guess the only missing part is a proper ACDC or merging part also needs some work?
