### ISSUE TITLE
Distinguish compactList from runsAndLumis in LumiList

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6243]
If you see the class docstring, compactList should be a range of lumis
{ '1':[[1,45],[50,80]]}
while runsAndLumis should be a list of individual lumis
{ '1': [1,2,3,4,6,7,8,9,10]}

**Comment by ericvaandering** [comment]
Yeah, what are you saying? Both of these forms can work in the constructor depending on what values you pass. Can you describe what you need? This code is shared with CMSSW and I maintain both parts of it, so if you tell me what you need to do, I can do it.

I wasn't actually telling you "Use this code," I just wanted you to be aware that it existed because for a long, long time, WMCore rolled its own code for this stuff.

**Comment by amaltaro** [comment]
What I needed today was just to know beforehand whether we had one or another (and a method to return each of them). 
What could also be useful is to implement other methods to return the list of lumis in both formats (provided a run number). 

This guy
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/Harvest.py#L168
would also be a good candidate to go in there (or it was your last commit maybe :))

**Comment by ericvaandering** [comment]
No, but I saw that function which reminded me that I should do something similar in my code.

So you should be able to do something like LumiList.getRunsAndLumis()['4'] and fetch all the lumis in a list for run 4? Or even LumiList.getRunsAndLumis(run=4)

I can do that, the problem comes with expanding theoretical lists like {'4':[1,9999999999]} which is perfectly valid but unstorable. :-)
