### ISSUE TITLE
Tier0 wmstats agent document is not updated properly

### ISSUE THREAD

**Issue by ebohorqu** [dmwm/WMCore#6256]
When we restart an agent, the agent info section in wmstats is not correctly updated. It shows there is an error with AnalyticsDataCollector component, when it is not the case and agent is running properly. @ticoann

**Comment by ticoann** [comment]
Hi Eliana, as we discussed I am not sure what is the cause of this. (wmstats doesn't have this problem)
I am guessing since tier0 record everything to local couchdb and replicate docs to central tier0_wmstats,
(unlike wmstats - agent document directly uploaded to central db), some how replication screwed up when agent is redeployed.  - Agent documents are the only document updated periodically.

I can change the code to update the agent document direct for tier0 as well whether that fixes the problem. @hufnagel, Dirk, is that ok? will this cause any problem when you do the stand alone test?

**Comment by hufnagel** [comment]
Shouldn't be a problem because replay instance anyways have everything local

WMSTATS_URL=http://admin:couch@localhost:5984/wmstats
REQUESTCOUCH_URL=http://admin:couch@localhost:5984/t0_request
WORKLOAD_SUMMARY_URL=http://admin:couch@localhost:5984/workloadsummary

ie. whether there replication local1 to local2 or upload directly to local2 should not matter. Does this answer your question or did I misunderstood something ?

**Comment by ticoann** [comment]
Thanks Dirk, that was what I wanted to know.
