### ISSUE TITLE
Switch ACDC request creation to create the reqmgr2 request

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6312]
Currenly when ACDC is created, It is creating reqmgr1 request. We can either make this optional or change to reqmgr2 request creation. I would say we switch to create reqmgr2 request. (And fix the bugs if we can find) Making this optional will can be done but not sure that will confuse ops more.
@amaltaro, Alan, what do you think?

**Comment by amaltaro** [comment]
Short answer, I do not know :-)
If possible, I think my choice would be to create reqmgr2 ACDCs when the original request is from reqmgr2, otherwise make a reqmgr1.
We could make this switch, but then I'm afraid McM may not be able to completely track all these requests (original + acdcs in reqmgr2).
