### ISSUE TITLE
Investigate couchdb replication for wmstats (checkpoint?)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6377]
In our current couchdb setup, every time couch is restarted it tries to replicate ALL the docs to central couch. I noticed it in the hard way when I restarted submit2 in the last Friday and today we still see wmstats behind the latest updates.

Things we should improve on replication side are:
 1. try to use checkpoints (at least for wmstats). Diego explained me there was a problem (doc creation in the source and target db --> permission issues) in the past and that's why it was disabled.
 2. drop deleted docs from wmstats replication (which is one way only agent to central).

**Comment by amaltaro** [comment]
@geneguvo Diego, this is the placeholder for the couchdb replication issue discussed in the last release planning meeting. Feel free to pass by my office or ping us here in case you need any help/test with this.

**Comment by geneguvo** [comment]
FYI. I'm working on it. I also took note on our monthly plan (https://gitlab.cern.ch/cms-http-group/doc/issues/27) so we don't loose track of it.

**Comment by amaltaro** [comment]
Thanks, Diego!

**Comment by geneguvo** [comment]
Hi,
I did several tests and adjustements using two VMs and I conclude the checkpointing feature is working with our Couch1.6.

However, we must use the proper configuration. In particular, the default "checkpoint_interval" of 5 seconds is too low a value to be used on poor performance private VMs, eventually making them overload to the point of crashing couch. I believe we were fooled by such crashes before when we decided to keep it disable. By setting to anything like 1min it already goes fine even on these poor VMs.

For production machines, it is unlikely that even low values like the default 5 seconds would be an issue. But in any case we should use even higher values like 5min or 15min IMHO. I don't see why we should be checkpointing at any high frequency.

I also did various tuning in the couch configuration while testing the replications. I could find the following set of config being the most performant:
```
worker_processes = 4
http_connections = 10
worker_batch_size = 5000
use_checkpoints = true
max_replication_retry_count = infinity
socket_options = [{keepalive, true}, {nodelay, true}]
```

But since in prod things are much more different, this tuning is probably not the best there. Anyhow, I just wanted to say that by tuning it I could manage to get a 2 - 3x faster replication. If replication time with wmstats in production (i.e. when we rotate the databases) would eventually be an issue, we should consider doing the tuning.

Finally, there were some minor issues the couch manage script (when adding replications), but IFAIR wmagents don't use it, so it should not be a problem for you guys.

Alan, I'll pass by your office so we enable it properly for an agent pointing to cmsweb-testbed in order to move forward.

**Comment by ticoann** [comment]
That's great. Thank you very much for taking care of this. We owe you beer. Since I am far, Alan will pay for it. :smile:

**Comment by amaltaro** [comment]
LoL, you better pay a coffee to Diego. Otherwise, you can pay me a beer, I don't mind ;)

**Comment by amaltaro** [comment]
Most of them production agents have checkpoint enabled. New agents are getting it by default, so closing this issue. Thanks to Diego for the fix!
