### ISSUE TITLE
Migrate wmstats views to erlang

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6382]
We've seen some issues with wmstats views in the last days and it's not managing to keep things up-to-date. Migrating its views from javascript to erlang would help us to mitigate these issues.

In addition to that, we have the same views in erlang and in javascript (agentInfo and requestHistory).
We could remove the javascript ones.

**Comment by amaltaro** [comment]
@juztas since you were playing with ASO views, would you like to take this issue? :-)
If not, @BrunoCoimbra is willing to do so.

**Comment by geneguvo** [comment]
Hi guys,
I have some good news about this.

I've checked my old notes from 1 year and a half ago, when we were having problems with the wmstats views still in the old couch, old machines.

At that time I wrote most of the views in erlang (12 out of 16 if I remember correctly), but only moved  to production 8 of those (the other 4 we left to be included later). In the meantime, you guys have cleaned up some views that were not anymore needed. So right now, wmstats has:
```
agentInfo
cooledoffRequests
jobsByStatusWorkflow
latestAgentSite
latestRequest
requestAgentUrl
requestHistory
time
```
From these, agentInfo and requestHistory are already there in erlang and being used, so we should be able  to drop their corresponding javascript version.

From the others, I have cooledoffRequests, latestAgentSite, latestRequest and requestAgentUrl from my old notes. I've double checked and their code haven't changed since then, so we should be ready to use them.

After that, there's only "time" and "jobsByStatusWorkflow" remaining. "time" is easy to implement, however "jobsByStatusWorkflow" seems to be the most complicated one of all the views for the map function. Its reduce function is easy since is the same already in use in other views.

If we could write "jobsByStatusWorkflow" in erlang, then we could drop completely the javascript version, otherwise even if we keep this last one things shall already improve by dropping the others.

Cheers,
Diego.

**Comment by juztas** [comment]
Go ahead @BrunoCoimbra Let me know if you need any help

**Comment by geneguvo** [comment]
I'm doing some performance tests using the current views we already have in erlang vs javascript. I'm using a snapshot of the database we had on the day of the issue in production.

Depending on the results, we may stay with the remaining javascript views. Otherwise, Bruno is going to work on the remaining views.

**Comment by geneguvo** [comment]
I've finalized my performance tests comparing the 6 (out of 8) views  we have written both in javascript and erlang. The erlang views performed ~1.7 times faster than the javascript ones with the wmstats production database we have atm.
Bruno is already working to write the two remaining views. I'll anyhow make a PR to include the current erlang views in next reqmon version.

**Comment by ticoann** [comment]
Thanks guys, The most important views for wmstats (always used and deals with most documents are 
latestAgentSite, latestRequest)
When I moved Diego's script to in WMStats,  I must have missed the other scripts, I only have 2 erlang versions in WMStats. 
https://github.com/dmwm/WMCore/tree/master/src/couchapps/WMStatsErl
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStats/rewrites.json

Diego, could you point me the erlang code you have I will put those in WMStatsErl. Thanks.

**Comment by ticoann** [comment]
For the reference, we have the issue already created for this. #5626
