### ISSUE TITLE
Add basic FJR attributes to job classad

### ISSUE THREAD

**Issue by bbockelm** [dmwm/WMCore#6590]
Since we're scraping `condor_history` and `condor_q` outputs, it would be useful if we could complement the job information with some more data about the job run.

WMRuntime can scalably set attributes in the classad by doing:

```
condor_chirp set_job_attr_delayed key value
```

where `value` is quoted according to classad rules.  This sends the additional key/value info along with the next scheduled update (so there aren't scalability issues here).

Particularly, I'd like to get the following pieces of information:
- Exit code of the job.
- Number of MB transferred from the last CMSSW step.
- Events process from the last CMSSW step.
- Log archive LFN.

**Comment by bbockelm** [comment]
@hufnagel also suggested that he may have time to tackle this.

**Comment by ticoann** [comment]
Thanks Dirk. :smile:

**Comment by hufnagel** [comment]
Started looking at this. WMAgent runtime code is highly modular, it's a sequence of steps that are executed, the global wrapper code is very short and minimal functionality. As such, there isn't really a good place to put this as a global implementation, it's better off in the step executors. Would have to touch both the cmssw and logarchive executor implementations. Likely want to have the chirp call implemented as a function that is callable from both executors instead of implementing it twice.

@bbockelm , this causes a problem though because this way you won't get the exit code of a job, just the exit code of the cmssw step(s). You also won't just get the info from the LAST cmssw step, but the infos from ALL cmssw steps (we can distinguish them by key name).

The only pieces of code that really looks at all these things together is the JobAccountant, ie. a central daemon. We don't aggregate this information at runtime.

**Comment by bbockelm** [comment]
Hi Dirk,

Can't we have both?  I.e., have the CMSSW executor update attributes name CmsFooExitCode and CmsExitCode?

I suggested the last step because I figured that was easiest.  If we can get all, that's even better.

Do note that classad attributes aren't json - there are various quoting rules you might hit if reporting each step.  What do the step names look like?

Brian

**Comment by hufnagel** [comment]
Sure we can do both, one set of attributes per cmssw step, the other common so the last step wins in setting it. Step names for cmssw are usually cmsRun1, cmsRun2 etc.

**Comment by hufnagel** [comment]
Another thing, what do you want the logarchive LFN for ? The one from the processing job is kind of useless as it is a temporary LFN in unmerged space. It survives maybe order one or two days at most.

**Comment by hufnagel** [comment]
Have some initial code, but it fails in testing because condor_chirp isn't in the search path. If I call it directly I get "command not found" from python, if I invoke it via bash I get exit code 127 (the same thing).

Is condor_chirp supposed to be usable out of the box at runtime ? Do I need to run some init before I can call it ?

**Comment by hufnagel** [comment]
Ok, after talking with Parag, I can bootstrap myself from the CONDOR_CONFIG environment and find the condor_chirp binary that way. This works now, call to condor_chirp also works, but the exit code is always 1. Guess I have to look at stdout and stderr next to see what it is complaining about.

**Comment by hufnagel** [comment]
No stdout and stderr, but found the problem. The key has to start with a case-sensitive 'Chirp'.

**Comment by hufnagel** [comment]
Ok, I have something working. Before I make a pull request, what does "quoted according to classadd rules" mean in this context.  I am using this right now:

args = [ condor_chirp_bin, 'set_job_attr_delayed', str(key), str(value) ]
returncode = subprocess.call(args)

which means passing strings directly to condor_chirp. Do I need to add quotes around them somehow ?

@bbockelm , any suggestions ?

**Comment by bbockelm** [comment]
Yeah - values need to be quoted - value.__repr__() should work.

Keys must start with Chirp and need to be alphanumeric.  No punctuation or special characters.

**Comment by hufnagel** [comment]
Ok, I changed it to str(value.__repr__()). It absolutely has to be a string because subprocess.call() only accepts strings in the argument list. Also changed the attribute names to

ChirpCMSSWcmsRunExitCode (for the last CMSSW step)
ChirpCMSSWcmsRun[1-9]ExitCode (for each individual CMSSW step)

Made a pull request #6618 , what's the best way to test this ? @bbockelm , can I see in these new attributes in the condor_q or condor_history output ? I can run another replay on vocms001 and we could check then if they are there...

**Comment by bbockelm** [comment]
The attributes should show up in both `condor_q` and `condor_history` output.

Since CMSSW itself uses the `ChirpCMSSW` prefix, can you use `ChirpWMCore`?

**Comment by hufnagel** [comment]
Ok, works, but with problems. All the condor_chirp calls return exit code 0, but not all attributes show up in condor_history. Sometime none show up, sometimes a few, it varies. Attributes from the second CMSSW step (this is an express job with two) never show up.

My suspicion is this:

Delayed setting of the attribute is synced with the submit node in up to 15 min. If the job terminates before this sync occurs, the sync is never done. This would explain the behavior I see.

@bbockelm , opinions ?

**Comment by bbockelm** [comment]
Nope - everything buffered locally should get passed on at the final update.

Looking at the past 24 hours, of 55.7k jobs reporting via condor_chirp from CMSSW, 237 have the final update missing.  Further, of those 237 that report an exit code, all are non-zero.

What version of HTCondor?  I know there were bugfixes in HTCondor for something in this code; don't know what.

**Comment by hufnagel** [comment]
HTCondor version on the Tier0 schedd I am using (vocms001) is 8.3.8.

**Comment by bbockelm** [comment]
ah - I mean on the worker nodes.  That's the relevant condor version for `condor_chirp`.

**Comment by hufnagel** [comment]
From condor_history

CondorVersion = "$CondorVersion: 8.3.1 Jul 22 2015 $"

**Comment by bbockelm** [comment]
Ah - yes, this is a bug that was fixed in 8.3.6.  The T0 must be running older glideins than everywhere else.  Can we upgrade?

Found the ticket here: https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=5050

**Comment by hufnagel** [comment]
I think this means we need to update the VM, because the pilot (and HTCondor) is baked into our image. Will request a new version.

**Comment by bbockelm** [comment]
Sure - in the meantime, can you give me a list of all the output attributes?  I think this is ready to go in!

**Comment by hufnagel** [comment]
#6618 is ready to be merged IMO

'Chirp_WMCore_cmsRun_ExitCode' : last CMSSW step exit code
Chirp_WMCore_cmsRun1_ExitCode : first CMSSW step exit code
plus all other CMSSW steps exit codes (cmsRun2, cmsRun2 etc)

Everything else needs more work because it wasn't readily available to me. But as soon as someone else ( @amaltaro ? ) writes the codes to extract the required information, the call to condor_chirp is a one liner.

**Comment by hufnagel** [comment]
Is anyone actually working on this ?

**Comment by ticoann** [comment]
No, I don't think so. I will put on my list.
