### ISSUE TITLE
add splitting button for each request in assignment page

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6622]
i.e. 
https://cmsweb-testbed.cern.ch/reqmgr2/assign

next to the each request name add the splitting button.

**Comment by vkuznet** [comment]
Well, since this page contains N requests, I think we need to assign ajax call
for splitting button, otherwise depending on N we may fetch too many requests
and need to construct long html with all splitting tasks. Do you agree?

And, my understanding that splitting button will only provide editable json,
right?

**Comment by ticoann** [comment]
> Well, since this page contains N requests, I think we need to assign ajax call for splitting button, otherwise depending on N we may fetch too many requests and need to construct long html with all splitting tasks. Do you agree? 

yes and splitting button is only per request it can't be multiple request. It is just need to be updated one by one.

> And, my understanding that splitting button will only provide editable json, right?
Yes, we can use the same GUI we have. (not a duplicate but actually pointing the code)

**Comment by vkuznet** [comment]
That was a tough one. Please check reqmgr2-dev with updated web UI which correspond to this PR: https://github.com/dmwm/WMCore/pull/6627
Please review and let me know.

**Comment by ticoann** [comment]
tested and worked fine. There was a bug in server side but it is fixed now.
