### ISSUE TITLE
ReqMgr2 does not take the site white list into consideration

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6647]
I see jobs running everywhere and an empty site whitelist (in the workload) list for the test workflows injected into testbed (anorkus_*).

**Comment by amaltaro** [comment]
It seems we are missing a workload.updateArguments() here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L413

which then would call this method:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L490

Anyways, this does not work. I'm still missing something :(

**Comment by ticoann** [comment]
Hmm, it should updated from following line.
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Service/Request.py#L393

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1714

Anyway, since you figured out the problem, I will just wait for your patch. Thanks Alan and stop working at night. :smile:

**Comment by amaltaro** [comment]
Yes, but L393 is not called for requests' update, since it has a status already. Anyways, feel free to trash my fix in case it should be fixed somewhere else. Have fun! :-D
