### ISSUE TITLE
reqmgr2 return indented json

### ISSUE THREAD

**Issue by anorkus** [dmwm/WMCore#6651]
Hi,

it would be great for developing/debugging to have a return of data from reqmgr2 in indented form.
Default one could be not indented, but if specified with `&debug=True` in url would return indented json.

Best regards,
    Antanas Norkus

**Comment by ticoann** [comment]
what do you mean by indented json? Are you saying when you look at the browser you want to be json formatted?  In that case this should be controlled by accept type. we can make text/html form with intended json format.

**Comment by anorkus** [comment]
yes something like in here:
https://cms-pdmv-dev.cern.ch/mcm//public/restapi/chained_requests/get_dict/EXO-RunIIFall15DR76-03799

in any case if you want to display indented output you have to return text/plain type. 

although i would prefer to have a separate parameret like debug=True (indented=True) which would save me editing request headers in browser. 

Also browser by default sets 'Accept: */*' so in this case i don't know which format data would be returned.

**Comment by ticoann** [comment]
> in any case if you want to display indented output you have to return text/plain type.
> 

Usually browser picks up text/html mime type first but text/plan would be simpler for me since I don't have to add <br />

> although i would prefer to have a separate parameret like debug=True (indented=True) which would save me editing request headers in browser.
> 

I think it is not very restful for controlling format like that. For the convenience I could add what you have above /get_dict/requestname.

> Also browser by default sets 'Accept: /' so in this case i don't know which format data would be returned.

I can make the default format test/plain so browser will pick up the type first. I don't think think it picks up application/json type ahead of other type I guess that is not guaranteed (Maybe different browser has different implementation)

Anyway, I will provide the format in away you don't have to change anything (Accept header) in the browser.

**Comment by anorkus** [comment]
i would like to discuss what is RESTFUL and what is not whole day. Feel free to pass by my office when you are in CERN and we can discuss about this with beer in hands.

My suggestion with extra parameter is widely used by bigger projects in industry like in elasticsearch or mongoDB:
https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_pretty_results
mongo return pretty printed by default.

And i don't see a reason to duplicate a method (having pretty  and non pretty ones) or play around with Accept headers.

**Comment by ticoann** [comment]
Thanks for the link. But I don't think we should do the same way just because some bigger project does that way.
Is there a any reason you want to have a extra parameter?
If you want to view the pretty format in the browser, I said I will provide the default view in browser in a way you don't have to change anything. (It seems default format is controlled in server side not browser side). So you will use the same url without extra parameter and get the indented json in browser.
For the script, you can control the return type by accept header.
I don't see any advantage having extra parameter for that. 
However, please let me know if you have specific use case that extra parameter is necessary. We can implement that if necessary.  Thanks,

**Comment by anorkus** [comment]
thanks for implementing this. 
If bigger project uses that maybe it shows that implementation is correct and people will use it same way. Thats why i gave this example: I would prefer to 'not reinvent the wheel'.
Other point with extra parameter is clarity: i want a prettified output i put pretty=true, if i don't i dont put parameter. In this way everything is clear to user.
If you pass prettified output depending on Accept headers in might be unclear how browser orders with the headers (usually they send Accept: */*). This might make different output depending on browser - i guess nobody likes that.

My point of view is that user should have more control/clearance on what/how he wants to see rather that some unknown voodoo things depending on browser.

**Comment by ticoann** [comment]
> If bigger project uses that maybe it shows that implementation is correct and people will use it same way. Thats why i gave this example: I would prefer to 'not reinvent the wheel'.

I don't think we are reinventing anything. If we are not following the standard, that wouldn't be good but I don't think it is the standard.

> Other point with extra parameter is clarity: i want a prettified output i put pretty=true, if i don't i dont put parameter. In this way everything is clear to user.

I think some times more options for user are not necessary good. But of course if there is specific use case we can try to make it convenient for the user. Please let me know if you have specific use case.

> If you pass prettified output depending on Accept headers in might be unclear how browser orders with the headers (usually they send Accept: /). This might make different output depending on browser - i guess nobody likes that.
> 
> My point of view is that user should have more control/clearance on what/how he wants to see rather that some unknown voodoo things depending on browser.

I think there is misunderstanding here (I misunderstood initially, too), controlling which format is not on browser side if browser accept multiple formats. It is on the server side, so if browser accept multiple formats, server gets to decide which format to send. (Unless the browser is asking specific format, but I don't think any major browser doing that).

Anyway, testbed is updated
i.e.
https://cmsweb-testbed.cern.ch/reqmgr2/data/request?name=amaltaro_RVCMSSW_7_0_0_pre11TTbar_PU__FastSim_140204_230436_8400
 
Please let me know if you find the problem or something can be improved.  I appreciate your feed back.
Thanks,
