### ISSUE TITLE
reqmgr2 view page need to display all data when drop down menu are not editable.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#6657]
When not editable page are displayed as below drop down down menu are locked. i.e. site white list.
which can be multiple values set. In those case, it might be better not to use drop down menu

https://reqmgr2-dev.cern.ch/reqmgr2/fetch?rid=sryu_MonteCarloFromGEN_Sryu_reqmgr2_160303_065637_3414

**Comment by vkuznet** [comment]
Well,
sitewhitelist is not a drop down, it is text area.
The locked dropdowns are:
Outputdatasets, Softwareversions, Teams, Inputdatasets

Do you want to flatten them all?

**Comment by amaltaro** [comment]
Valentin,
yes, make these flat please:
Outputdatasets, Softwareversions, Teams, Inputdatasets

you probably need to flatten or expand Requestdate as well.

BTW, why do we have Inputdatasets and Input Dataset?

I noticed other cosmetic things, but in the end I don't think people will really look at this view.

**Comment by vkuznet** [comment]
Seangchan,
I made a change from drop-down to non-modifiable textarea where entries
will be shown as comma separated values. Please take PR
https://github.com/dmwm/WMCore/pull/6674

But I can't test it on reqmgr2-dev since there is no assigned workflows
and I can't assign one due to team error. If you'll fix team error we
can test this PR. BTW, for team I made another
PR:https://github.com/dmwm/WMCore/pull/6675
but it is awaiting your API.

Valentin.

**Comment by vkuznet** [comment]
@ticoann , Seangchan I'm awaiting your input on PR #6674.

**Comment by vkuznet** [comment]
Please take https://github.com/dmwm/WMCore/pull/6682 and discard #6674

**Comment by ticoann** [comment]
Thanks Valentin, you mean #6892 :smile:
