### ISSUE TITLE
apply archivedelayhours to aborted workflows

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6824]
Hi,

It would nice if the archivedelayhours parameter was applied to aborted workflows (instead of only announced workflows) so that we can keep aborted workflows in wmstats longer for debugging purposes.

Thanks.

Andrew

**Comment by amaltaro** [comment]
Andrew, I don't think this is a legit case and it will just overload wmstats with more info that's generally not used. Instead of keeping useless info around (for 1 out of ~10k wfs), you better spend some time debugging before you flip the flag to aborted.

I'm closing this issue because we'll likley not develop it. If you have strong arguments on why it's needed, provide them and reopen the issue please.

**Comment by AndrewLevin** [comment]
no, Alan it is a legit case, we need the information for aborted workflows

it is actually a very common case that I have some aborted workflow, and I want to get more information about it several weeks later

for example, someone might ask why it was aborted, and I might not remember

**Comment by amaltaro** [comment]
Well, in this case you need some tracking tool and not to have aborted info in wmstats for weeks.
ReqMgr2 has that logging box, maybe that could be used for that purpose (though I'm not sure that works as it is now...)

**Comment by AndrewLevin** [comment]
no we really need the info in wmstats

info about number of job failures in each step and what the cause of the failures is important

there is really no difference between what we are interested in for aborted wfs and for completed wfs

for both we can use wmstats for debugging or answering questions from PPD

there are not that many aborted wfs compared to completed wfs, so it should not be that much of an issue
