### ISSUE TITLE
Expose the site of failure for SubmitFail

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#6868]
when a job is in status SubmitFailed, wmstats does not report to which site(s) it failed to do so : this should be reported instead so that one can judge on whether an ACDC is possible

**Comment by ticoann** [comment]
In this case it is a little tricky to add that information. When job is created it creates the job without location because whitelist doesn't contains file location. I think as you said before, it should be more job creation error than submit failure error. Is it OK if create Job creation error and add the reason (site) on the message. - I haven't look at the code whether it is simple to do that or not yet.

**Comment by vlimant** [comment]
Yes please expose whatever site it want to use but could not

**Comment by vlimant** [comment]
I notice that the error message is now mentioning the site, however, the site the error is reported for is Null, not the site itself (or themselves)
