### ISSUE TITLE
web interface for changing request priority in reqmgr2

### ISSUE THREAD

**Issue by AndrewLevin** [dmwm/WMCore#6874]
Hi,

In the current request manager 2 interface, you cannot change the workflow priority without also changing the workflow status:

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_8_0_8_patch1QCD_FlatPt_15_3000HS_13__testSubsetInput_160520_115440_3999

Can you please make it possible to change the workflow priority without changing the workflow status?

Thanks.

Andrew

**Comment by vkuznet** [comment]
I need more input about that. What you ask is to change a field in provided list of attributes without changing status of workflow, right? A field on web form can be anything, e.g. workflow priority, campain, release, basically anything. I need to understand how user should interact with Reqmgr2 APIs in that case. On a web interface if you ask to change a field we need to introduce either AJAX call or add button to send an action to save your value. Therefore I need first to know how reqmgr2 API should be called in that case. Therefore Seangchan @ticoann input is required.

**Comment by AndrewLevin** [comment]
Only the request priority should be changeable, not the campaign, release, etc.

**Comment by ticoann** [comment]
Hi Valentin, In reqmgr2 any field change is associated to status change. since different status has different dependency to change specific field to change, but priority is exception. (Sorry I didn't forsee this).
Anyway, I think the easiest change will be just add the "no status" field in drop down menu. and make that default. if it clicked, only the allowed field changes, use the same api.

**Comment by vkuznet** [comment]
Please take: https://github.com/dmwm/WMCore/pull/6878
