### ISSUE TITLE
ReqMgr2: changes to view/edit fields in web UI

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#6932]
Just a place holder. Possible related to #6881

Having a look at a request in *assignment-approved* in my VM (running 1.0.17.pre6), I can highlight the following (Table view):
1. there should be fields that can no longer be changed at this point. Couple examples: Requestor, Lumilist, Dqmuploadurl, etc.
2. TBD: empty fields (or None or empty dict) could be perhaps skipped from this visualization
3. Unmergedlfnbase should be a drop-down menu, with default to '/store/unmerged. It's a text box now.
4. Mergedlfnbase should be a drop-down menu, with default to... '/store/mc' sounds Ok
5. Unmergedlfnbase key is shown twice
6. Mergedlfnbase key is shown twice
7. Outputdatasets should be a list inside a text box, instead of a drop-down menu.
8. Requestdate has to be a text box, not a drop-down menu
9. Why do we have 'Software Releases'  and 'Softwareversions' keys? BTW, the latter should be a list in a text box, not a drop-down menu.

**Comment by amaltaro** [comment]
@vkuznet in case you are bored with DAS...

**Comment by vkuznet** [comment]
Alan, to start please provide an URL that I can see visually all your items. I'd suggest that you add some requests to reqmgr2-dev node where I can full access and we can start from there (item by item).

**Comment by amaltaro** [comment]
We can use my VM, under https://alan-cloud2.cern.ch
There are a few requests in both reqmgr and reqmgr2.
I've just added you to the authmap.json frontend file, let me know in case you have problems accessing it

**Comment by vkuznet** [comment]
Alan,
I see no request on your VM, e.g. this page is empty:
https://alan-cloud2.cern.ch/reqmgr2/requests?status=assignment-approved
Please provide full URL to requests that I can see them through web interface.

**Comment by amaltaro** [comment]
Interesting that it does not show requests under that status... Here you have a few
https://alan-cloud2.cern.ch/reqmgr2/fetch?rid=amaltaro_TaskChain_Data_Test_SeveralPRs_160613_214155_6001
https://alan-cloud2.cern.ch/reqmgr2/fetch?rid=amaltaro_MonteCarlo_Ext_Test_SeveralPRs_160613_214211_2445
https://alan-cloud2.cern.ch/reqmgr2/fetch?rid=amaltaro_MonteCarloFromGEN_Test_SeveralPRs_160613_214137_4132

Otherwise you can see all of them through WMStats (push "all requests" button):
https://alan-cloud2.cern.ch/wmstats/index.html

**Comment by vkuznet** [comment]
Alan,
I'll respond to every item in your list:

1. these should be defined somehow in WMCore code for every state
similar to Seangchan's code here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py

I would suggest that you come up with initial implementation
for states you know. The suggested structure should be
```
HiddenAttributes = {state: [... list of attribute names to be hidden ...]}
```
a concrete example would be
```
HiddenAttributes = {'assignment-approved': ['requestor', 'lumilist', 'dqmuploadurl']}
```
Please note that web UI intentionally capitalize attribute names, so
the HiddenAttributes should carry correct attribute names as you use them
in workflow.

2. this can be implemented in similar way as #1

3. my understanding that web UI receives only single value (of type string)
for unmergedlfnbase. I don't know who provide the data to GUI interface but we
should change the data over there with whatever values you want, e.g.
['/store/unmerged', ... whatever values you need ...]. So far I don't see it as
a GUI issue.

4. the same as #3

5. I don't see that it is listed twice, please clarify and check GUI yourself

6. the same as #5

7. this is an interested aspect of the GUI. How code should distinguish
what to show as drop-down or what to show as a textarea.
So far code does the following. If provided value is a list data type, it is
shown as drop-down but if it is not visible attribute it is shown as textarea.
The visible attributes are provided by 

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Web/ReqMgrService.py#L471
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/DataStructs/RequestStatus.py#L109

therefore in order to accomplish your request we need either to always use
text area for list data types or have a way similar to visible attributes
to define what should go as drop-down and what as textareas. Once it is
defined elsewhere (outside of GUI) the GUI adjustment can be done trivially.
I insist to keep GUI data agnostic, i.e. do not introduce if statements
based on attribute values like
```
# not acceptable in GUI
if  value == 'outputdatasets':
    # do this
if  value == 'bla-bla':
    # do this
```
the above code is a path to a mess.

8. the same as #7

9. I don't know, the GUI accepts what it is given, therefore if you
think software releases and softwareversions should not be in a data
fix the data. Then see #7.

**Comment by amaltaro** [comment]
Ok, thanks Valentin. I'll get back to you once I manage to do something on this front.

**Comment by amaltaro** [comment]
Posting another use case that I just faced - before I forget it - I just noticed we need to properly handle (on both server and web UI) workflow assignment. I just assigned this one:
https://cmsweb-testbed.cern.ch/reqmgr2/fetch?rid=amaltaro_ACDC_MonteCarlo_LHE_HG1607_ReqMgr2_Validation_160706_174602_1372

without changing anything but the status (so no team, no site, only the ACDC initial parameters).

**Comment by vkuznet** [comment]
Alan, I'm not sure I understood the problem. Could you please elaborate more and in a different way. Is the problem was with assignment or you can't change the status. Please provide full description/steps to demonstrate the problem.

**Comment by amaltaro** [comment]
That was a reminder to myself. For you, I need to write down all the web UI use cases and what can change. Later :)

**Comment by amaltaro** [comment]
At least a couple of PRs fixing this issue #7255, #7254
