### ISSUE TITLE
Convert mox to mox3 

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#7071]
mox3 should be compatible with python 2.7 and 3.5. I think @SaltumDis is already looking at this. Part of #7067

**Comment by ericvaandering** [comment]
Can close this if its really not an issue.

**Comment by mapellidario** [comment]
This is the result of my brief investigation.

#### mox3 is no longer maintained

This is the pypi webapge: https://pypi.org/project/mox3/, whose "Homepage" link redirects to https://opendev.org/openstack/mox3/src/branch/master/README.rst, which states that the project is no longer maintained

#### mox is used only in one unit test

The only file that emerges when running `grep -r "mox" .` in dmwm/WMCore is `./test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py`. This is promising, since in order to remove the dependency could be enough refactoring a single file.

### the unit test that uses mox fails

This is strange and may be my fault. 

If I run the unit test that uses mox with `python setup.py`, the no unit tests are executed

```
[dmwm@bb364d87db84 WMCore]$ python setup.py test --buildBotMode=true --reallyDeleteMyDatabaseAfterEveryTest=true --testCertainPath=test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py
running test
Using the tests below: test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py
#### WE ARE DELETING YOUR DATABASE. 3 SECONDS TO CANCEL ####
#### buildbotmode is true
We are going to trash databases after every test
### We are in buildbot mode ###
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
path lists is ['test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py']
Out of 0 cases, we will run 0
Testing complete, there are now 1 threads
```

If I try to run it with `nosetests`, than it seems like that the unit test is configured properly, since I get

```
[dmwm@bb364d87db84 WMCore]$ nosetests test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py
EEEE
======================================================================
ERROR: testFailOnFileSize (WMCore_t.Storage_t.Plugins_t.SRMV2Impl_t.SRMV2ImplTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py", line 149, in testFailOnFileSize
    None)
  File "/home/dmwm/unittestdeploy/wmagent/1.3.2.pre2/sw/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
TypeError: doTransfer() takes exactly 9 arguments (8 given)

[...]

======================================================================
ERROR: testWin (WMCore_t.Storage_t.Plugins_t.SRMV2Impl_t.SRMV2ImplTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py", line 222, in testWin
    None)
TypeError: doTransfer() takes exactly 9 arguments (8 given)

----------------------------------------------------------------------
Ran 4 tests in 0.021s

FAILED (errors=4)
```

In any case, these tests do not seem to be in jenkins (or at least I have not been able to find them)

### there is another unit test with the same name of the one one that uses mox

there is another unit test with the same file name in a similar directory: 
* `test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py`  : uses mox, all test fails when I try to run them with nosetests. 
* `test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py`: does not uses mox and runs successfully in jenkins

### opinion

It seems that the unit test that uses mox has already been refactored, but I may be super wrong stating this.

**Comment by amaltaro** [comment]
Thanks for investigating this, Dario.

When you run the unit tests in bot mode, those unit tests don't get executed because they have been marked as integration, such `integration` unit tests are skipped from our jenkins CI tests.

I think there was a previous person (Adelina) working on those Backends tests in the past and getting rid of mox, so perhaps you could look into:
test/python/WMCore_t/Storage_t/Backends_t/SRMV2Impl_t.py
and replicate the same mocking behavior in
test/python/WMCore_t/Storage_t/Plugins_t/SRMV2Impl_t.py

That way, we can finally get rid of mox and have one less dependency.

**Comment by amaltaro** [comment]
@mapellidario as we discussed in the past week, I'm setting this issue free such that others can pick it, if they want.
