### ISSUE TITLE
LogCollect not moving from running to completed

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7074]
https://cmsweb.cern.ch/reqmgr/view/details/jen_a_ACDC_task_B2G-RunIISpring16DR80-01193__v1_T_160804_213906_2780
https://cmsweb.cern.ch/reqmgr/view/details/prozober_ACDC_task_B2G-RunIISpring16reHLT80-01139__v1_T_160802_151622_5969
https://cmsweb.cern.ch/reqmgr/view/details/jen_a_ACDC_task_B2G-RunIISpring16DR80-01193__v1_T_160804_213914_4857
https://cmsweb.cern.ch/reqmgr/view/details/jen_a_ACDC_task_B2G-RunIISpring16DR80-01193__v1_T_160804_213929_1879

 are all LogCollect ACDC and not toggling done

**Comment by amaltaro** [comment]
Can I ask you why on earth you guys are creating ACDC workflows for logCollect
```
    "InitialTaskPath": "/pdmvserv_task_B2G-RunIISpring16DR80-01193__v1_T_160731_123432_3198/B2G-RunIISpring16DR80-01193_0/B2G-RunIISpring16DR80-01193_1/LogCollectForB2G-RunIISpring16DR80-01193_1", 
```
???

LogCollect and Cleanup ACDC workflows are not supported:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L124

I checked only the last request, but if all of them are ACDCs for LogCollect, then please force-complete and let them *gracefully* get to completed status.

**Comment by vlimant** [comment]
On the one hand, true that LogCollect should probably not be ACDCed.
On the other hand, if it's not supported, it should not succeed to create. But since a job was made and run and succeeded, natural would be that the wf goes to completed and we'd all be happy ever after.

**Comment by amaltaro** [comment]
I really don't want to spend time on something that is not supported and that Ops should be aware that makes no sense.

Since we have very few "users" of the production system, it would be great if the team know what makes sense to do, what they _should_ and what _not_, instead of making the code blocking all these not allowed actions.

So, please force-complete and get those workflows out of the system.

**Comment by vlimant** [comment]
I force-complete those about an hour ago @scarletnorberg. @amaltaro  I am suspecting that something is odd as they have not reached a further stage yet.

If there isn't anything to be done : i.e. empty acdc doc, then there should be nothing created... while there is. 
Double checking ,the acdc doc itself is containing something https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_task_B2G-RunIISpring16DR80-01193__v1_T_160731_123432_3198%22&include_docs=true&reduce=false for these LogCollect steps.
 
The https://github.com/CMSCompOps/WmAgentScripts/blob/master/makeAllACDCs.py script does not prune out the LogCollect, so it must have always been this way, why are we getting this problem now ?

**Comment by amaltaro** [comment]
Those you initially reported have no acdc docs, however the last one has indeed 3 logcollect docs:
pdmvserv_task_B2G-RunIISpring16DR80-01193__v1_T_160731_123432_3198

If possible, leave this one in the system for a couple of days. The only case I see it passing through that check would be either having no job type or perhaps a diffecrent char case.

**Comment by amaltaro** [comment]
@vlimant can you or someone else abort these LogCollect ACDC workflows please? They will *never* move to `completed` because they contain only one subscription (LogCollect) which will never be seen by this query:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/TaskArchiver/TaskArchiverPoller.py#L185

I'm closing this urgent issue and will create another one for why the acdc server contains logCollect entries.

**Comment by vlimant** [comment]
@amaltaro cannot abort from force-complete. Shall I set "completed" ?

**Comment by amaltaro** [comment]
Hm, we should have the abort option over there...
I'll use Seangchan's script to kill them directly from the agent.
