### ISSUE TITLE
Make error code more organized and useful in wmstats report

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7091]
example of error report.
https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/pdmvserv_BPH-RunIISpring16DR80-00041_00606_v0__160819_164036_1207
1. The top level error code is the first error found in the step. 
   i.e. if the error is found in cmsRun1 step it will report that error, but if the cmsRun1 is successful but next step has error (it will report that error).
2. All the steps which contains error code will be reported  so there could multiple layers of errors.  If cmsRun1 fails, it could cause stage out errors and both will be reported.

I am not sure what would make more sense (Probably, we need to look at the error which occurs in first in multiple step.

**Comment by vlimant** [comment]
@ticoann the link you send is empty, probably because the workflow got archived and disappeared from wmstats (that's good).
Looking now at 
https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/pdmvserv_HIG-RunIISummer15wmLHEGS-00482_00150_v0__160823_201915_1419

I am starting to get a better feel for it. N.B.  #6919 

In the nested dict, here is what I can make of the keys
key1 : taksname
key2 : job status
key3 : main error code
key4 : site
key5 is "errorCount" -> int, and "samples"

"samples" is a list of info collected from agents (*action item number one* is to have all contributing agents to collect in this document. right now it's only one).
Each item is a nested object, good. it has several interesting keys, but the one including reports and code is "errors" where a key indicates the subchildren of the task (cmsRuns, logArch1, ... I wonder whether we should hide the stageout error if the cmsRun1 failed ...)
One of the interesting piece of information is the "output" that contains location of temporary logarchive files.
*action item number two* is to not have only *one* items overall in "samples" but at least 10 as in wmstats view
@dabercro

**Comment by ticoann** [comment]
> In the nested dict, here is what I can make of the keys
> key1 : taksname
> key2 : job status 
> key3 : main error code  

The error code found first from the list of step. (So I think if there is error for cmsRun1 and Stageout, this report the cmsRun1 error)

> key4 : site
> key5 is "errorCount" -> int, and "samples"

The view for getting this error is 

https://github.com/dmwm/WMCore/blob/master/src/couchapps/WMStats/views/jobsByStatusWorkflow/map.js#L12

And we are retrieving  following data from to get the statistics - number of errors per site.
doc.workflow, doc.task, doc.state, doc.exitcode, doc.site

We can increase granularity by the whole set (all 8 element). 

Is this for the analyzing the error code using machine running? or for the human readable debugging purpose. If it is first case we might need to provide bulk query instead of querying one by one (by request)

**Comment by ticoann** [comment]
@vlimant, @dabercro Sample size can be controlled by sample_size param

https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/prozober_ACDC1_task_EXO-PhaseIFall16wmLHEGS-00014__v1_T_170217_094501_9422?sample_size=5



> And we are retrieving following data from to get the statistics - number of errors per site.
> doc.workflow, doc.task, doc.state, doc.exitcode, doc.site
> 
> We can increase granularity by the whole set (all 8 element).
> 
> Is this for the analyzing the error code using machine running? or for the human readable debugging purpose. If it is first case we might need to provide bulk query instead of querying one by one (by request)

Could you comment on the questions above? Is there anything should be added on this issue?

**Comment by dabercro** [comment]
The bulk query you mentioned a while ago might actually be very useful (sorry for missing that question). Sample size is a very useful parameter, thanks! What is the default value at the moment?

**Comment by ticoann** [comment]
Hi Daniel, default value is 1.  If you don't need any other feature, could you close the issue. Otherwise, please let me know what we can add for the api. Thanks

**Comment by dabercro** [comment]
I can't close the issue since I'm neither the creator nor a member, but I'm satisfied for now. Feel free to close this.
