### ISSUE TITLE
Update condor version and build new wmagent release

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7127]
Just talked to Dirk (who talked to Brian), we need to update the condor.spec file to 8.5.4:
https://github.com/cms-sw/cmsdist/blob/comp_gcc493/condor.spec

and then build a new wmagent rpm and make sure it works (mainly PyCondorPlugin).

**Comment by hufnagel** [comment]
We need to either adjust or remove the patch to the package since it doesn't work anymore with 8.5.4

https://github.com/cms-sw/cmsdist/blob/comp_gcc493/cms-htcondor-build.patch

@bbockelm can you take a look at the patch and see if we still need it ?

**Comment by hufnagel** [comment]
Ok, you can't completely remove the patch either, fails to build. Will try to adjust and just remove the sections that can't be used...

**Comment by hufnagel** [comment]
Adjusted the patch and it applies clean, but the build still fails. @bbockelm , I am stuck now.

* The action "build-external+condor+8.5.4" was not completed successfully because Failed to build condor. Log file in /build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/log. Final lines of the log file:

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PACKAGE_DEP_CFLAGS
and PACKAGE_DEP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
configure: error: ./configure failed for gsi/openssl_error/source
make[3]: *** [externals/bundles/globus/6.0/globus-prefix/src/globus-stamp/globus-configure] Error 1
make[3]: Leaving directory `/build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4'
make[2]: *** [externals/bundles/globus/6.0/CMakeFiles/globus.dir/all] Error 2
make[2]: Leaving directory `/build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4'
make[1]: *** [CMakeFiles/externals.dir/rule] Error 2
make[1]: Leaving directory `/build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4'
make: *** [externals] Error 2
error: Bad exit status from /build/hufnagel/w/tmp/rpm-tmp.5D7EN3 (%build)


RPM build errors:
Bad exit status from /build/hufnagel/w/tmp/rpm-tmp.5D7EN3 (%build)

**Comment by bbockelm** [comment]
@hufnagel - can you format that comment so it's readable?  Also, can you send me the build machine you use above so I can poke around at log files?

**Comment by hufnagel** [comment]
Better ? Build machine is vocms022, build is in /build/hufnagel/w/

**Comment by hufnagel** [comment]
Ok, I could fake a pkginfo file for openssl, but only by putting full expanded paths into it (couldn't find a way to put environment variables into a package file). Even with that I get build errors:

'''
* The action "build-external+condor+8.5.4" was not completed successfully because Failed to build condor. Log file in /build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/log. Final lines of the log file:
if ( (method_bitmask & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false ) {
^
/build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4/src/condor_io/authentication.cpp: In member function 'int Authentication::handshake_continue(MyString, bool)':
/build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4/src/condor_io/authentication.cpp:1039:45: error: 'Condor_Auth_Kerberos' has not been declared
if ( (shouldUseMethod & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false ) {
^
/build/hufnagel/w/slc6_amd64_gcc493/external/cmake/2.8.5-comp/bin/cmake -E cmake_progress_report /build/hufnagel/w/BUILD/slc6_amd64_gcc493/external/condor/8.5.4/condor-8.5.4/CMakeFiles 50
[ 52%] make[2]: *** [src/condor_utils/CMakeFiles/condor_utils.dir/__/condor_io/authentication.cpp.o] Error 1
'''

**Comment by bbockelm** [comment]
That indeed looks like a bug in HTCondor - looks like they broke conditionally disabling Kerberos.

Still exists in master.  Will put together a patch.

**Comment by bbockelm** [comment]
Try this:
```
--- a/src/condor_io/authentication.cpp
+++ b/src/condor_io/authentication.cpp
@@ -997,7 +997,12 @@ int Authentication::handshake(MyString my_methods, bool non_blocking) {
         dprintf (D_SECURITY, "HANDSHAKE: handshake() - i am the client\n");
         mySock->encode();
                int method_bitmask = SecMan::getAuthBitmask(my_methods.Value());
-               if ( (method_bitmask & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false ) {
+#if defined(HAVE_EXT_KRB5)
+               if ( (method_bitmask & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false )
+#else
+               if (shouldUseMethod & CAUTH_KERBEROS)
+#endif
+               {
                        dprintf (D_SECURITY, "HANDSHAKE: excluding KERBEROS: %s\n", "Initialization failed");
                        method_bitmask &= ~CAUTH_KERBEROS;
                }
@@ -1047,7 +1052,12 @@ Authentication::handshake_continue(MyString my_methods, bool non_blocking)
        dprintf ( D_SECURITY, "HANDSHAKE: client sent (methods == %i)\n", client_methods);
 
        shouldUseMethod = selectAuthenticationType( my_methods, client_methods );
-       if ( (shouldUseMethod & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false ) {
+#if defined(HAVE_EXT_KRB5) 
+       if ( (shouldUseMethod & CAUTH_KERBEROS) && Condor_Auth_Kerberos::Initialize() == false )
+#else
+       if (shouldUseMethod & CAUTH_KERBEROS)
+#endif
+       {
                dprintf (D_SECURITY, "HANDSHAKE: excluding KERBEROS: %s\n", "Initialization failed");
                shouldUseMethod &= ~CAUTH_KERBEROS;
        }
```

**Comment by hufnagel** [comment]
Had to adjust the patch a bit, didn't apply and also was functionally wrong (you had a copy&paste error on the first chunk where you referenced shouldUseMethod  when it should be method_bitmask).

In addition there were was one more place where they forgot to wrap with HAVE_EXT_KRB5 conditionals, so I had to fix them too. See vocms022:/build/hufnagel/cmsdist/cms-htcondor.patch for the changes.

The package builds now. Unfortunately I can't really make a pull request for review due to the hack with the openssl package file. If I don't get feedback in HN on that I'll bring it up in the release planning meeting on Friday.

**Comment by hufnagel** [comment]
Tested new package with PyCondorPlugin in a Tier0 replay, seems to work. Doesn't mean everything works though, I am bit suspicious about the openssl package info hack and how it affects binaries. We don't use any binaries from the condor package in the agent though AFAIK.

**Comment by hufnagel** [comment]
Have a self-contained recipe to build this now, up to @BrunoCoimbra to decide how we want to deal with this (we either change the openssl build to create a pkginfo file or create a fake one inside the condor spec). To be followed up on in HN.

**Comment by hufnagel** [comment]
Pull request is in

https://github.com/dmwm/WMCore/issues/7127

**Comment by amaltaro** [comment]
I built 1.0.19.patch2 wmagent tag with the new condor PR (as provided by Dirk) and ran all the DMWM/Integration tests using PyCondorPlugin.
* job priority change looks good
* job removal by id looks good
* jobs removal by request name looks good
* all the rest looks good.

From my side, we can upgrade condor version. Is Marco taking care of this for CRAB3? Should we ping someone else to carry this validation on the analysis land?

**Comment by amaltaro** [comment]
New condor 8.5.4 is available in the official repo. Closing this issue.
