### ISSUE TITLE
WQE Failed for workflow in running-closed

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7179]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_HIG-RunIISpring16DR80-01830_00657_v0__160905_161208_8622

the workflow has no pulse. First time I see this configuration and WQE in failed.

**Comment by amaltaro** [comment]
This workflow is processing a _peculiar_ dataset which seems to face data bookkeeping issues, as we can see from the das query (too many small blocks, almost 9k blocks):
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=dataset%3D%2FTTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8%2FRunIISummer15wmLHEGS-MCRUN2_71_V1-v1%2FGEN-SIM

then this is the first logging I have in central workqueue showing an element was being marked as Failed:
```
2016-09-10 03:16:37,273 INFO     WorkQueue: Request pdmvserv_HIG-RunIISpring16DR80-01830_00657_v0__160905_161208_8622 finished ({'Status': 'Failed', 'PercentSuccess': 93, 'PercentComplete': 95})
```

which seems to be then triggering a transition of the whole request to failed (which fails, since this transition is no longer allowed):
```
2016-09-10 03:25:03,066 INFO     WorkQueueReqMgrInterface: Checking Request Manager for open requests and closing old ones
2016-09-10 03:26:10,765 WARNING  Service: The cachefile /data/srv/state/workqueue/cache/.wmcore_cache_100034/requests/cmsweb.cern.ch/7118294399707410289_PUT_request does not exist and the service at https://cmsweb.cern.ch/reqmgr/reqMgr/request is unavailable - it returned 403 because Forbidden
 with result: {"exception": 403, "message": "Failed to change status: Cannot change status from running-closed to failed.  Allowed values are ['force-complete', 'completed', 'aborted']", "type": "HTTPError"}

2016-09-10 03:26:11,237 ERROR    WorkQueueReqMgrInterface: Error talking to ReqMgr about request "pdmvserv_HIG-RunIISpring16DR80-01830_00657_v0__160905_161208_8622": Traceback (most recent call last):
  File "/data/srv/beHG1608b/sw/slc6_amd64_gcc493/cms/workqueue/1.0.19.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 192, in report
    self.reportElement(ele)
  File "/data/srv/beHG1608b/sw/slc6_amd64_gcc493/cms/workqueue/1.0.19.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 323, in reportElement
    self.reportRequestStatus(element['RequestName'], element['Status'])
  File "/data/srv/beHG1608b/sw/slc6_amd64_gcc493/cms/workqueue/1.0.19.pre4/lib/python2.7/site-packages/WMCore/WorkQueue/WorkQueueReqMgrInterface.py", line 277, in reportRequestStatus
    raise ex
HTTPException
```

Most of those elements (>5k) was acquired by vocms0311 and we can find some WorkQueue logs at:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/vocms0311_WorkQueue_Issue7179

where we see the WQE was set to Failed due to
```
Failing workflow "pdmvserv_HIG-RunIISpring16DR80-01830_00657_v0__160905_161208_8622" as not queued in 86400 secs: cannot invoke setopt() - perform() is currently running
```

which seems to come from pycurl/multithreading problem. Still debugging this issue...

**Comment by vlimant** [comment]
Why was the WQE marked as failed ?

**Comment by amaltaro** [comment]
Is mentioned in the end of my reply: "as not queued in 86400 secs", workqueue failed to split that block from the local workqueue_inbox to workqueue. Then why it took so long, I couldn''t find.

**Comment by vlimant** [comment]
ping. the workflow is dead stuck.
If there is a chance that a force-complete function, I'd like to know.
It would be good to know and protect for the timeout failing the WQE

**Comment by amaltaro** [comment]
Sigh, `force-complete` won't cancel the Failed wqe, so it will make no difference in this case.
We could set it to `aborted`, this way we can get rid of all the wqe, otherwise If we flip the status manually to `completed`, then all the wqe will stay around. In which status you want to have it in the end (completed)?

Another thing, does it help if I script something that collects all the block names from wqe in Failed status and inject a new workflow with those blocks whitelisted?

Yes, the initial patch is meant to protect from these cases.

**Comment by vlimant** [comment]
The large dr sample would be good to get to completed. If we start it over, we have to have the confidence that it will not get in the same hole.

Making a workflow that will collect the remaining work, with the proper prepid (for tracking) and be assigned to the same whitelist with the same output would work. If it's a Resubmission workflow, then the original one has to end up being in "completed".

You can make a clone and assign it for the same output, then pass it through to completed right away if you really have to set "aborted" the original wf. Then assign your resubmission *after* doing so.

**Comment by amaltaro** [comment]
I chatted with JR and a clone was created with the 376 failed blocks in the white list
amaltaro_HIG-RunIISpring16DR80-01830_00657_v0__160916_142209_4986

here is the original list of wqe ids and block that are in Failed status:
http://amaltaro.web.cern.ch/amaltaro/forWMCore/pdmvserv_HIG-RunIISpring16DR80-01830_00657_v0__160905_161208_8622_FAILED.json

Jean-Roch gave us the green light to abort the original workflow, IF needed. However, we need first run ACDCs, otherwise aborting it would also trigger the acdc db cleanup AFAIK.
@ticoann I'd like to discuss with you how we handle this case

**Comment by ticoann** [comment]
I discussed with Alan, 
Alan told me that new workflow is created for failed WQEs. So

1.We will manually complete this workflow by moving the state. and delete all the elements from the GQ and LQ.  (currently all the elements are either Failed or Done status)
2. Then Ops can make ACDC before closeout and announced.

I would like to check few more things about the WQ status before doing 1. I will post when I do that (either later today or tomorrow morning)

**Comment by amaltaro** [comment]
@ticoann Seangchan, have you started deleting or updating any of these documents in an ad-hoc way? Just wondering whether this could be somehow related to the central workqueue couch instabilities over the last 12h (some corrupted doc or so).

**Comment by ticoann** [comment]
@amaltaro Hi Alan, I haven't start to deleting the WQE yet. I haven't moved the workflow to complete either.

**Comment by amaltaro** [comment]
Then I can't blame you for the cmsweb GQ instabilities :)

**Comment by ticoann** [comment]
Couldn't do it partially because couchserver kept crashing. Now I will delete those. :smile:

**Comment by ticoann** [comment]
@vlimant, @amaltaro, did anyone do with this workflow? I seems it is force-completed and completed this morning and now it is announced. WQ elements are all deleted as well.

**Comment by vlimant** [comment]
the requestor send a "I want it" signal over Unified triggering a force-complete

**Comment by ticoann** [comment]
Thank for clarifying that. Closing the issue. Alan has new issue and  patch for this problem

**Comment by amaltaro** [comment]
Just for my education, this action taken by the requestor triggers this transition to force-complete only, right? Did this workflow move itself to `completed` or someone had to force it (just to know whether I was wrong)?

**Comment by vlimant** [comment]
it moved to completed by itself. be re-assured that we don't move to completed manually, or by script.

**Comment by ticoann** [comment]
force complete changes all the workqueue element in WQ to Cancelled (CancelRequested) and it will delete all the WQ element eventually if there is no running job or finish killing job.
I guess Failed status changed to Canceled and got deleted eventually. Which also triggers workflow to move completed status.
