### ISSUE TITLE
WQE Running but not moving forward with jobs

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7183]
spotted https://cmsweb.cern.ch/reqmgr/view/details/pdmvserv_EXO-RunIISpring16MiniAODv2-05043_00539_v0__160914_132202_6483 with all blocks in 304 all job success but nothing further

http://vocms0304.cern.ch:5984/workqueue_inbox/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_EXO-RunIISpring16MiniAODv2-05043_00539_v0__160914_132202_6483

appears all completed.

http://vocms0304.cern.ch:5984/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_EXO-RunIISpring16MiniAODv2-05043_00539_v0__160914_132202_6483

or not

further than fixing that issue itself, I'd like a monitor/alarm of any such discrepancy so that we can view this kind of issue straight from wmstats.

**Comment by vlimant** [comment]
@scarletnorberg

**Comment by ticoann** [comment]
@vlimant, Jean-Roch, did you do any manual completed this workflow?

**Comment by amaltaro** [comment]
It's all clean right now, both woekqueue and workqueue_inbox db... I've no clue of what happened, it could be due to the other very big workflow that was aborted over the night, summing up with additional load on couch (compaction/indexing), but just speculation :(

BTW, I'm switching couch back to localhost on vocms0304, the last time I seen it in the RelVal node, it was very very unstable.

**Comment by vlimant** [comment]
The workflow stayed in this limbo for more than 10 hours, and I have not done any status change. We have to understand what was in the way, the agent logs must be able to provide this.

What it the characteristic timeout after which we should consider something being really problematic ? 12h ? a day ? Can we have an alarm after this timeout

**Comment by vlimant** [comment]
should the localhost setup be a default for stability/speed ?

**Comment by vlimant** [comment]
![daily](https://cloud.githubusercontent.com/assets/4989875/18547565/5e390822-7b44-11e6-878b-71f363e17ff4.png) for the record

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr/view/details/pdmvserv_EXO-RunIISpring16MiniAODv2-05051_00542_v0__160915_001654_3773 another chance to look at this http://cms-gwmsmon.cern.ch/prodview/pdmvserv_EXO-RunIISpring16MiniAODv2-05051_00542_v0__160915_001654_3773

**Comment by amaltaro** [comment]
localhost is the default case, we switch it when some debug is needed.

About pdmvserv_EXO-RunIISpring16MiniAODv2-05051_00542_v0__160915_001654_3773, what are you suggesting? The workflow is running-open, that's why it's waiting for the OpenRunningTimeout delay in order to inject the secondary jobs. OpenRunningTimeout should only be used for requests where the input dataset is still growing (I'm actually consider to remove that), but it's something else.

**Comment by vlimant** [comment]
I think you just explained it, the OpenRunningTimeout is too large for all production. That's a parameter made at creation. Can that be changed in assignment ? it's actually set to 12h and that's the delay to create secondary jobs.

We'll have to have all request injected with a small value for that parameter, or assign with a small value.
If you think it's fine to remove that parameter all together, even better.

**Comment by amaltaro** [comment]
I'm in favor of completely removing it from the submission side.  I still have to go deep into the code to make sure all the past use cases are no longer needed for this feature (already have the green light from T0), if so then we can clean this up from WMCore as well.

Nope, it's a creation parameter only.
