### ISSUE TITLE
Open blocks left in TMDB

### ISSUE THREAD

**Issue by sidnarayanan** [dmwm/WMCore#7223]
We have noticed a number of blocks in TMDB whose transfers cannot finish because the blocks are still open. These blocks are quite old (at least several days), so I do not think it is a simple race condition. Here are a couple examples:

```
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/None-v1/GEN#1a998bba-bd98-11e5-ab12-a0369f23d050
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/AODSIM#a7130922-c767-11e4-b23a-a0369f23d008
```

Please let me know if you need any other information.

**Comment by ticoann** [comment]
@sidnarayanan 
Hi Sid, 
Those 2 blocks doesn't seem to be exist in dbs.
Do those blocks contain any files?

The first block seems to be invalid block. (The workflow it creates that block is aborted - also acquistion era is set to None)
/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/None-v1/GEN#1a998bba-bd98-11e5-ab12-a0369f23d050

The second block, it seems there is no record in wmagent as well. I suspect whether it ran in draining agent and it was removed before block is cleared. One thing I suspect since it was closed-out and announced, it might be the case we just discard this block but it already started PhEDEx injection. - I have to check further.

https://cmsweb.cern.ch/dbs/prod/global/DBSReader/blocks?block_name=/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/AODSIM%23a7130922-c767-11e4-b23a-a0369f23d008

For both of this case we can delete the blocks from TMDB, but could you give the complete list of the blocks whose transfers cannot finish.

**Comment by sidnarayanan** [comment]
@ticoann , thanks for taking a look!

I do not think these are empty blocks. At least, TMDB belives they are not, e.g. [1]. 

Here is a JSON of all stuck transfers that are complete, but not closed due to open blocks [2].

[1] https://cmsweb.cern.ch/phedex/datasvc/json/prod/data?block=/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/None-v1/GEN%231a998bba-bd98-11e5-ab12-a0369f23d050

[2] http://t3serv001.mit.edu/~snarayan/TransferErrors/www/stuck_m1.json

**Comment by amaltaro** [comment]
Sid,
from your list [2], most of those blocks have AcqEra = None. You can safely go ahead and remove them from TMDB. That leaves us just a few blocks that need deeper investigation.

**Comment by ticoann** [comment]
Thanks Sid, for the list. I will investigate those blocks.
The first block seems to have file in TMDB which is invalid block which makes more sense since it works as normal but someone/program has to invalidate the blocks.

However I couldn't see any record in the second block, does that mean there is no files in TMDB?
https://cmsweb.cern.ch/phedex/datasvc/json/prod/data?block=/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/AODSIM%23a7130922-c767-11e4-b23a-a0369f23d008

**Comment by amaltaro** [comment]
Adding @vlimant @prozober

From the list of open blocks provided by Sid above, there are 30 blocks and 26 of them have `None` as AcqEra (old bug in the agent fixed > 3 months ago), they are:
```
>>> pprint(noneBlocks)                                
[u'/ZJetsToNuNu_HT-800To1200_13TeV-madgraph/None-v1/LHE#09897098-c4ae-11e5-8a1d-001e67abf094',
 u'/gluinoGMSB_M1950_ctau1p0_TuneCUETP8M1_13TeV_pythia8/None-v1/AODSIM#8f16176c-ed52-11e5-88f6-a0369f23d05a',
 u'/TTbarDMJets_pseudoscalar_Mchi-1_Mphi-20_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/AODSIM#25d7ce42-d07b-11e5-9370-a0369f23d01e',
 u'/SMS-T2bW_X05_mStop-125to275_mLSP-0to150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/MINIAODSIM#07fa020c-c5f2-11e5-9207-a0369f23d01e',
 u'/TTbarDMJets_pseudoscalar_Mchi-1_Mphi-500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/MINIAODSIM#96f4b1aa-d187-11e5-ac46-a0369f23cf8a',
 u'/SMS-T2bW_X05_mStop-125to275_mLSP-0to150_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/AODSIM#072f870c-c5f2-11e5-9207-a0369f23d01e',
 u'/ttH_HToZZTo2LX_M145_13TeV_powheg2_JHUgenV6_pythia8/None-v1/LHE#ce56c906-c4aa-11e5-8a1d-001e67abf094',
 u'/ZJetsToNuNu_HT-600To800_13TeV-madgraph/None-v1/LHE#9013ae92-c550-11e5-b6a9-a0369f23cf8a',
 u'/WplusH_HToZZTo4L_M124_13TeV_powheg2-minlo-HWJ_JHUgenV6_pythia8/None-v1/MINIAODSIM#8d1124be-bc49-11e5-ab12-a0369f23d050',
 u'/SeesawTypeIII_SIGMAplusSIGMA-ZW_M-540_13TeV-madgraph/None-v1/MINIAODSIM#9a69c2b8-edd8-11e5-ba7c-001e67abf094',
 u'/WplusH_HToBB_WToLNu_M125_13TeV_powheg_pythia8/None-v1/LHE#9c0e2f26-c553-11e5-b196-001e67abefa8',
 u'/RSGravToEEMuMu_kMpl-001_M-750_TuneCUEP8M1_13TeV-pythia8/None-v1/AODSIM#14ff1d70-e2b2-11e5-aaaa-001e67abf094',
 u'/SMS-T2cc_mStop-100to150_mLSP-20to90_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/AODSIM#ae12ffd0-c607-11e5-815d-001e67abf518',
 u'/WToLNu_2J_8TeV-amcatnloFXFX-pythia8/None-v1/GEN#f66b9122-bfca-11e5-9207-a0369f23d01e',
 u'/ZH_HToZZTo2LX_M130_13TeV_powheg2-minlo-HZJ_JHUgenV6_pythia8/None-v1/LHE#45bb280c-c4c4-11e5-b196-001e67abefa8',
 u'/TT_TuneEE5C_13TeV-powheg-herwigpp/None-v1/AODSIM#ae3d92f8-c509-11e5-8a1d-001e67abf094',
 u'/SMS-T2cc_mStop-325to365_mLSP-245to365_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/MINIAODSIM#c92f1148-c6b9-11e5-b196-001e67abefa8',
 u'/ttHJetToGG_M120_13TeV_amcatnloFXFX_madspin_pythia8/None-v1/MINIAODSIM#8f1202de-d741-11e5-ac7e-001e67abf094',
 u'/DYToEE_M-20_CT10_TuneZ2star_v2_8TeV-powheg-pythia6/None-v1/GEN#1a998bba-bd98-11e5-ab12-a0369f23d050',
 u'/ZprimeToZhToZinvhAA_2HDM_M-1000_13TeV-madgraph/None-v1/MINIAODSIM#d4122bf6-e2aa-11e5-a5ee-a0369f23cf8a',
 u'/SMS-T2cc_mStop-100to150_mLSP-20to90_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/MINIAODSIM#1f3bfcfa-c614-11e5-815d-001e67abf518',
 u'/ttH_HToZZTo2LX_M125_13TeV_powheg2_JHUgenV6_pythia8/None-v1/LHE#d6f75e68-c4c3-11e5-b196-001e67abefa8',
 u'/TT_TuneEE5C_13TeV-powheg-herwigpp/None-v1/MINIAODSIM#5f1e868e-c56b-11e5-b196-001e67abefa8',
 u'/ZH_HToZZTo2LX_M160_13TeV_powheg2-minlo-HZJ_JHUgenV6_pythia8/None-v1/LHE#304513b2-d27e-11e5-ac7e-001e67abf094',
 u'/SMS-T2cc_mStop-325to365_mLSP-245to365_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/None-v1/AODSIM#7a15c89c-c608-11e5-815d-001e67abf518',
 u'/WToENu_M-5000_TuneCUETP8M1_13TeV-pythia8/None-v1/MINIAODSIM#d7e432c4-dfc1-11e5-9fff-a0369f23d05a']
```

Can we ask Sid/Transfer Team to invalidate them in TMDB and remove any replicas? Should we invalidate only those blocks or the whole dataset (which would have None as well). I think the whole dataset. Jean-Roch/Paola, please confirm.

Then the last 4 blocks with valid naming:
```
>>> pprint(okBlocks)                                  
[u'/RelValQCD_Pt_80_120_13_HI/CMSSW_8_1_0_pre8-81X_mcRun2_HeavyIon_v1-v1/GEN-SIM#c152a2d0-42df-11e6-836c-02163e016cc2',
 u'/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/DQM#51ad5484-2b08-11e4-909a-00221959e69e',
 u'/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/AODSIM#10d22eea-2a53-11e4-909a-00221959e69e',
 u'/TZTo2LNuB_FCNC_8TeV_madgraph_TuneCUETP8M1/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM#a7130922-c767-11e4-b23a-a0369f23d008']
```

the 1st belongs to an aborted-archived wf; the 2nd and 3rd belong to _several_ workflows where 1 is normal-archived and all the others are rejected-archived; the 4th and last one belongs to a workflow normal-archived.
What should we do with those? Do we just invalidate these blocks in TMDB/DBS and remove their replicas?

**Comment by amaltaro** [comment]
@sidnarayanan can you please invalidate/remove those 26 datasets with `None` as AcqEra (first list)?

About the second list, please invalidate/remove the first 3 blocks (since they are not in dbs anyways):
```
/RelValQCD_Pt_80_120_13_HI/CMSSW_8_1_0_pre8-81X_mcRun2_HeavyIon_v1-v1/GEN-SIM#c152a2d0-42df-11e6-836c-02163e016cc2,
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/DQM#51ad5484-2b08-11e4-909a-00221959e69e,
/QCD_Pt-15to1000_fwdJet_bwdJet_Tune4C_Flat_2p76TeV-pythia8/ppSpring2014DRX53-castor-v2/AODSIM#10d22eea-2a53-11e4-909a-00221959e69e,
```

Finally, the last block 
`/TZTo2LNuB_FCNC_8TeV_madgraph_TuneCUETP8M1/Summer12DR53X-PU_S10_START53_V19-v1/AODSIM#a7130922-c767-11e4-b23a-a0369f23d008`
has input data in DBS already. Actually, it's opened since Mar 20. Could you please close this block in phedex? Unfortunately there is no way we can investigate what happened half year ago.

Once you're done, feel free to close this issue.

**Comment by sidnarayanan** [comment]
Done! Closing the issue.

**Comment by amaltaro** [comment]
Thanks, Sid. Let us know in case you find new open blocks in PhEDEx.
