### ISSUE TITLE
CSP not communicating OS agent component error

### ISSUE THREAD

**Issue by scarletnorberg** [dmwm/WMCore#7235]
The CSP is not providing any feedback and OS seems to not be active. There is an agent with component error and loosing jobs.

**Comment by amaltaro** [comment]
Scarlet, if the CSP is not reporting on agent issues, then it may be that instructions are not clear. There is nothing that WMCore team can do to improve that.

About the component error, please follow the following procedure (if not written in any twiki yet, please do so):
1. get the whole error message/traceback and agent name and report the problem here (if not already reported)
2. restart the component and watch the logs for 5min or so, just to make sure it's not going down right away again. IF it does go down, then please update the issue with this info (that requires a developer to look at the agent right away).

Please, close this issue or update its description and subject with the problem (always providing enough information)
