### ISSUE TITLE
Duplicated lumis on ACDC server?

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#7301]
Hi guys,

As I explained here https://its.cern.ch/jira/browse/CMSCOMPPR-137, we have a MonteCarlo workflow that overproduced events by a large number. The workflow only had one ACDC round. 

Looking into this https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22pdmvserv_SUS-RunIISpring16FSPremix-00055_00034_v0__160929_122033_2363%22&include_docs=true&reduce=false
we can see there is something rare with the lumis to be recovered.
Could you please help us to understand why the lumis are duplicated in the acdc server?

Thanks.

**Comment by amaltaro** [comment]
Hi Paola, I was having a look at this workflow and honestly... I have no clue at all how that happened. It seems we got more than 20 entries for `MCFakeFile-pdmvserv_SUS-RunIISpring16FSPremix-00055_00034_v0__160929_122033_2363-Production-fa3a91bc780de492218c2fe34047a1c3` with the full runLumi mask (31k lumi sections).

It will probably require deep debugging - and provided I have a few other nasty issues in my hands right now - could you please leave this request in `completed` status and clone/run another workflow (<3k jobs, it's faster if you run a clone than wait for me).

**Comment by vlimant** [comment]
I unfortunately rejected that wf.

**Comment by amaltaro** [comment]
I managed to get some info though. I was following the ErrorHandler algorithm and these are my notes.

There are 133 jobs in failed status for `fileset_name` /pdmvserv_SUS-RunIISpring16FSPremix-00055_00034_v0__160929_122033_2363/Production.
Somehow, 22 jobs don't have a valid jobMask, so instead of 
`{'LastRun': 1, 'FirstRun': 1, 'inclusivemask': True, 'runAndLumis': {1: [[36767, 36798]]}, 'LastEvent': 16175250, 'FirstEvent': 16161623, 'LastLumi': 36798, 'FirstLumi': 36767}`
they have
`{'LastRun': None, 'FirstRun': None, 'inclusivemask': True, 'runAndLumis': {}, 'LastEvent': None, 'FirstEvent': None, 'LastLumi': None, 'FirstLumi': None}`
which matches exactly to the number of docs in the ACDC server with 31k lumi sections!!!

Then following the ACDC internals, these were all the jobs passed upstream:
http://amaltaro.web.cern.ch/amaltaro/forAlan/jobs_mask
which then falls into this code:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ACDC/DataCollectionService.py#L104
and finally this one:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ACDC/CouchFileset.py#L97
then since `mask` has only null values, this `mask.getRunAndLumis()` returns `{}`, thus `runs` key is untouched.

Now two things that I don't understand yet are:
1) why those jobs have no mask valid information?
2) `job['input_files']` is empty for all those jobs. So where does it get the `files` from??

We probably care only about the invalid mask information though... (now that the workflow is rejected, this info is probably vanishing from the agent very soon)

**Comment by amaltaro** [comment]
and this is the call we use to load the mask given a jobid:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/Mask.py#L116

Since I could not find any problems in the code and all the info is gone from wmbs, I'm closing this ticket.

Paola, Jean-Roch, please reopen it if the same issue happens again.

**Comment by prozober** [comment]
Thanks Alan.
