### ISSUE TITLE
Deprecate request.schema in favor of reqmgr2 couch workload doc

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7342]
This schema section was originally not present in reqmgr2 and, it was added  back because Unified was retrieving some information that are present only there(?) I suggest we get rid of of that data e.g.:
https://cmsweb.cern.ch/reqmgr2/config?name=pdmvserv_HIG-RunIISummer16DR80-00016_00018_v0__161029_201254_6106

and use only the workload cache doc:
https://cmsweb.cern.ch/reqmgr2/data/request?name=pdmvserv_HIG-RunIISummer16DR80-00016_00018_v0__161029_201254_6106

which AFAIK gives all the needed information right now.

@vlimant can you point to where Unified uses this info? Or even better if you know exactly what it has to be retrieved from these attr.

**Comment by vlimant** [comment]
Hi, to my knowledge https://cmsweb.cern.ch/reqmgr2/config?name= is not used at all in Unified and access to that flat file is not required from Unified. 

On the other hand, this might still be in use somewhere in some pdmv codes.

N.B. the two url that you gave do not have the same information. i.e. the first link has way more information, which one should access using the /spec (#7357) extension

**Comment by ticoann** [comment]
I think it was used by McM script. Yes, 2 link doesn't have the same information since the first one is basically spec file which include auto generated information and second one is basically user provided info which is needed for the db creation (plus request status, etc)

The first one is for the human read though not for program to parse and extract information.

**Comment by amaltaro** [comment]
Fixed by https://github.com/dmwm/WMCore/pull/8383
