### ISSUE TITLE
RootEmbeddedFileSequence no input files specified for secondary input source.

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7384]
Can one please take a look at 

https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_BTV-RunIISummer16DR80Premix-00010_00006_v0__161106_201423_2069

 assigned with 

  "TrustPUSitelists": true 

but the secondary filelist seems to be missing. 

----- Begin Fatal Exception 13-Nov-2016 01:38:51 CST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=DataMixingModule label='mixData'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------

**Comment by amaltaro** [comment]
I took a look at one job and it failed at T1_ES_PIC. This site is not in the site white list and that's why this job failed for lack of secondary input source.

The `TrustPUSitelists` flag assumes your pileup blocks are located at all the sites set **in** the `SiteWhitelist`. You see these failures because those jobs were overflowed.

**Comment by amaltaro** [comment]
I created another issue to follow up on this feature change https://github.com/dmwm/WMCore/issues/7387
I'm closing this one.
