### ISSUE TITLE
Bypass any sites when TrustPUSitelists True

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7387]
At the moment, this flags adds all the PNNs (mapped from the SiteWhitelist value) to the pileup json file.

We could change this feature such that if jobs are overflowed to other sites, the runtime scripts would see those blocks as present at that sites as well. 

We likely want to add a job baggage and treat it at SetupCMSSW script.

**Comment by vlimant** [comment]
@amaltaro please do add this functionality, we clearly want to have the handle on being able to send work outside of the site whitelist dynamically. Consider this quite a show-stopper for the on-going premix campaign.

**Comment by vlimant** [comment]
FYI @mcremone @prozober @areinsvo

**Comment by hufnagel** [comment]
@amaltaro , can you explain why the runtime cares about location ? Runtime comes after matching the job to a site, how is location coming into play after that ?

**Comment by amaltaro** [comment]
The agent builds a json file with location:block key values during work acquisition (WorkQueueManager). 
Then during runtime we collect all the blocks available at the PNN attached to that worker node. See
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L401

**Comment by hufnagel** [comment]
Hm, so this is an artifact of the old style local-only way to read pileup. Each job knows where it runs and can then select from the local blocks which pileup files it can read ?

Messing with the mapping is the wrong thing to do IMO. The mapping is correct. If we overflow to a site that has no local pileup data, we still want to run there (otherwise we wouldn't have overflown).

Why don't we just change the code so that if there is no match in the mapping, ie. no local pileup data, we allow to read any and all pileup data. It'll just use AAA then ?

Wouldn't that work  and be simpler ?

**Comment by amaltaro** [comment]
> Hm, so this is an artifact of the old style local-only way to read pileup. Each job knows where it runs and can then select from the local blocks which pileup files it can read ?

Yes and no. It's local-only if the flag `TrustPUSitelists` is False. IF it's true, then we assume (read fake) the PU location at all the PNNs that match the site white list.

About overflow, it's certainly a newer concept. Such that the PU location design did not consider overflow.

> Why don't we just change the code so that if there is no match in the mapping, ie. no local pileup data, we allow to read any and all pileup data. It'll just use AAA then ?

I don't think transparently reading PU remote is something we want in production.
 I know how to solve this issue without being too intrusive, I hope.

**Comment by hufnagel** [comment]
Ok, that's your problem then, you fake the location. Stop doing that. The location is what it is. If you end up at a site that has no local pileup, you just assume all the pileup is local. Trust that a job can only end up on a site without local pileup if we specifically sent it there, ie. trust whatever overflow mechanism allowed the job to run there. Do not mess with locations. That was the wrong approach with assigning workflows to sites without the first input and it's the wrong approach to deal with the second input.

**Comment by hufnagel** [comment]
This doesn't mean you transparently read pileup from all over the place. Normal job assignment will only sent jobs to places that have at least part of the pileup and in these cases you use the correct location map for pileup data to select local pileup data.

But if we decide outside the agent to overflow such jobs somewhere else, this is completely different. In that case we explicitly want to use AAA.

All I am saying is you do not need to have such intrusive checks at multiple levels. If a job runs and doesn't have local pileup, we simply trust that this is ok since this could only have come about by someone interfering in the job routing and we assume this is the desired behavior. You don't fail the job in these cases, but allow it to read all pileup data from everywhere (since it doesn't make a different what you read at this point, everything is remote).

**Comment by hufnagel** [comment]
Location map is real location map, no faking.

Job runs at a site that is in the location map => job uses only the local pileup data 

Job runs at a site that is not in the location map => job can use all pileup data

Simple.

**Comment by hufnagel** [comment]
By default a job would only be submitted to sites that have both GEN-SIM and at least some of the pileup data locally, right ?

**Comment by hufnagel** [comment]
Hm, does this work for both TrustPUSitelists False and True ?

If it's True we already say "assume that we have local pileup at all sites we want to run". By faking location you actually allow fully transparent read of pileup from everywhere. By my suggestion your would read local pileup if there is local pileup and only read remote pileup if there is nothing local. Not faking location would mean you have to ignore pileup location for job submission though.

If it's False, you would have to use primary and secondary input location for job submission. Then the only case you could end up at a site without local pileup is if you explicitly change the jobs site list while it's in HTCondor. In that case you also want to allow remote pileup reads.

The agent code is not an enforcer of policy here. The agent code just has to make sure it works correctly and allows the job to run under all circumstances.

**Comment by hufnagel** [comment]
> I don't think transparently reading PU remote is something we want in production.

Btw, isn't that exactly what we want and actually already have ???

**Comment by hufnagel** [comment]
And @vlimant was complaining that it doesn't work correctly :-)

**Comment by amaltaro** [comment]
> The agent code just has to make sure it works correctly and allows the job to run under all circumstances.

It's easier said than done.

Summarizing what you said:
 * if there is local data - no matter if it's a single block or the whole dataset - use only local data (trust flag would have no impact, so PU files would get recycled more often)
 * if there is NO local data - use all the files from all the blocks as secondary list of files.
 * TrustPU* flag is only needed to get work from GQ to LQ.
?

If not, please summarize how you think it should work.

**Comment by hufnagel** [comment]
This needs feedback from @vlimant . I don't know how Ops wants to run these workflows. But since they talk about overflow and being able to dynamically change where these jobs are supposed to run, I think the second point in your summary is a must. I much prefer to do this in the runtime code than to keep faking locations. End effect is the same and you just paint yourself into a corner faking information, much better to handle this in algorithm.

First point makes sense if we distribute the pileup sample in a way that we only keep large fractions of the dataset at a handful of well connected sites. You want to prefer local pileup input at these sites (they usually also have a lot of cpu). But you need enough local pileup data to not bias yourself for the samples you produce at these sites. Needs confirmation from Ops, but AFAIK it's what we are doing.

About point 3, the TrustPU* flag, there is a difference for the short and long term here, isn't there ? Changed in how this flag behaves affect cmsweb, correct ? Since this is urgent, can we get away with giving Ops what they want just changing runtime code for now ? In the long run I think this should simply be a flag that tells the system to ignore pileup location for job submission without actually faking the location of pileup in the workflow. Same change we did for forcing submission to ignore primary input location, we also don't fake location there anymore, we just override in the submission itself,

**Comment by vlimant** [comment]
Hi, that's a long thread with too much to read. I think there are two use cases at stake, and only one actually does matter for what concerns dev.

 a) running premix like we do now (2 main aaa source for all workflows ; one US, one EU) with the primary input at some sites : if we want to have the jobs overflown to neighbors (and we do) then the secondary comes out wrong and fails with error code 73. The solution is to indicates that defacto, with trustpusitelist=True, the secondary is everywhere. Let's fix that.

 b) running premix with local input for small workflows. This can be indentified prior to assignment and we would assign it with truspusitelist=False to have the local files read in. We will have the same pu location issue at that point if we try to overflow it away and want to read the premix files from the initial sites.

 Actually we ran into an issue earlier this year (I cannot find the GH issue) when replicating the MB to another site and overflowing jobs to it ; it would be great to have this fixed too while we are at looking into the secondary location business.

**Comment by ticoann** [comment]
I was told that when cmssw framework if patching the input file (block) (including PU), it always tries local first and then look for the remote source. 
If that is the case, do we want to set truspusitelist=False, ever? Sorry if I misunderstood and asking completely stupid question.

**Comment by hufnagel** [comment]
It does that per file, ie. if you pass it a list of 100 files and the first is not local and all other 99 are, it still tries to read the first file locally and then reads it remotely. What we want for the pileup is to configure the job to only select events from the 99 local ones.

As for the trustpusitelist flag, it's still needed, but it would not affect jobs runtime behavior, only submission. With trustpusitelist = true you would ignore pileup location for submission, with trustpusitelist = false you would take pileup location into account when submitting the jobs.

Either way unified-overflow can assign both types of jobs to other sites and this should still work. At runtime both will work, with the pileup either locally present (and then used) or not. The flag only affects the initial site assignment.

Does that make sense ?

**Comment by hufnagel** [comment]
And as I said before, we can make the runtime change now and patch the agents to solve the immediate problem. The changes to trustpusitelist  can be made later. This modus operandi is a bit less efficient than changing both, but faster to implement.

Btw, even if we change the runtime code and patch the agents, this change will only affect newly created workflows. Any workflow already in the system has it's sandbox with runtime code already created and fixed.

**Comment by bbockelm** [comment]
In @amaltaro 's comment above, he wrote the following options:
   * if there is local data - no matter if it's a single block or the whole dataset - use only local data.
   * if there is NO local data - use all the files from all the blocks as secondary list of files.

I think the first item is incorrect: for now, we must consider _all_ possible premixed input.  Only looking at the data from the local site increases the possibility of reusing backgrounds (thought experiment: what happens if Wisconsin - with 12,000 cores - had a single block of premixed background?).  My understanding is we got sign-off on a certain threshold of reuse, lower than this.

At some point in the future, it may be possible to determine the ratio between (# site cores) / (# PU blocks at site) is small enough to not affect statistics.

**Comment by amaltaro** [comment]
That's not up to WMCore to decide what to do in such case. We make a stable feature in WMCore and then Production/Unified uses it. Meaning, Ops has to make sure they have enough PU blocks at the sites they are running jobs OR set the TrustPU flag to True.

I was discussing this issue with Seangchan a few minutes ago and, if people want to have all the PU files fed into the PSet (blindly or not), we could simply get rid of the worker node vs pileup json location and simply use all the PU dataset in the PSet, if the framework fails to find it, then it tries reading it via xrootd. It would be much simpler, though the risk of bringing the whole infra down is going to be higher.
