### ISSUE TITLE
TaskChain with TrustPUSitelists=true and Premix in step

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7428]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_BTV-RunIISummer15GS-00069__v1_T_161125_213521_3712
was assigned with TrustPUSitelists=True but this is not sufficient since 

pdmvserv_task_BTV-RunIISummer15GS-00069__v1_T_161125_213521_3712.tasks.BTV-RunIISummer15GS-00069_0.tree.children.BTV-RunIISummer15GS-00069_0MergeRAWSIMoutput.tree.children.BTV-RunIISummer16DR80Premix-00071_0.tree.children.LogCollectForBTV-RunIISummer16DR80Premix-00071_0.constraints.sites.trustPUlists = False

how do I get the subsequent step to do trustPUlists=True ?

**Comment by vlimant** [comment]
pdmvserv_task_BTV-RunIISummer15GS-00069__v1_T_161125_213521_3712 
pdmvserv_task_BTV-RunIISummer15GS-00070__v1_T_161125_213537_5698
pdmvserv_task_BTV-RunIISummer15GS-00071__v1_T_161125_213556_5980
pdmvserv_task_BTV-RunIISummer15GS-00072__v1_T_161125_213611_6014
pdmvserv_task_BTV-RunIISummer15GS-00073__v1_T_161125_213646_6031
pdmvserv_task_BTV-RunIISummer15GS-00074__v1_T_161125_213652_5819
pdmvserv_task_SUS-RunIISummer15GS-00196__v1_T_161125_233700_7116

are the only such examples so far

**Comment by amaltaro** [comment]
For the record, this hack
https://github.com/amaltaro/WMCore/commit/2fb0738893f84ef91086b43505447fe3a9ae511a

was applied to the following sandbox:
pdmvserv_task_BTV-RunIISummer15GS-00069__v1_T_161125_213521_3712

in all the agents that have acquired this workflow.
Note, it was NOT applied to the WMAgent code, but to that specific sandbox only.

A proper fix will be done on Monday, I assumed the `TrustPUSitelists` use case should be the same as `TrustSitelists` (i.e. applying these settings to the top level task only). Instead, the PU flag needs to be propagated to all tasks otherwise TaskChains cannot really use it if starting from scratch.

**Comment by jenimal** [comment]
still seeing errors as of 5 hrs ago.  I assume that the "proper fix on Monday" hasn't been implemented yet?
