### ISSUE TITLE
Should there be no retry on Error Code 71304

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7438]
It was suggested to not retry these kinds of jobs. 
I'd like to understand better how jobs can end it this way without triggering the watchdog.
The only way I can see is multiple resubmit by condor because the job went way out of its requested time and over the pilot lifetime ; which is a good reason for no resubmit, so that it can be treated as a bad splitting

**Comment by amaltaro** [comment]
If SoftTimeout is > than the JobStatusLite default time for jobs in Running state (169200 secs), then the component could be killing a job that has passed that amount of time in the same condor status (running).

This is the error message:
```
                      71304: "The job was killed by the WMAgent for using too much wallclock time (WMAgent) Job status was Running.",
```

otherwise it might be automatic scheduling by htcondor and how the current status time is accounted.
