### ISSUE TITLE
WQE stuck in acquired

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7446]
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/element/d2769483b92e8d394d07f54a4e979a51

2016-11-27 04:56:10,436:139644204320512:ERROR:WorkQueue:vlimant_HARVEST-Run2016H-v1-ZeroBiasBunchTrains1-09Nov2016_8023_161127_004049_7396, [u'/ZeroBiasBunchTrains1/Run2016H-09Nov2016-v1/DQMIO']: 
failed to retrieve data from DBS/PhEDEx in LQ: 
u'/ZeroBiasBunchTrains1/Run2016H-09Nov2016-v1/DQMIO#975ff104-ad82-11e6-88d9-02163e01820e'

is what I can see in the agent. The block is not in phedex anymore indeed. It has disappeared after assignment and the agent acquiring it it seems.

How should this be handled ?

**Comment by amaltaro** [comment]
This is an interesting case. DQMHarvesting uses Dataset start policy, which means it acquires a dataset per wqe instead of blocks. The problem is, we ask DBS for all the blocks inside that dataset, then the location is based on PhEDEx API, which of course doesn't have that block anymore in TMDB.

We have two issues to fix:
a) when we ask phedex about a single block that has no complete block replicas (it shouldn't crash):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L665
b) we probably have to skip blocks that have 0 files, from this api:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L420

Though I'm concerned about sequential workflows that would be reading a fresh dataset with a possible "temporary" empty block in phedex. This is a legit case that we - of course - cannot skip the block.

@ticoann would you have comments on b) ?

**Comment by ticoann** [comment]
If a block is not in TMDB, is it sill valid status in DBS?
As for b) how can we distinguish legit case from deleted files in TMDB case?

**Comment by amaltaro** [comment]
Yes, Nicolo confirmed it yesterday and this is what happens when all files from a block are
invalidated.
a) files AND block are deleted from TMDB
b) files are set as invalid in DBS (is_file_valid=0). Block is untouched since
there is no block status concept in DBS.

What we could check is something like:
if block has more than > 0 files and all of them are invalid, then skip this block from processing
Though it adds another dbs call and not a very cheap one, AFAIK.

@yuyiguo can you enlighten us on what would be the best api/procedure to check whether a given block has **only** invalid files in dbs?

A second option would be to have a dbs api that returns blocks in a given dataset, but only blocks that contain at least 1 valid file. How does it sound?

**Comment by amaltaro** [comment]
@vlimant meanwhile, feel free to abort it and proceed with block black or white list, that should work (classical words)
