### ISSUE TITLE
missing function definition.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7488]
while moving the code to under WMCore/Services/TagCollector

Pylint complains about 

E0602, line 41 in xml_parser: Undefined variable 'adjust_value

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ReqMgr/Utils/utils.py#L68

@vkuznet, Valentin, is there a missing code in original code above?

**Comment by vkuznet** [comment]
Seangchan,
this code was originally copied from DAS codebase where I developed xml parser
for CMS XML docs. The adjust_value function is defined here:
https://github.com/dmwm/DAS/blob/master/src/python/DAS/utils/utils.py#L587
with float_number_pattern defined here:
https://github.com/dmwm/DAS/blob/master/src/python/DAS/utils/regex.py#L56
and int_number_pattern defined here:
https://github.com/dmwm/DAS/blob/master/src/python/DAS/utils/regex.py#L58

So, I'll suggest to take these pieces and embed them into new TagCollector.
I'll avoid adding dependencies on DAS since it will create a circular
dependency between WMCore and DAS.

Can you do it or do you want me to do it for TagCollector code?
For later I think you first need to put TagCollector code into WMCore master
head and then I can fix it.

Best,
Valentin.

**Comment by ticoann** [comment]
Thanks Valentin, I will update the code.

**Comment by ticoann** [comment]
code is updated in #7484, closing this issue
