### ISSUE TITLE
higher number of creation failures

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7536]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2016B-v2-ZeroBias6-17Jan2017_8020_170117_170800_2500

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2016B-v2-ZeroBias6-25Nov2016_8020_161125_152646_3953

have basically identical settings and yet, the 17Jan has had way more creationg failures. which is counter intuitive, has the code that generate that failure been changed much ?

**Comment by vlimant** [comment]
also, is max_events_per_lumi calculated at all ? why not adjusting it automatically to 48h/TimePerEvent internally ? (maybe because then we cannot fool request manager to still create the jobs ... questions and answers)

**Comment by vlimant** [comment]
eventually : how does one set that max_events_per_lumi at assignment time ?
I think the default should be a godzillion, 20k does not make any default sense.

**Comment by vlimant** [comment]
@amaltaro @ticoann  any indications ?
FYI @areinsvo

**Comment by ticoann** [comment]
Sorry i missed this. I will investigate.

**Comment by ticoann** [comment]
Code hasn't been changed long time (at least which code affect this)
Here is condition  which make creation fail

As you said both split setting seems to be identical, I am not sure how there will be number of failure difference. (I can't see the earlier workflows failure number since that workflow is archived already)

As far as logic goes, following is the logic for not creating the job. 
I am not sure the logic behind it and why eventLimit is set to 20K by default.

@vlimant, @amaltaro, Could you explain if you know the logic behind it.
```
#If the number of events per lumi is higher than the limit
#and it's only one lumi then ditch that lumi
if f['avgEvtsPerLumi'] > eventLimit and f['lumiCount'] == 1:

```

**Comment by vlimant** [comment]
Is max_events_per_lumi only parameter that one sets ?

How does one change that value via api ? is this just passing max_events_per_lumi in the json ?

**Comment by amaltaro** [comment]
Interesting, I thought this algo was failing any jobs that were supposed to process more events than the limit (default 20k), but it *only* fails if the file has a single lumit section (such that `avgEvtsPerLumi` is the exact number of events per lumi, instead of an average).

I was looking at the `splitting` rest api and I came up with a working example that you can use to update this `max_events_per_lumi` (and in theory any other splitting parameters), see:
https://github.com/amaltaro/scripts/blob/master/ReqMgr2/changeSplitting.py#L20

As you can see in the script, we only post the task arguments that were really changed, not everything. It seems there are algos (in my case it was "MinFileBased") that we cannot really update.

@vlimant 20k used to be a quite good number, but if you think there is a better default value to be put in place, please let us know. Ideally we should base it on TimePerEvent + some safe margin.

**Comment by vlimant** [comment]
Can the value be create from 48h and the timeperevent ?

**Comment by amaltaro** [comment]
Maybe for March deployment.

**Comment by vlimant** [comment]
in the context of data reprocessing, I think we need to solve this max_events_per_lumi issue, and have it automatically adjusted so that it never gets in our way in ACDC or recoveries

**Comment by vlimant** [comment]
ping on that one. for data reprocessing, we have to have this parameter auto-adjusted in the agent.
I'd rather not have this in unified

**Comment by vlimant** [comment]
ping ping https://its.cern.ch/jira/browse/CMSCOMPPR-1911

**Comment by vlimant** [comment]
@ticoann @amaltaro could we put the default value up to 200k so that it does not bother us until we get the value properly adapted to the max pilot lifetime (46-48h) and the time/event provided.

**Comment by ticoann** [comment]
Hi let me check whether there will be any side effect on 200k default value.  I move to a high priority and I will take the look at the problem too.

**Comment by ticoann** [comment]
It seems increasing default value will add the risk of creating long running jobs.
With EventAwareLumiBased algorithm, the minimal lumi per jobs is 1 and and increasing max_events_per_lumi  to 200k might cause some long running jobs to be created.

I can create the patch which only fails the job in creation if estimated jobs  (number of events per job * time per events) is exceeded the 48h. I don't think we can automatically adjust the job size in that case since the minimum lumi size is 1.

**Comment by vlimant** [comment]
de-facto, when faced with creation failures of this type Ops would just set max_events_per_lumi to 200k if not more. In such cases there has been no very long jobs created.
