### ISSUE TITLE
Server Error when changing splitting

### ISSUE THREAD

**Issue by areinsvo** [dmwm/WMCore#7557]
I'm trying to change the splitting for the following workflow using the request manager interface. I want to change it to EventBased splitting with events_per_job = 40. Every time I try, however, it first says "Your request has been submitted" immediately followed by "Server Error Message: server error." The splitting doesn't get changed. I've been trying since yesterday, so I don't think it is a transient issue.
@vlimant , any suggestions?

https://cmsweb.cern.ch/reqmgr2/fetch?rid=request-pdmvserv_TRK-PhaseIIFall16DR82-00001_00007_v0__170126_135209_3127

**Comment by vlimant** [comment]
if you set event_per_job and events_per_lumi the request does get through.
since events_per_lumi is going to be inactive for that request which has an input dataset, I'd say it's fine to give any value.
Yet, I am surprised that an non-mandatory parameter is made mandatory. Maybe @amaltaro or @ticoann can clarify how EventBased splitting works these days

**Comment by amaltaro** [comment]
This should have been fixed around 4 or 5 months ago. Please reopen if it happens again.
