### ISSUE TITLE
Preventing Schedd to run at their limit

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7559]
following up on #7509 discussion.
We should think hard on how to prevent the agents to push the schedd to its limit, by refusing more work when a certain limit is reached.
@bbockelm provided the classad for when the schedd stops matching. Is there an access to the limit and the number of jobs running (the agent has it anyways) ?

My idea is that agent should stop getting new work when at 80% of the schedd limit, and send an alarm to wmstats for P&R to react. 
Of course, the already acquired work would have to be handled.

@scarletnorberg FYI

**Comment by ticoann** [comment]
What will be the schedd limit and what is the contribution to that? (memory on local machine, etc)
I am just wondering that the limit changes by different local machine with different resources.
I was told that there is virtually no limit (on high limit) for pending jobs in schedd. But I might be mistaken.

**Comment by vlimant** [comment]
I meant the "running limit", which is 25k something.
As far as pending is concerned, the current situation is fine, modulo the fact that it would be great to have the limit in number of cores instead of number of jobs.

**Comment by bbockelm** [comment]
The schedd's limit is not static but dynamic: it can also go up and down based on the responsiveness of the schedd.

The administrator might set an upper bound (say, 25k running jobs) but this can get lowered if the schedd is struggling to keep up.  Examples include when we hit a poorly-split workflow or a failing workflow; both cases cause many jobs to quickly churn through the system and significant IO load.

Unfortunately, this makes it difficult to estimate what 80% of the limit will be - we can only reliably say whether we've hit it.  We *can* provide the original upper limit from the admin, but I'd prefer to avoid this.

It's important to stop acquiring more work for the schedd in such a case - regardless of thresholds - as it is a source of priority inversion.  Schedds at their limit will not start additional jobs, even if they are the highest-priority work inside the global pool.  Additional acquired WQE's by the limited agent will, by definition, be high priority and make the priority inversion worse.

**Comment by vlimant** [comment]
is there a way to get a "pre-warning" classad from the schedd, ahead of CurbMatchmaking ?

**Comment by bbockelm** [comment]
Like I said - not in general.  You can possibly guess at this by looking at the maximum job running limit.

**Comment by ticoann** [comment]
If it "running limit", I am not sure what agent can do not to pressure schedd. At least I think it will be harder to control that than in schedd. Agent can control how many jobs be submitted to schedd. which is currently proportional to the slots available site.
Whether those jobs will be running or stay pending are beyond its control. 
Are you suggesting that we should be submitting the jobs small enough so not many pending jobs in the schedd?  I don't think control should be there. 

What Brian said sounds like it not problem seem to be more of how the jobs running (fast failed/IO load) rather than how many jobs are running.

**Comment by vlimant** [comment]
With #7509 implemented (thanks) the agents are going to share more evenly the WQE on the top of the basket (so no agent will acquire them all in one sitting, good).
Given that jobcreator and jobsubmitter are fast in ramping up, we need a mechanism to tell the agent to not acquire any more WQE when the schedd is maxed out, so that the agent/schedd go first through all already acquired, leaving any extra work to other agents that would not be maxed.

This will not prevent the schedd to be at max (and it's bad that we cannot) but will prevent a maxed schedd to get even more work, potentially at high priority.

**Comment by amaltaro** [comment]
I suggest we read the `IsCritical` schedd metric and use it to decide whether we pull work from GQ to LQ. Just keep in mind this metric is not optimal, it's evaluated from a bunch of other metrics and even if the schedd is in critical state, it could be that the schedd is normally handling the load.

Second thing to keep in mind is, it can potentially delay work acquisition for the ultra important and highest priority workflow if ALL schedds decide to go into critical state at the same time.

**Comment by vlimant** [comment]
agreed that it will be bad if all schedd are bad, but that we can monitor and react.

I think it should be CurbMatchmaking, or both. IsCritical by itself is not good, because the schedd could be running "non critical" at max.

**Comment by bbockelm** [comment]
I would suggest we start with `CurbMatchmaking`, as that guarantees the schedd is no longer accepting new matches.  `IsCritical` is meant for human monitoring and the schedd itself takes no action.

Once the infrastructure is there for `CurbMatchmaking` I suspect adding / switching to `IsCritical` is very simple.

As @ticoann notes, this is not any sort of a hard limit but very rough guidance - basically, we want the WMAgent to avoid making the situation worse.

**Comment by vlimant** [comment]
@ticoann @amaltaro any time line for this ?
can we have a >N hours after hitting CurbMatchmaking "no work acquired" cooloff period so that it does not start right back ? or is there already such cooloff period on the schedd side @bbockelm ?
can we record the total number of running jobs when CurbMatchmaking is met, and use 80% of that value to prevent work for getting in ?

**Comment by vlimant** [comment]
@ticoann @amaltaro coming back to this with schedd entering dangerous grounds of throttling the amount of work running. We need to think about the mechanism to prevent new work to get in agent already maxed out, and leave it some time to chew on already acquired work.

I would push this a bit higher up in the priority list @ericvaandering

**Comment by vlimant** [comment]
FYI @scarletnorberg @mcremone @thongonary

**Comment by amaltaro** [comment]
We can certainly improve the thresholds and how work gets pulled/matched against available resources.
However, a short solution for this would be decreasing the site thresholds. We used to have pending percent set to 50% long ago (now it's 100%), overflow came in and you asked it to be bump to have the possibility to play with jobs in condor. This is just a bad side effect of that.

Again, it doesn't mean it can be improved, but ...

**Comment by vlimant** [comment]
Can you please explain how reducing the thresholds will improve the situation with a schedd throttling on running jobs ? how will we keep the pending job pressure high enough for the glidein mechanism to serve production well ?

**Comment by aperezca** [comment]
Hi guys, 

I agree with JR's comment regarding the need of keeping high numbers of pending jobs for the glideinWMS FE to trigger the submission of new glideins, to always maximize our use of the resources. However, increasing the load per schedd risks:

-the glideinWMS FE ignoring the schedd completely if it is too close to the limits of running/queued jobs

-the HTCondor negotiator being slowed down in the negotiation cycle and ultimately disconnecting from overloaded schedds, missing the matchmaking phase (=idle slots and jobs not running)

Because of that, instead of trying to push more stuff through the same number of schedds, how about scaling horizontally adding more agents/schedds? 

Cheers

**Comment by amaltaro** [comment]
Reading this thread from the beginning, your initial report was on: "can we make the agent stop acquiring work once it hits 80% of its running limit?", which - as discussed - is something not easy to figure out and it can vary.

Second request was "can we stop acquiring even more work when the schedd is maxed out". That's what my reply was for. LQ pulls wokr down based on the pending slots thresholds, the moment that got increased, it also increased the backlog of LQ elements that are waiting to get jobs created for (instead of allowing it to go to lighter scheddds).

If the agent has less work queued, it will of course have a faster response to jobs pending and high priority work.

Antonio, if 6 agents can fill up the global pool resources (including the analysis share), why would we have 12 agents running? I think the only reason I'm against having more (than needed) agents in production is the maintenance cost. It's not every week, but from time to time we have to make some surgery on the agents and that takes a significant effort. In addition to that, I'd rather keep a small set of well behaving nodes than increasing the changes of having one node misbehaving (one could say the damage is bigger with less agents though :))
* maintenance more expensive

**Comment by vlimant** [comment]
Ok to less agents in production at once, and hopefully large single-core workflows will disappear in favor of multi-core ones.

Can we introduce a global re-scaling factor to lower the thresholds globally for the "LQ pulling" with respect to the "job submitting" part ? so that we mitigate the situation about high thresholds.

What can be done to operate any limitation on the agent ? there is information we can extract from the schedd to get some mitigation going, we should enable this and get it in the next agent release.
How do we go about this ? 

if we know the schedd component has a hard understood limit and hard times defined, let's have the agent take this into account ; is there any reason not to ? (except for dev manpower related considerations)

**Comment by aperezca** [comment]
Alan, my point is that perhaps the easiest solution to solve the puzzle of keeping the pool busy but preventing the schedds from running at max is simply to distribute the load. Yes, you could fill the pool with 6 machines (6 x 25k = 150k, so still not the full pool, but ok, that depends on the single/multicore job ratios, as JR mentions). But you'd need them running with little or no safety margin in number of jobs. So what I'd suggest is, instead of trying balancing tricks to remain "living on the edge", simply scale up with more machines, so that you can really fill 200k cores with the schedds at 50% load.
By the way, is the surgery on the nodes you mention on the nodes triggered by the load (node running out of memory, job router or schedd processes timing out/dying, etc?
In any case, of course you know your system better than I do, so merely suggesting.

**Comment by bbockelm** [comment]
Hi,

The conversation seems to be getting away from the point of the ticket.

There's a simple 10-ish lines of Python that can be to determine whether the schedd is already past the limit, right?  Can we simply add a check for that and avoid acquiring new work on the local agent until we are below threshold?

Brian

**Comment by ticoann** [comment]
I think controlling the pending threshold (if we can find optimal case between pressuring the condor and not pulling dow too much work so work could get stuck which can be distributed to other agent) would be enough solution as Alan said.
However, as Brian said we can focus on that aspect which seems to be simple to add. I am not sure about the side effect it might causes. (Especially if the measurement for limit is not accurate) We can implement this feature and give the switch to turn on  and off (maybe through the config),

**Comment by bbockelm** [comment]
There is no way to control the pending threshold because the limit is a dynamic number -- an appropriate pending threshold today may not be an appropriate one tomorrow.

We can *not* accurately say "we are at 95% of the limit" (as it is essentially the same problem as above).

However, we *can* say quite reliably "we are past the limit".

**Comment by ticoann** [comment]
Pending threshold doesn't have to be static. I was just wondering what would be the relation between optimal pending threshold regards to other factors running limit, current running job, etc. 
If you know formula on this even roughly, that could help to improve setting the pending threshold. (Still this would be hard problem for us, since there is no way to find if job will go to certain site, - due to multiple site white list and overflows) 

> However, we can say quite reliably "we are past the limit".

Yes you are right, I was confused that we are checking before we reach the limit.

**Comment by ticoann** [comment]
@bbockelm, Hi Brian, how I can get the information using python binding.
Farrukh showed me how to get the information from condor command

```
condor_status -schedd -pool cmssrv211 vocms0116.cern.ch -af:h CurbMatchmaking
```

But I try to construct the python binding code but failed.  (http://research.cs.wisc.edu/htcondor/manual/v8.7/7_7Python_Bindings.html)

Thank you for your help in advance.

**Comment by bbockelm** [comment]
Hi,

The most efficient way of doing this via python is:
```
import htcondor
coll = htcondor.Collector()
schedd_ad = coll.locate(htcondor.AdTypes.Schedd)
print schedd_ad["CurbMatchmaking"]
```

That will query the local default schedd.  You'd probably hew to the manual's documentation a bit more closely if you want to query a remote schedd.

Brian

**Comment by ticoann** [comment]
Thanks Brian for the example. Actually, I tried with similar comments before.

```
import htcondor
cl = htcondor.Collector()
scheddAd = cl.locate(htcondor.DaemonTypes.Schedd)
print scheddAd['CurbMatchmaking']                      
```
But result is gives was not a boolean.

```
> ( ShadowsRunning > 9.700000000000000E-01 * 6000 ) || ( RecentDaemonCoreDutyCycle > 9.800000000000000E-01 )
```

When I switched htcondor.DaemonTypes.Schedd -> htcondor.AdTypes.Schedd as your example above it gives me the following error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    Collector.locate(Collector, AdTypes)
did not match C++ signature:
    locate(Collector {lvalue}, daemon_t)
    locate(Collector {lvalue}, daemon_t, std::string)
```

**Comment by ticoann** [comment]
Hmm, it seems I can get following values as well.

```
>>> print schedd_ad['ShadowsRunning']
1411
>>> print schedd_ad['RecentDaemonCoreDutyCycle']
0.224188651479
```
So can I just plug in this values to get scheddAd['CurbMatchmaking']?
```
( ShadowsRunning > 9.700000000000000E-01 * 22000 ) || ( RecentDaemonCoreDutyCycle > 9.800000000000000E-01 )
```

**Comment by amaltaro** [comment]
Seangchan, this `CurbMatchmaking` is a ExprTree object, you can evaluate it with:
```
>>> type(scheddAd['CurbMatchmaking']) 
<class 'classad.ExprTree'>
>>> scheddAd['CurbMatchmaking'].eval()      
False
```

**Comment by ticoann** [comment]
Thanks Alan, is False means shedd is not reach the limit yet, correct?

**Comment by amaltaro** [comment]
That's correct! 

@bbockelm and would you know why a schedd running more than 0.97 * 22000 condor shadow processes is considered overloaded? Is it a hardware limitation?
If that's the case, maybe we should simply drop the MAX_RUNNING_JOBS such that we don't go beyond 21k jobs in one single schedd.

**Comment by ticoann** [comment]
How about the second condition? Can schedd deamon be slow down due to the various reasons other than the number of running jobs?

```
( RecentDaemonCoreDutyCycle > 9.800000000000000E-01 )
```

**Comment by bbockelm** [comment]
@amaltaro - In the config file, I think the expression is something like `ShadowsRunning > 0.97 * $(MAX_RUNNING_JOBS)`.  The `MAX_RUNNING_JOBS` is substituted at reconfig time.

The interaction of `CurbMatchmaking` and the `MAX_JOBS_RUNNING` is somewhat asynchronous.  Hence, you want to stop accepting new matches _before_ you hit the hard limit.

@ticoann - the second condition is a catch-all for host slow downs (particularly if it is due to other activity on the host unrelated to HTCondor).

**Comment by vlimant** [comment]
was there a "grace period" added to this implementation ?
like, do not get more work N hours after hitting the limit ?
can we retrieve ShadowsRunning and MAX_RUNNING_JOBS and do a pre-curbing in the agent ? like 

(ShadowsRunning > 0.80 * MAX_RUNNING_JOBS) => no more work for 5 hours + alarm in wmstats

**Comment by vlimant** [comment]
@ticoann @amaltaro is there a sign in wmstats that the limit has been reached ?
given that jobs will run and go away, there must be a timeout implemented after curbing was hit.
please point me to the GH issue to get this implemented, as well as maybe using 80% of MAX_RUNNING_JOBS. or re-open this GH.

**Comment by amaltaro** [comment]
Yes, it's reported to the logdb database (it can be seen in the "error logs" tab in wmstats).

> given that jobs will run and go away

The agent usually has a reasonable backlog, so there is a natural timeout for this mechanism. Jobs go away but others take their place.

Please open a new GH issue with the requirements and we can follow from there.
