### ISSUE TITLE
Files missing in DBS

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7610]
I don't know of any mechanism that leads to file missing in DBS from Transfer Team (@sidnarayanan).

http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=B2G-RunIISummer16DR80Premix-01493
http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=B2G-RunIISummer16DR80Premix-01423

they both have one file missing from DBS (present in phedex)

 /store/mc/RunIISummer16MiniAODv2/LQLQToTopMuTopTau_M-300_TuneCUETP8M1_13TeV_pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/110000/12D10401-CDED-E611-A618-0CC47A0AD792.root 
 /store/mc/RunIISummer16MiniAODv2/BprimeTToBZ_M-1700_Width-10p_LH_TuneCUETP8M2T4_13TeV-madgraph-pythia8/MINIAODSIM/PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/110000/84B43CA1-5EED-E611-865A-02163E012E0C.root 

we have to chase those files down and fix what is causing the absence of injection in dbs. maybe related to the DBS instability of the last few days.
FYI detective work on agent @scarletnorberg

**Comment by vlimant** [comment]
http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=B2G-RunIISummer16DR80Premix-01445

are we supposed to have that many file mismatch from the agents ?

**Comment by amaltaro** [comment]
Investigating the first workflow, the ACDC was running on vocms0126 and this is when it got completed:
completed: 2017/2/9 (Thu) 01:15:31 UTC

but DBS3Upload component only injected the block at this time:
2017-02-10 19:44:44,431:140604740036352:INFO:DBSUploadPoller:About to insert block /LQLQToTopMuTopTau_M-300_TuneCUETP8M1_13TeV_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM#6cd4a500-ee2e-11e6-8f76-02163e0184a6

Which means, my assumption that all blocks/files are injected as soon as the agent sees a request is completed, is wrong. The component was running with no issues and the block was inserted into DBS in the first attempt.

The first 2 workflows have all the data consistent in DBS and PhEDEx by now.

Looking at the 3rd case (reported today), that is really weird... there are several ACDCs, but the block missing belongs to the original request:
pdmvserv_task_B2G-RunIISummer16DR80Premix-01445__v1_T_170117_154428_4839

that run - among others - in agent vocms0310. This workflow got into completed status on Feb 7, even though the block was "created" on Feb 12:
```
	ID DATASET_ID BLOCKNAME 																														   LOCATION CREATE_TIME STATUS			DELETED
---------- ---------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------- ----------- -------------------- ----------
     79482	10514 /TprimeBToTZ_M-1400_Width-20p_LH_TuneCUETP8M2T4_13TeV-madgraph-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM#f56d883a-f0e2-11e6-b555-001e67abefa8								  6  1486876825 Open			      0
```

This request set `  "BlockCloseMaxWaitTime": 172800, `, which means it will remain open for 48h since the creation time. I updated it directly in the database to somewhere in Feb 10, such that it gets closed in PhEDEx and injected into DBS. Should happen soon.

**Comment by amaltaro** [comment]
Since we have 3 issues on the same subject, I'm closing this one and we can follow it up in any of those. In this case, I suggest #7439

**Comment by vlimant** [comment]
fine with closing this issue. as long as we get this under control and something we can operate
