### ISSUE TITLE
Locking data from request manager in the view of dynamo

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7651]
Opening this GH issue for starting the thread that could lead to a more stable system.
Dynamo (@yiiyama) needs to know the data that should not be touch, to the eye of Dataops. unified is taking care of this for the moment and in the way it is implemented right now, I think this would be best as a view in reqmgr2.
All inputs of workflows in status assignment-approved, acquired, assigned, running-open, running-closed, force-complete, completed, should appear in the list.
All outputs of workfows in  acquired, assigned, running-open, running-closed, force-complete, completed  should appear in the list.
All secondary of workflows in status assignment-approved, acquired, assigned, running-open, running-closed, force-complete, completed less than 2 months ago should appear in the list.

This should cover most use cases.

**Comment by ticoann** [comment]
Could you specify the format on this?(i.e. dictionary with workflow as key, etc for each case below) Is the result fed for other script? Or just checking for the human?

> All inputs of workflows in status assignment-approved, acquired, assigned, running-open, running-closed, force-complete, completed, should appear in the list.


> All outputs of workfows in acquired, assigned, running-open, running-closed, force-complete, completed should appear in the list.

> All secondary of workflows in status assignment-approved, acquired, assigned, running-open, running-closed, force-complete, completed less than 2 months ago should appear in the list.

What is the secondary workflow. You mean cloned, acdc workflows? do you just need the list of workflow.

**Comment by vlimant** [comment]
https://vocms049.cern.ch/unified/public/globallocks.json is the current format, maybe @yiiyama has a recommendation.

secondary is MCPileup and DataPileup in this context

**Comment by yiiyama** [comment]
Yes I do - The next release of Dynamo will include a REST service where you can register the locks. So instead of writing files (either by unified or by reqmgr2), whoever wishes to lock datasets will be talking to a URL.
Is it a set deal that reqmgr2 will be deciding what to lock? Or are we still evaluating the possibilities?

**Comment by vlimant** [comment]
@yiiyama how would the unlock work ? I don't think we had discussed this with the main users, have we ?
the plan was to remove the lock from unified's talsk list and I think the descrition in this GH is covering all cases that matters IMO, given also the check operated within dynamo.
if we have to go for a rest call for lock and unlock, that's going to be painful and not cover tests and other workflows that the above would cover

**Comment by yiiyama** [comment]
How about adding a mode in the new interface where you POST the list of locks, and that data will replace the existing list of locks that the user has? That way you don't need to lock and unlock individual datasets.

**Comment by ticoann** [comment]
Sorry for my complete ignorance. Could you explain a little bit about locking and unlocking datasets? So the current list generated by unified is not the final list for locking?

**Comment by amaltaro** [comment]
Since Dynamo will provide this API, may I suggest to add this {un}locking capability in WMCore itself. The way I see it working would be the following:
 *) Unified provides two more keys during assignment: `InputLockedSites` and `PileupLockedSites` with a list of sites where the input dataset [^} must be locked.
 **) these input data are unlocked when the request goes into `announced` status (handling `aborted` requests will be trick here, unlock or not?). Without mentioning input being used by multi-request
 ***) all ouputdatasets for `acquired` or `running-*` requests are locked
 ****) outputdatasets are unlocked when their requests are in `closed-out` or `announced`. Again, have to see whether it's not being used as input.

[^] locking blocks wouldn't be impossible, though it would take much longer to get it implemented.

Otherwise, we do as initially proposed in this issue, an API that would return those 3 different info.

**Comment by amaltaro** [comment]
The description above was just updated, if you were reading it, please read it again.

**Comment by vlimant** [comment]
@amaltaro while the locking mechanism is a "local" thing (something needs the data, it gets locked), the unlocking is more "global" since an item could have been locked from two reasons and the first one to expire should not unlock until the other one is still valid. That makes unlocking a very tricky business which only the "global view" I described initially seems to provide an answer to, unless the lock registry can account for multiple locks, and we make sure every single source of lock does get back eventually (to avoid dead locks). How do you handle the only secondary input >2month of announced ? 
IMO there needs to be a much longer and detailed discussion on the lock registry and its operation.
In the meantime, if the view described above is a no brainer, then we should have it and experience

**Comment by yiiyama** [comment]
@amaltaro @vlimant Sorry that we haven't finalized our spec proposal of the lock registry yet. We'll send an email today / tomorrow and also put it here.
Locks in the registry will have owners, so if there are two parties locking a dataset, both have to unlock before the dataset actually becomes free for deletion. That should solve the unlocking issue @vlimant is concerned with.

We should indeed take a careful approach before switching to fully relying on Dynamo lock registry. What I wanted to say was that we might want to run as is (unified producing a json file) until we sort the registry spec out, if this move to reqmgr or WMCore is a large work. But if as @vlimant says it is not too big of a deal, we have no problem using either one or the other as the lock source.

**Comment by ticoann** [comment]
Thanks for the explanation.
Here are some questions I have
So basically locking/unlocking mechanism, is(will) be used whether workflow will be assigned depending on that condition, correct?  If that is the case what is the purpose of that? Is that something related to protecting data integrity or controlling resource management. 

It seems the condition for locking isn't clearly defined yet which @yliyama will do, right?

**Comment by ticoann** [comment]
Also, temp solution for this issue is created (moving to reqmgr api) is created #7655, Please check whether output format is acceptable.

**Comment by ticoann** [comment]
@vlimant, Jean-Roch,  
At least what unify does move to wmstatsserver REST api. 
https://cmsweb-testbed.cern.ch/wmstatsserver/data/globallocks

Could you check on that? If that is not what you want at the moment, let me know.

**Comment by vlimant** [comment]
Looks good to me so far. Once in prod, we should check it against the existing locks.
Then we should check with @yiiyama how to operate it

**Comment by yiiyama** [comment]
In the Aug 31 meeting, we decided that Dynamo will directly query ReqMgr to get the "global view" of datasets/blocks in use. So essentially the responsibility for making the list of locked items moves to Dynamo, which does it internally.
I'm belatedly getting on to implement this. @ticoann @vlimant could you point me to the code that makes the globallocks list? I need to know what queries to make where. Thank you!

**Comment by vlimant** [comment]
https://cmsweb-testbed.cern.ch/wmstatsserver/data/globallocks is that global view IMO.

if you want to cook it internally, I think you can use

output : 
https://cmsweb.cern.ch/reqmgr2/data/request?mask=OutputDatasets&status=assigned&status=acquired&status=running-open&status=running-closed&status=completed&status=force-complete&status=closed-out

primary input : 
https://cmsweb.cern.ch/reqmgr2/data/request?mask=InputDatasets&status=assigned&status=acquired&status=running-open&status=running-closed&status=completed&status=force-complete&status=closed-out

secondary input : 
https://cmsweb.cern.ch/reqmgr2/data/request?mask=MCPileup&status=assigned&status=acquired&status=running-open&status=running-closed&status=completed&status=force-complete&status=closed-out with the twist that secondary should be kept locked for an extra 2 (or N) months after not being in the returned value above.

we could add the mask=SiteWhitelist in the url (but it is failing #8161) to make it site-aware, but I am afraid this would not work so great with overflowing in some cases.

**Comment by yiiyama** [comment]
@vlimant Thank you!
Dynamo should query whichever the interface that gives fresher data. Do you mean https://cmsweb-testbed.cern.ch/wmstatsserver/data/globallocks is as good as querying the three? In that case we should indeed use it.

**Comment by vlimant** [comment]
https://cmsweb-testbed.cern.ch/wmstatsserver/data/globallocks  is composed internally from the three different calls as far as I know

**Comment by yiiyama** [comment]
I see.
I'm looking at #7655 and indeed it combines the three calls, but I guess there is no mechanism for
"with the twist that secondary should be kept locked for an extra 2 (or N) months after not being in the returned value above."
So I'll have the three calls made within Dynamo. @ticoann I'm sorry we asked for a feature and then changed the strategy..

**Comment by yiiyama** [comment]
We also have another issue open closely related to this: #8332

**Comment by amaltaro** [comment]
Looking back at the code already implemented for this data locking, it looks like we could start using this `globallocks` wmstats REST API:
https://cmsweb-testbed.cern.ch/wmstatsserver/data/globallocks

Which works as follow. The `globallocks` API used this object to build the list of datasets to be locked:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMStats/Service/ActiveRequestJobInfo.py#L111

by scanning the workflow configuration and making sure their `RequestStatus` matches this filter:
```
ACTIVE_NO_CLOSEOUT_FILTER = {"RequestStatus": ['assigned', 'staging', 'staged', 'acquired',
                                               'running-open', 'running-closed', 'force-complete',
                                               'completed']}
```

this uses the WMStats local cache:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMStats/DataStructs/DataCache.py#L41

and extracts the following keys from each request (it knows how to handle TaskChain/StepChain):
```
["InputDataset", "OutputDatasets", "MCPileup", "DataPileup"]
```

I see two possible flaws in this locking logic:
1) it does NOT consider the parent dataset (we don't keep the parent dataset name anywhere in a workflow description)
2) it does NOT list transient datasets (either defined by `KeeptOutput` or by `TransientOutputModules`). AFAIK, we need to lock those otherwise it might be that the site admin (or DDM) cleans up the /store/unmerged area. @vlimant might be able to confirm this though.

Problem 2) could be workaround by using the LFNs from `OutputModulesLFNBases` and building the dataset name ourselves.
Problem 1) is a bit harder though. Whatever change we make here, we need to make sure that old requests in the system are also covered. So a new workflow parameter will not suffice until the next year or so.

FYI @goughes

**Comment by vlimant** [comment]
the transient never make it in dbs/phedex. I think they are properly listed in the protectedlfn #7645
