### ISSUE TITLE
Add search filter for Campaign on approved page in reqmgr2 GUI

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7704]
@fabozzi, do you need exact matching or substring matching or wild card for this field?

**Comment by fabozzi** [comment]
@ticoann 
The Campaign name uniquely identifies the batch. For instance:
'Campaign': 'CMSSW_9_0_0_pre6__HIN_noPU-1489070660'
You can have another similar batch, but at least the time stamp will be different,
for instance:
'Campaign': 'CMSSW_9_0_0_pre6__HIN_noPU-1489070675'

Therefore, when we search the batch by campaign name 
we can do exact matching, and substring matching is a feature
that makes the seach easier when there are no ambiguities ("HIN_noPU",
"HIN_noPU-1489070660")

Instead, the prepID identifies uniquely a certain workflow belonging to
a batch. 
For instance:
'PrepID': 'CMSSW_9_0_0_pre6__HIN_noPU-1489070660-QCD_Pt_80_120_13_HI'

Therefore, when we search the batch by prepID we can only 
do by substring matching, 
i.e. search "HIN_noPU-1489070660"

**Comment by ticoann** [comment]
@fabozzi, I am a little confused. None of the current active workflows has campaign name with time stamp attached.

https://cmsweb.cern.ch/reqmgr2/data/request?status=ACTIVE&mask=Campaign&mask=PrepID

And it seems RequestName contains always Campaign names

**Comment by fabozzi** [comment]
@ticoann 
this is because the current version of the script that is in production is still using the old parameters (no prepID and Campaign name = release). The new cfg with new parameters definition has been used only in test workflows. Currently there are 2 tests workflows in assignement-approved state:
fabozzi_RVCMSSW_9_0_0_pre6QCD_Pt_80_120_13_HI__testUnif_170309_154634_5251
fabozzi_RVCMSSW_9_0_0_pre6EPOS_PPb_8160GeV_MinimumBias__testUnif_170309_154623_428

with Campaign name:
"Campaign": "CMSSW_9_0_0_pre6__HIN_noPU-1489070660"

I see them in wmstat.

**Comment by ticoann** [comment]
@fabozzi, So it will be changed how request name/Campaign is constructed using new cfg. Thanks.  It sounds like to have the search option by Campaign is more useful also sufficient. correct? Unless you need a search by PrepID, we will add just Campaign search for next deployment.
But it won't be much trouble if you want us to add other search options (PrepID or others) for other use cases.

**Comment by fabozzi** [comment]
@ticoann 
I agree with you that search option by Campaign is suffient for us. We will see if we have more use cases.
Thanks!

**Comment by ticoann** [comment]
@vkuznet, Valentin, Could you take this issue?

**Comment by vkuznet** [comment]
Seangchan, I need more info:
- please provide an example of document which send to this page, in particular I need to see if campaign and/or prepid are presented in this document
- do we need to show campain for every request, since so far we only show Request/Status/Date/User/Group attributes
- the existing search does "Filter by pattern" which basically apply JS filter to pattern names shown on a page, do you want to extend the same search field to search by campaign or do we need another input field. The problem may be JS code which needs somehow to distinguish if given input value is a request pattern or campaign one.

**Comment by ticoann** [comment]
Hi Valentin,

Just to clarify the changes on approve page and we just need the search option for Campaign but not PrepID

https://cmsweb-testbed.cern.ch/reqmgr2/approve

> please provide an example of document which send to this page, in particular I need to see if campaign and/or prepid are presented in this document

Could you point me the call populate this page? 
If you are getting all the "new"  document (without masking), Document structure is something like this.
https://cmsweb.cern.ch/couchdb/_utils/document.html?reqmgr_workload_cache/prozober_MonteCarlo_eff_Vienna_Commissioning_160713_163720_893

Campaign is always set with some string but it is not required in the system so it could be empty string but it key should exist.

> do we need to show campain for every request, since so far we only show Request/Status/Date/User/Group attributes
I thinks that will be helpful

> the existing search does "Filter by pattern" which basically apply JS filter to pattern names shown on a page, do you want to extend the same search field to search by campaign or do we need another input field. The problem may be JS code which needs somehow to distinguish if given input value is a request pattern or campaign one.

I think it should be another fields so it can distinguish whether searches are on request name or campaign.  For campaign, even it might be better for exact match rather than substring match. In case one of the campaign name is the substring of other campaign name.
@fabozzi, could you verify whether this is what you need?

Thanks,

**Comment by vkuznet** [comment]
Seangchan, @ticoann, please take https://github.com/dmwm/WMCore/pull/7719 This PR includes changes to include new filter. Don't merge yet, but please deploy to your VM for testing.
