### ISSUE TITLE
wmstats color warning.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7705]
1. have different color for drainging agent (blue?)
2. If there are multiple warnings display everything. draining, disk full warning.

**Comment by ticoann** [comment]
@scarletnorberg, Scarlet, Is this what you want?

**Comment by scarletnorberg** [comment]
@ticoann  I am not sure about the warning because I do not think we have a disk warning and an agent in drain right this second. I think you changed the draining agent from yellow to red, if there is another color that would be great. If my only color choices are red or yellow than I would prefer yellow.

**Comment by amaltaro** [comment]
Seangchan, blue sounds good for me. Then just summarizing:
* green: everything is fine, so no error/detail message.
* blue: everything is fine, BUT the agent is in drain (so usual draining message)
* yellow: agent has warning alarms, so something is not correct and it should display all possible warnings (AND the draining message, in case it's in drain).
* red: agent has errors, something is really bad AND it should display all possible errors AND warnings (and the draining message if needed).

Can you confirm this? I think this is how it should work.

**Comment by ticoann** [comment]
@scarletnorberg, Hi Scarlet, I am fine with what Alan suggested. Do you agree? 
I am wondering if there is drain and and disk warning. do you still want to warning color (yellow)?

**Comment by scarletnorberg** [comment]
@ticoann I agree with this color scheme Alan proposed. I think for when we have agents in drain and a disk warning it is fine to keep it blue since I have to check on them ever once in a while any ways. I am hoping with the agent in drain the logs will not expand to much more than they already expanded and it would be fine.
