### ISSUE TITLE
Add code to parse FWJR "NEvents="400"

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#7711]
<Run ID="300">
<Lumi Section ID="2" NEvents="400">

NEvent can be empty "" or "0" which has a different meaning.
"" means value is not available.
"0" means 0 events processed.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/FwkJobReport/XMLParser.py#L212

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WMAgent copies XML data to internal job report](https://trello.com/c/BHWX3laI/2-wmagent-copies-xml-data-to-internal-job-report)

**Comment by ericvaandering** [comment]
Start with the XML report created in https://github.com/dmwm/WMCore/pull/7717 which has the new format

**Comment by ericvaandering** [comment]
Looking at this... This info is stored in Report in a Run object where that object contains a list of lumis. Now we'd really like a dict of lumis with events as the values. That's going to be really intrusive since that Run object is used everywhere.

What I'm thinking instead is that we duplicate the info in the file object with an dictionary that is per lumi event counts like this
```
{'1': {'11': 100, '12': 200}, '2': {'10':100}}
```
Where the single digit numbers are runs, 2 digit numbers are lumis, and 3 digits are event counts and can be None.

**Comment by ticoann** [comment]
I think Run object might be a good place to store this information. Maybe we can make this less intrusive by keeping all the accessor and setter with the same format as it is and just add new method to get event information.

**Comment by ericvaandering** [comment]
I thought about that too. Maybe I can even store things things just once and make Run.lumis return the right thing through some python magic.

**Comment by ticoann** [comment]
#7748
