### ISSUE TITLE
Propagate event/lumi/file information through merges

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#7714]
Maybe this does not need to be done since there will still be a FWJR from the output of the merge with the new count. 

Could be use this function to verify that merges went OK without files being silently dropped?

@ticoann ?

**Comment by ericvaandering** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Propagate info through WMAgent merges](https://trello.com/c/z8jfDUzC/3-propagate-info-through-wmagent-merges)

**Comment by ticoann** [comment]
@ericvaandering,  I don't think this is needed, since merge fwjr report should have this information, isn't it? 
Currently we don't validate input events and output events using wmbs record. If files are skipped in the merge job, those skipped files are returned with fwjr and put into ACDC. We could add validation but there could be a case CMSW framework send back wrong information. (I mean do we need another validation?)

**Comment by ericvaandering** [comment]
OK, so what I thought was a silent failure is only a partially silent failure?

As long as we currently get the events that eventually wind up in DBS from the merge outputs, then getting the per-lumi counts from the merge outputs is fine as well. 

Feel free to close this issue if you like.
