### ISSUE TITLE
New relval agent setting

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7722]
Following up from https://github.com/dmwm/WMCore/issues/7715 we should set the relval agent limits to [60 min, N min] so as to have utilitarian jobs ask for 60min and processing jobs maxed to N min.
N could be the default setting IMO, which would change ~nothing to the current situation.
We can live with N=2200 min for the time being.

We should enforce that TimePerEvent is set to pseudo-reasonable values in the matrix to avoid having jobs requesting much less than what they need ; @fabozzi may you please follow up on this

**Comment by amaltaro** [comment]
@vlimant I'll simply remove this tweak from the relval agent deployment, such that it will use the same limits as any other agent:
`{'MaxRequestDiskKB': 20971520, 'MinWallTimeSecs': 3600, 'MaxWallTimeSecs': 162000, 'MinRequestDiskKB': 1048576}`

is that Ok?

In addition to that, we have two more tweaks for the relval agents.
1. LogCollect retry is 2 instead of 1
2. archiveDelay (time to cleanup all the data for an announced workflow) is set to 336 instead of 24h

Should I keep them or you would like to have the same settings as the production nodes?

**Comment by amaltaro** [comment]
@vlimant patch was created, I just need your feedback on these 2 points above.

**Comment by vlimant** [comment]
I would go without touching the other tweaks

**Comment by amaltaro** [comment]
Thanks. I updated the patch then.
