### ISSUE TITLE
Missing files at T2_CH_CERN

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7834]
Sid, Sebastian, please subscribe and report future cases here.

**Comment by sidnarayanan** [comment]
I was going to send this in the email thread, but I'll put it here instead:

The reason I have a suspicion it has to do with WMAgent is because almost all of the files were produced at T2_CH_CERN (and lost at T2_CH_CERN). If it were an SE problem, I'd expect files produced elsewhere to also be affected. Furthermore, EOS admins seem to indicate that for the files they were able to check, there was no record of the file arriving in the namespace. To me, this seems like that the problem occurs even before the file gets to EOS, which then leads me to WMAgent. If I'm thinking about this incorrectly, please let me know.

**Comment by amaltaro** [comment]
I'd say the other way around, since it happens only/mostly at T2 CERN, a site/storage issue would be on the top of my list of suspects.

If EOS admins found no records (and logs?) at all for those files, then it probably means the file was not even attempted to be staged out. And in this case, I'd say the job got killed (or killed itself) before the stage out kicked in. And in such cases, the agent wouldn't retrieve a valid FWJR, making it impossible to add the output files to the local database and a posterior phedex injection.

Please do inform us in case you face other files not know by the site and the site admin.

**Comment by amaltaro** [comment]
Since we haven't had any issues during the last 11 months, I'm closing this issue
