### ISSUE TITLE
MonteCarlo request RequestNumEvents default to 1000

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7861]
as discussed in https://github.com/CMSCompOps/WmAgentScripts/pull/221 operation have had a hard time with clones defaulting to 1000 event to be processed.
Looks like that parameter should be made mandatory at creation time and fail creation if not provided, never fall back to 1000 by default.
@amaltaro this is a show-stopper for operation
FYI @prozober

**Comment by amaltaro** [comment]
Darn it!! We keep some of these default values for unit test purposes, I missed the point it has the default value assigned to it before the request validation, and that's why it doesn't fail :(

I'll fix it for tomorrow's testbed. However, it's clearly not a show-stopper, since you _just_ need to provide the expected parameters.

**Comment by vlimant** [comment]
yes, the value is not provided, I am trying to track why it does not come through.
