### ISSUE TITLE
Problem with SimpleCondorPlugin and Tier0

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#7876]
Trying out the latest WMCore tag in the Tier0, the JobSubmitter dies on me in the SimpleCondorPlugin in this line

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L605

Backtrace:
  <WMComponent.JobSubmitter.JobSubmitterPoller.JobSubmitterPoller instance at 0x7fe3dc0a2368> BossAirException
Message: Unhandled exception while submitting jobs to plugin: SimpleCondorPlugin
Unknown ClassAd value type.
        ModuleName : WMCore.BossAir.BossAirAPI
        MethodName : submit
        ClassInstance : None
        FileName : /data/tier0/srv/wmagent/2.0.6/sw.hufnagel/slc6_amd64_gcc493/cms/wmagent/1.1.0.pre6-comp/lib/python2.7/site-packages/WMCore/BossAir/BossAirAPI.py
        ClassName : None
        LineNumber : 401
        ErrorNr : 0

I added some debug printout and what it tries to do here is:

condorAd['AllowOpportunistic'] = None

I guess it doesn't like the None. First question, why do we get a None here ? Second question, shouldn't that code barf on that None before ?

**Comment by amaltaro** [comment]
The None is likely coming from the fact that create and assign spec arguments were separated, so you don't really set it (and a bunch of other arguments):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1102

unless you override this method on your spec:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L913

BTW, which spec file is that? I don't remember if I talked to you about the T0 specs when this change was happing, maybe only for the PromptReco spec... 

If you want, I can help you migrating the other specs to WMCore, but only on the next week.

**Comment by hufnagel** [comment]
I did some of the needed adjustments already (without them nothing worked). You can see the current state here:

https://github.com/hufnagel/T0/commit/91d9e35bd2cabfbd63b6ca4309b66bdcc1ad45c8

One thing that is messy is that the new parameters are split into creation arguments and assignment arguments. This split makes no sense to the Tier0, we don't distinguish. Which breaks some things already (like how I deal with SiteWhitelist and SiteBlacklist is kind of hacky and I am not sure this will work).

**Comment by amaltaro** [comment]
> One thing that is messy is that the new parameters are split into creation arguments and assignment arguments.

that was the whole point of the latest changes. The arguments separation was needed to avoid confusions and endless debugging in production, from time to time.

Yeah, I know that doesn't make sense for T0. You could update the assignment scripts by updating the workload object with this method:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1633

but anyways it won't work completely for T0 because I see you have a bunch of new arguments there.
Thanks for fixing them!

**Comment by hufnagel** [comment]
Ok, good suggestion. Will look into that (next week). You think this is the reason for my problem in the SimpleCondorPlugin though ?

**Comment by amaltaro** [comment]
Yes, because AllowOpportunistic is no longer set when the workflow gets created. It's an assignment parameter (speaking in terms of central prod) which is set (to either False/True) here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1673

and that method is called to update the workload settings during assignment. So I expect it to fix the T0 problem. I still think you'll need to keep defined some of those other arguments that are nowhere defined in WMCore.

**Comment by hufnagel** [comment]
Closing since #7889 will address this problem.
