### ISSUE TITLE
Improve stage out logging

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#7919]
Making a place holder from discussions Seangchan had with Stephan and others. What I remember is:
* adding proxy information to the log (DN, lifetime, voms roles)
* always log the command(s) executed
* possible list permissions of the directory we're trying to write to

Just not sure whether we should print these stuff by default, or only in case of failures... (?)

In addition to that, maybe @belforte Stefano can point us to a stage out failure log from CRAB3, which I heard to be much better than the WMAgent one :)

**Comment by amaltaro** [comment]
@ticoann can you please complement anything that I missed? Thanks

**Comment by belforte** [comment]
how comes today people make me smile so much !
Main point about log IMHO is: do not look at what WMA writes ! WMA is quite good since years, we never need to debug it, and especially.. never paste WMA tracebacks etc. into messages to site/grid/user... 

Extracting the external command stdout/stderr from WMA printout is currently an art, would be great if @ticoann could make it a science by e.g. some prefix like Brian did for CRAB log.
I attach an example crab log (since file is currently on our schedd and will be deleted in a month):
[job_out.5.0.txt](https://github.com/dmwm/WMCore/files/1064670/job_out.5.0.txt)


Note that not even Brian could really properly flag/remove WMA tracebacks, in CRAB logs we are stuck with:
there's a lot of WMA lines that we try to ignore while they try to confuse us, but buried in the middle
the CRAB's own stageout tool (the dreaded cmscp.py, a horribly long and very hard to read beast) makes sure that it prints the command it executes, and the stdout and stderr from that command, over the years Stefano and a few others have learnt how to filter the noise and get lines like the ones I pasted in HN in no more than ten minutes.

To find the "stageout log" in the uploaded file one needs to:
- look for `-----> Stageout implementation log star
- look below for lines which look like stderr from the actual command
- only somehow below there's the actual command that was issued, in this case `Command : #!/bin/bash
env -i X509_USER_PROXY=$X509_USER_PROXY JOBSTARTDIR=$JOBSTARTDIR bash -c '. $JOBSTARTDIR/startup_environment.sh; date; gfal-copy -t 2400 -T 2400 -p   file:///srv/EventTree.root srm://gfe02.grid.hep.ph.ic.ac.uk:8443/srm/managerv2?SFN=/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/adow/92X_HLTPhysics2_VBFcuts/HLTPhysics2/crab_HLTPhysics2/170608_123905/0000/EventTree_5.root'` inside the typical WMA wrapper that only says:
 `Non-zero gfal-copy Exit status`

Yeah.. large room for improvement !

About your 3 bullets Alan I would say :
* the 3rd is likely hopeless and often useless, esp. for local stageout
* after the second I woul like to add my favorite point:
   * alway log the command to be executed before executing it
   * always capture stdout/stderr from the command
   * if the command fails, print that stdout/stederr

**Comment by ticoann** [comment]
Thanks Stefano for the feed back and advice.

**Comment by belforte** [comment]
hey !! do not stop making fun of me, I still can use some smile today !!!

**Comment by ticoann** [comment]
And you made me smile. 😄

**Comment by belforte** [comment]
too bad we never met, should have some beer toghether

**Comment by ticoann** [comment]
I think we met but no beer yet. :-)
