### ISSUE TITLE
Site Status not synching

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#7935]
https://cmsweb.cern.ch/couchdb/wmstats/_design/WMStats/_view/agentInfo?stale=update_after

has 

"T3_IN_TIFRCloud":{"state":"Normal","running_slots":100,"pending_slots":50

for submit1, submit2, 130, 304, while it is disable in ssb.

FYI @scarletnorberg

**Comment by amaltaro** [comment]
It has no ioBound metric (161), that's why the site isn't touched in the database. It requires all 3 metrics:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py#L176

I wrote most of that code myself, but I acknowledge it can be improved. Like, isolating site status from threshold changes, logging when there is some missing info (I was expecting this to be the case, but it iterates over the "wrong" struct), etc.

**Comment by amaltaro** [comment]
BTW, if you want to get it fixed *now*, please ask the SS team to fix the metric 161.

**Comment by vlimant** [comment]
But one metric says : disabled, so it should be in mode "down" regardless of the other metrics ?
Or was it forced enabled somehow (because of the missing metrics) and does not sync back to disabled ?

**Comment by vlimant** [comment]
can you actually please spin the email to site support with what they have to do to make this right ; is that "just" including T3_IN_TIFRCloud in the table 161 ?
