### ISSUE TITLE
Replays not writing to the backfill area on eos

### ISSUE THREAD

**Issue by johnhcasallasl** [dmwm/WMCore#8001]
Hello:

We have noticed that the output from the recent replays is not going to the
/eos/cms/tier0/store/backfill/1/data/ area, but to the /eos/cms/tier0/store/data/ area. We checked the Tier0  configuration and everything seems to be properly set up.  Operationally it not causing particular problems right now, but it is not the expected behavior. Discussing it with @hufnagel, it is likely related to the general parameter reorganization in StdBase.

--
Regards,

John

**Comment by hufnagel** [comment]
No time to look into it due to the Princeton workshop. But nothing changed in the Tier0 code that overrides MergedLFNBase and UnmergedLFNBase, so my first order assumption is that for some reason these parameters reset back to default values for some reason.

**Comment by hufnagel** [comment]
Ok, it seems during "assignment", ie. WMWorkload.updateArguments(), the LFN bases reset to the default values. To prevent this from happening, I made a change in the Tier0 code and now pass ALL parameters again to the updateArguments.

https://github.com/hufnagel/T0/commit/af85db1bd695de1abf7eff8a277852c12a1640a2

@amaltaro @ticoann can you comment on whether this is OK ?

Also, with this change, the updateArguments() call actually fails since the LFN validation doesn't understand Tier0 LFN.

**Comment by ticoann** [comment]
I think that is fine as long as it passes the correct values.

**Comment by hufnagel** [comment]
Fixed by #8007
