### ISSUE TITLE
align stepchain and taskchain schema validation

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8024]
we are getting tons of taskchains with TimePerEvent & SizePerEvent at the task level (good!) and also at the base level (useless value?) and that passes validation.
while transforming those into stepchain, the base level is not accepted for the clone.
I think things should be aligned.

FYI @thongonary

**Comment by vlimant** [comment]
alright, that has the value of documenting this. for taskchain, the value is allowed everywhere. For stepchain it is allowed *only* at the base level.

**Comment by vlimant** [comment]
FYI vlimant_task_B2G-RunIISummer15wmLHEGS-01341__v1_T_170725_221625_2289 was accepted, and reqmgr2 blew up ... 
@ticoann if you can take a look

**Comment by ticoann** [comment]
I don't have a direct access to production server log. So I am not completely sure what happened. But it seems couch server is down in production site. (https://cmsweb.cern.ch/couchdb/_utils/) It usually restarts itself unless there is some problems. I can get a delayed log (~20 min), I will update if I can find any more specific information.

**Comment by ticoann** [comment]
couch server is running now. I am not sure what cause the crash

**Comment by amaltaro** [comment]
vlimant_task_B2G-RunIISummer15wmLHEGS-01341__v1_T_170725_221625_2289
was accepted because it has TpE and SpE at top level only.

I don't think there is anything to be done here, TaskChain has always had those parameters at both level and task level, as we do for several other arguments that can be inherited from top level.

StepChain runs all in one job, so having it in a step basis is pointless.

If you have a strong argument, please reopen it.

**Comment by amaltaro** [comment]
and I forgot to mention, these arguments have been documented here:
https://github.com/dmwm/WMCore/wiki/Workflow-creation-and-assignment-definition
