### ISSUE TITLE
Problems tweaking PSet for StepChain - job splitting updates

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8025]
regarding https://cmsweb.cern.ch/reqmgr2/fetch?rid=vlimant_task_B2G-RunIISummer15wmLHEGS-01341__v1_T_170725_221625_2289 it is getting some errors with code 70

----- Begin Fatal Exception 26-Jul-2017 04:33:41 CDT-----------------------
An exception of category 'Configuration' occurred while
[0] Constructing the EventProcessor
[1] Validating configuration of input source of type PoolSource
Exception Message:
Illegal parameter found in configuration. The parameter is named:
'numberEventsInLuminosityBlock'
You could be trying to use a parameter name that is not
allowed for this plugin or it could be misspelled.
----- End Fatal Exception -------------------------------------------------

indicating a mis-tweaking of the input module of the subsequent step of the chain

**Comment by vlimant** [comment]
@amaltaro @ticoann I think we can consider this high priority, give the push for StepChain.

**Comment by amaltaro** [comment]
I failed to see how it's related to StepChain and even WMCore, but I'm investigating it.

Isn't this `numberEventsInLuminosityBlock` part of the events per lumi recent developments in CMS? Maybe a release doesn't support it, though I'd doubt that...

**Comment by amaltaro** [comment]
Nevermind, this is defining how large a lumi section should be, so it makes sense only steps with no input data and, it seems to be harmful if it's set for steps/pset with input data, apparently...

I've a dump of the Step1 and Step2 psets in [1], the important part.

We have a test case similar to this one and that has been working fine for several and several months. By comparing my testbed config with this workflow, the difference is that this workflow defines `eventsPerLumi` for all steps, while mine only does it for step1.

Then looking at the PSet tweak code, it only applies the process.source tweak if eventsPerLumi attr is found for that step:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L774

@vlimant have you changed the job splitting for that workflow? Or you just rely on the TpE and let the auto splitting handle everything?

[1]
Config for Step1:
```
process = cms.Process("SIM")

process.source = cms.Source("EmptySource",
    firstLuminosityBlock = cms.untracked.uint32(257),
    firstEvent = cms.untracked.uint32(45057),
    firstRun = cms.untracked.uint32(1),
    numberEventsInLuminosityBlock = cms.untracked.uint32(200)
)
```

Config for step2:
```
process = cms.Process("HLT")

process.source = cms.Source("PoolSource",
    fileNames = cms.untracked.vstring('../cmsRun1/RAWSIMoutput.root'),
    numberEventsInLuminosityBlock = cms.untracked.uint32(200),
    overrideCatalog = cms.untracked.string('trivialcatalog_file:/srv/job/WMTaskSpace/cmsRun2/CMSSW_8_0_21/override_catalog.xml?protocol=direct'),
    secondaryFileNames = cms.untracked.vstring()
)
```

**Comment by ericvaandering** [comment]
So this is caused by a mis-configuration in the StepChain request? We could also consider an added layer of protection by refusing to add it to anything but an EmptySource....

**Comment by amaltaro** [comment]
Seems to be the case, though apparently we have the same type of template and I have never seen this issue.
Jean-Roch, would you still have the dictionary you sent to ReqMgr? I can get it from the service logs, but that also contain some default values added by ReqMgr.

**Comment by amaltaro** [comment]
Found it (well, reproduced it), the problem is triggered when you change the job splitting. 

Since the job splitting is task driven, when you make any job splitting changes to the production/processing task (where only one exists for StepChain), that's then applied to all the CMSSW steps in the task.

Can you please clone - with the proper job splitting settings in place during creation time -  and assign a new workflow please? Let me know its name.

I don't think I can fix it today, this will certainly be a delicate change, as anything for stepchains :(

**Comment by amaltaro** [comment]
Eric, I think your suggestion is a good candidate to fix this issue ~now and avoid a new ReqMgr release/patch.

**Comment by amaltaro** [comment]
I've just discussed a possible PSet solution with David Lange and we agreed that relying on the source type will eventually cause problems (there are so so many sources).

Since adapting the job splitting is something quite uncommon in production, I suggest to keep it that way (let the auto job splitting handle it) and then we fix it in WMCore for the next cmsweb release
