### ISSUE TITLE
WMBSMergeBySize definition of merge units is too strict

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8092]
We ran into a problem where PromptReco AlcaSkim job seemingly ignored merge size limits (they use the WMBSMergeBySize job splitter since mostly what they do is merges).

An AlcaSkim job had two input files of 14GB each, even though we use the default merge limits (min 2GB, max 4GB). This should have been two jobs processing one file each.

Looking at the WMBSMergeBySize code, there is strange definition of a merge unit. If two files to be merged have the same parent file, the algorithm forces them to be merged together. Why ?

If we process a 10 lumi RAW file, what's wrong with getting two RECO outputs with 5 lumis each ?

**Comment by hufnagel** [comment]
Basically any workflow that expands data size significantly will have serious problems with this.

**Comment by hufnagel** [comment]
Just looked at github 'Blame'. This code is ancient. Surprised we didn't run into this earlier...

**Comment by hufnagel** [comment]
Checking a bit further, the results of this code are also completely random since they depend on the timing of job completions (the N jobs running on the single parent file) and when the job splitter is run. In this case there were many more jobs than just two running on the same input. It was just random chance that two files were available when the job splitter was run.

I would suggest to just get rid of this condition and ignore parent files for the definition of merge units.

**Comment by hufnagel** [comment]
Ok, checking even further, this was intended to protect against splitting lumis for event based splitting. Using it together with a data discovery that hides incompletely processed lumis this would ensure that all partial lumis are assigned to the same job.

Likely this is still a holdover from the days when we ran PromptReco with event splitting. If I switch the PromptReco spec to use the ParentlessMergeBySize algorithm instead, things should work the way I want, correct ?

**Comment by hufnagel** [comment]
@ticoann @amaltaro , comments ?

**Comment by amaltaro** [comment]
Checking the other specs, we don't really use `WMBSMergeBySize` but for merging files where the parent is not a "Production" task and it uses the EventBased splitting
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L617

It probably makes sense to keep the parent check for WMBSMergeBySize, since it ensures (or best effort) that all parts of a lumi section will be in the same file.

I think it's safe to update it to ParentlessMergeBySize:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/PromptReco.py#L91

BTW, what splitting algo is used by PromptReco? If it's not EventBased, you might want to update the default job splitting in the spec too:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/PromptReco.py#L174

**Comment by hufnagel** [comment]
Default for PromptReco is EventAwareLumiBased

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L1032

but you are right, I should change the default in the PromptReco Spec itself as well.
