### ISSUE TITLE
Do not make EventsPerJob override the 8h target

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8124]
related to 

https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4328.html
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2941.html

 injection of a request specifying EventsPerJob should not be let to overide the value that is calculated otherwise according to TimePerEvent (or SizePerEvent thereof) if the injected value is *larger* than the calculated estimate.

**Comment by vlimant** [comment]
it could be that the injected value is currently considered as a lower limit that should not be changed (for generator integration purpose), so there is the need to sort out what to do with this.

**Comment by vlimant** [comment]
looks like indeed we need to make EventsPerJob set the splitting, unless it makes it larger than the value derived for the 8H target

**Comment by vlimant** [comment]
@amaltaro @ticoann  could you please confirm what is the current effect of setting EventsPerJob in the original request ?

**Comment by ticoann** [comment]
Default EventsPerJob is calculated so job can have approximately 8h hour running time (rely on time per event value).

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/TaskChain.py#L491

But EventsPerJob is given it will just use that without any restriction.  (Actual algorithm to split jobs are different from splitting algorithm. For EventAwareLumiBased, it is used to get the number of lumis per job and that is used to determine job boundaries.

So what you want to do is only honors EventsPerJob if that creates less than 8h job otherwise change EventsPerJob to have 8h job?

I was just wondering why? Both parameters (EventPerJob, TimePerEvents) are assigned by requestor. Shouldn't the requestor have the full control?

**Comment by amaltaro** [comment]
Here is my take on this. WMCore provides two options:
1) one can provide TimePerEvent and get the automatic 8h job splitting
2) one can provide EventsPerJob (or LumisPerJob) and skip the automatic job splitting.

Having said that, I don't think we should add any other complexity (well, it's simple but...) to how the job splitting is performed.

If there is a client providing EventsPerJob when it should not, then that client has to be fixed. There might be moments that you want to enforce a job splitting (smaller than 8h) and then this feature will become a bug...

**Comment by vlimant** [comment]
Yes, requester has control on both EventsPerJob and TimePerEvents, but *not* 8H that is hardcoded somewhere in reqmgr. For the case I was referring to, EventsPerJob would be provided as a guidance as the "max events per job", which indeed should only take action if it ends up creating a job shorter than 8H.
If one wants to adjust the splitting a posteriori, the splitting interface allows it anyways, so there is no bug.
That said, the correct way is to handle this is to fix the underlying generator software and there is hope (on-going dev of a fix backport), so maybe we won't need this feature. But "maybe" that won't get fixed and we'll be still screwed with spewing 10s of thousands of failed jobs. 
For 1 to 10, how hard is it to put this min(8h, EventsPerJob*TimePerEvents) ?

Is the 8H a configurable parameter BTW ?

**Comment by vlimant** [comment]
the use case of having EventsPerJob be a suggestion of "do not run more than that many events per job" is ~dead as it does not seem we have an agreement with ppd/gen on what/when/how to provide this. Since it looks like we are lucky with getting gen code fixed instead of finding this work-around, I would close this issue until next time.
