### ISSUE TITLE
Messed up ACDC documents

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8157]
related to https://its.cern.ch/jira/browse/CMSCOMPPR-1224
the acdc was created, assigned using the announced site list in the acdc documents, and still

Job Name: 0f8a9278-9479-11e7-85c1-002590494fb0-2
WMBS job id: 1267929
Workflow: vlimant_ACDC0_task_SMP-RunIIWinter15wmLHE-00116__v1_T_170908_110320_1957
Task: /vlimant_ACDC0_task_SMP-RunIIWinter15wmLHE-00116__v1_T_170908_110320_1957/SMP-RunIIWinter15GenOnly-00012_0MergeRAWSIMoutput
Status: jobfailed
Input dataset:
Site: Unknown
Agent: vocms0304.cern.ch
ACDC URL: https://cmsweb.cern.ch/couchdb/acdcserver
State Transition
Exit code: 71101
Retry count: 4
Errors:

    JobSubmit
        SubmitFailed (Exit Code: 71101)

            No sites are available to submit the job because the location of its input(s) do not pass the site whitelist/blacklist restrictions (WMAgent).: file locations: T2_UK_London_IC, T3_UK_London_RHUL, T3_UK_SGrid_Oxford: site white list: T2_UK_SGrid_Bristol, T2_UK_SGrid_RALPP, T2_UK_London_Brunel, T2_BR_SPRACE: site black list: 

note the T3_UK_* which are IMO messing things up.

 T3 does not appear in 

https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22mcremone_task_SMP-RunIIWinter15wmLHE-00116__v1_T_170807_191109_6978%22&include_docs=true&reduce=false

**Comment by vlimant** [comment]
if this was a site playing black magic with site configs, I want a GGUS or something to understand if sites go untested in production.

**Comment by amaltaro** [comment]
I had a look yesterday and I couldn't find any issues.
I was investigating it further today, but unfortunately all the acdc data is gone.

It seems some of those files were available at T2_UK_London_IC, while it's not sitewhitelisted and that's why those jobs failed to be submitted. However, if it's not in the sitewhitelist, then I assume it wasn't in any of the acdc docs either (?)

When the WorkQueueManager is pulling and getting available work, it doesn't apply any location mapping (pnn x psn) nor data location update. The first place we hit a mapping is during job creation:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/JobFactory.py#L190

which in the end uses the sitedb data-processing API. So if data is placed in T2_UK_London_IC PNN, that would actually get mapped to 5 PSNs (the agent knows 3 of them):
 'T2_UK_London_IC': ['T3_UK_SGrid_Oxford',
                     'T3_UK_London_RHUL',
                     'T2_UK_London_IC'],

that's where these T3_UK_* come from.

I don't think there is much left we can do here. Since it was one incident and all the debugging info is gone, I suggest we close it.

**Comment by vlimant** [comment]
@prozober, if that shows up again, please come back to this
