### ISSUE TITLE
Fix unstable test EventAwareLumiByWorkTest:test_NotEnoughEvents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8159]

**Comment by amaltaro** [comment]
@alexanderrichards this is a simple one. Would you like to have a look at it?
Problem is, the database returns a different job mask from time to time.

Instead of comparing dicts, we should compare keys and then # of values. OR something like that.

**Comment by ericvaandering** [comment]
Different job mask for a job or a task? Latter should not happen. Also I wrote a nested dictionary comparison that should work. It's an extension of the unittest test case.

Sent from a mobile device. Please excuse my brevity or transcription errors.

On Sep 15, 2017, at 06:35, Alan Malta Rodrigues <notifications@github.com<mailto:notifications@github.com>> wrote:


@alexanderrichards<https://github.com/alexanderrichards> this is a simple one. Would you like to have a look at it?
Problem is, the database returns a different job mask from time to time.

Instead of comparing dicts, we should compare keys and then # of values. OR something like that.

**Comment by amaltaro** [comment]
Job mask for a job. I think this is where it fails from time to time (that's why I added that try/except):
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/WMBS_t/JobSplitting_t/EventAwareLumiByWork_t.py#L869

Perhaps it's a peculiarity of the WMBS object (loading - unordered - lumis/files from the database or something like that... ?)

**Comment by ericvaandering** [comment]
Quite possibly. I'd suggest removing all checks on actual job masks and instead accumulate the job masks to make sure all the data gets processed instead. That's what we care about.
