### ISSUE TITLE
force-fail option

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8168]
looking at the ACDC of https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-PhaseIITDRSpring17DR-00074 I wonder if we could benefit from a force-fail option which would fail jobs in the agent and let Ops do the ACDC on the failed jobs.
This would be useful in this particular case where you'd want to let the acdc complete, and maybe try something else on the remaining work

**Comment by amaltaro** [comment]
It can't be done. First, because it's a very expensive process, second, because we'd need to acquire all elements from GQ, run the job splitting and only then fail jobs.

**Comment by vlimant** [comment]
it  might be expensive, fine. It would considerably help cutting on tails though, until better days come.
better days include : being able to change splitting, changing memory, changing time/event, ... on the resubmitted job.

**Comment by amaltaro** [comment]
These are coming, eventually :) I'm closing this one

**Comment by vlimant** [comment]
when, @amaltaro ?. In the meantime, this is one way things can get significantly improved for data reprocessing and funky campaign that gets high priority. So I insist on getting a more in depth estimation on how this can be done

**Comment by amaltaro** [comment]
This is not going to be supported nor implemented, that's why I closed it.
It's a hacky way to get documents updated to the acdc server, the performance will be terrible and it can potentially blow up agents (if requests have a few 100k jobs to process). Without mentioning all the orchestration needed in the agent <--> global workqueue logic to get these documents acquired and sent straight to ErrorHandler.

It's just too much work to get something that might be used a couple of times in the error and might give us more problems. I think we have much better things to work on the 400 issues already opened.

**Comment by amaltaro** [comment]
BTW, if there isn't one yet, feel free to open a new issue for every feature you'd like to have in the system and we can discuss it from there. Just throwing a bunch of items that would be interesting isn't helpful at all.

**Comment by ticoann** [comment]
Hi Jean-Roch, I don't quite understand what you want to do with this.
1. Do you need all the remaining jobs in ACDC failed so you can have ACDC of ACDC?
2. Do you want to include jobs which hasn't been created (only in GQ/LQ)?

I agree with Alan, if you want to do 2nd option. That will cause too much trouble. It seems it is the same effect as we just wait out all the jobs are created and then make it failed.

If you just want to do 1.  I am not sure what is the difference between force-complete and force-failed?

**Comment by vlimant** [comment]
@ticoann the purpose is to be able to force a workflow to "completed" status and still have all information in it's ACDC document so that people can go ahead and run the corresponding ACDC workflows with adapted configuration.

**Comment by ticoann** [comment]
Since we still need to discuss the problem. I am reopening the issue.

As far as I understood, when force-fail happens 

1. kill all the jobs if jobs are created/running
2. kill all the jobs which hasn’t been created after waiting for those jobs created. (To have ACDC record)
3. complete workflow - but this has to happen when? (before 1. or between 1, 2, or after 2).

If you can specify what exactly need to be done, We can evaluate the cost.
But as mentioned above it will be helpful to know what problem need to be solved. (And what are the constraints - how much delay is allowed to create the ACDCs, etc).

**Comment by vlimant** [comment]
hints in #8385

**Comment by vlimant** [comment]
@ticoann 1.2.3 you laid out seems good to me
