### ISSUE TITLE
quantize RequestDisk

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8176]
I have been fighting all day with 126 to try and reduce the number of auto-cluster thinking that there was something really bad with tuning and resizing (thanks @juztas ). 
Turned out that making RequestDisk being 10G or 20G made a huge difference (reduce the number of autocluster from 2800 to 1400).
It's quantized by 1G. I suggest 5G, at least

**Comment by amaltaro** [comment]
Instead of going bit by bit, how about we generalize this issue and quantize all ads that affect auto-clustering? That would require checking with the SI team to see what ads they round/quantize (I know about RequestMemory, which is far from optimal BTW) and what would be an ideal (or reasonable) quanta for each of them.

**Comment by ticoann** [comment]
Yes, I agree with Alan, What is auto clustering rules? Could you explain how that works? If we know the algorithm for auto clustering, we can change all the parameters affect that as Alan said.

**Comment by vlimant** [comment]
+1 on doing them all at once. +1 on starting with those that will have an immediate effect

**Comment by vlimant** [comment]
@amaltaro this was done recently, wasn't it ?

**Comment by amaltaro** [comment]
Yes, we're still missing RequestMemory though, but we need to be more thoughtful about that one. I think a new issue can be opened.
