### ISSUE TITLE
How to handled multiple files from the same output module within a job

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8180]
Within the context of large output files, it might be beneficial to use the feature of cmssw to create multiple files of ~fixed size from each single job instead of making 20G*ncore single output file.
Is that functionality already in ?

**Comment by hufnagel** [comment]
I've played around with this in the Tier0 a long time ago but decided at the time it was not useful. As far as I remember mainly because you couldn't really control where it split, so you couldn't really treat these as separate files, they always had to be handled as a unit (if you cared about data integrity).

As such, this isn't really useful since our tools can't deal with multiple files that have to be treated as a unit in term of bookkeeping, processing, data management etc.

**Comment by hufnagel** [comment]
In other words, while the wmagent probably supports this more or less out of the box, you likely screw up data management in DBS and PhEDEx and subsequent processing that uses these files as input.
