### ISSUE TITLE
Throttle JobSubmitter to 100k or MAX_JOBS_PER_OWNER

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8224]
as per https://cms-logbook.cern.ch/elog/GlideInWMS/5638 we need JobSubmitter to go idled and put a warning sign when reaching 95% of MAX_JOBS_PER_OWNER schedd classad 
FYI @bbockelm

**Comment by amaltaro** [comment]
My take on this is. If this has no impact on condor stability, I'd rather have that limit bumped from 100k to something beyond that (maybe 150k) in the condor_schedd configuration and avoid adding hooks to the agent. Eventually these hooks become evil and they do more harm then help

**Comment by vlimant** [comment]
agreed on trying to run the agents/schedd away from that limit.
having the throttling alert would prevent to shoot 80k jobs down the drain within an hour.

**Comment by vlimant** [comment]
and also the fact that draining agents have no limit (opened thresholds)

we need to patch the draining agents quite fast to be able to put them safely back in operation and get the jobs that people are watching for ran ; even a patch that we through away afterwards would do.

alternatively we patch the draining agents for the proper sharing of threshold and we set them back on (not draining)

@ticoann @amaltaro please suggest something fast

**Comment by amaltaro** [comment]
Let me have a coffee and I'll look into it. Maybe that's not really needed...

**Comment by amaltaro** [comment]
We can restart the components. The draining agents cannot submit more than 123k jobs:
```
SQL> select sum(pending_slots) from wmbs_location where state=(select id from wmbs_location_state where name='Normal');

SUM(PENDING_SLOTS)
------------------
	    122991
```

Still, it would be good to have a protection for the longer future.

**Comment by amaltaro** [comment]
Since Ops is no longer blocked by this issue, I'm removing these labels.
For the record, this is the issue that hit us on JobSubmitter
```
2017-10-03 16:16:31,616:140432992196352:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
2017-10-03 16:16:31,616:140432992196352:ERROR:SimpleCondorPlugin:Failed to create new proc id.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.4.patch2/sw/slc6_amd64_gcc493/cms/wmagent/1.1.4.patch2/lib/python2.7/site-packages/WMCore/BossAir/Plugins/SimpleCondorPlugin.py", line 148, in submit
    clusterId = schedd.submitMany(clusterAd, procAds)
RuntimeError: Failed to create new proc id.
2017-10-03 16:16:31,782:140432992196352:ERROR:SimpleCondorPlugin:SimpleCondorPlugin job submission failed.
2017-10-03 16:16:31,782:140432992196352:ERROR:SimpleCondorPlugin:Moving on the the next batch of jobs and/or cycle....
```

**Comment by amaltaro** [comment]
Oh, actually the SI team has to change the schedd setting first.

**Comment by vlimant** [comment]
123+20 is very close to 150k IMO.
draining agent do have a limit then ?

**Comment by vlimant** [comment]
BTW : this is a blocker for Ops since if you implement this throttling we can restart the jobsubmitter all around and be sure we won't shoot ourselves in the head, this time, or the next time.

**Comment by amaltaro** [comment]
Jean-Roch, Scarlet, I've just finished restarting JobSubmitter on all the agents that it was down (all draining I think). These were the changes before the component got restarted:
* pending thresholds lowered to 50/45 percent. (that gives us ~42k pending slots)
* AgentStatusWatcher restarted, in order to get the slots changes right away
* JobSubmitter added back to the cron watching/restarting it and ErrorHandler
* JobSubmitter restarted

I had another look at the code, and when an agent goes into drain it still uses the pending slots setting. So if it's 50%, it will use only 50% of the pending slots.

**Comment by scarletnorberg** [comment]
Good to know Alan. I saw Phedex down on 250 and 251 I assume someone restarted them. Because of this issue we have not really been opening Jira tickets or keeping track of this much. Are things back to normal now? When things go down now Jira ticket and I can restart it. Or are we still in stress mode and the potential of another melt down is still here and it is a free for all for who ever wants to restart restarts components?

**Comment by scarletnorberg** [comment]
@amaltaro @vlimant It seems like based on unified:  https://vocms049.cern.ch/unified/ under agent health this is red vocms0303.cern.ch in distress should we just leave it for now?

**Comment by amaltaro** [comment]
Production should be stable again, though there is still a very high pressure on global pool.
Feel free to restart/report any issues you spot.

(Just a side comment not to mix subjects, if you see timeouts being reported in wmstats (phedex for instance), make sure to check the logs before restarting anything. Cmsweb phedex had 2 instabilities today, components take longer to go through its work, but it doesn't crash).
