### ISSUE TITLE
Ignored Phedex subscriptions to tape

### ISSUE THREAD

**Issue by cronot99** [dmwm/WMCore#8259]
We are running with some issues with Phedex subscriptions since T0 2.1.0. On our configuration file we have (for SingleMuon PD):

do_reco = True,
write_reco = False,
raw_to_disk = True,
write_dqm = True,
tape_node = "T1_IT_CNAF_MSS",
disk_node = "T1_IT_CNAF_Disk",

But on Phedex subscriptions for "/SingleMuon/Run2017F-v1/RAW" we only have a subscription to T1_IT_CNAF_Disk[1]. Checking DBSBUFFER_DATASET_SUBSCRIPTION table, we found that there is only T1_IT_CNAF_Disk too.

I'll keep pending if you need more information about this.

[1]
https://cmsweb.cern.ch/phedex/prod/Request::View?request=1130093

**Comment by hufnagel** [comment]
I am running some test, but to first order it seems that multiple subscriptions for the same dataset are not handled correctly, it only sets one. This is definitely in the WMWorkload or more likely WMTask subscription code since the missing subscription already shows up in the dbsbuffer tables.

@amaltaro , you were the last one touching that code, maybe you have an idea what's wrong.

**Comment by hufnagel** [comment]
Ok, I figured out why this happens, but not the underlying reason. It seems even though from the Tier0 code we only call WMWorkload.setSubscriptionInfo once with all the subscriptions in a single data structure

https://github.com/dmwm/T0/blob/master/src/python/T0/RunConfig/RunConfigAPI.py#L667

what happens internally is that WMTask.setSubscriptionInfo is called twice for the same task (Repack) and primary dataset (SingleMuon). First call is for custodial subscpriptions for CERN and CNAF MSS, second call is for non-custodial subscriptions for CNAF Disk. You can't do it like this since the second call is not supplemental to the first, it instead replaces whatever the first call did.

**Comment by hufnagel** [comment]
Ok, after further debugging, that part is actually as expected. We do call it twice from the Tier0, once for custodial and once for non-custodial subscriptions. We have done this for at least a couple years. This used to work with the 1.1.4 tags and now doesn't work anymore with 1.1.6 tags.

It seems the latter call to add the non-custodial subscriptions wipes the previous settings for the custodial subscriptions.

For PromptReco I already have a method to make custodial and non-custodial subscriptions in a single call. Let me try this here...

**Comment by hufnagel** [comment]
Ok, single calls works. Since this is also cleaner I am pushing the change to the T0 repo. Still worth following up on this in WMCore to check if this change was intentional though IMO.

**Comment by ericvaandering** [comment]
Any update on this?

**Comment by ticoann** [comment]
Sorry, completely miss this issue. I will take a look.

**Comment by hufnagel** [comment]
Just to add, the immediate problem is solved, we worked around it on the Tier0 side by setting up custodial and non-custodial subscriptions with a single call to WMWorkload.setSubscriptionInfo. Since that is also cleaner code, I plan to leave this "workaround" no matter what you do in the backend.

Still worth following up to see if you did break something unintentionally...

**Comment by amaltaro** [comment]
Yes, the idea was to indeed call the workload setSubscriptionInformation method only once, since this is an assignment configuration:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/WMWorkload.py#L1773

As you said, using a single call works for T0 and it's cleaner. So I think this issue can be actually closed(?)

**Comment by hufnagel** [comment]
So this change was intentional ? Tier0 doesn't use it as an assignment configuration, we set this ourselves right after creation. And two separate calls worked with 1.1.4, they don't work with 1.1.6.

**Comment by amaltaro** [comment]
I mean, it was intentional that we should call setSubscriptions only once. About the MSS ignored subscription, that is not true and it does not happen. It only happened in your environment because you were calling it > 1 times.

It worked in 114 because this change was added for 116, in this PR:
https://github.com/dmwm/WMCore/pull/8021

where one can see that the updateSubscriptions method was removed.
Anyways, isn't the "issue" fixed and understood?

**Comment by hufnagel** [comment]
Ok, I can see it. So the change was intentional. Any particular reason why ? Not complaining, just trying to understand. And yes, with that (pending maybe a bit more information for my curiosity) his issue can be closed.

Also, FYI, as-is Tier0 will never be able to set subscriptions during assignment since your assignment call can only handle simplified subscriptions that don't need all the parameters of the underlying WMWorkload and WMTask setSubscriptionInformation methods (which the Tier0 relies on). Again, not a complaint, just to keep in mind if that code is ever touched again.

**Comment by amaltaro** [comment]
I think this change was driven by limitations of automatic subscriptions to StepChain requests (which comes from the task/node structure and possibly duplicate output modules). In addition to that, it also comes from the create/assignment arguments separation and a better validation of parameters provided at each of those actions.

Yes, I know there isn't much of an "assignment" definition in T0 land. I just want to avoid having legacy code around that in the end just makes our life harder :)

**Comment by hufnagel** [comment]
Ok, I think that answers my question. Closing the issue.
