### ISSUE TITLE
Injection in DBS is particularily slow

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8297]
over the last few days, there has been numerous workflows in completed with missing files in DBS.
related to #8148 but not only. there appears to be some severe delays in getting files registered, holding up workflows of high priority.

**Comment by vlimant** [comment]
pdmvserv_task_HIG-RunIISummer15wmLHEGS-01262__v1_T_170906_162107_4411
pdmvserv_task_HIG-PhaseIITDRFall17wmLHEGS-00015__v1_T_171010_201726_6880
pdmvserv_task_HIG-PhaseIITDRFall17wmLHEGS-00013__v1_T_171010_201709_6648
pdmvserv_task_SUS-PhaseIITDRFall17wmLHEGS-00001__v1_T_171009_161734_6361
at the moment, the list was longer at the beginning of the week

**Comment by vlimant** [comment]
note the PhaseIITDR

**Comment by ticoann** [comment]
I haven't found any errors in DBS3Upload. It seems it is still inserting the blocks on those workflows.

2017-11-03 13:51:07,594:140163629393664:INFO:DBSUploadPoller:About to insert block /ChargedHiggs_HplusTB_HplusToTauNu_IntermediateMassNoNeutral_M-200_13TeV_amcatnlo_pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM#2aa58202-bf03-11e7-abc1-02163e018570

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/reqmgr2/fetch?rid=pdmvserv_task_HIG-PhaseIITDRFall17wmLHEGS-00013__v1_T_171010_201709_6648 

force-complete: 2017-11-01 09:02:07 UTC
completed: 2017-11-01 09:06:35 UTC

and still missing 2 files in DBS holding it up for the Upgrade group.

**Comment by amaltaro** [comment]
I started checking this workflow
pdmvserv_task_HIG-PhaseIITDRFall17wmLHEGS-00013__v1_T_171010_201709_6648

which had an inconsistency in dbs/phedex because the workflow was force-completed and the agent hit a race condition where jobs were still getting created/submitted. I have just removed a condor job for HIG-PhaseIITDRFall17MiniAOD-00026_0 (that was pending > 2 days now) and force completed the workflow in the agent.

I still see this block open:
/GluGlu_HToMuMu_M125_14TeV_powheg_pythia8/PhaseIITDRFall17MiniAOD-PU200_93X_upgrade2023_realistic_v2-v1/MINIAODSIM#f423df82-c153-11e7-abc1-02163e018570

with this file in it:
/store/mc/PhaseIITDRFall17MiniAOD/GluGlu_HToMuMu_M125_14TeV_powheg_pythia8/MINIAODSIM/PU200_93X_upgrade2023_realistic_v2-v1/30000/D85DBD3D-51C1-E711-9547-7CD30AD0A1F8.root

**Comment by amaltaro** [comment]
A new issue has been created: https://github.com/dmwm/WMCore/issues/8300

and the file mentioned above should have been injected to DBS already. Jean-Roch, can you please x-check and close it if everything looks fine now? Thanks
