### ISSUE TITLE
Define a timeout for Merge jobs creation

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8326]
As discussed in yesterday's O&C session, we should add a hard timeout to merge jobs creation (maybe 7 or 10 days) such that unmerged files never reach a 14 days lifetime.

I don't see any problems for the Parentless algorithm, but it might cause side effects on WMBSMerge when we have an EventBased job splitting and we try to assemble events from the same run/lumi... any thoughts?

**Comment by hufnagel** [comment]
Yeah, you can't do that for WMBSMerge. But then, we aren't actually using WMBSMerge anywhere, are we ?

**Comment by amaltaro** [comment]
It's almost never used, though there are a case here and there that sometimes require EventBased splitting for Processing tasks (maybe run dependent MC?)

**Comment by hufnagel** [comment]
Ok, for these cases I don't think we can do anything. You can't merge incomplete lumis. These cases would need to be covered by the also discussed increase in the unmerged space cleanup delay.

**Comment by vlimant** [comment]
The regular merging is not at all a problem here, as was explained at length in many places.
The scenario that we encounter weekly now is the follow. A workflow runs for n>2 weeks with several jobs reading unmerged files (reco jobs from NOT merged digi files, because the digi is not kept in output) failing because of something we will be able to recover (memory, job length, site setting, ...) OR a robust merge issue sends the unmerged file directly in the ACDC doc. For those two cases, which are the primary source of issue with unmerged files being deleted by sites contrary to the recommended policy, the workflow will be doomed to be clone (or extension).

**Comment by ericvaandering** [comment]
I've also argued for years that ACDC is fundamentally mis-designed. Relying on merge files still being somewhere in temporary storage is a mis-design. 

If I were designing ACDC's today, I'd have a list of work needed for each output that that step knew about. Preceding steps would be the union of the work needed for their children. You wouldn't rely on any input that wasn't registered in DBS.
