### ISSUE TITLE
TotalInputEvents not totally accurate

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8376]
looking at 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_RVCMSSW_10_0_0_pre1RunJetHT2016H_nanoinput__test_RelVal_nanoin_jetHT2016H_171130_172549_5546

  "TotalInputEvents": 109302, 

114697 were created in /JetHT/CMSSW_10_0_0_pre1-94X_dataRun2_relval_v5_test_RelVal_nanoin_jetHT2016H-v1/NANOAOD without duplicates.

looks to me there is a mis-handling of the lumilist mask in calculating TotalInputEvents

**Comment by ticoann** [comment]
This was impossible to calculate correctly. since dbs didn't contains each events per lumi and file.
We just estimated the all the lumis have the same number of events with in the file. In case some lumis in the file has different event number then others the number will be slightly off.
Now we are putting that information on DBS there are some data we can calculate accurately, (Since June 2017 and which also uses specific CMSSW (9_X_X or something?). 
I mean some data we could calculate this correctly but some datasets are not. (Only happens lumi mask is set)
Do you still want me to fix this problem with this limitation?

**Comment by ticoann** [comment]
Just for me to remember

Fix will be filtering exact matching events with the corresponding lumis from this call.

https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filelumis?logical_file_name=/store/mc/PhaseIITDRFall17wmLHEGS/TTGamma_SingleLeptFromTbar_TuneCUETP8M1_14TeV-madgraph-pythia8/GEN-SIM/1core5k_93X_upgrade2023_realistic_v2_ext1-v3/40000/E61A3274-21DA-E711-B8BF-5065F381A251.root

In WMCore/WorkQueue/Policy/Start/StartPolicyInterface.  getMaskedBlock method

**Comment by ericvaandering** [comment]
What's the field used for? If nothing, maybe it could be named "estimated" for cases where it can't be calculated correctly.

Seangchan, do you know (not suggesting a partial solution here) if the calculation assumes all lumis in the dataset are the same or all lumis in a FILE are the same?

**Comment by ticoann** [comment]
Not directly in WMAgent, I can change the name. I am not sure how this is used in Unified. Jean-Roch, could you comment on that?

**Comment by vlimant** [comment]
it can stay inaccurate as it is. I understand the lumitation from the lumimask now. it's only used in prodmon monitoring (not in unified)
