### ISSUE TITLE
Jobcooloff as final status?

### ISSUE THREAD

**Issue by prozober** [dmwm/WMCore#8385]
Regarding https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160
I was taking a look at the failures it got https://cmsweb.cern.ch/wmstatsserver/data/jobdetail/fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160

I noticed that it has several jobs in "jobcooloff" status, but the workflow already finished running, even I created a couple of ACDCs for the "failed" tasks.
The problem is I cannot create ACDCs for tasks in "cooloff".
Could you please take a look? @ticoann @vlimant 

related #8168

**Comment by ticoann** [comment]
@prozober, Paola, jobcooloff state is not the final state.  Actually those jobs are all killed and currently in clean up state.

It seems it missed couch update on that time to wmstats - this could happen and we don't have mechanism to automatically recover.

One weird thing is there is transition for jobfailed - jobcool off in couch db. (I am suspecting there is either race condition for updating couch or mixed with some id collision - see below)

However it is actually in failed jobs, there shouldn't be a problem creating ACDC.

I will investigate jobfailed -> jobcooloff transition.
```
in vocms0255
wmbs job id: 1512849030 job name 4c173f3c-dd0a-11e7-b15a-02163e01c3a1-0

Sat, 09 Dec 2017 17:56:35 GMT new -> created
Sat, 09 Dec 2017 18:50:24 GMT created -> executing (T2_IT_Legnaro)
Sat, 09 Dec 2017 19:05:13 GMT executing -> complete
Sat, 09 Dec 2017 19:08:41 GMT complete -> jobfailed
Sat, 09 Dec 2017 19:09:54 GMT jobfailed -> jobcooloff
Sat, 09 Dec 2017 19:10:27 GMT jobcooloff -> created
Sat, 09 Dec 2017 19:20:35 GMT created -> executing (T2_IT_Legnaro)
Sat, 09 Dec 2017 19:46:48 GMT executing -> complete
Sat, 09 Dec 2017 19:49:40 GMT complete -> jobfailed
Sat, 09 Dec 2017 19:50:30 GMT jobfailed -> jobcooloff
Sat, 09 Dec 2017 21:15:06 GMT jobcooloff -> created
Sun, 10 Dec 2017 10:51:52 GMT created -> killed
Sun, 10 Dec 2017 10:52:52 GMT exhausted -> cleanout


wmbs JobID - 1250044, job name 4a334762-dd12-11e7-b15a-02163e01c3a1-0
State Transitions:
Sat, 09 Dec 2017 18:53:48 GMT new -> created
Sat, 09 Dec 2017 19:20:35 GMT created -> executing (T2_IT_Legnaro)
Sat, 09 Dec 2017 19:46:48 GMT executing -> complete
Sat, 09 Dec 2017 19:49:40 GMT complete -> jobfailed
Sat, 09 Dec 2017 19:50:31 GMT jobfailed -> jobcooloff
Sat, 09 Dec 2017 19:50:40 GMT jobcooloff -> created
Sat, 09 Dec 2017 20:13:56 GMT created -> executing (T2_IT_Legnaro)
Sun, 10 Dec 2017 10:51:51 GMT executing -> killed
Sun, 10 Dec 2017 10:52:52 GMT exhausted -> cleanout
```

**Comment by prozober** [comment]
Hi @ticoann, we are having problems creating ACDCs because the documents are not there.
https://cmsweb.cern.ch/couchdb/acdcserver/_design/ACDC/_view/byCollectionName?key=%22fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160%22&include_docs=true&reduce=false

As you can see there are documents for
- DataProcessing
- DataProcessing/DataProcessingMergeALCARECOStreamHcalCalIterativePhiSym

but we are missing
- DataProcessing/DataProcessingMergeAODoutput
- DataProcessing/DataProcessingMergeMINIAODoutput

**Comment by ticoann** [comment]
@prozober, Hi Paola, Now I understand what is going on. The workflow is force-completed.

https://cmsweb.cern.ch/reqmgr2/fetch?rid=fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160

which kills any none finished jobs except log collect/clean up jobs. We don't create acdc record for killed jobs currently (If I recall correctly, I think we removed that some long time ago due to creating too many unnecessary ACDCs especially  when jobs gets aborted.

I was wondering whether this was normal procedure. (force-complete job and create a ACDC for remaining jobs).
To have complete set of ACDC, it seems workflow has to be going through without force-complete.
If that is the case we have to change the code to handle that but also prevent from creating unnecessary ACDC entries.

To create ACDC we have to manually put missing entries. I am not sure how many jobs are in that condition. I can try to create the script to do that. But it might be better to clone and return the whole workflow.  Just let me know.

**Comment by vlimant** [comment]
a clarification please @ticoann , setting force complete will NOT remove already existing ACDC documents for that workflow and will just not create any new document for the work that was forced, correct ?

**Comment by vlimant** [comment]
so indeed, since these were in transition phase, there won't be any ACDC for DataProcessingMergeAODoutput and DataProcessingMergeMINIAODoutput @prozober .
I wondered why these error show up in the report https://vocms049.cern.ch/unified/report/fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160 and that's because they do show up in this url http://cmsweb.cern.ch/wmstatsserver/data/jobdetail/fabozzi_Run2017B-v1-DoubleEG-17Nov2017_940_171124_165655_3160 that has still trace of cooloffs. How do we get that "jobdetail" information cleaned-up ?

**Comment by ticoann** [comment]
> a clarification please @ticoann , setting force complete will NOT remove already existing ACDC documents for that workflow and will just not create any new document for the work that was forced, correct ?

Yes it won't remove existing ACDC document but it won't create the new document for the killed jobs.

It seems killed status is not propagated to wmstats as failed job. Which probably is not desired behavior. I will take a look whether we should push the killed status to wmstats.

If force-complete and creating ACDC is a normal operation, we can also consider putting killed job in ACDC as well. - I have to investigate.

**Comment by vlimant** [comment]
@ticoann yes, we'd like to be able to force-complete and run ACDC with what is there prior to doing anything else. we need this understood and corrected.

I note that we could be doing what I had asked some time ago "create ACDC document with all killed/removed jobs when force-completing" ; this would be a great asset operationally, so please consider re-prioritizing this

**Comment by ticoann** [comment]
@vlimant,  Unless jobs are created first then failed/created, ACDC recover those (not created jobs).
It sounds like you want to make faster procedure for those workflows but don't want to actually submit and run the jobs, is it correct?
I am not sure how to add this in current system. As I mentioned in #8186
1. set the force-fail status
2. In that case, make the priority highest and so it can be pulled to agent then create jobs. 
   (We have to check all the job is created)
3. then fail those jobs so ACDC can be picked up (ACDC will not pick up the jobs if it is not submitted, so we have to do something unless we submit jobs and fail - which I don't think we should do)

Basically, I cannot think of any clean/acceptable solution at this moment.
As far as your other suggestion, what do mean by killed/removed jobs, are you talking about the jobs not in ACDC? In that case, we will have the similar problem of above we don't have any information if job is not created yet and removed.

Could you explain what problem you want to solve by this? I am guessing
1. You want to keep successful jobs for workflow
2. However, something went wrong, it will be too mush waste of time if we wait until all the jobs created and failed, hence ACDC can be created after that.

If that is the right guess,  could you give me some examples of that. I mean what specific problems requires this kind of solution.

**Comment by vlimant** [comment]
For data reprocessing, ops is now force-completing at 95% or so, ACDC whatever is there, then recovery. But the recovery is very expensive in CPU usage. Hence the need for having all work not done go in the ACDC, so that we can work with that ACDC. 
Please propose a manageable alternative.
There is an alternative that requires development outside of wmcore (essentially reworking the recoverMissingLumi to be less expensive on grid time), and if you prefer developing that one, this would be fine with me

**Comment by ticoann** [comment]
> For data reprocessing, ops is now force-completing at 95% or so, ACDC whatever is there, then recovery. But the recovery is very expensive in CPU usage. Hence the need for having all work not done go in the ACDC, so that we can work with that ACDC.

It seems you need to get 100% of workflow but last 5% is not processing soon enough and you need to speed up that 5%? I wonder what is the situation when force fail will be used (if it is implemented)  used. Do you need to twig anything when you create the ACDC?

I am not sure what will be the advantage doing let workflow completed and create the ACDC vs force fail and create the ACDC. If ACDC is failed recovery is needed in both cases, right?

**Comment by amaltaro** [comment]
Discussion has deviated from the original issue reported. Closing it.
