### ISSUE TITLE
Include basic debugging information in the cmsRun stdout

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8423]
Hostname
dump of environment variables
dump of job classad

**Comment by ticoann** [comment]
I assume this is only for the job which is failed, right?
Shouldn't this be propagated to some where, wmstats?

**Comment by bbockelm** [comment]
I think this should be done for all jobs.

Given that logfiles are often the reference point for debugging -- and it's often difficult to correlate logs and external systems -- it would be fairly high value to get most of the debugging information in one place.

Think of it as a denormalized database table...

**Comment by amaltaro** [comment]
In order to avoid duplicate information in different log files, perhaps we could add the _condor wrapper logs and the scramOutput into the cmsRun logArchive logs. I know the _condor logs aren't complete/finished by there, but they would contain all the information mentioned above (+ stageout information).

**Comment by amaltaro** [comment]
@ticoann I'm owning this issue and you take the other one :)
