### ISSUE TITLE
DrainStatusPoller fails to query the schedd when the agent is empty

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8427]
Scarlet noticed that there are errors (apparently on the CERN agent only) in the AgentStatusWatcher logs (DrainStatusPoller thread) when the agent is running but there is actually no work on going and nothing in condor. See part of the log from vocms0255.
```
2018-01-29 13:41:17,442:139865845200640:INFO:DrainStatusPoller:Checking agent drain status...
2018-01-29 13:41:17,459:139865845200640:ERROR:PyCondorAPI:Condor failed to fetch schedd constraints for: JobStatus==1Error message: Failed to fetch ads from schedd.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Services/PyCondor/PyCondorAPI.py", line 31, in getCondorJobs
    jobs = self.schedd.query(constraint, attr_list)
IOError: Failed to fetch ads from schedd.
2018-01-29 13:41:17,460:139865845200640:ERROR:PyCondorAPI:Condor failed to fetch schedd constraints for: JobStatus==2Error message: Failed to fetch ads from schedd.
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.1.8.patch3/sw/slc7_amd64_gcc630/cms/wmagent/1.1.8.patch3/lib/python2.7/site-packages/WMCore/Services/PyCondor/PyCondorAPI.py", line 31, in getCondorJobs
    jobs = self.schedd.query(constraint, attr_list)
IOError: Failed to fetch ads from schedd.
2018-01-29 13:41:17,460:139865845200640:INFO:DrainStatusPoller:Finished collecting agent drain status.
```

**Comment by bbockelm** [comment]
Are you sure that's "real" and not just a transient issue?

There were problems pool-wide over the last week (and not necessarily related to the number of running jobs), including a restart.  That would be what I would expect in terms of error messages if you queried during a restart.

**Comment by amaltaro** [comment]
That's what I thought too, however looking at the log file, I see it repeatedly happening
`2018-01-31 01:50:23,712:139865845200640:ERROR:PyCondorAPI:Condor failed to fetch schedd constraints for: JobStatus==2Error message: Failed to fetch ads from schedd.`

Still weird why it doesn't happen with FNAL submit4...

**Comment by scarletnorberg** [comment]
Yes. I was going to say that 255 still seems to be in the same state condor running (unknown (schedd query error)) and condor idle (unknown (schedd query error)) where submit4 is fine. Even if someone had restarted it seems to be going back to this state.

**Comment by goughes** [comment]
Here's where the query stops working from the AgentStatusWatcher log:
`2018-01-25 13:30:56,176:139865845200640:INFO:DrainStatusPoller:Drain stats: {'upload_status':{'dbs_notuploaded': 0, 'dbs_open_blocks': 0, 'phedex_notuploaded': 0}, 'workflows_completed': True, 'condor_status': {'idle': 0, 'running': 0}}`

`2018-01-26 01:31:58,925:139865845200640:INFO:DrainStatusPoller:Drain stats: {'upload_status': {'dbs_notuploaded': 0, 'dbs_open_blocks': 0, 'phedex_notuploaded': 0}, 'workflows_completed': True, 'condor_status': {'idle': 'unknown (schedd query error)', 'running': 'unknown (schedd query error)'}}`

And right in between we see from the condor logs that the schedd restarts between those two drain status runs:
`01/25/18 19:20:19 (pid:14721) Got SIGQUIT.  Performing fast shutdown.`
\<snip\>
`01/25/18 19:20:21 (pid:1921887) ** condor_schedd (CONDOR_SCHEDD) STARTING UP`

I'll make a patch to make sure we are querying the current schedd, instead of whatever schedd was around when the drain thread started.

**Comment by amaltaro** [comment]
Does it mean we need to create a new schedd instance
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/PyCondor/PyCondorAPI.py#L20

after every schedd restart?

**Comment by goughes** [comment]
PR #8446 might do the trick.  I can't test though because I am unable to restart condor on my test agent.  I would need sudo access to systemctl.

**Comment by bbockelm** [comment]
I wouldn't suggest recreating the schedd object each API call -- better to reuse it if possible.

I'd suggest:
1.  Have the `PyCondorAPI` recreate the schedd object on error.
2.  Have users of `PyCondorAPI` recreate the `PyCondorAPI` object on error.
3.  Simply regenerate some of these cached objects every time a poll occurs or algorithm runs. 
 For example, here: https://github.com/dmwm/WMCore/blob/3ded0969545c1a0f82425cb57dfd3e0cce0fd901/src/python/WMComponent/AgentStatusWatcher/DrainStatusPoller.py#L32 would be a good place to recreate the `drainAPI` object.

**Comment by goughes** [comment]
Cool, thanks Brian! I'll do another PR based off your suggestions.

**Comment by ticoann** [comment]
> Have the PyCondorAPI recreate the schedd object on error.

I would vote for this solution.  So whoever uses api doesn't have to deal with it explicitly.
Maybe using retry decorator (?) https://pypi.python.org/pypi/retrying (We already have this package in wmagent rpm).

**Comment by ticoann** [comment]
fixed
