### ISSUE TITLE
Adjusting the pending/running threshold via central configuration

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8428]
@amaltaro @ticoann is there a way to update the pending threshold via the agent configuration in couchdb ?

which is better to increase job pressure ? increase the threshold or put a new agent in production ?

**Comment by amaltaro** [comment]
It's in our plans, but there is no central location yet.

About the global pool pressure, I'd actually bump the agent thresholds instead of adding a new one.
I see an average of 40k pending jobs in each agent, last time we discussed we said the ideal'ish number would be around 55k. We (someone has to change) can try that number and see if it improves.

**Comment by aperezca** [comment]
Once more we'd much rather go in the direction of using more agents. Each schedd has a limited number of maximum running and pending jobs for a number of reasons (max number of shadows, autoclusters, max allowed negotiation time per schedd, etc). There's no point in continuously trying to get the last few % out of each one, when we can easily expand horizontally.

**Comment by amaltaro** [comment]
Antonio, this is certainly not an issue here. We're talking about 4 agents running 40k jobs only (out of ~90k). Their pending could go as high as ~4*75k, thus 300k pending jobs, and we're approaching around 210k now and going down.
That's why I think there is no need for another agent and, it's actually not the best choice if we want to make sure priorities are always obeyed.

**Comment by vlimant** [comment]
@amaltaro OK for having the thresholds adjustable via couchdb.
pressure just solved itself with several high priority workflows coming in multi-core. 

@aperezca an answer to https://cms-logbook.cern.ch/elog/GlideInWMS/5964 would be much appreciated. I'll put something in unified to adjust thresholds once we know where they have to be.

**Comment by aperezca** [comment]
Alan, we want to keep schedds in the "comfort zone", not stressed, as much as possible from the SI point of view. Right now I see you are using at least 6 agents (including one at FNAL, there are two more empty), and a few more available. Why not keep it like that? The more stuff you stack on a single schedd, the more likely it is that it will get dropped in the negotiation, so that's what would definitely affect prioritization.

JR, answer is on the way, I'm writing in parallel

**Comment by vlimant** [comment]
@aperezca you would have to define what "comfort zone" is other than "put as many schedd as you have in hand", with numbers and all.

**Comment by aperezca** [comment]
Certainly. That's however a multivariate analysis on the status and performance of the pool we have not yet done. Manpower and priorities, like everything else. 

For the time being, as a guiding rule, I'd just keep sufficient agents to avoid them running into the warning or critical status, as defined in 
/etc/condor/config.d/95_cms_daemon_monitoring.config, 
something that regularly happens with production schedds. 

Additionally, not seeing production schedds in this list would be a good indicator:
http://submit-3.t2.ucsd.edu/CSstoragePath/aperez/HTML/globalpool_dropped_schedds.txt

**Comment by vlimant** [comment]
sigh ...
it was said that the warning/critical status has little to do with the schedd actually not getting to match, all the values defining the warning are hand made and not representative as far as I am concerned ; best way to avoid getting into the warning is to increase the threshold for getting into the warning. So let's have the exact reason and let's work on this, otherwise we just waste time we don't have, as you said.

As for your list, if there is no indicator of why the schedd ends in the list, there is no way to have it out, except by actually not adding it to the list.

status-quo until we know of an exact targetted operating point.

**Comment by bbockelm** [comment]
The warning / critical status there was carefully tuned to indicate the level of stress being put on the system, particularly in terms of auto-clusters.  It does not indicate that the schedd is non-functional (same way that monitoring alarms for disk space usage should go off at 80% full, not 100%!).

As usual, note that the *number* of idle jobs is almost irrelevant (especially beyond, say, a thousand idle jobs) to grid-style workflows (bursting into 100k brand-new cores is a different matter).  What's more relevant is:

* How complex is the matchmaking?
* Are there enough jobs for each *site*?

Unless the pending thresholds per site are under 1,000 jobs, I don't see it as a worthy tunable.

**Comment by aperezca** [comment]
JR, schedds in that list were dropped by the negotiators because they were dragging them. So they will not achieve matchmaking for their jobs at least for another cycle, that's it. 

More autoclusters per schedd-> longer negotiation ->increased chances of being dropped. So the warning/critical status is relevant in that case

**Comment by amaltaro** [comment]
Is it still desired? If so, we'll push it to the agent configuration in central couch, meaning we would have to update the thresholds in every single agent.
