### ISSUE TITLE
Access to production logs (both condor and cmsRun)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8442]
More or less on the same line as https://github.com/dmwm/WMCore/issues/7224,
but creating a new issue with new ideas that came up yesterday (there seems to be some details still to be sorted).

In short, every single production job would copy the logArchive tarball to both the site's /store/unmerged area AND to a CERN EOS space behind a web server.

The working items Seangchan and I came up with are:
1) rename the logArchive tarballs to something like (that will guarantee a unique id):
agentName-wmbsid-siteName-date.tar.gz
2) we need to change the LogArchive step to stage out to this EOS space (do we fail the job if it fails?)
3) we need to make sure the correct data structure is properly created, e.g.:
workflowName/taskName/mergeTaskName/taskName/etc
4) update the log URL to dashboard (or monit, for ALL jobs) and to wmstats (for failed jobs only)
5) Brian is contacting CERN IT to get us this storage space
6) cleanup policy, but I'd call it a last item here (maybe anything older than 30 days)

FYI @ticoann @bbockelm @vlimant

**Comment by ticoann** [comment]
Hi Alan, thanks for creating the issue. A couple of comment on the plan.
What will be the advantage and disadvantage for transferring log archive from WorkerNode vs from WMAgent?
Also we shouldn't fail the job if transferring the logArchive to EOS fails. (I don't think we even don't fail the job if the log archive fails)

**Comment by bbockelm** [comment]
I think the advantage of doing it from the worker node is it keeps complexity and load off the agent itself: a daemon would have to run on the agent and launch many file copies and keep state.  Additionally, if done in the HTCondor job, we can record the EOS URL in the job ad itself -- meaning it automatically gets to Kibana.  The downside of doing it on the worker node is there's less opportunity for later retries.

I don't think this should fail the job.

**Comment by hufnagel** [comment]
If you don't fail a job on "copy to EOS", you need to be able to monitor this in some other way.  Otherwise you could just mass fail these things without noticing for a while.

**Comment by bbockelm** [comment]
@hufnagel - As this is the mechanism to get the logfiles to operators, I hope it is somewhat self-monitored...

**Comment by hufnagel** [comment]
True. But my question is: is an operator not finding the logs he is looking for not too late ?

I mean, you only monitor this by searching for logs you want to look at, right ?

**Comment by amaltaro** [comment]
We actually have this behavior already - since we added multi stage out to CASTOR and CERN EOS - and I haven't ever heard a complaint about logs not accessible in the EOS area.
I explicitly asked that question just to make people aware that logs might be missing, of course not all of them.

I think checking the presence of those logs during a new WMAgent release validation is good enough.

**Comment by hufnagel** [comment]
True, logCollect stageout only checks the Castor stageout, it ignores failures on the EOS stageout.

**Comment by bbockelm** [comment]
Yeah - I don't think it's too late.  Right now, they manage to work around the fact we have no logs from any FNAL agent -- so random failures shouldn't be too bad.

The problem becomes when there's a bias in the failures - in that case, operators will have to dig in.

**Comment by DAMason** [comment]
Just to understand -- we've been staging logs to unmerged at each site for years, and then we have these log archive jobs which tar up a bunch of them and already ship them to CERN after some period of time.  Not 100% sure, but assume there is a cleanup job after the log archiving that then removes the original unmerged tarballs -- maybe at workflow closeout?  Here we're saying the job not only stages out to the site unmerged area, but additionally to some CERN EOS location so that a CERN based web thingy can serve them up to operators.  Certainly better than the current ssh based hackery -- begs a few more questions though:

1.  Existing log archive (assuming it still is) infrastructure/jobs stays in place, or this replaces it?  Or?
2. Adding dependence on being able to xrdcp to CERN at any given time -- would it be worth asking for a simple "xrdcp back to CERN" SAM test (even noncritical) so as to have something ops can check against if they aren't finding their logs?
3. Making the xrootd URL of the original site (assuming both local site and CERN still happens) staged out xrootd URL easily found (it has though been given in the limited wmstats failure summaries) as a backup for the CERN log stageout failing?  BTW never really having that xrootd URL easy to get a hold of is the root of this whole problem/discussion...
4.  Need to worry about knocking over CERN EOS if we have some other global failure?  like frontier or more likely large request misconfig, etc?  Have we hit CERN with the world all trying to xrdcp at once before?  Would we block T0 stageouts if something like this happens?
5.  At one point we were only keeping logs of failures?  Is that the case now?  Often having a successful job to look at helps in debugging.

Would be interesting to see when we start breaking CERN EOS FUSE as this archive grows.  Glad its happening there.

**Comment by ticoann** [comment]
fixed by #8456

**Comment by amaltaro** [comment]
Wooohoooo!!!!!

**Comment by ticoann** [comment]
If we don't clean up,  we will have a problem. 😄

**Comment by vlimant** [comment]
the "year of the log" ; champagne all around !
