### ISSUE TITLE
Migrate machine tools to port 8443

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#8565]
We need to identify machine tools which access cmsweb and start switching them to use port 8443 to access cmsweb.

**Comment by vkuznet** [comment]
Is there any progress on this?

**Comment by amaltaro** [comment]
I started working on this, but then it came to my mind.. can you clarify again why we need to change this everywhere in our software? Is it to distinguish between end users and CMS services accessing cmsweb services?

Can't we use something else from the logs in order to find that out? Maybe the DN or agent-user?  What happens when we move the cmsweb infra to a CERN-IT managed system (kubernetes, etc), do we need to switch it back to 443?
