### ISSUE TITLE
ErrorHandler very high memory footprint while creating ACDCs

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8614]
vocms0255 was going from 0 to 20GB within 20min or so.

The problem seems to be coming from this query 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Jobs/LoadForErrorHandler.py#L43

when there are several MCFake file jobs to be handled (generating > 100k run/lumi maps).
Apparently we get the run/lumi map for unique fileids, but if we have 100 of them in the same binds, it might take all the memory...

**Comment by amaltaro** [comment]
We've mapped most of high memory footprint (and slowness) to this method:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/MySQL/Jobs/LoadForErrorHandler.py#L47

where 157k run/lumi maps (for the same file, e.g. 199892) explodes to ~500MB of RSS memory.

I'm looking into that method to see what can be done to decrease it.

**Comment by amaltaro** [comment]
Apparently 0256 has hit the same issue, I'm decreasing it to 10 jobs per iteration.

**Comment by amaltaro** [comment]
Seangchan, I did some further investigation and comparison of the patched x non-patched component. Results are indeed the same and we should be safe :-)

On the other hand, I noticed this method (and/or the DAO):
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L351

are adding the whole Run object in the Job object. So if I print the job dict here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L196

I see something like this (truncated):
```
{'id': 469L,
 'input_files': [{'checksums': {},
                  'lfn': 'MCFakeFile-amaltaro_MonteCarlo_LHE_Agent1114_Validation_180711_130640_7340-Production-d1eb5b8a1994a5ee0cac6e89f9d32357',
                  'runs': set([<WMCore.DataStructs.Run.Run object at 0x7f466fc39410>]),
```

then expanding these Run objects like
```
            for run in job['input_files'][0]['runs']:
                logging.info("AMR run: %s", run.json())
```

I get ALL the run/lumi/events (events is None, usually) present in that input file. Even if we don't load run/lumis multiple times for the same file inside the DAO, somewhere we set `runs` for a job which basically contains the whole thing.

BTW, these observations are with your patch in.

**Comment by ticoann** [comment]
Thank you very much for double checking Alan. 

> I get ALL the run/lumi/events (events is None, usually) present in that input file. Even if we don't load run/lumis multiple times for the same file inside the DAO, somewhere we set runs for a job which basically contains the whole thing.

Yes that is true, and that should be the same run object if the file ids are the same for the different jobs.

Masking actually happens a line below.

https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ErrorHandler/ErrorHandlerPoller.py#L197

Which calls here 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ACDC/DataCollectionService.py#L130

Then calls here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/ACDC/CouchFileset.py#L121

Then here,
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/DataStructs/Mask.py#L209

Which seems to create the new set not the modifying original object. (That was the case we were discussing yesterday).

My only concern was here.

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/DataStructs/Mask.py#L198

If the job contains empty mask it returns original run object, so potentially it can be modified later. But since masked job always has new instance. It should be fine.

If you thinks following line create new Run object, we are fine I think. But you think it is not the case. we need to make that return the new instance.

**Comment by amaltaro** [comment]
> Yes that is true, and that should be the same run object if the file ids are the same for the different jobs.

I forgot mentioning, it's not the same Run object, even though the input `lfn` is the same. I still didn't find where this `runs` is set, since the DAO queries/loads `newruns` only.

> My only concern was here.
> https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/DataStructs/Mask.py#L198
> If the job contains empty mask it returns original run object, so potentially it can be modified later. But since masked job always has new instance. It should be fine.

If I got your point, then the answer is above. Yes, there is a new Run object.

**Comment by amaltaro** [comment]
BTW, I'm missing something or doing the masking in the CouchFileset module is sort of bad?
