### ISSUE TITLE
Priority of subsequent jobs in task chains

### ISSUE THREAD

**Issue by vlimant** [dmwm/WMCore#8660]
how complicated would it be to have a mechanism that make a +=(N-1)*1000 priority on the job of task_N of a task chain, with respect to the workflow priority ?
trying to avoid having tasks competing for resource.
(on a suggestion from Tom)

**Comment by amaltaro** [comment]
I'd say it's somehow complicated to make it. RequestPriority is a workflow attribute, so this would be the first inconsistency. Then on the agent side, it doesn't know what is Task1 or Task3, it only knows that a TaskN is used as input for TaskM and so forth.

**Comment by bbockelm** [comment]
We already use the `PostJobPrio` attributes to sort later tasks in a chain in front of earlier ones (@amaltaro - you can figure this out by parsing the sub-task name).

I would worry about doing this within the job priority itself as that would affect the negotiation load.  The current scheme does effectively what Tom asks for within a task, but the sorting is only exposed inside the schedd.

**Comment by tommasoboccali** [comment]
I elaborate a bit on the idea.
Evidence is that users see a workflow as "done" only when MINI are done.
if we have today 20 WFs at the same Prio, if one of them is shorter (*), when it is done the jobs producing MINI will compete with the jobs producing AOD from the other WFs (which are usually many more / longer). To the users, it seems nothing is being produced.
If instead the AOD->MINI would have a +1 in the prio, it would be scheduled in a prioritized way wrt and go "before" the jobs producing AOD.
To the user, a MINI appears!

possible (good) side effects: if RECO is scheduled a little higher than DIGI, that would limit the lifetime of GEN-SIM-RAW on disk, hence unmerged space. The same applies to WFs which do not need to save the AOD permanently: the AOD could be deleted as soon as the MINI are done, block by block




*:
it can apply also to different blocks inside the same WF

**Comment by bbockelm** [comment]
Well, I don't see any jobs from that particular prep ID in HTCondor right now.  It might be plausible to do something internal to the agent to get the jobs into HTCondor faster.

@amaltaro ?

**Comment by tommasoboccali** [comment]
this got solved yesterday / today, but was reported to stay with 4M AOD  / 0 MINI for quite some time.

**Comment by amaltaro** [comment]
> producing AOD from the other WFs (which are usually many more / longer). To the users, it seems nothing is being produced.

are we keeping AOD output for such workflows? IMO users should be aware that 1 AOD file doesn't map to 1 MINIAOD file, especially because MINIAOD usually has a job splitting much larger than AOD, so there is the need to have several AOD files in order to create a MINIAOD job. 
Output monitoring would be more precise if it was considering all outputs as well, instead of the last one only (especially in a 7-tasks workflow).

Brian makes a valid point too, if we slightly bump their priority, this will increase the number of autocluster by a factor of ~5 or so, which will cause scalability issues to the SI layer.

> If we have 20 workflows today at the same priority, internal to the agent, the jobs are sorted by:
>     When the workflow was injected (oldest first).
>    The task in the chain (later tasks first)
>     A bunch of other attributes.

For jobs in condor, yes, that's true. For jobs in the JobSubmitter cache, it's solely driven by the final job priority:
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/JobSubmitter/JobSubmitterPoller.py#L618

FIFO. However, we might use the same mechanism used by the `PostJobPrio` which uses the `task_id` to give a internal-boost in priority. This task_id is the id record in the local database, later tasks usually have a greater number.

Just a final comment, those workflows apparently stuck in AOD could have had different tasks jobs really competing for resources, or of course something higher priority taking them. Do we know? Do we know for how long there was a MINIAOD plateau?
