### ISSUE TITLE
Debug LogCollect jobs for Production jobs in CMS@Home

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8665]
e.g. ireid_MonteCarlo_eff2_IDR_CMS_Home_180626_171641_2516

**Comment by ticoann** [comment]
@amaltaro, Is this still a issue?

**Comment by amaltaro** [comment]
Yes, low prio though

**Comment by amaltaro** [comment]
Hmm, maybe it's related to the "locationless" lfns passed to that job (if you look at the job description at the top of wmagentJob.log log).

**Comment by hufnagel** [comment]
Ah, I think I know what's going on. The relevant part here is "===> Attempting Local Stage In". It seems the LogCollect implementation doesn't actually use the read rules defined in SITECONF. It instead used the stageout rules to *stage in* the input files to merge them locally.

Which obviously doesn't work for a site that has different read and stageout rules. We get away with it for true cpu-only sites since we never run any LogCollect jobs there.

**Comment by hufnagel** [comment]
Of the top of my hat I can't think of a way to fix this without fixing the hack in the LogCollect implementation and actually use the read rule instead of the stageout rule. But the read rule is just that, it's a read rule understood by the framework, not a 'how to copy this file' rule that is needed by LogCollect.

OTOH, the read rule might be good enough for an xrdcp, which should work. Maybe implement it as a site specific conditional for now to test it out and then think about how/if/when to switch all other LogCollect ?

**Comment by bbockelm** [comment]
This sounds vaguely familiar.

Isn't this what `edmCopyUtil` was supposed to avoid (https://github.com/dmwm/WMCore/issues/6740)?

**Comment by hufnagel** [comment]
Yes, that rings a bell. The use of edmCopyUtil was CMSSW version dependent though, right ? Maybe the CMS@Home workflow is too old ? If it isn't I am not sure why this is using stagein.

**Comment by bbockelm** [comment]
Yes, `edmCopyUtil` is only in CMSSW_8_0_x and later.  However, not clear why the workflow version has to match the LogCollect version?

**Comment by hufnagel** [comment]
Well, that would just follow naturally the CMSSW versions (and arch) we use for production. We could hardcode a single CMSSW and arch, but that eventually would get out of date.

How about adding a fallback to a modern CMSSW version if the CMSSW_8_X check fails ?

**Comment by hufnagel** [comment]
Although, presumably we should at least honor the scramArch (so we don't try to run the wrong platform edmCopyUtil). A mapping from scramArch to fallback CMSSW release would be good enough I guess.

**Comment by bbockelm** [comment]
I would be OK with a fallback version per scram_arch.

**Comment by hufnagel** [comment]
In practical terms we could even just restrict ourselves to the OS and cpu arch part of the scram arch, no reason to use the same compiler version (plus some scram archs we had CMSSW_7_X releases for we never did get any CMSSW_8_X or later releases). So basically

if cmssw < CMSSW_8_X and scram_arch = sl6_amd64_*:
  use CMSSW_8_0_0 and scram_arch sl6_amd64_slc6_amd64_gcc493

Anything non SL6 and AMD64 we would never run in production anyways.

We don't support sl5 scram archs anymore, do we ?

**Comment by bbockelm** [comment]
That looks good to me!  All _old_ CMSSW versions are only used on SL6 in production.  I would assume, as new arches are added, we won't backport them to pre-8.x!
