### ISSUE TITLE
Update url for /store/logs/prod/recent

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8711]
I just noticed the https url I've been using since day 0 (eoscmshttp...) is no longer working, e.g.:
https://eoscmshttp.cern.ch/eos/cms/store/logs/prod/recent/TESTBED/amaltaro_MonteCarloFromGEN_HG1808_Validation_180725_154304_9472/MonteCarloFromGEN/vocms0192.cern.ch-11822-0-log.tar.gz

while asking Daniel (VoC) to create a ticket for CERN IT, he has found this old snow ticket 
https://cern.service-now.com/service-portal/view-request.do?n=RQF0957020

which says the endpoint is actually "eoscmsweb.cern.ch", since March...

**Comment by amaltaro** [comment]
Ok, the situation isn't that bad since it doesn't touch reqmgr, it's all on the agent side.

**Comment by amaltaro** [comment]
Daniel asked them to re-enable that alias. So both url will work until the VoC ask CERN IT to disable eoscmshttp one. Anyways, the sooner we patch the agents the better.

**Comment by bbockelm** [comment]
Hi Alan,

Hold on, let's coordinate first - there's another SNOW ticket that just closed to remove the alias:

https://cern.service-now.com/service-portal/view-incident.do?n=INC1749765

We had Herve remove the alias because the X509 authentication was never setup correctly for `eoscmshttp` (hm - did we stageout via Xrootd?  It certainly shouldn't have worked for HTTP).

Brian

**Comment by amaltaro** [comment]
Yes, stage out is done via xrdcp.

**Comment by bbockelm** [comment]
Sigh.  Can you comment on that SNOW ticket then?

(But yes, let's change over agents ASAP...)
