### ISSUE TITLE
Clean up how the performance parameters are updated

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8735]
1. define what need to be hard coded. maxRSS, maxVSize
2. define what need to be configurable and updated SoftTimeout, etc
3. set the default value clearly 

related to discussion in https://github.com/dmwm/T0/issues/4458

**Comment by amaltaro** [comment]
I'm not sure there is anything to be done in here.
1. MaxRSS follows the Memory requirements (read hard-coded). Still, if someone wants to change the Memory requirements during assignment, it's allowed, which will also update MaxRSS.
1.a. MaxVSize has to be removed, but it's not a simple few lines code deletion...

2. SoftTimeout and GracePeriod have a **default** value at assignment (hard-coded during creation, but who cares, we can't run a workflow that doesn't get assigned :))
2.a. MAYBE, we could remove GracePeriod and keep only SoftTimeout and HardTimeout then? Since GracePeriod doesn't show anywhere but in the workload_cache couch doc, not in the workload spec.

3. They are in the assignment method, I don't think it can be more clear.

More input on the T0 ticket: https://github.com/dmwm/T0/issues/4458#issuecomment-411985167

**Comment by amaltaro** [comment]
Seangchan, it seems there was some confusion when this ticket was created. However, I think we can still work on something that this issue raises. Like, MaxVSize and possibly the GracePeriod time retirement.
Given that things work, we can as well just close it and don't touch on this code that is functional.

**Comment by amaltaro** [comment]
MaxVSize has been recently removed from the code. Grace period works and don't cause any issues, so I suggest to close this one in favor of better things to work on :)
