### ISSUE TITLE
Add Sanity check and more automation on production agent deployment.

### ISSUE THREAD

**Issue by ticoann** [dmwm/WMCore#8792]
https://github.com/dmwm/WMCore/wiki/WMAgent-deployment

1. check whether agent is already registered in wmstats. 
   - if true, check the drain status, if false proceed to next step
      - if drain is not completed abort the procedure
      - else proceed to next step.

2. automatically check schedd is installed and connected to pool, if not abort

3. automatically create the secrete file from template. 
     - set the flavor according to host name (vocmsbox oracle, fermi agent maria db)  - you have option to overwrite this.
     - Fill up could host with host ip address automatically
      - User types user and password  for database. (We can add the validation for db connection or whether it can be wiped out) - This is most critical case if we made a mistake.

4. automatically set the cert and proxy (We need to improve this part)

5. automatically deploy the agent

**Comment by ticoann** [comment]
@amaltaro, @vlimant, Please review the plan.

**Comment by amaltaro** [comment]
To start with, I'd say I'm against automatic deployment of WMAgent. It can be completely automated, BUT the part that triggers an agent deployment. An agent free/drained/empty doesn't mean we need to push a new release right away. The reason is, it might be that tomorrow we have a new release and now this agent is sort of out-dated. Even worse, it might be that this agent is never used until we have a new campaign deployment.

Now my comments:
> 1.check whether agent is already registered in wmstats.

see comments above.

> 2.automatically check schedd is installed and connected to pool, if not abort

only useful for new nodes, but Ok. Still, I'm not sure we can check whether the SI team made the proper schedd setup on both FNAL and CERN collectors. We need to check.

> 3.automatically create the secrete file from template.

that's interesting and will save possible mistakes. But again, it only pays off for new nodes.

> 4.automatically set the cert and proxy (We need to improve this part)

agreed! It could be done via puppet, however we need to figure out a place where the certificate is taken from (it could be copied from another node, but it will change once every couple of years) and the proxy file too (which lasts only 8 days, and we might deploy a new agent when it has already expired...).

> 5.automatically deploy the agent

let's work on the wmagent containerisation first, that should address this point.

**Comment by amaltaro** [comment]
Seangchan, I created this new label for all deployment-related issues.

**Comment by bbockelm** [comment]
I like your distinction between automatic and automated -- indeed, we want as high level of automation as possible, but we don't want the robots deciding when to roll out new agents ;)

There may be a few cases like distributing secrets (i.e., bootstrapping proxy) where automation is quite difficult - that's OK, we can save it for later.  Many of the container-based tools (such as kubernetes) have their own mechanisms for this, meaning we would be taking a step further away from containers if we rolled our own.

However, if we can minimize steps required to deploy agent, we reduce the likelihood of human error and increase the number of people who could help with this task.
