### ISSUE TITLE
Setup a stable testbed agent for the SS team

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8800]
As discussed in the P&R meeting, we should setup a somehow stable testbed WMAgent and disable AgentStatusWatcher such that the Site Support team can easily run small backfill tests before putting a site back into production mode.

Also write a simple and straight-forward wiki such that Maria from SS can do all of that by herself.

**Comment by amaltaro** [comment]
@mapsacosta Maria, we've just deployed the latest WMAgent in vocms0265. I've also given you the required ReqMgr role in SiteDB such that you can create/assign requests.

I was going to write a wiki in WMCore, but I figured it's better if you move the following details to one of the SST twikis/documentation. Setup and further details are here [*]

Can you please try following it and report if it works ok or not, or if you have any further questions? Then we can close this ticket. Thanks!

[*]
*** Injecting test workflows into cmsweb-testbed for site re-commissioning
1. Create a user proxy and export it to X509_USER_PROXY. E.g. (replace the file name by your proxy file):
```
voms-proxy-init -rfc -voms cms
export X509_USER_PROXY=/tmp/x509up_u31275
```

2. Download the following script, which is used for creating and assigning workflow(s):
```
curl https://raw.githubusercontent.com/dmwm/WMCore/master/test/data/ReqMgr/inject-test-wfs.py > inject-test-wfs.py
```

3. Then create and assign a TaskChain workflow to the site you'd like to test. E.g. (replace T2_IT_Rome by the site you'd like to test):
```
python inject-test-wfs.py -m DMWM -f TaskChain_ProdMinBias.json -c SST_SiteTests -r SST_SiteTests -t testbed-vocms0265 -a DMWM_Test -p SST_SiteTests_v99 -s "T2_IT_Rome"
```

3.a. among the output of this script, what's important are the lines confirming that the workflow was created and assigned, e.g.:
```
INFO:root:Create request 'amaltaro_TaskChain_ProdMinBias_SST_SiteTests_180920_104126_5139' succeeded.
INFO:root:Assigning amaltaro_TaskChain_ProdMinBias_SST_SiteTests_180920_104126_5139 with request args:
INFO:root:Assign succeeded.
```

4. From this point on, you can monitor this workflow via wmstats:
https://cmsweb-testbed.cern.ch/wmstats/index.html


Basic information about this WMAgent setup:
 * will be kept in sync with production in a best effort mode (which should suffice)
 * jobs are set to have one retry
 * all sites are by default enabled and have 1000 slots set in the thresholds
 * it's connected to cmsweb-testbed services, thus we need to use testbed for any monitoring, output data check, etc
 * in case of issues, email: Alan Malta / Seangchan Ryu

Basic information about that TaskChain workflow template:
 * it does not have any input dataset or pileup
 * it has 3 tasks, where intermediate tasks write/read to/from the /store/unmerged area
 * output data is written to "/store/backfill/1" LFN path. It can be changed if needed.
 * it creates around 300 jobs in total
 
If services in cmsweb-testbed are unavailable, please check whether there is any intervention going on on:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/ScheduledInterventions

**Comment by mapsacosta** [comment]
Hi @amaltaro thanks! I'll give it a try. Can you please grant ssh access to my account (macostaf) to the machine? Should I contact Daniel Valbuena?

**Comment by amaltaro** [comment]
Maria, you don't actually need to have access to vocms0265, do you? The pre-requirements are your proxy and curl/wget to download that script, I guess nothing else.

**Comment by mapsacosta** [comment]
@amaltaro Gotcha, so I tried it and got:
<h2>400 Bad Request</h2>
<p>Invalid spec parameter value: (403, 'You are not allowed to access this resource.')</p>
Is there anything else I need besides a valid proxy and the X509 env variable?

**Comment by amaltaro** [comment]
Weird! Roles seem to be correct. Can you please post the whole output of the script execution and also voms-proxy-info -all?

**Comment by mapsacosta** [comment]
**Ok so I redid the proxy and got this:**

[21:51][macostaf@lxplus040:~/private/testbed]$ voms-proxy-init -rfc -voms cms
Enter GRID pass phrase for this identity:
Contacting voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "cms"...
Remote VOMS server contacted succesfully.

Created proxy in /tmp/x509up_u106204.

Your proxy is valid until Tue Sep 25 09:51:39 CEST 2018
[21:51][macostaf@lxplus040:~/private/testbed]$ export X509_USER_PROXY=/tmp/x509up_u106204
[21:56][macostaf@lxplus040:~/private/testbed]$ echo $X509_USER_PROXY
/tmp/x509up_u106204

**And the complete output of the script: **
[21:56][macostaf@lxplus040:~/private/testbed]$ python inject-test-wfs.py -m DMWM -f TaskChain_ProdMinBias.json -c SST_SiteTests -r SST_SiteTests -t testbed-vocms0265 -a DMWM_Test -p SST_SiteTests_v99 -s "T2_IT_Rome"
WMCore directory found. I'm not going to clone it again.
You have 5 secs to abort this operation or live with that forever...


Processing template  TaskChain_ProdMinBias.json
Processing command line arguments: '['reqmgr2.py', '-u', 'https://cmsweb-testbed.cern.ch', '-f', '/tmp/macostaf.json', '-i', '-g']' ...
INFO:root:ReqMgr url: https://cmsweb-testbed.cern.ch
INFO:root:RESTClient URL: https://cmsweb-testbed.cern.ch
INFO:root:Using HTTPS protocol, getting user identity files ...
INFO:root:Identity files:
	cert file: '/tmp/x509up_u106204'
	key file:  '/tmp/x509up_u106204'
INFO:root:Creating connection HTTPS ...
INFO:root:Loading file '/tmp/macostaf.json' ...
WARNING:root:No request arguments to override (--json)? Some values will be wrong.
INFO:root:Actions to perform: ['create_request', 'assign_request']
INFO:root:Performing 'create_request' ...
INFO:root:Injecting request args:
{u'Group': u'DATAOPS', u'Comments': [u'MC from scratch; Given 100 EpLumi for Task1, set EpJob and EpLumi to 41 (instead of 100), so 1LpJob;', u'Task2 and Task3 EventAwareLumiBased with 800 and 900 EpJob; diff ProcStr'], u'Requestor': u'amaltaro', u'ProcessingString': {u'ProdMinBias': u'81X_mcRun1_realistic_v5', u'DIGIPROD1': u'81X_mcRun1_realistic_v5', u'RECOPROD1': u'81X_mcRun1_realistic_v5'}, u'ScramArch': u'slc6_amd64_gcc530', u'SizePerEvent': 1234, u'Memory': 2300, u'DQMUploadUrl': u'https://cmsweb-testbed.cern.ch/dqm/dev', u'IncludeParents': False, u'Task2': {u'KeepOutput': True, u'GlobalTag': u'81X_mcRun1_realistic_v5', u'InputFromOutputModule': u'RAWSIMoutput', u'TimePerEvent': 36, u'InputTask': u'ProdMinBias', u'SplittingAlgo': u'EventAwareLumiBased', u'ProcessingString': u'Task2_WMCore_TEST', u'ConfigCacheID': u'fd79406f016da454e5ac53c393491320', u'Memory': 1500, u'TaskName': u'DIGIPROD1', u'AcquisitionEra': u'CMSSW_8_1_0'}, u'SubRequestType': u'RelVal', u'RequestType': u'TaskChain', u'TimePerEvent': 0.10000000000000001, u'AcquisitionEra': u'CMSSW_8_1_0', u'CouchDBName': u'reqmgr_config_cache', u'CMSSWVersion': u'CMSSW_8_1_0', u'EnableHarvesting': False, u'Task1': {u'KeepOutput': True, u'GlobalTag': u'81X_mcRun1_realistic_v5', u'TimePerEvent': 700, u'SplittingAlgo': u'EventBased', u'ProcessingString': u'Task1_WMCore_TEST', u'RequestNumEvents': 9000, u'ConfigCacheID': u'fd79406f016da454e5ac53c393476d2d', u'Memory': 1200, u'EventsPerLumi': 100, u'TaskName': u'ProdMinBias', u'AcquisitionEra': u'CMSSW_8_1_0', u'PrimaryDataset': u'RelValProdMinBias', u'Seeding': u'AutomaticSeeding'}, u'RequestPriority': 600000, u'ProcessingVersion': 1, u'Task3': {u'KeepOutput': True, u'GlobalTag': u'81X_mcRun1_realistic_v5', u'InputFromOutputModule': u'RAWSIMoutput', u'TimePerEvent': 32, u'InputTask': u'DIGIPROD1', u'SplittingAlgo': u'EventAwareLumiBased', u'ProcessingString': u'Task3_WMCore_TEST', u'ConfigCacheID': u'fd79406f016da454e5ac53c3934a46df', u'Memory': 2000, u'TaskName': u'RECOPROD1', u'AcquisitionEra': u'CMSSW_8_1_0'}, u'RequestString': u'TaskChain_ProdMinBias_SST_SiteTests', u'GlobalTag': u'81X_mcRun1_realistic_v5', u'Campaign': u'SST_SiteTests', u'DbsUrl': u'https://cmsweb-testbed.cern.ch/dbs/int/global/DBSReader/', u'ConfigCacheUrl': u'https://cmsweb.cern.ch/couchdb', u'TaskChain': 3} ...
ERROR:root:Error occurred, exit.
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>400 Bad Request</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>400 Bad Request</h2>
        <p>Invalid spec parameter value: (403, 'You are not allowed to access this resource.')</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>

TaskChain_ProdMinBias.json request FAILED injection!

Injected 0 workflows out of 1 templates. Good job!

**Comment by mapsacosta** [comment]
Hi Alan, I'm ataching the output and my proxy info:
[inject_test.txt](https://github.com/dmwm/WMCore/files/2412675/inject_test.txt)

**Comment by amaltaro** [comment]
Hmm, I don't really know. Can you try injecting the same workflow but against cmsweb production? Just to rule out any possible CRIC x SiteDB issues. The command is the same as you executed before, but you need to add `-u https://cmsweb.cern.ch`. If it works, please let me know the workflow name.

**Comment by mapsacosta** [comment]
This one succeeded: macostaf_TaskChain_ProdMinBias_SST_SiteTests_180925_000000_278
[inject_prod_out.txt](https://github.com/dmwm/WMCore/files/2413048/inject_prod_out.txt)

**Comment by amaltaro** [comment]
Ok, then it proves there is an issue with how the roles are fetched in testbed. However, I see no differences between the prod and testbed authmap file... Unfortunately I also don't have the testbed reqmgr2 logs since yesterday afternoon (we'll need to fix that), so I'll ask you to try to inject it again once Lina updates the reqmgr2 config file.

About cmsweb-dev, I guess that was actually decommissioned. It was used only by the CMSWEB team and only for their validation, so we shouldn't rely on it at all.

I aborted your workflow in production.

**Comment by amaltaro** [comment]
@mapsacosta as discussed in a private thread, this is a problem with the cric dev instance (which testbed frontends are pointing to). Apparently the mapping was fixed in testbed as well, can you give it another try please?

**Comment by ticoann** [comment]
Thanks Alan, Maria, closing the issue.

**Comment by amaltaro** [comment]
Maria, just one note. Not all sites have /store/backfill setup, so you might see stage out issues here and there. You can either follow with the sites to create/enable it or you can change the template from
`        "MergedLFNBase": "/store/backfill/1",`
to
`        "MergedLFNBase": "/store/mc",`
