### ISSUE TITLE
make the TaskType job classad more meaningful

### ISSUE THREAD

**Issue by hufnagel** [dmwm/WMCore#8802]
At the moment TaskType isn't set fine grained enough. In particular, we want *at least*

GENSIM
DIGI
RECO
DIGIRECO (are we using this ?)
GENSIMDIGIRECO

**Comment by hufnagel** [comment]
Forgot the utility type jobs:

MERGE
CLEANUP
LOGCOLLECT
DQMHARVEST

**Comment by hufnagel** [comment]
Some of these might very well be there already. But for instance in a TaskChain with both Digi and Reco, the Reco job is also marked as DIGI, so it's not all there yet.

**Comment by amaltaro** [comment]
Dirk, WMAgent job types are defined in the ad `CMS_JobType` (or something similar), and those include:
Production, Processing, Merge, LogCollect, Cleanup, etc etc

Distinction of DIGI, RECO, AOD, MINIAOD, NANOAOD is something made up by Brian for the MonIT monitoring, which relies on something that AFAIK isn't really a convention between Computing and Offline/PPD (it simply parses the task name). That's why you see RECO flagged as DIGI.

As you know, we cannot really distinguish which Processing job is a NANOAD and which is a DIGI, for instance. For that, we'd need to look into the PSet configuration of such jobs, which isn't something that we have (and probably we should remain like that) in the JobCreator component. So JobSubmitter cannot set an ad for that.

Unless you know a non-convoluted way to properly get the human task type, I don't think we can make it in WMAgent.

**Comment by hufnagel** [comment]
I'll close this for now. Discussion is still ongoing in email, but even if something comes of it, it won't be the TaskType we are modifying but likely another new parameter.

**Comment by amaltaro** [comment]
Will be needed this year, reopening

**Comment by amaltaro** [comment]
Closing it in favor of #8958
