### ISSUE TITLE
CRIC/SiteDB whoami API does not work with user proxy

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#8825]
Even though it works if one passes the certificate file and the private key in different pem arguments.
```
cmst1@vocms0252:/afs/cern.ch/user/a/amaltaro $ curl --cert $X509_USER_CERT --key $X509_USER_KEY 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
{"result": [
 {"dn": "blah...
```

while a proxy file returns
```
amaltaro@vocms0192:/data/amaltaro/HG1810_Validation $ curl --cert $X509_USER_PROXY --key $X509_USER_PROXY 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
curl: (35) Peer does not recognize and trust the CA that issued your certificate.
```

so, when using a user proxy I think we should also pass a CA file or CA path such that the peer can be verified.

**Comment by amaltaro** [comment]
@belforte replying here, yes, I refer to the whoami api in SiteDB or CRIC

**Comment by belforte** [comment]
curious... seems to me a problem with vocms0192. since I get same error there with my proxy, which works elsewhere. Besides this also works:
belforte@vocms0192/TC3> curl --capath /etc/grid-security/certificates/ --cert $X509_USER_PROXY --key $X509_USER_PROXY 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
curl: (35) Peer does not recognize and trust the CA that issued your certificate.
belforte@vocms0192/TC3>

**Comment by amaltaro** [comment]
Hmm, maybe it hasn't been running the fetch-crl job and it's missing CAs then?
Anyways, Stefano did you actually test the WMCore whoami API? If CRAB could migrate to that instead of triggering creating a subprocess, that would be certainly helpful.

**Comment by belforte** [comment]
I checked /etc/grid-security/certificates and file dates are recent. I am very puzzled by this error, have seen many kind of SSL errors, but this is a first.
Can you you try from another VM ideally with same conifg ? I suspect a problem with curl.

In CRAB Client we intentionally do a curl to the SiteDB (now CRIC) URL instead of using the WMCore method because it is a diagnostic command used to shed light on problem cases, so we want to be sure to look at the DB, not debug problems with a WMCore call which would only be used for this.
Other than this diagnostic `crab checkusername` CRAB get username from CMSWEB frontend, never talks directly with sitedb/cric about username.

**Comment by belforte** [comment]
et voila':
belforte@vocms0109/CMSSW_10_1_0> curl --capath /etc/grid-security/certificates/ --cert $X509_USER_PROXY --key $X509_USER_PROXY 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
{"result": [
 {"dn": "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=belforte/CN=373708/CN=Stefano Belforte", "login": null, "method": "X509Proxy", "roles": {}, "name": null}
]}
belforte@vocms0109/CMSSW_10_1_0> 

problem is curl
I am now using:
elforte@vocms0109/CMSSW_10_1_0> which curl
/cvmfs/cms.cern.ch/slc7_amd64_gcc630/cms/cmssw/CMSSW_10_1_0/external/slc7_amd64_gcc630/bin/curl
i.e. I did
```
export SCRAM_ARCH=slc7_amd64_gcc630
cd CMSSW_10_1_0/
cmsenv
```
it is some other manifestation of the old problem that support for SSL authentication in system curl is not good enough and we need the one built by CMS.
CRAB client runs inside CMSSW, so there is no problem for users.
If you want to do curl outside CMSSW env... well.. I do not know how exactly you can import only the needed things from CVMFS, but I guess CMSSW experts can help. I guess you do not want to do a cmsenv before starting WMA (if that's your use case)

**Comment by belforte** [comment]
I think you can close, or rename as : need to use proper version of curl to talk with CMSWEB/CRIC

**Comment by bbockelm** [comment]
Agreed.  The general case is `curl` doesn't work with X509 proxies -- it's a "happy surprise" when we have special builds available where this is patched.
