### ISSUE TITLE
WMAgent components silently or almost silently crashing due to DB/connection errors

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/WMCore#8975]
This issue takes a while for operators to notice because it does not show up as a paused job that could be failed but they got failed immediately. There could be some protection, notification or a component auto restart mechanism in order to have have less issues and less component's downtime.

A preliminary task could be to create a cron job that uploads a blank entry to the couchdb every 5 minutes or so and then removes it to test if the connection is working properly and send a notification if it is down.

**Comment by amaltaro** [comment]
@andresfelquintero from our discussion in the WMCore meeting, I understood the problem was with oracle instabilities instead of couchdb. Can you please clarify?

As I told you, we've added another layer to WMCore which protects against temporary oracle/mysql instabilities, but the T0 agent is almost 2 versions behind and doesn't have those developments.

If it's oracle, please provide the errors that cause the component to crash and we can evaluate whether we can simply skip that error or if we need to really stop the component until something improves in oracle.

**Comment by andresfelquintero** [comment]
So we will know if this works only after T0 agent gets upgraded. I will talk to Dirk about it.

**Comment by amaltaro** [comment]
Yes, and if we need to extend to other temporary oracle error codes, then we need to add those.
Andres, I'd suggest to close this issue and open a new one once the T0 agent is upgraded and you hit one of those temporary oracle issues that bring the component down.

**Comment by andresfelquintero** [comment]
Okay I will leave this open until the agent is updated, then I will close it and open the new one with the new oracle issues if they appear.

**Comment by andresfelquintero** [comment]
Agent was updated, nothing has happened. I think this can be re opened on Run 3, but there should not be any problem with it.
