### ISSUE TITLE
Automatic re-submission of jobs with no error reports(Exit code 993030/99400/99401)

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#9022]
Having the workflows coming into assistance-manual with no error report (exit code 99303/99400/99401) has no value as the result is to run a blind ACDC. 
May be this can be automated from the agents' side and resubmit the jobs which have this exit code in order to have a valuable output that can be read, interpreted and taken appropriate action. Also, this helps in reducing manual work. 
@amaltaro I think this is something that could help us a lot from PnR point of view. @thongonary FYI

**Comment by vlimant** [comment]
2 cents : 

- there is always a condor log available somewhere (if not on the unified report directly) that can give hints of what is going on. https://cms-unified.web.cern.ch/cms-unified//report/pdmvserv_task_SMP-RunIIFall18wmLHEGS-00093__v1_T_181130_043458_1233

-  "no job report" is a rather catastrophic event, often due to something rather nasty happening at the site. if that job has only one possible location, chances are that it's going to be resubmitted to fail again.

I am actually surprises, picking on pdmvserv_task_SMP-RunIIFall18wmLHEGS-00093__v1_T_181130_043458_1233 example that the job was a job failing with 99303 was not retried, even though it was only the second trial on that job.

Job Name: c6cbb008-0c8f-480b-aaf3-9aac63c7ebef-5
WMBS job id: 3384144
Workflow: pdmvserv_task_SMP-RunIIFall18wmLHEGS-00093__v1_T_181130_043458_1233
Task: /pdmvserv_task_SMP-RunIIFall18wmLHEGS-00093__v1_T_181130_043458_1233/SMP-RunIIFall18wmLHEGS-00093_0/SMP-RunIIAutumn18DRPremix-00076_0/SMP-RunIIAutumn18DRPremix-00076_1
Status: jobfailed
Input dataset:
Site: T2_US_Purdue
Agent: vocms0251.cern.ch
State Transition
    jobcooloff: 2019/1/25 (Fri) 08:01:25 UTC, T2_US_Vanderbilt
    jobfailed: 2019/1/30 (Wed) 01:47:49 UTC, T2_US_Purdue
Exit code: 99303

**Comment by amaltaro** [comment]
There is no surprise, this agent is in SpeedDrain.

**Comment by vlimant** [comment]
@amaltaro indeed :-( 

from 

```
"NoRetryExitCodes": [
    70, 
    73, 
    8001, 
    8006, 
    8009, 
    8023, 
    8026, 
    8501, 
    50660, 
    50661, 
    50664, 
    71102
  ], 
```

the request in this GH issue is already full-filled

**Comment by amaltaro** [comment]
Ok, closing as nothing to be done here.
