### ISSUE TITLE
EventAwareLumiBased algo should not fail job creation for T0 agents

### ISSUE THREAD

**Issue by andresfelquintero** [dmwm/WMCore#9053]
Taking information from ticket https://its.cern.ch/jira/browse/CMSTZ-651, we agreed with @hufnagel that a change on the time estimation for jobSplitting will be useful to avoid the 48 hours limit that is set upon some PromptReco jobs. Specifically we discussed this code https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L170 and it is suggested that a different type of jobSplitting should be done just for PromptReco and it should have some optional parameter for this specific type.

**Comment by amaltaro** [comment]
Andres, Dirk, I'm not sure I understand it. Are you saying that with the standard TimePerEvent and EventsPerJob values for PromptReco workflows, it sometimes exceeds the JobTimeLimit default value, thus possibly failing the job in this line:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L171
?

How about increasing this JobTimeLimit, would it cause an issue for T0 jobs (pilot lifetime)?

Or are you suggesting that you would like to change the EventsPerJob value for some specific PromptReco such that they don't hit the 48h default limit?

**Comment by hufnagel** [comment]
Yes, we sometimes exceed the maximum allowed lifetime. Reason is that Tier0 sets reasonable limits for normal collision data taking, which assumes "normal" pp events with a few second reco time. Sometimes we get data that is not normal collision data taking and which goes into the same datasets. If this data is high rate, but mostly empty events, it's still reconstructable in the Tier0 and detector groups usually want that reco output. But due to the preset limits for time per event the Tier0 fails the jobs without even trying to reconstruct it.

As such, for PromptReco we want to ignore the calculated job wall time and instead configure an upper limit of (pilot lifetime minus epsilon). This didn't used to be a problem before because our pilots had 30 day lifetime, but now we share the HTCondor queue and AFAIK the limit there is 48h (Tier0Ops should double-check that, could also be 72h).

**Comment by amaltaro** [comment]
I see, thanks.

So I take it we only want two behaviours:
1. not fail jobs during job creation
2. cap job time estimation such that it fits within the standard 48h pilots.

Having said that, how about we add a new attribute to the JobCreator section specifying whether we want or not to have creationFailures in the job splitting? Then we can also take the JobTimeLimit and cap the job estimation there, such that this job manages to run once it hits the condor pool.

**Comment by hufnagel** [comment]
Yes, that's exactly what we want. The new attribute should default to the current behavior, we can override in the PromptReco spec.

**Comment by hufnagel** [comment]
Can we change this in the component or do we need to modify the job splitter? Problem is here

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L261

when it passes failNextJob=True to

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/JobFactory.py#L121

**Comment by amaltaro** [comment]
I'll provide a fix tomorrow and ask for your review. It's very simple.

**Comment by amaltaro** [comment]
I renamed the issue to reflect what we discussed.
@khurtado this seems a good and simple candidate for you. We basically need 2 things
*) create another JobCreator attribute in WMAgentConfig.py (`config.JobCreator.allowCreationFailure=True`). T0 will have to override it to `False`
* pass this new attribute to the JobSplitting algo
* if it's False, then we don't mark the job as failed, according to this line:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventAwareLumiBased.py#L171

Last but not least, it would be important to have a unit test for it. Let me know if you have any questions please.

**Comment by andresfelquintero** [comment]
Hello, I have run a replay on vocms047 with some PromptReco jobs that have a very long time per event parameter (5000). The jobs were still created as seen on Grafana, JobCreator and Tier0Feeder. If @amaltaro or @hufnagel think that there should be something else done to it, please comment or if there is nothing else to be added then we can close this issue.
