### ISSUE TITLE
StoreResults dataset should preserve the original input dataset name

### ISSUE THREAD

**Issue by thongonary** [dmwm/WMCore#9092]
The original issue can be found here: https://its.cern.ch/jira/browse/CMSCOMPPR-4907

For a test workflow: https://cmsweb.cern.ch/reqmgr2/fetch?rid=sagarwal_EmbeddingRun2017B-TauTauFinalState-inputDoubleMu_94X_miniAOD-v2_190305_162744_2306
Input dataset: /EmbeddingRun2017B/TauTauFinalState-inputDoubleMu_94X_miniAOD-v2/USER
Output dataset: /EmbeddingRun2017B/StoreResults-inputDoubleMu_94X_miniAOD-v1/USER is the output dataset 
The `TauTauFinalState` in the original input dataset has been replaced by `StoreResults`. As a result, several different input datasets come out with the same output dataset:
https://cmsweb.cern.ch/reqmgr2/fetch?rid=sagarwal_EmbeddingRun2017B-TauTauFinalState-inputDoubleMu_94X_miniAOD-v2_190305_162744_2306
https://cmsweb.cern.ch/reqmgr2/fetch?rid=sagarwal_EmbeddingRun2017B-ElTauFinalState-inputDoubleMu_94X_miniAOD-v2_190305_162740_957

@amaltaro Can you please fix this? Ideally the output name for the above example workflow should be /EmbeddingRun2017B/StoreResults-TauTauFinalState-inputDoubleMu_94X_miniAOD-v1/USER

**Comment by GaelTouquet** [comment]
Also it seems that "miniAOD-v2" has been changed to "miniAOD-v1"

**Comment by amaltaro** [comment]
@thongonary I think this is the expected behaviour for StoreResults. I don't really remember, but I think in the past we discussed that StoreResults workflows should all have `AcquisitionEra=StoreResults`.

Second comment is, I don't think WMCore is hard-coding this AcqEra, since it can be updated during workflow assignment. Can you point me to the script creating and assigning these workflows?

**Comment by thongonary** [comment]
This is the script https://github.com/CMSCompOps/WmAgentScripts/blob/master/createStoreResults.py
