### ISSUE TITLE
Investigate pickle differences between Py2 and Py3

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9128]
As discussed in the morning session, about CMSSW being compatible with both python versions. The PSet is tweaked using the python version available in the CMSSW area. However, the PSet pickle file is probably created in the WorkQueueManager component, when creating the sandbox. Thus we need to make sure that pickling and unpickling in different version will have the same outcome.

From the python3 documentation, we just need to define/use a compatible protocol
"""
The pickle serialization format is guaranteed to be backwards compatible across Python releases provided a compatible pickle protocol is chosen and pickling and unpickling code deals with Python 2 to Python 3 type differences if your data is crossing that unique breaking change language boundary.
"""

To be tested/investigated though

**Comment by amaltaro** [comment]
@mapellidario do you think we should keep this issue open? Or there is no value anymore and we should just get it closed? Thanks

**Comment by mapellidario** [comment]
I think that you opened this when you were thinking about decoupling WMCore from CMSSW. If that was the scope of this investigation, then we can close it. 

However, we may still face this problems within WMCore or when communicating with DBS. I am not sure that these differences with pickle are no longer a problem, so I would keep this open just to remind us that this can still hurt us back.

**Comment by amaltaro** [comment]
@mapellidario Dario, I would suggest to close this issue with all the investigation and discussion that happened in:
https://github.com/dmwm/WMCore/pull/10619
and the final changes that were taken in: https://github.com/dmwm/WMCore/pull/10628

Since you did all the hard work here, can I ask you to write a few lines with the outcome/summary of all this? Then feel free to close it as well. Thanks

**Comment by mapellidario** [comment]
This investigation was actually carried out in this branch https://github.com/mapellidario/WMCore/compare/f7739cb..10609-investigation (compared against the commit that was on dmwm/WMCore/master at the time of creating the branch). 

I based my investigation on the types that the [official pickle doc](https://docs.python.org/3/library/pickle.html#data-stream-format) says that are supported when pickling. 

The result of the investigation is
- from py2 to py3: if you have bytes strings (which are the py2 default strings) containing non-ascii characters or if you have some bytes sequence that does not represent a string (such as a pickle file itself, an image, whatever), then you may need to juggle a bit with string encodings (if the bytes are actually an ascii/utf8 encoded string) OR with keys retrieval when loading from py3 (if the bytes are actually a bytes stream that is not a string and requires a different decoding from ascii/utf8)
- from py3 to py2: when you unpickle an object, make sure that it belongs to a class that inherits from `object` (or from python-future's `from builtins import object`, otherwise pickle.load fails when instantiating the object since it cannot call `object.__new__(cls)`

All the rest looks good and working. These two peculiar quirks that we found should actually not affect us (we should not have encoded bytes that represent something different from an ascii string and all our classes in py2 inherit from `object`), so we propose to move forward with the code that we have. In case we find some problems (unexpected!), then we could use my branch to have some guidelines for adapting our pickling/unpickling.

Thanks Alan for already pointing to the relevant PRs, thanks for implementing a lot of fixes related to pickle and for leaving me the pleasure to close this!
