### ISSUE TITLE
site column empty in workqueue link

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#9129]
https://github.com/CMSCompOps/WmAgentScripts/issues/400

https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=vlimant_task_HIG-RunIIFall17wmLHEGS-01995__v1_T_181030_224109_3526
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=vlimant_task_HIG-RunIIFall17wmLHEGS-02954__v1_T_181015_122154_4974

These two requests were in the system for a long time. I had a look at these links and they had no site under the site column. @amaltaro as you said, if the column is empty, then it means there is no common site between sitewhitelist and data location and in case there is no input data for MC, it should be full of sites. Can you please correct me if I understood something wrong.

@vlimant @thongonary FYI

**Comment by vlimant** [comment]
the WQE are gone, since the requests are rejected now : please update if you find any other such workflow in such situation

**Comment by sharad1126** [comment]
They are gone because we rejected them but the cloned workflows should help.
http://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-01995
http://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIIFall17wmLHEGS-02954

**Comment by vlimant** [comment]
the empty "Sites" in the WQE table is normal

see https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_HIG-RunIIFall17wmLHEGS-02380__v1_T_190216_082922_9801 running just fine.
the others are not being picked up because of priority

**Comment by vlimant** [comment]
@amaltaro please close if you agree

**Comment by amaltaro** [comment]
Yes, that's correct.
It looks like `Sites` column shows where your `Inputs` data is located, and in the case where there is not input dataset (empty dict for Inputs), then nothing is shown:
https://github.com/dmwm/WMCore/blob/master/src/couchapps/WorkQueue/_attachments/js/ElementInfoByWorkflow.js#L52

When the element has input dataset but it's not available anywhere, then `Sites` would show `No sites`.

I'm closing this issue since there is nothing wrong.
