### ISSUE TITLE
Investigate why reqmgr2 runs under 2 processes

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9172]
Besides running with 2 processes, this file
```
amaltaro@alancc7-cloud1:/data/srv/current $ cat ../state/reqmgr2/pid 
```

reports a PID that I can't find when `ps auxww`.
This will be needed to get reqmgr2_exporters/prometheus properly working

**Comment by vkuznet** [comment]
Alan,
I understood why we have two processes. It is due to the fact that REST server
`wmc-httpd` has the following
```
from WMCore.REST.Main import main
main()
```

If you look at WMCore/Rest/Main.py you'll see that it is a python process which
start daemon internally. That's why we have 2 PIDs.

But as you pointed out the pid which is written in state area does not
correspond to running process. Moreover we need to write a pid of the daemon
which is started here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Main.py#L593

I think this line should be corrected:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Main.py#L414

**Comment by amaltaro** [comment]
The PID we persist is actually a PGID (process group ID) and, that's why we can't list it with the standard `ps` command. This ps does the trick though:
```
amaltaro@alancc7-cloud1:/data/srv/current $ ps axo user,pid,pgid,%cpu,%mem,vsize,rss,stat,bsdstart,bsdtime,comm | grep _reqmgr2
_reqmgr2 11487 11414  0.0  0.0  18168   864 S     10:45   0:00 rotatelogs
_reqmgr2 11489 11488  0.0  0.4 163220 16692 S     10:45   0:00 python
_reqmgr2 11490 11488  1.3  1.6 1168472 58516 Sl   10:45   2:09 python
```

if we have two processes started by the same PGID, then it makes sense to send a kill to the PGID instead of the PID. Still not clear though why two processes.

> If you look at WMCore/Rest/Main.py you'll see that it is a python process which
start daemon internally. That's why we have 2 PIDs.

Yes, it starts a daemon in a different process. But then shouldn't the first python wrapper (wmc-httpd) exit after that last line L593 (leaving only one process around...)?

**Comment by vkuznet** [comment]
Ahh, good to know.

The main process does not exit since you run it as
```
wmc-httpd -r -d /data/srv/state/reqmgr2 -l | ....
```
So it is alive, but it also has a daemon. For exporter I need to know the pid of
the daemon since it is the process which does the job. Its parent just start the
daemon.

**Comment by vkuznet** [comment]
Alan, I found a way to modify process_monitor script to take as an input the file with pid. This allows to identify WMCore/Rest services whose group pid is written to state area, e.g. `/data/srv/state/reqmgr2/pid` or `/data/srv/state/crabserver/pid`. This was done in this commit: https://github.com/vkuznet/cmsweb-exporters/commit/7172f9c4e07151540abd280e25fa9073e25b795b and I'm including monitoring for ReqMgr2 and CRABServer into July cmsweb release. Therefore we can safely close this issue since it is no longer valid.

**Comment by amaltaro** [comment]
Thanks, Valentin. Yes, let's just assume it's not an issue per se.
