### ISSUE TITLE
Possible priority inversion

### ISSUE THREAD

**Issue by thongonary** [dmwm/WMCore#9180]
After discussion with @amaltaro and @chwissing, it seems the current logic in condor job creation could lead to priority inversion:
- If 110k-priority work-queue-element (WQE) has only FNAL in the whitelist, it has to wait for FNAL's free slot so that the agent can create jobs for such WQE.
- If 85k-priority WQE has FNAL and other 9 sites in the whitelist, any free slot in one of 10 sites will create condor jobs for such 85k-prio WQE and assign to all 10 sites.
As a result, 85k-prio WQE can get jobs in the queue at FNAL before the 110k-prio WQE. 

According to @chwissing, the agent should take priority of the current jobs at sites into account, so that only jobs of equal or higher priorities should be submitted to such sites. 

More discussion is needed to sketch out the details, which is the purpose of this GH issue.

**Comment by amaltaro** [comment]
You missed some details from our discussion. Higher priority work is always pulled down by the agents, even if there are no free slots (~25% resources over commitment). 
So, the agent might have lower priority jobs created in the local queue, or in the condor local queue, however, it does not mean those jobs will run before the 110k priority. Because the same agent - and all others - would have a bunch of 110k prio jobs pending in condor. The only way to get lower priority jobs running would be to fill resource gaps.

This issue has been extensively discussed and fixed a few times in the past. Around 2 years ago we got it fixed for good. 

Unless you can show and prove there is priority inversion (which could happen if schedds are overloaded) originating from a flaw in WMAgent, I don't think there is any issue here.

**Comment by vlimant** [comment]
@amaltaro where is that wiki @ticoann and you put together after all the changes we hammered on over the last years?

**Comment by chwissing** [comment]
There is one (out of more WFs) that were submitted more than a week ago with prio 110k and not a single Condor job seems to be created for it:
 TOP-RunIISummer15wmLHEGS-00421

During last week quite some WFs with prios of 95k or 85k got started (=Condor jobs were submitted), while the example one didn't. This surprises people and it would be good to understand why this happening. If the higher priority work is not submitted to Condor lower priority stuff will continue to take resources and people will complain about priority inversion.

Issues with single-core jobs are filling slots before multi-core jobs of higher priority WFs can take them are understood as such, but here we seem to have a different issue, since higher priority jobs are not released and cannot even compete on Condor level.

**Comment by amaltaro** [comment]
https://github.com/dmwm/WMCore/wiki/workflow-for-job-creation-and-submission

**Comment by amaltaro** [comment]
@thongonary I believe the PU dataset was getting delete for the request you were asking further info on Friday.
https://cmsweb.cern.ch/couchdb/workqueue/_design/WorkQueue/_rewrite/elementsInfo?request=pdmvserv_task_TOP-RunIISummer15wmLHEGS-00421__v1_T_190424_171801_4552

Looking at the first 2 GQE, their SiteWhitelist is set to `T1_US_FNAL`, while the PU data is only available at 
```
"PileupData":{"/MinBias_TuneCUETP8M1_13TeV-pythia8/RunIISummer15GS-MCRUN2_71_V1_ext1-v1/GEN-SIM":["T2_IN_TIFR","T2_DE_DESY","T3_IN_TIFRCloud"]}
```

It does not have TrustPUSitelists set to `True`, so it will not run.

**Comment by hufnagel** [comment]
Even if it had TrustPUSitelists  set to True, it would run badly, reading pileup VERY remotely.

**Comment by thongonary** [comment]
The PU was only removed on the last Friday, but the workflow has stayed in such state for more than a week.

**Comment by amaltaro** [comment]
Apparently we didn't conclude anything here. Are there any other cases such that we can keep investigating this issue? If not, then I'm afraid there isn't anything that can be done.

**Comment by amaltaro** [comment]
Given the lack of activity and more debugging data (and/or new cases), I'd like to close this issue. We can always reopen it if needed. Thanks everyone!
