### ISSUE TITLE
MS Transferor is not creating PhEDEx subscription on a workflow basis

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9226]
The subject is too short to describe the problem, so let me clarify it here.

It looks like MS Transferor is first finding out all datasets/blocks that have to be subscribed (belonging to workflows in a given status, like `assigned`), then it adds the same datasets/blocks to the requests to be made in PhEDEx, here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py#L486

which then make it to repeated PhEDExSubscription here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L149

The expected behaviour would be to make a workflow-wise data placement, such that we can store the transfer ids and properly track their progress.

**Comment by vkuznet** [comment]
Alan, your description is not complete and ambiguous. I don't know/understand exactly what needs to be done here. The current code does the following:
- as you pointed out on L486 we get all information about given workflow. This includes datasets/blocks/sites and aux info like nevents, lumi, etc.
- this info is taken by transferor code here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L119
- then we loop over all requestRecords and for each one we call PhEDExSubscription
- the PhEDExSubscription takes two arguments list of datasets and sites
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L151

So I don't understand what you refer as "The expected behaviour would be to make a workflow-wise data placement". I think the code does exactly that, it starts from workflow, then finds all datasets and subscribe them to found sites. What do you mean by workflow-wise data placement?

Please elaborate on correct behavior more.

**Comment by amaltaro** [comment]
> then we loop over all requestRecords and for each one we call PhEDExSubscription

exactly. The problem is that requestRecords length is equal to the number of workflows it is processinng. Then for each element of the list, we stored the same list of datasets and blocks, which means...

> the PhEDExSubscription takes two arguments list of datasets and sites

this is getting created over and over with the same data.

Can you try to access my VM (alancc7-cloud2)? The service log should give you a better picture of what I'm saying (please don't change any code in there :))

**Comment by vkuznet** [comment]
then please be precise with your description. Your issue title is misleading. We do create subscription for each workflow. If workflows share the same datasets/blocks/sites it is another issue. And, I think what you're asking is to reduce number of subscriptions. May be my definition of workflow is different to what you have in mind. If I'll strip out all details the code does the following:
```
workflows = requestWorkflows.values()
for wflow in workflows:
     for wname, wspec in wflow.items():
          record = {...} # record to process
return records
...
for record in records:
     subscription = PhEDExSubscription(...)
```

So what's wrong with a code structure (apart that each record has identical datasets/blocks)? My take from this is that we get list of workflows and for each workflow we create a record to deal with. Why this code is not creating subscription on workflow basis?

**Comment by vkuznet** [comment]
and if you want me to access your VM you need to grant permission for that too.

**Comment by vkuznet** [comment]
I think I understand what the problem.
On line https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py#L486
we need to pass datasets as primary+secondary rather then use datasets list we start with. Such that record will have only dataset associated with this workflow. Is this the problem you're talking about?

**Comment by amaltaro** [comment]
Yes, the same list of datasets/blocks is used - as data placement - for different workflows, even though workflows don't necessarily share the same input data. So problem is reusing this:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py#L431

when iterating over each workflow (which creates a record to be transferred):
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/RequestInfo.py#L486

> Such that record will have only dataset associated with this workflow. Is this the problem you're talking about?

yes!

**Comment by vkuznet** [comment]
ok, now it is clear. The fix is here: https://github.com/dmwm/WMCore/pull/9229 Feel free to review.
