### ISSUE TITLE
Persist the campaign configurations in couch

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9228]
List of actions to be taken here are:
* fetch all the current campaigns available in the Unified database (or repository?)
* insert every single of them in ReqMgrAux (one time insert for now)
* we already have REST APIs to insert/update/retrieve them, so we're all set on that respect
* create a default campaign configuration such that we can use in testbed and for our tests (whether we use it or not has to be configurable, we do NOT want to fallback to it in production)

However, before taking this issue, we better work on a campaign schema and make sure we have reasonable data stored in the Campaign collection, tracked in this issue:
https://github.com/dmwm/WMCore/issues/9139

**Comment by vkuznet** [comment]
In order to implement this I need to know the following:
- the MSTransferorMonit operates with request names
- the ReqMgrAux provides an API `getCampaignConfig(campaignName)`
Therefore in order to get campaigns I need to know how to find campaignName from request name.

I think it is possible if we'll fetch all details of request specs in monit, so far it is not the case since we only get requests from reqmgr without details, see https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L69

Alan, please advise.

**Comment by amaltaro** [comment]
I'm pretty sure we already have a function/method implemented which looks up a key in the request dictionary. If not, let me create a generic one because we also need it for other parts of the MS implementation.

**Comment by vkuznet** [comment]
Alan, for MS monit part originally I get requests info from reqmgr2 using `detail=True` option. With that I can get the campaign name. But then you requested to change call to `detail=False` and now I only get requests names. Please see it here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Unified/Transferor.py#L69

That's why I asked now how should I get campaign name if I only know requests name. If you still want to operate with request names and fetch them via `detail=False` option, then you should provide me an API how to get campaign name. Otherwise I think we can get it directly from call to reqmgr2 if we'll use `detail=True` option.

**Comment by amaltaro** [comment]
For the record, 115 campaigns have been injected into cmsweb-testbed (fetched from Unified mongodb a day or two ago), plus 4 test campaigns.
