### ISSUE TITLE
where is "retry" ?

### ISSUE THREAD

**Issue by belforte** [dmwm/WMCore#9474]
**Impact of the bug**
breaks CRAB TaskWorker

**Describe the bug**
Hi @amaltaro , one month ago this line appeared in DB3Reader
https://github.com/dmwm/WMCore/blob/4e2bea88d787f4af2099e7c91dc498990de8cc9b/src/python/WMCore/Services/DBS/DBS3Reader.py#L13
But when I run it I get
`ImportError: No module named retry`

Note that I am using python from COMP envirornment 
`slc7_amd64_gcc630/external/python/2.7.13-comp/bin/python`

Where is retry supposed to be imported from ?

P.S. I had build a working crab TW with WMCore 1.2.9 in December, so am not
sure how this got in, 

**How to reproduce it**
python
import retry

**Comment by belforte** [comment]
I think I found it, I need to change the TaskWorker build spec to require `py2-retry` as well
thanks anyhow

**Comment by amaltaro** [comment]
Sorry Stefano, that change went in in August with this patch:
https://github.com/dmwm/WMCore/pull/9355

and I obviously forgot once again that that module is used by external services (and that they needed to updated their spec files too in order to get it running).

Your change is correct though, you need to update the spec file for every CRAB server using that DBS module (by adding `Requires: py2-retry`)

**Comment by belforte** [comment]
thanks for confirming Alan. Onward we go !
