### ISSUE TITLE
StepChainParentageFixTask timing out (502 Proxy Error)

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9537]
**Impact of the bug**
ReqMgr2, `StepChainParentageFixTask` cherrypy thread.

**Describe the bug**
The cherrypy thread fails to get a response back from the DBS server within the CMSWEB/frontend cluster 5min limit, thus receiving a `502 Proxy Error` error message back from the frontend.

**How to reproduce it**
Likely making the same DBS client POST call `fileparentsbylumi` as seen in the traceback, proving the same block and same list of LFNs

**Expected behavior**
Well, it's expected to go through within the limit of 5min. It's actually an expensive call (confirmed from Yuyi as well), but if it does not go through, then we might have to rethink the whole process of StepChain parentage update/fix.

A possible workaround - as privately discussed - would be to make > 1 calls for the same block, providing smaller slices of LFNs and aggregating all the result in the end. However, this needs to be very well implemented to avoid having parentage information for only a fraction of the block...

**Additional context and error message**
traceback from
amaltaro@vocms055:/build/srv-logs/vocms0743/reqmon $ less /build/srv-logs/vocms0766/reqmgr2/parentageFixTask-vocms0766-20200210.log 
```
2020-02-10 00:12:14,631:ERROR:DBS3Reader:Parentage updated failed for block /TTToHadronic_hdampDOWN_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL18HLT-102X_upgrade2018_realistic_v15-v2/GEN-SIM-RAW#1bb50416-6f34-40ce-b8e4-fb301d3853f3
Traceback (most recent call last):
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/reqmgr2/1.3.0.pre6-comp/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 1022, in fixMissingParentageDatasets
    numFiles = self.findAndInsertMissingParentage(blockName, insertFlag=insertFlag)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/reqmgr2/1.3.0.pre6-comp/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 961, in findAndInsertMissingParentage
    fileParents = self.dbs.listFileParentsByLumi(block_name=childBlockName, logical_file_name=childLFNs)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 484, in listFileParentsByLumi
    return self.__callServer("fileparentsbylumi", data=kwargs, callmethod='POST')
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 201, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 225, in __parseForException
    raise http_error
HTTPError: HTTP Error 502: Proxy Error
2020-02-10 00:17:14,802:ERROR:DBS3Reader:Parentage updated failed for block /TTToHadronic_hdampDOWN_TuneCP5_13TeV-powheg-pythia8/RunIISummer19UL18HLT-102X_upgrade2018_realistic_v15-v2/GEN-SIM-RAW#71ead48d-0e66-4c82-9a7c-ca805582371f
Traceback (most recent call last):
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/reqmgr2/1.3.0.pre6-comp/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 1022, in fixMissingParentageDatasets
    numFiles = self.findAndInsertMissingParentage(blockName, insertFlag=insertFlag)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/reqmgr2/1.3.0.pre6-comp/lib/python2.7/site-packages/WMCore/Services/DBS/DBS3Reader.py", line 961, in findAndInsertMissingParentage
    fileParents = self.dbs.listFileParentsByLumi(block_name=childBlockName, logical_file_name=childLFNs)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 484, in listFileParentsByLumi
    return self.__callServer("fileparentsbylumi", data=kwargs, callmethod='POST')
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 201, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/beHG2002h/sw/slc7_amd64_gcc630/cms/dbs3-client/3.11.2/lib/python2.7/site-packages/dbs/apis/dbsClient.py", line 225, in __parseForException
    raise http_error
HTTPError: HTTP Error 502: Proxy Error
```

**Comment by amaltaro** [comment]
Just updating this issue as well.
From the discussion Todor and I had with Yuyi today, here are some actions that we can take either to mitigate or to workaround this issue, until a redesign of parentage in StepChain can be properly implemented on the WMAgent side.
--------------
1. Action to mitigate the impact on the end users and only announce workflows with
complete dataset information (Todor will get this fixed in the coming hours)
 * fix parentage before it gets announced (closed-out status in ReqMgr2)
 * add a check on unified to only announce workflows that have the correct parentage (ParentageResolved)

2. try to break `listFileParentsByLumi` into multiple APIs, even if that means WMAgent
would have to do the parentage mapping by itself (Yuyi is looking into it)
 * Yuyi will also investigate the query (together with the CERN DBA) and look for improvements

3. have WMAgent to only publish full information to DBS (long term fix! Alan and Todor will
have to investigate it. It will touch even design changes, so it needs to be properly investigated
and well thought.)

4. We have also discussed throttling DBS access to try to mitigate users stressing too much the service.
DBS is currently set to 30 threads:
https://github.com/dmwm/deployment/blob/master/dbs/DBSGlobalReader.py#L39
so throttling settings must be smaller than that, perhaps 25(?)

**Comment by todor-ivanov** [comment]
For the first step of the list of the action items from the previous comment a separate issue was created [1].

[1]
 https://github.com/dmwm/WMCore/issues/9656

**Comment by yuyiguo** [comment]
@amaltaro 
listParentDSTrio(dataset=child_dataset)
listBlockTrio(block_name=block) 
Both will return below data format for what is in the cmsweb-testbed now:
{'554307997': [[1, 557179], [1, 557178], [1, 557181], [1, 557182], [1, 557183], [1, 557184], [1, 557185], [1, 557186], [1, 557187], [1, 557188], [1, 557189], [1, 557190], [1, 557191], [1, 557192], [1, 557193], [1, 557194], [1, 557195], [1, 557196], [1, 557197], [1, 557198], [1, 557199], [1, 557176], [1, 557177], [1, 557180]]}
Note here the key is file id, in each list is [run_number, lumi_section_numer].
The insertion is not changed at all.

**Comment by yuyiguo** [comment]
@amaltaro @vkuznet 

Here is the two different output formats' comparison with time and memory for the API listParentDSTrio.
F1 is organized output that has formate: {'fid1':[[run1, lumi1], [run1, lumi2] ....]},  { 'fid2':[[runx, lumiy], [runx, lumiz] ....], .....}, .....

F2 is Oracle's output without any re-org: {'pfid': 554307997, 'r': 1, 'l': 557176}, {'pfid': 554307997, 'r': 1, 'l': 557177}, {'pfid': 554307997, 'r': 1, 'l': 557180}  .

I have reported the timing on F1, but for your convenience, I put them here too. I used below call for the comparison. 
The API listParentDSTrio(dataset=child_dataset) 
where the child_dataset="/QCD_Pt_600to800_TuneCP5_13TeV_pythia8/RunIISummer19UL18MiniAOD-106X_upgrade2018_realistic_v11_L1v1-v2/MINIAODSIM"

For each output format, I did two groups' measuring of the time. The DBS server is configured same, but the client acted differently. In the group 1, the client got the data and printed it out. In the group 2, the client only loop over the generator, but not print out the data.
 
Time definition:
Client time(From the client sent request to got the data)
Total server time(It is the time that the server received the request to it started passing the data to the client)
sql time(it is the time that Oracle used to get the result)
Data organization time(it is the server loop over the data and organize them to this format {fid:[[r, l], [r2,l2], ...]},  then send it to the client
 
I did three repeated tests for each group, The unit is second.
The time order is  :(client_time, server_time, sql_time, data_org_time ),
F1 group 1: 

- (26.760, 12.451, 0.369, 11.565)
-  (16.095, 9.818,   0.387,  9.364)
- (22.260, 16.327, 0.408,  15.851)

 
F1 Group 2: 

- (9.761, 9.045, 0.367, 8.580)
-  (12.630, 11.748, 0.385, 11.295)
-  (15.890, 15.064, 0.491, 14.504)

For F2,  the data_org_time is the time that the sever send out the data only since we just send whatever oracle gives
F2 Group1: 

- (29.92, 14.64, 0.35, 14.22)
-  (38.17, 22.43,0.35, 22.00)
-  (28.57, 12.72,0.40, 12.25)
 
F2 Group2: 

- (20.44, 19.26, 0.33, 18.86)
-  (15.00, 13.93, 0.36, 13.83)
-  (18.93, 17.84, 0.33, 17.43)

As you may see, The format of the data did not make much difference from the timing point of view.

Now Let's take a look at the memory. F2 has no extra memory required. Before we look at F1's extra memory consumed, let's first look at the memory used the data/cursor. [Line 43](https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/FileParent/ListParentDatasetFileLumiIds.py#L43) is the cursor return by calling Oracle.  This cursor is a list of sqlalchemy.engine.result.ResultProxy object with length=1, then the line 47 convert the cursor to a list of dict. However the dict has all the data that are 675022 rows in this case. The total size of data is 216MB.  [Line 48](https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/dao/Oracle/FileParent/ListParentDatasetFileLumiIds.py#L48). and Line 49 define the dict and list used to format the data output F1. The biggest dict is 10752 bytes and the biggest list is 10448 bytes. So they are together in worst case the total extra memory introduced by F1 is only 21KB. So this is nothing comparing with the 216MB used by the cursor.  

Alan, What output formate do you prefer, F1 or F2?  I don't really care at this point. You pick one that easier for you to do the data matching.

So we need to look into WMCore in order to save memory to a reasonable size. Let me know if I did not use the cursor  correctly.

**Comment by vkuznet** [comment]
Yuyi, thanks for putting this together. From what I understand that memory comes from formatCursor method of DBFormatter class, see
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBFormatter.py#L120
And, I think memory allocation depends on how many rows you fetch at once, in your code you fetch size=1000. Since formatCursor converts data from ORACLE to a list of dicts this is where memory goes. The way to resolve it is to yield one row at a time and above DBFormatter class completely, or you can reduce a size=1000 parameter to fetch fewer rows but it may increase time in your code.

I suggest the following:
- do not use formatCursor and write code which will only rely on using DB cursor and walk through  it yielding back results one by one, you may simplify the code to dump ORACLE results so far without worrying how to convert it to JSON
- you may try to use a smaller size parameter and see how it will affect time/memory.

**Comment by yuyiguo** [comment]
@vkuznet 
Change the size at [Line 120](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBFormatter.py#L120) will not affect the total the total memory used.  The  [Line 133](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Database/DBFormatter.py#L133) shows that the formatCursor will return the entire result set  no matter how many rows fetched each time from Oracle.  I could change DBS code to make a real cursor, but then everyone else has to do the same too. So I suggested the change should be made in WMCore.

BTW, I tested with size=1, the sql time is almost the same as size=1000.   So Oracle does a good job here.

**Comment by yuyiguo** [comment]
@amaltaro 

The APIs are done. For the client APIS, please 

https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L469

https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L486

The server APIs:

https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/web/DBSReaderModel.py#L150

https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/web/DBSReaderModel.py#L152

Thanks,
Yuyi

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, thanks for providing this summary and further performance tests. From your test results, I'd say the total wallclock time (time taken by the client to send a request and receive a response in full) is quite similar. It sort of surprises me though, all that time to serialize the response back to the client.

Anyhow, I think we can proceed with your data structure in F1:
```
F1 is organized output that has formate: {'fid1':[[run1, lumi1], [run1, lumi2] ....]}, { 'fid2':[[runx, lumiy], [runx, lumiz] ....], .....}, .....
```
which will be much easier for the client to perform the parantage mapping, and a smaller memory footprint.

I'll work on this today/tomorrow and let you know in case I see any issues and/or need any further information. Thanks!

**Comment by amaltaro** [comment]
@yuyiguo Yuyi, I actually have a question about the output of these 2 new APIs. 
Will it always be a list with a single item/dictionary in it? Or could that list contain multiple items (dictionaries)?

**Comment by yuyiguo** [comment]
@Alan,

Sorry that I just saw your question. The two APIs both return a generator. When loop over the generator , you get 'fid1':[[run1, lumi1], [run1, lumi2] ....].
