### ISSUE TITLE
deprecated py2-cryptography library

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9547]
**Impact of the bug**
WMAgent

**Describe the bug**
While restarting 'AgentStatusWatcher' component I noticed the following message: [1]. It tells us that Openssl version 1.0.1 is deprecated, but I think the actual package to update is this one [2] and eventually to change to this [3].

[1]
```
Starting : AgentStatusWatcher
/data/srv/wmagent/v1.3.0/sw/slc7_amd64_gcc630/external/py2-cryptography/2.4.2-comp2/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning

```

[2]
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-cryptography.spec

[3]
https://pypi.org/project/cryptography/

**How to reproduce it**
Restart the AgentStatusWatcher component in any of the agents. 

**Expected behavior**
Using up to date cryptography libraries. 

**Additional context and error message**
N/A

**Comment by amaltaro** [comment]
Even though it's a high priority issue, it will not happen until we can migrate to a newer version of openssl. Which will only happen when:
* someone updates the openssl spec in the cmsdist/comp repo
* or we migrate to CC8 and stop using our own version of openssl

I'd suggest to mark it as medium priority, especially because I don't see it getting worked on in 2020 :-)

**Comment by amaltaro** [comment]
Given that WMCore has migrated to python3 for more than a year now, I suspect this issue is no longer relevant. Todor, please reopen it if there is anything else missing.
