### ISSUE TITLE
MS: perform output data placement for completed standard workflows

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9609]
**Impact of the new feature**
ReqMgr2MS

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

This issue is meant to address **only** the standard output datasets, thus talking to DDM to carry out the data management/transfer.

**Describe the solution you'd like**
NOTE: this implementation has to have all the hooks/placeholders for Rucio.

This standard output data placement relies on the Unified configuration (DDMcopies has been deprecated). It relies on `tiers_no_DDM` and `tiers_to_DDM`.

Fetch workflows sitting in the following status:
`'completed', 'announce', 'closed-out'`

filter their output datasets `OutputDatasets`, and make a DDM call to place the data. Parameters of the call have to be further discussed, either from the wiki documentation or by further check of the Unified code.

Persist the workflow name, output datasets, and maybe transfer id somewhere in MongoDB. 

**Describe alternatives you've considered**
The logic of what has to be handled and what has been already handled might need further thought.

**Additional context**
another reference to these unified configuration: https://github.com/CMSCompOps/WmAgentScripts/pull/518

**Comment by todor-ivanov** [comment]
@amaltaro once I started to deal with the implementation I found few misinterpreted details in my previous document so I should clear them here. 

Basically we should consider the workflows only in status `'closed-out'` but not in all those `'completed', 'announce', 'closed-out'` as we initially thought. Because the whole logic we are discussing for the Output data placement is triggered after this check in Unified [1]. And actually it sounds even more logical after reading more carefully the request status documentation [2] for status `'completed'`. And yes indeed, Unified does deal with `'completed'` workflows in a different place - the checkor module [3], after doing all its checks on the output etc. 
Then about `'announce'` - it is not a request status according to reqMgr. It is an internal transient state for Unified [4]. Of course we can do an additional check later in order to be sure we do not have a false announcements, but this is another story. Which leads me to my second thought - Maybe we should think of adopting the announcement of the workflows in this stage, because those two ('output' and 'announcement') they look like they cannot be split in the Unified code. The decision whether to announce or not depends on the results from the output data placement submissions to the data management system [5]. And we are also adding another dependency these days [6]. 


[1] 
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L485

[2]
https://github.com/dmwm/WMCore/wiki/Request-Status

[3]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/checkor.py#L1357

[4]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L607

[5]
https://github.com/CMSCompOps/WmAgentScripts/blob/master/Unified/closor.py#L588-L591

[6]
https://github.com/CMSCompOps/WmAgentScripts/pull/547
