### ISSUE TITLE
MS: decide data structure of what will be persisted in MongoDB

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9610]
**Impact of the new feature**
ReqMgr2MS, MongoDB

**Is your feature request related to a problem? Please describe.**
This is part of the output data placement migration to WMCore, see:
https://github.com/dmwm/WMCore/wiki/ReqMgr2-MicroService-Output

The persisted storage will be necessary to figure out what needs to be transferred, what has already been taken care of. It will likely be used for the REST APIs as well, such that we can expose data to the end users.

**Describe the solution you'd like**
There are two items to be addressed with this issue:
* come up with a logic to be used within the MicroService to identify which workflows need to be worked on or not;
* then, come up with a schema / data structure of the documents to be stored in MongoDB. Flat json documents are preferred.

UPDATE from what has been discussed here. The document structure would be:
```
{
"workflowName": "blah",
"transferStatus": "blah", # either "pending" or "done",
"creationTime": integer timestamp,
"lastUpdate": integer timestamp,
"outputDatasets": ["list of datasets"],
"isRelval": boolean,
"transferIDs": ["list of transfer IDs"],
"destination": ["list of locations"],
"destinationOutputMap": [{"destination": ["list of locations"], "datasets": ["list of datasets"]},
                                            {"destination": ["list of locations"], "datasets": ["list of datasets"]}, etc],
"campaignOutputMap": [{"campaignName": "blah", "datasets": ["list of datasets"]},
                                          {"campaignName": "blah", "datasets": ["list of datasets"]}, etc],
"numberOfCopies": integer
}
```

SECOND UPDATE (on Sept 10, 2020), here is the document schema:
```
            {
            "_id": "ReqName",
            "RequestName": "ReqName",
            "Campaign": "Top level campaign name",
            "CreationTime": integer timestamp,
            "LastUpdate": integer timestamp,
            "IsRelVal": (True|False),
            "Destination": ["list of locations"],
            "OutputDatasets": ["list of output datasets"],
            "DestinationOutputMap": [{"Destination": ["list of locations"],
                                      "Datasets": ["list of datasets"]},
                                     {"Destination": ["list of locations"],
                                      "Datasets": ["list of datasets"]}],
            "CampaignOutputMap": [{"CampaignName": "blah",
                                   "Datasets": ["list of datasets"]},
                                  {"CampaignName": "blah",
                                   "Datasets": ["list of datasets"]}],
            "TransferOutputMap": [{"TransferID": "rucio rule id",
                                   "TransferType": "disk",
                                   "DatasetName": "dataset name"},
                                  {"TransferID": "rucio rule id",
                                   "TransferType": "tape",
                                   "DatasetName": "dataset name"},],
            "TransferStatus": "pending"|"done,
            "TransferIDs": ["list of transfer IDs"],
            "NumberOfCopies": integer
            }
```

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by amaltaro** [comment]
@todor-ivanov here is my first proposal of how the database documents can look like
```
{
"workflowName": "blah",
"transferStatus": "blah", # either "pending" or "done",
"lastUpdate": integer timestamp,
"outputDatasets": ["list of datasets"],
"transferIDs": ["list of transfer IDs"],
"destination": ["list of locations"],
"campaignOutputMap": [{"campaignName": "blah", "datasets": ["list of datasets"]}],
"numberOfCopies": integer
}
```

the `outputDatasets` and `campaignOutputMap` would have the same list of output datasets. However, in case we want to provide some extra/meta-data information, having a map of output datasets to a campaign would be useful.

I haven't added it here, but we might need a map of destination to output datasets as well (for the RelVal case...)

My idea with this document is the following:
* one thread fetches data from ReqMgr2, constructs all this information and persists it in the database
* a second thread, fetches these documents from the database (with some filter), makes the transfer request, and update the document in couch.
It doesn't necessarily need to be multi-thread, we could handle those in different stages of the service cycle as well.

The way to retrieve these documents would be likely based on their status value, something like:
```
find({"transferStatus": "pending})
```

@vkuznet Valentin, if you can spare a cycle here. What do you think about the data structure above?
@todor-ivanov am I missing any important information? Any thoughts or comments here?

**Comment by todor-ivanov** [comment]
Thanks @amaltaro it covers almost everything. And I am full supporter of the idea to make the component relation as you described it. We may need a third thread although - to check for the health of past transfers and resubmit if needed.
 
About the document itself I would suggest to add the Workflow status from Reqmgr too, especial because we are about to deal with workflows in more than one state here. We already briefly discussed with you and agreed for the time being, we do not want to copy the whole representation of a workflow from [1] into MongoDB, but we could at least make it a dictionary here with few values.
So then we can basically split the document in two sections: one should be Workflow related information  and the other should be transfer related information like that:
```
{
"Workflow": {
    "Name": "blah"
    "outputDatasets": ["list of datasets"],
    "destination": ["list of locations"],
    "ReqMgrStatus": "....",
   "campaignOutputMap": [{"campaignName": "blah", "datasets": ["list of datasets"]}]
    }
"Transfer:" {
    "transferStatus": "blah", # either "pending" or "done",
    "lastUpdate": integer timestamp,
    "transferIDs": ["list of transfer IDs"],
     "numberOfCopies": integer
    }
}
```
And yes I agree the destinations should be helpful. 

[1]
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/DataStructs/Workflow.py

**Comment by todor-ivanov** [comment]
looking at it again the Campaign map itself does not quite fit inside the workflow. I would suggest to put it outside too:

```
{
"Workflow": {
    "Name": "blah",
    ...
    },
"Campaign": {
    "Name": "blah",
    "OutputMap": { "datasets": "datasets": ["list of datasets"]},
    },
"Transfer:" {
    ...
    }
}

**Comment by amaltaro** [comment]
Todor, let me try to reply to all your remarks/questions:
> We may need a third thread although - to check for the health of past transfers and resubmit if needed.

I would not bother checking past transfer. If our request to the DM system is successful and we get back a transfer ID, that data is then in charge of the DM system to make sure that data will _eventually_ arrive at the destination. That's how it will be with Rucio.

> About the document itself I would suggest to add the Workflow status from Reqmgr too, especial because we are about to deal with workflows in more than one state here.

We used to have ReqMgr (one) relying on both Oracle and Couch. It was a nightmare to keep them consistent. Thus, I strongly recommend to not even store that information in MongoDB, sooner or later it goes out of sync, users/clients start report and complaining about it, etc...
 
> ... we do not want to copy the whole representation of a workflow from [1] into MongoDB, but we could at least make it a dictionary here with few values.

I don't think there is any need to use that `Workflow` object for the MSOutput. Reason being that most of the information in that object (besides the high level workflow description) is related to ALL sorts of input data. 
I think the object / data struct we are discussing here is all we need.

> So then we can basically split the document in two sections: one should be Workflow related information and the other should be transfer related information like that:

I like this idea to better organise our data. However, Valentin and I discussed it a few times for the other MS and the final conclusion is to make the data structure as flat as possible. It makes it easier to expand the schema in the future (keeping backwards compatibility), and it's likely more friendly to perform database queries as well.

Regarding the campaign mapping, a workflow can have many different campaigns, so we need a data structure either like the one in my first comment, e.g.:
```
"campaignOutputMap": [{"campaignName": "blah", "datasets": ["list of datasets"]}],
```

or through a dictionary, e.g.:
```
"campaignOutputMap": {"campaignNameA": ["list of datasets"],
                                          "campaignNameB": ["list of datasets"]},
```

Honestly, I like the dictionary/second option the best. However, having the campaign name as a key of the dictionary makes it a bit more fragile. It would be a problem to MonIT if we start pushing some of this information upstream to monitor as well.

Todor, what are your thoughts here:
> I haven't added it here, but we might need a map of destination to output datasets as well (for the RelVal case...)

? I think we will have to add it the same way as for the campaign map. I really do not want to fetch the workflow description more than once from ReqMgr2, so we better store all the information we need for the output data placement in this mongo document.

**Comment by todor-ivanov** [comment]
@amaltaro Thanks! You expressed your argumentation quite well. I have no reason to doubt your past experience. Even more - the motivation about 'as flat as possible', I was kind of already expecting it :) . And I can agree with that one too, even though it makes things a little bit worse human readable but all the rest is true. 

About the destination map per output dataset, I agree we may have it in the document, especially when it comes to Relval, because there the separation (with different destinations) is not per workflow, but per data tier, while we keep a document per workflow, and we may for sure end up with output datasets  from a single workflow traveling  to different destination. (I hope I got your idea right here.)

**Comment by amaltaro** [comment]
That's correct Todor. There will be some duplicate information persisted in those documents, but given the amount of documents to be stored (< 50k, I just made this number up), I think it's totally fine to use a bit of extra storage and profit from a cleaner source code.

This extra parameter would be something like:
```
"destinationOutputMap": [{"destination": ["list of locations"], "datasets": ["list of datasets"]},
              {"destination": ["list of locations"], "datasets": ["list of datasets"]}, etc],
```

I'll update the description of this issue with the - current - agreed schema :)
I'll likely start working on it today as well.

**Comment by todor-ivanov** [comment]
Thanks Alan @amaltaro

**Comment by vkuznet** [comment]
@amaltaro, @todor-ivanov, before creating a schema for your docs you should understand few things:
- which attributes of your schema should be indexed, please note that the speed of data look-up depends on the existing index. In MongoDB, the indexes should fit into RAM to be efficient. Therefore you should create an index on an attribute with relatively small cardinality. This is not specific to MongoDB as any DB use indexes for fast data look-up. But in document-oriented databases, the schema choice is important because there is no relationships among documents.
- the usage of nested docs is fine but you should ensure that you don't mix data-types within arrays and/or nested structures
- you may store documents of different structures/schemas either in single DB collection or different ones. I strongly suggest that within single DB collection you have documents of identical schema/structure to avoid issues with document look-up
- the choice of index should reflect your DB queries, i.e. first define your set of queries, then you'll create indexes for those fields. Please pay attention to data-types as "1" is a string and not integer, therefore your query should use proper data-type.
- when you'll inject your docs to DB please validate your docs against your schema, since Python allows you to change data-types at run-time you may inject docs with different data-types from what your schema represents. We saw this type of error many times in Monitoring, when one document contains an attribute with an integer, while another with string.

I strongly suggest that you study [MongoDB indexes](https://docs.mongodb.com/manual/indexes/) document which describes different types of indexes used in DB. For instance, you may use single vs compound indexes, multi-key vs text indexes. The document provides code snippets in different languages, including Python. The proper choice of indexes and schema will significantly speed up your application.

Apart from that, the proposed schema
```
{
"Workflow": {
    "Name": "blah"
    "outputDatasets": ["list of datasets"],
    "destination": ["list of locations"],
    "ReqMgrStatus": "....",
    "campaignOutputMap": [{"campaignName": "blah", "datasets": ["list of datasets"]}]
    },
"Transfer:" {
    "transferStatus": "blah", # either "pending" or "done",
    "lastUpdate": integer timestamp,
    "transferIDs": ["list of transfer IDs"],
    "numberOfCopies": integer
    }
}
```
 looks good to me.

**Comment by amaltaro** [comment]
Thanks, Valentin. I think we can have a db collection like `ms_output_records`.
Queries that come to my mind will be based on:
* `transferStatus`: retrieving all the documents in a given status
* `workflowName`: fetching one single document in the collection

and I can't think of any other at the moment. Those would be the initial query to fetch the whole document and use the rest of their information.

**Comment by amaltaro** [comment]
We went slightly off course on this one, compared to the initial data structure that has been discussed. Differences are:
* `workflowName` is now `RequestName`
* new key `Campaign`, which likely has to go away, since workflows can have multiple campaigns; and it's present in the `campaignOutputMap` attribute
* new key `isTaken`, which can likely go away and instead we query the database with `transferStatus == "pending"` (default value for the Producer)
* new key `isTakenBy`, implemented if we want to have multiple threads/components looking those documents up (and especially updating them). I'm again in favor of dropping this attribute as well. Output data placement is a lightweight process and I don't think we will need this functionality for the many years to come

I also suggest to make these attributes consistent, so either all of them upper camel case, or lower camel case.

**Comment by amaltaro** [comment]
@todor-ivanov as we just discussed, this issue needs to be updated and then the necessary source code changes applied. Thanks

**Comment by todor-ivanov** [comment]
What we finally agreed on (and is already implemented) is the following:
```
    {                                                                                                                                                                                    
    "RequestName": "ReqName",                                                                                                                                                                                                                                                                                          
    'Campaign': "Campaign",                                                                                                                                                                 
    "creationTime": integer timestamp,                                                                                                                                                      
    "lastUpdate": integer timestamp,                                                                                                                                                         
    "isRelVal": (True|False),                                                                                                                                                               
    "isTaken": (True|False),                                                                                                                                                              
    "isTakenBy": "ThreadIdentifier",                                                                                                                                                      
    "destination": ["list of locations"],                                                                                                                                                 
    "OutputDatasets": ["list of datasets"],                                                                                                                                              
    "destinationOutputMap": [{"destination": ["list of locations"],                                                                                                                      
                              "datasets": ["list of datasets"]},                                                                                                                             
                             {"destination": ["list of locations"],                                                                                                                         
                              "datasets": ["list of datasets"]}],                                                                                                                           
    "campaignOutputMap": [{"campaignName": "blah",                                                                                                                                       
                           "datasets": ["list of datasets"]},                                                                                                                          
                          {"campaignName": "blah",                                                                                                                                        
                           "datasets": ["list of datasets"]}],                                                                                                                           
    "transferStatus": "blah", # either "pending" or "done",                                                                                                                                
    "transferIDs": ["list of transfer IDs"],                                                                                                                                               
    "numberOfCopies": integer                                                                                                 
    }                              
```

We need to change in this  schema two more things. 
   1. Capitalize all the keys, so that we have a consistent naming convention (e.g.   `campaignOutputMap` -> `CampaignOutputMap` )
   2. Rename to `TransferOutputMap` and extend the `transferIDs` to become a map similar to `transferOutputMap`, so that we can cover the cases of tracking both 'Custodial' (type) and 'NonCustodial' (Disk) transfer request, without the need of making thousands redundant calls to Rucio in order to figure out the type of rules we already have for a given dataset:

```
[{'transferID': 'blahblah', 'transferType': 'disk', 'datasetName': 'blah'},
 {'transferID': '2321sadas12', 'transferType': 'disk', 'datasetName': 'blah'}]
```

For the later change in MsoutputTemplate is needed, because in there only top level key type checks are done. And the transfer map itself will still remain embedded into a list, so we are safe. But we still need to change the rest of  the places in the code where the `transferIDs` key is generated/used.

Another topic to be covered with this change is the different type of `treansferId`s we are having in both Phedex and Rucio: 
   * Phedex - integer value
   * Rucio - hash value

This in general, can be used as an identifier of the Data Management system to which the transfer request has been generated. But I would say it is more like introducing a code dependency on a side effect (or more precisely a second order characteristics of the system) - which I would not consider a safe approach. The alternative would be to add a third field in the transfer map, stating: `transferSytem: "Rucio", "Phedex"` But this is an approach that Alan does not approve. And in some extend I tend to agree with his argumentation -  this would become an extra field which which will be used only during the transition Period and then it will stay forever. So a decision needs to be made about that.

**Comment by amaltaro** [comment]
The description of this issue has been updated (second update) to reflect the last discussions and what has been implemented.
