### ISSUE TITLE
Reduce size of WMArchive docs

### ISSUE THREAD

**Issue by vkuznet** [dmwm/WMCore#9628]
**Impact of the new feature**
We identified that recently WMArchive starts slowing down due to increased load introduced by FWJR/CRAB streams with large document sizes. In particular, we found that adding run/lumis information into WMArchive doc significantly increases its size. The impact on WMArchive service was reported by Jen A. and it slows down data look-up on the WMArchive interface. Then, we got report from the CERN MONIT team who claimed that WMArchvie docs fill out the Kafka pipeline with large docs and cause infrastructure interruptions. In particular, they reported seeing WMArchive docs of 30MB in size. Please note, the Kafka is designed to process millions of small size documents and shared among different experiments. 

**Is your feature request related to a problem? Please describe.**
Yes, it affects WMArchive service and MONIT infrastructure.

**Describe the solution you'd like**
I suggest we should reduce WMArchive doc size either by eliminating run/lumi info completely (since it is present in DBS) or using a compact format such as lumi ranges. 

**Describe alternatives you've considered**
Drop large documents above a certain size in WMArchvie/MONIT. Currently, I added 10MB threshold in WMArchive to drop docs which it supposes to send to MONIT if their size goes above it.

**Additional context**
This is somewhat critical since data-ops (Jen A) heavily rely on WMArchive service.

**Comment by amaltaro** [comment]
Valentin, thanks for creating this issue. By a quick look at the code and the history, I think the function to be changed is this one:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/WMArchive/DataMap.py#L132

From your last email, I'm also not sure how important this information is. I agree, providing only the total number of lumis and events per run should suffice.

@khurtado Kenyi, if you have free cycles to look at this issue by Monday, please do so and I can help you validating it. Otherwise I'll try to work on it on Tuesday.

**Comment by vkuznet** [comment]
yes, this function will do the trick, but we should be very careful to not break the [WMArchive schema](https://github.com/dmwm/WMArchive/blob/master/src/python/WMArchive/Schemas/FWJRProduction.py#L50). The schema we use has this structure:
```
'runs': [{'lumis': [164, 165], 'runNumber': 160960}]}],
```
Therefore, once you made a change please ensure that you'll not break the schema, otherwise the data transformation from JSON to Avro data-format will fail. Avro is schema-based data-format and can't change it w/o breaking backward compatibility. Therefore we should provide `lumis` as list (even it will be one number).

**Comment by amaltaro** [comment]
So, my question to you and @belforte Stefano is, which option is the best:
a) provide the total number of lumis in the input/output files and an empty list for the eventsPerLumi, e.g.: `...'lumis': [500], 'eventsPerLumi': []...`
b) or simply set both of them to empty lists
?

Clearly a range of lumis is no longer possible because we cannot meet the data schema.

**Comment by belforte** [comment]
I have a few things to say:
1. no backporting to a CRAB branch is needed, we build on top of latest WMCore tag
2. this is not something we can hurry. From the time a new CRAB TaskWorker is deployed, change
   will only affect new submissions. Tasks already in the system keep using old code and will only
   disappear fully after a month. 
3. I do not know about WMA timeline on that, can they really  patch all running agents
   w/o disturbing operations so that changes are pushed quickly enough to justify
  putting this item at top of all priorities ?
4. Since we have been running with this code for years, I can't see the urgency.
   Can we simply delay migration to  Kafka feed until we are ready and keep sending
   data to HDFS as before until summer. This does not mean doing nothing. It is simply
   the natural timeline of the development/deployment cycle.
5.  I am confused as to the goal  of this WMArchive project. IIUC it is a long term archive of
   summaries for later analytics which nobody is doing at the moment, hence the lack of
   clarity on what's actually needed.
6. Unless someone knows better, my take on 5. is that we should not persist for
   posterity detailed list of lumis and/or event per lumi. And rather we should think
   how to avoid the event-level bookkeeping to become a problem in Run4 and beyond.

So I vote for  empty lists !!

**Comment by vkuznet** [comment]
Stefano, let me answer a few of your questions.
4. we run WMArchive for years, but only recently CRAB docs were added which contribute to the problem. Please note that WMArchvie consumes O(M)/day and puts them to HDFS. These docs are stored in MongoDB before migrating them to HDFS. As such when we added a new source (CRAB) we mostly double the load. Jen A. reported that recently  WMArchive web interface starts behaving poorly and my research on this subject was that it is due to large docs which we aggregated in Mongo. Therefore I proposed to migrate WMArchvie to MONIT to take advantage of the common infrastructure. Turns out that these large docs cause issues in the Kafka pipeline which designed to consume mostly small docs. In any case, WMArchive web UI is a custom app and we are In favor of replacing it using MONIT dashboards.
5. WMArchive is an archive, but the data-ops team uses it extensively to spot various problems with failures on different sites. We also use WMArchive to troubleshoot the problems and find logs of failed jobs. I don't recall that we ever used WMArchive to run/event/lumi studies though. The WMArchive schema was proposed by the DMWM team and I followed it with WMArchive implementation.

Therefore since I also don't know any use cases for run/lumis usage I suggest using empty lists for them.

**Comment by belforte** [comment]
@vkuznet sorry,  I wrote before I fully read the situation and just edited my comment to remove things which are fully wrong, useless, stupid or worse (I hope). I will now read your reply.

**Comment by belforte** [comment]
OK. sounds like we agree. Actually CRAB was sending data to WMArchive for a year or so, then it stopped during SL6/7 migration and looks like we resumed after the reports had got larger. I see no problem in taking CRAB stream off until we are sure that all jobs report with the new format. I apologize again for having written w/o fully understanding. A side effect of working from home with kid at home.

**Comment by amaltaro** [comment]
Valentin, has WMArchive completely migrated to the MonIT infrastructure? Since when?
I'm trying to evaluate the real impact on the MonIT infrastructure and/or if there are any other options besides running with this among many other items on our plate. Even though the change is meant to be trivial...

**Comment by vkuznet** [comment]
Alan, I added support to inject WMArchive data into MONIT a long time ago. But due to the misconfiguration of credentials, we didn't send data until recently. When I identified the issue I worked with MONIT team to establish WMArchive data stream and now it is fully functional, see [1]. The WMArchive data now are fed into ES and landed on HDFS [2]. But these also complement the original WMArchive HDFS location [3] which stores WMArchvie data in Avro format according to our schema. The data in [2] are stored as JSON, therefore, in principle, we can adjust the schema once this issue will be resolved, and eventually, we can simplify WMArchive service to only feed data to MONIT.

Therefore, the migration to MONIT is not yet complete, but it is fully functional. Once we'll have full data flow, we can work on setting up dashboards from ES and use grafana instead of WMArchive custom web UI. Once this is complete, I can re-factor WMAchive code and drop local MongoDB, custom web UI, and potentially completely refactor (or re-write) WMArchive to be independent from WMCore and serve only as a proxy between WMA and MONIT where all data will be fully handled by MONIT infrastructure.

[1] https://monit-kibana.cern.ch/kibana/goto/cf4d7e3824487359262edaf6185b8e6f
[2] /project/monitoring/archive/wmarchive/
[3] /cms/wmarchive
