### ISSUE TITLE
Proxy renewal failing in the CERN agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9641]
**Impact of the bug**
WMAgents

**Describe the bug**
We noticed a couple of CERN agents started failing to renew my proxy - which is done through a cron entry - and over the last few days, there has been a couple more agents failing as well. Debugging shows a problem with java, likely related to some sort of update that hit those nodes in the last days..

**How to reproduce it**
Running the command manually works fine, either with or without the agent environment (!)

**Expected behavior**
The proxy renewal should go through. Ideally it would be better to have a component taking care of it, but we can simply fix it for now and keep the same renewal model.

**Additional context and error message**
After piping the error to a log, here is the problem:
```
A credential has been received for user amaltaro in /data/certs/mynewproxy.pem.
Error occurred during initialization of VM
java.lang.Error: Properties init: Could not determine current working directory.
        at java.lang.System.initProperties(Native Method)
        at java.lang.System.initializeSystemClass(System.java:1168)
```

**Comment by todor-ivanov** [comment]
Thanks for finding that @amaltaro . I was not suspecting Java problems in my previous debugging (even though I should). But since it is the case I think there is an easy solution. We need to move away from 'voms-clients-java-3.3.0-3.el7.noarch' and use only 'voms-clients-cpp-2.0.14-1.el7.x86_64' instead. This is a thing that was done for CRAB schedds at least two years ago and all problems of the sort vanished for good.
