### ISSUE TITLE
AgentJobInfo is failing since yesterday evening 

### ISSUE THREAD

**Issue by sharad1126** [dmwm/WMCore#9722]
**Impact of the bug**
The `actor.py` module in unified fails every time it runs since yesterday evening 8:22pm cern time. https://github.com/CMSCompOps/WmAgentScripts/blob/master/utils.py#L8209

**Describe the bug**
The query to wmstats server works but the `agentjobinfo` for almost every second workflow is found as a `NoneTypeObject`. 
https://cms-unified.web.cern.ch/cms-unified/logs/actor/2020-06-05_12:40:20.log
https://cms-unified.web.cern.ch/cms-unified/logs/actor/2020-06-05_12:35:31.log
https://cms-unified.web.cern.ch/cms-unified/logs/actor/2020-06-05_12:30:36.log

**How to reproduce it**
It is reproducing itself. Check the actor logs. 

**Expected behavior**
There should be `agent job info` for the tasks of the workflow.

**Additional context and error message**
@amaltaro @todor-ivanov as discussed over slack, here is the GH issue with the code and logs. If you think there is some changes required in the code, please let us know.

**Comment by sharad1126** [comment]
Here is an example:
https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?RequestName=pdmvserv_task_HIG-RunIIFall17GS-00173__v1_T_200131_163729_7838&mask=PrepID&mask=AgentJobInfo
the error report shows the number of job failures:
https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_task_HIG-RunIIFall17GS-00173__v1_T_200131_163729_7838

**Comment by amaltaro** [comment]
If I run this call:
https://cmsweb.cern.ch/wmstatsserver/data/filtered_requests?RequestName=pdmvserv_task_HIG-RunIIFall17GS-00173__v1_T_200131_163729_7838&mask=PrepID&mask=AgentJobInfo

here is the content I get:
```
{"result": [
 {
  "AgentJobInfo": null, 
  "PrepID": [
    "HIG-RunIIFall17NanoAODv6-03886", 
    "HIG-RunIIFall17MiniAODv2-06354", 
    "HIG-RunIIFall17GS-00173", 
    "HIG-RunIIFall17DRPremix-06306"
  ], 
  "RequestName": "pdmvserv_task_HIG-RunIIFall17GS-00173__v1_T_200131_163729_7838"
}]}
```

and `AgentJobInfo` is likely empty because we have dropped the wmstats database a week or two ago, as discussed in other threads. So, it's not that AgentJobInfo "fails", but it does not have any content (actually it's `None`).

If actor crashes with this, then I'd say you need to fix the actor code.

**Comment by sharad1126** [comment]
yeah so this was more of the question here. I am adding an if condition there such that we check `AgentJobInfo` is not `None`. Hope this should be fine after that.
