### ISSUE TITLE
Transferor MS should be able to get data location from Rucio

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/WMCore#9725]
We have this issue https://its.cern.ch/jira/browse/CMSRUCIO-119 which I think makes sense for the next round of transitions, which is that all data location goes through Rucio. Are there other parts of the microservices which should do the same? Alternatively are there parts of Unified which are not in MicroServices which would need to be modified?
 

@todor-ivanov ? @amaltaro ?

**Comment by amaltaro** [comment]
Eric, I have this issue created: https://github.com/dmwm/WMCore/issues/9461
which basically requests MS to have the ability to talk to Rucio. I think it's fair to say that, once that issue gets addressed, this one can be taken care of (likely a configuration change though).

Does beginning of July meet the Rucio plans?

PS.: for your future WMCore issues, please follow the bug/feature templates ;)
PPS.: I'll have questions about Rucio, but better to ask them in the other issue.

**Comment by ericvaandering** [comment]
Beginning of July is good.

**Comment by amaltaro** [comment]
Just replicating what has been discussed over the slack wmagent-dev channel (not a very exhaustive discussion btw):
"""
Alan:
Okay, considering MSTransferor is dealing with a classical mixing pileup (thus, whole dataset goes to a single RSE). Here is a draft algorithm:
we provide the container DID to list_did_rules API
check if any rule belongs to the new rucio account, e.g. wmcore_transferor
for all the rules from this account - and assuming it returns the rseExpression too - we get the RSE map from the list_rses  API
next we call list_contentpassing the container name, retrieving a list of blocks (rucio datasets)
finally, we call list_dataset_replicasfor every single block. IF ALL blocks are available in one of those RSEs from the step3, then the pileup container is already in place and we just reuse that rule_id to associate it to the pileup in this workflow ABC. Otherwise, we find the RSEs with more blocks (or more data) already available and make a rule for that RSE.
Do you think this makes sense for the pileup? Am I missing anything (besides possible a recent rule that has been created and data did not move yet…)?
Just for the record, these are python client APIs, I still have to find their correspondent REST api.
"""

"""
and Nick:
1. I believe list_rules can filter on did and account at the same time
2. wma_transfer ? we already have special permissions for wma_* account
rules have a “grouping” property, such a pileup rule for classical mixing would have grouping set to ALL, so that can also be filtered. what it means is that whatever RSE the expression selected will contain the whole container
"""
