### ISSUE TITLE
Skip ACDC workflows in MSOutput

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/WMCore#9870]
**Impact of the new feature**
MicroServices

**Is your feature request related to a problem? Please describe.**
This is not yet a strictly identified problem, but can easily become one as soon as we start MSOutput in production and subsequently re-modify/re-purpose it to deal with custodial transfer requests too. The major problem would become for the disk replica requests though. Since the initial disk transfer request is expected to come immediately once the first agent finishes a block creation, we expect that a transfer rule would already exist at the time the ACDC for a broken request has been created. This of course will not cover the cases when everything fails even before a single block has been completed and the ACDC is more or less a full remake of the already existing request.     

**Describe the solution you'd like**
Skip all workflows where `'RequestType' == 'Resubmission'` for the full MSOutput service.

**Describe alternatives you've considered**
Check for a transfer request / Rucio Rule existence for every dataset on every iteration. This would generate enormous load.    

**Additional context**
N/A

**Comment by amaltaro** [comment]
Actually, these ACDCs will make our life a bit harder in MSOutput.
One rare - but yet possible - use case would be that the initial workflow fails all the merge jobs, then an ACDC workflow gets created to recover those merge jobs. In such case, output data placement would fail for the initial workflow, because the DID would not exist yet in Rucio. And, if we skip output data placement for ACDCs (Resubmission), it means that that output dataset would never get locked with a rule anywhere.

Having said that, we do need to run output data placement for ACDC workflows as well, and for that I see 2 options:
a) easy! Just run the output data placement logic as done for any other request. If a duplicate rule is hit, great, reuse that rule id; otherwise just make a new rule, which means MSOutput might be making a lock for 2 copies of the output dataset...
b) harder! Before running any output data placement, check whether MSOutput has already made a rule for that DID. How to do so with DDM?
c) improvement of b), only run rule discovery for ACDC workflows (likely a schema change to keep the request type in the mongodb record as well)

**Comment by amaltaro** [comment]
Actually, I was wrong with the comment above. If we assume that workflows will only be moved to `closed-out` or `announced` once they are ready to be announced, skipping ACDCs would be something safe to do.

The only problem would be if the parent workflow gets moved to closed-out or announced, before the ACDC completes. I guess we can call that an operational error and something that the system cannot be protected from...
